- storm-client/src/jvm/org/apache/storm/scheduler/Cluster.java
- storm-client/src/jvm/org/apache/storm/scheduler/TopologyDetails.java
- storm-client/src/jvm/org/apache/storm/utils/ConfigUtils.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/test/jvm/org/apache/storm/scheduler/ClusterTest.java
- storm-client/test/jvm/org/apache/storm/utils/ConfigUtilsTest.java
- storm-client/test/jvm/org/apache/storm/utils/UtilsTest.java
- storm-core/src/jvm/org/apache/storm/command/ConfigValue.java
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/test/java/org/apache/storm/DaemonConfigTest.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
Addresses https://issues.apache.org/jira/browse/STORM-2421 by:
- changing the annotation on DaemonConfig childopts to isStringOrStringList
- providing a utility method to read such values as a space-separated string
> STORM-2421: support lists of childopts in DaemonConfig.

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-core/test/clj/org/apache/storm/submitter_test.clj
[https://issues.apache.org/jira/browse/STORM-2602](https://issues.apache.org/jira/browse/STORM-2602)
"storm.zookeeper.topology.auth.payload" doesn't work even you have set it,because there doesn't use it when the value of STORM_ZOOKEEPER_TOPOLOGY_AUTH_PAYLOAD isn't null or other abnormal condition.
> [STORM-2602] storm.zookeeper.topology.auth.payload doesn't work even you set it

- storm-server/src/main/java/org/apache/storm/blobstore/FileBlobStoreImpl.java
- storm-server/src/main/java/org/apache/storm/blobstore/LocalFsBlobStore.java
- storm-server/src/test/java/org/apache/storm/blobstore/BlobStoreTest.java
See https://issues.apache.org/jira/browse/STORM-2478
I couldn't think of a way to fix this test without exposing the getKeyDir method. When the AtomicOutputStream in BlobStoreTest L181 is closed, the temporary file is renamed to `data`, which is deleted explicitly when the blob store is deleted. This makes the test meaningless since it's checking that the blob store directory can be deleted when there are temporary files in it.
> STORM-2478: Fix BlobStoreTest.testDeleteAfterFailedCreate on Windows

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
Heap dumps created on OOM, when served through the logviewer in secure multi-tenant configurations have permissions set such that the logviewer cannot read them.
This change checks permissions in this case before serving and then runs the worker-launcher to enable the logviewer to serve them.  
see https://github.com/apache/storm/pull/2032
> [STORM-2093] Fix permissions in multi-tenant, secure mode

- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
- external/storm-kafka/src/test/org/apache/storm/kafka/KafkaTestBroker.java
- external/storm-kafka/src/test/org/apache/storm/kafka/PartitionManagerTest.java
- integration-test/pom.xml
@HeartSaVioR this PR includes fixes for https://issues.apache.org/jira/browse/STORM-2608
> STORM-2608 Remove any pending offsets that are no longer valid

- docs/storm-rocketmq.md
- examples/storm-rocketmq-examples/src/main/java/org/apache/storm/rocketmq/topology/WordCountTopology.java
- examples/storm-rocketmq-examples/src/main/java/org/apache/storm/rocketmq/trident/WordCountTrident.java
- external/storm-rocketmq/README.md
- external/storm-rocketmq/pom.xml
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/ConsumerMessage.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/DefaultMessageBodySerializer.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/DefaultMessageRetryManager.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/MessageBodySerializer.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/MessageRetryManager.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/RocketMqConfig.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/RocketMqUtils.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/SpoutConfig.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/bolt/RocketMqBolt.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/common/mapper/FieldNameBasedTupleToMessageMapper.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/common/mapper/TupleToMessageMapper.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/common/selector/DefaultTopicSelector.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/common/selector/FieldNameBasedTopicSelector.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/common/selector/TopicSelector.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/spout/RocketMqSpout.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/spout/scheme/KeyValueScheme.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/spout/scheme/StringKeyValueScheme.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/spout/scheme/StringScheme.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/trident/state/RocketMqState.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/trident/state/RocketMqStateFactory.java
- external/storm-rocketmq/src/main/java/org/apache/storm/rocketmq/trident/state/RocketMqStateUpdater.java
- external/storm-rocketmq/src/test/java/org/apache/storm/rocketmq/TestMessageRetryManager.java
Changed the class names including MQ to Mq. 
>Since storm-rocketmq is only merged into master branch and storm 2.0 hasn't been released, so the changes should hurt nothing.
> STORM-2594: Apply new code style to storm-rocketmq

- docs/storm-kafka-client.md
- external/storm-kafka-client/README.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutBatchMetadata.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/trident/TridentKafkaStateUpdater.java
* Added TridentKafkaStateUpdater, otherwise users have to create a class themselves.
usage scenario:
```
stream.partitionPersist(stateFactory, fields, new TridentKafkaStateUpdater(), new Fields());
```
* Fixed documents
> STORM-2618: Add TridentKafkaStateUpdater for storm-kafka-client

- bin/storm.py
Just a minor typo in storm.py. When typing "storm get-errors", it should print the usage of "get-errors" command. However, it shows "<get_errors> is not a valid command" instead.
> Fix typo in storm.py file

- docs/Setting-up-a-Storm-cluster.md
This should be able to be pulled into all of the 1.x release branches without any issues.
> STORM-2620: Updated docs for JDK needed (1.x)

- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/AbstractExecutionResultHandler.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/BaseExecutionResultHandler.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/CassandraContext.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/DynamicStatementBuilder.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/ExecutionResultHandler.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/Murmur3StreamGrouping.java
This broke the Travis CI builds for other pull requests.
Sure this is the temporary solution, and I filed issues for reducing check style violation count for each module.
> Quick Fix: fix storm-cassandra to not exceed current max violation count

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java
Situation: Spout configured to use manual commit with a finite number of retries.
In the above scenario if and when a tuple fails repeatedly and hits the retry limit, it will neither be scheduled for an attempt again nor properly accounted for in the ack() method and in OffsetManager. This will block commits for the partition that the tuple belongs to.
> STORM-2544: Fixing issue in acking of tuples that hit retry limit under manual commit mode

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java
The logic currently does a simple subtraction between the first and last offset in the committed range. If the commit spans offset voids then this would be incorrect. This incorrect number would always be on the higher side and impact the logic around maximum uncommitted offsets allowable in the spout.
> STORM-2639: Kafka Spout incorrectly computes numCommittedOffsets due to voids in the topic (topic compaction)

- docs/storm-kafka-client.md
- examples/storm-kafka-client-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaClientWordCountNamedTopics.java
- examples/storm-kafka-client-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaClientWordCountWildcardTopics.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/SerializableDeserializer.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/KafkaConsumerFactoryDefault.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainNamedTopics.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainWildcardTopics.java
This should contain the same changes as https://github.com/apache/storm/pull/2155, but deprecates methods instead of removing them.
> STORM-2548: Simplify KafkaSpoutConfig (1.x)

- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/deep_search_result.html
- storm-core/src/ui/public/index.html
- storm-core/src/ui/public/js/script.js
- storm-core/src/ui/public/logviewer_search.html
- storm-core/src/ui/public/owner.html
- storm-core/src/ui/public/search_result.html
- storm-core/src/ui/public/supervisor.html
- storm-core/src/ui/public/topology.html
As a user, I would like a simple timestamp of when a UI page was rendered, so that, I can quickly check if the information is fresh.
This is mainly for the case of keeping browser tabs open for a long while during debugging. Seeing old data in your browser could harm the effort.    -Reported by @d2r 
see: https://issues.apache.org/jira/browse/STORM-2133
This PR adds timestamp on index, topology, supervisor, owner, component pages, etc. I didn't add timestamp on logviewer pages since logs have clear timestamps.  Please let me know if it's also needed. Thanks.
> [STORM-2133] add page-rendered-at timestamp on the UI

- storm-core/src/ui/public/component.html
Confirmation before performing " start profiling", "stop profiling", "dump heap", "dump jstack", "dump profile", "restart worker" actions.
see: https://issues.apache.org/jira/browse/STORM-2643
> [STORM-2643] add confirmation before profiling/debugging actions

- storm-core/src/ui/public/deep_search_result.html
- storm-core/src/ui/public/templates/deep-search-result-page-template.html
Deep search shows a blank area if no results are found. see https://issues.apache.org/jira/browse/STORM-2644
Show some message to avoid confusion about whether the searching is finished or not.
> [STORM-2644] Show message when result not found on deep search page

- storm-client/src/jvm/org/apache/storm/Config.java
[https://issues.apache.org/jira/browse/STORM-2627](https://issues.apache.org/jira/browse/STORM-2627)
The annotation of "storm.zookeeper.topology.auth.scheme" in Config.java is wrong.As StormSubmitter.java,line 91, says "STORM_ZOOKEEPER_TOPOLOGY_AUTH_SCHEME is should always be set to digest.", the annotation of "storm.zookeeper.topology.auth.scheme" in Config.java should be consistent with it.
> [STORM-2627] The annotation of storm.zookeeper.topology.auth.scheme in Config.java is wrong

- storm-multilang/python/src/main/resources/resources/storm.py
Function `emitBolt()` emits a `map`, which is not json serializeble in python3. It should be changed to return a `list` in order to be json serializeble.
> STORM-2645 -- Update storm.py to be python3 compatible

- storm-multilang/python/src/main/resources/resources/storm.py
Function `emitBolt()` emits a `map`, which is not json serializeble in python3. It should be changed to return a `list` in order to be json serializeble.
> #2645 -- Update storm.py to be python3 compatible

- external/storm-jms/pom.xml
- external/storm-jms/src/main/java/org/apache/storm/jms/spout/JmsSpout.java
- external/storm-jms/src/test/java/org/apache/storm/jms/spout/JmsSpoutTest.java
I open this PR since I was delighted to see that there is an existing JMS spout implementation, but encountered a bug when trying to use it. The bug caused an exception (described below) to be thrown when trying to set up (`open`) the spout, since the value of `Config.TOPOLOGY_MESSAGE_TIMEOUT_SECS` corresponds to a `Long`, and not to an `Integer`.
This is a minor change, hope it's ok :)
```
7317 [Thread-18-a-executor[2 2]] ERROR o.a.s.util - Async loop died!
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
at org.apache.storm.jms.spout.JmsSpout.open(JmsSpout.java:175) ~[storm-jms-1.1.0.jar:1.1.0]
at org.apache.storm.daemon.executor$fn__4976$fn__4991.invoke(executor.clj:600) ~[storm-core-1.1.0.jar:1.1.0]
at …
```
> STORM-2652: fix error in open method of JmsSpout

- conf/drpc-auth-acl.yaml.example
[https://issues.apache.org/jira/browse/STORM-2626](https://issues.apache.org/jira/browse/STORM-2626)
The default value of drpc.authorizer.acl.filename in defaults.yaml is "drpc-auth-acl.yaml",so I think we should provided a template for drpc-auth-acl.yaml.
> [STORM-2626] Provided a template for drpc-auth-acl.yaml

- bin/storm.cmd
See https://issues.apache.org/jira/browse/STORM-2659
The python script was updated to handle this (https://github.com/apache/storm/blob/v1.1.1/bin/storm.py#L260), but it seems like storm.cmd was missed.
> STORM-2659: Add daemon.name variable to storm.cmd to fix log4j logging

- docs/storm-kafka-client.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/ManualPartitionSubscription.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/ManualPartitioner.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/NamedSubscription.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/PatternSubscription.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/NamedTopicFilterTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/PatternTopicFilterTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
This is the 1.x subtask of https://issues.apache.org/jira/browse/STORM-2542
The first commit is from https://github.com/apache/storm/pull/2223. I'd like us to switch to using manual partitioning in 1.2.0 as the default rather than waiting for 2.0, since the subscribe API seems to cause people issues. It's not something I feel strongly about though, so if it's too big of a change for a minor version release, let me know and I'll revert it.
> STORM-2640: Deprecate KafkaConsumer.subscribe API option, make KafkaConsumer.assign the default

- docs/Metrics.md
I am happy to pull this back into 1.x branches too.  I am not sure exactly how the metrics might have changed though, so we might want to be careful about doing so.
> STORM-2616: Documentation for built in metrics

- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/topology.html
See https://issues.apache.org/jira/browse/STORM-2654
The stack trace is not formatted on UI.
> [STORM-2654] preserve the formatting of the exception stacktrace on UI

- README.markdown
We seem to miss describing the existence of issues@ and how to subscribe the list.
This will be also applied to [getting help page on website](http://storm.apache.org/getting-help.html) after reviewing. (I'll update the website accordingly.)
> Add explanation for issues@ mailing list

- storm-client/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java
See: https://issues.apache.org/jira/browse/STORM-2674
Catch the NoNodeException.
> [STORM-2674] catch NoNodeException when IStormClusterState tries to delete znodes in reportError function

- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/mapper/JsonRecordHiveMapper.java
[https://issues.apache.org/jira/browse/STORM-2676](https://issues.apache.org/jira/browse/STORM-2676)
The class in "LoggerFactory.getLogger()" should be JsonRecordHiveMapper.class.
> [STORM-2676] Error class name for log in JsonRecordHiveMapper.java.

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Slot.java
- storm-core/src/jvm/org/apache/storm/daemon/supervisor/timer/UpdateBlobs.java
This is the 1.0.x version of  #2266 and should probably apply cleanly to all of the 1.x line of releases.
This prevents doing a clean rolling upgrade from 1.0.3 to 1.0.4 and 1.1.0 to 1.1.1.  We should look at getting this in and possibly doing another release ASAP.
> STORM-2682: Fix issues with null owner on rolling upgrade (1.0.x)

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
It seems to me that `private final IStormClusterState clusterState;` is a dup of ` private final IStormClusterState stormClusterState;`. So I removed `clusterState`.
> Quick fix: remove duplicated IStormClusterState object in ReadClusterState.java

- storm-core/src/ui/public/templates/index-page-template.html
"Uptime" spelling is used elsewhere in index.html, so this change makes everything consistent.
> Nitpicky cosmetic change - use "Uptime" instead of "UpTime" 

- storm-core/src/clj/org/apache/storm/pacemaker/pacemaker_state_factory.clj
In 1.1.x PacemakerClient was refactored so waitUntilReady was private, and called by the send method. But this clojure reference remained, causing pacemaker to fail to initialize. AFAIK this reference can simply be removed, as waitForReady is called on send. However, I'm not very familiar with the code base. I applied this patch to our own cluster with success.
> STORM-2500: remove call to waitUntilReady

- storm-client/src/jvm/org/apache/storm/utils/ObjectReader.java
The exception message like `Don't know how to convert  false + to boolean` can be confusing. I deleted `+`
> Quick fix confusing exception message in ObjectReader.java

- .travis.yml
We've running issue on build failures on all PRs against 1.x version, due to using Oracle JDK 7 as JDK, which Oracle withdraws it.
Same issue is filed to Travis CI, and you can see the comment here: https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
Changed OracleJDK7 to OpenJDK7 and checked the build result against my fork: https://travis-ci.org/HeartSaVioR/storm/builds/266178126
This should be ported back to all 1.x version line branches.
> Change OracleJDK7 to OpenJDK7 in Travis CI build

- docs/distcache-blobstore.md
See: https://issues.apache.org/jira/browse/STORM-2695
We need to update the doc for "uncompress" argument from String (e.g. "false") to Boolean (e.g. false)
> [STORM-2695] Fix in docs: BlobStore uncompress argument should be Boolean

- external/storm-cassandra/README.md
- external/storm-cassandra/pom.xml
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/ObjectMapperOperation.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/builder/ObjectMapperCqlStatementMapperBuilder.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/impl/ObjectMapperCqlStatementMapper.java
- storm-client/src/jvm/org/apache/storm/lambda/SerializableCallable.java
Allow bolts to emit object annotated with `@Table` and generate CQL for them automatically using the Cassandra object mapper.
> STORM-2492: Adding Cassandra Object Mapper statement builder.

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
I really would like feedback on the configs and if it makes since to modify other schedulers to support this too.
Config:
I thought about using regexs for nodes instead of just a host name.  Would that be better? Would it make it simple for someone to prefer a large section of a cluster and essentially abuse the feature?
Other Schedulers:
The isolation scheduler possibly, where we could resort The HostAssignableSlots if the topology want to prioritize one host over another.  And then sort them back if they don't
The even scheduler is a little odd as it feels completely against what it stands for.  It would almost turn it into an odd hybrid with the isolation scheduler.
MT scheduler is so complex at this point I could do it, but only if someone really wants it.
> STORM-2673: add support for prioritizing nodes in scheduling

- external/storm-cassandra/pom.xml
- external/storm-druid/pom.xml
- external/storm-elasticsearch/pom.xml
- external/storm-hbase/pom.xml
- external/storm-mongodb/pom.xml
- external/storm-pmml/pom.xml
- external/storm-redis/pom.xml
- external/storm-rocketmq/pom.xml
- external/storm-solr/pom.xml
- pom.xml
[https://issues.apache.org/jira/browse/STORM-2699](https://issues.apache.org/jira/browse/STORM-2699)
I think it's better to put all the version information of third party components into the main pom for more efficient version control
> [STORM-2699] Put all the version information of third party component into the main pom 

- storm-server/src/main/java/org/apache/storm/localizer/Localizer.java
- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
- storm-server/src/test/java/org/apache/storm/localizer/LocalizerTest.java
See: https://issues.apache.org/jira/browse/STORM-2700
`canUserReadBlob ` function should take `STORM_BLOBSTORE_ACL_VALIDATION_ENABLED` config into consideration. 
> [STORM-2700] Should not check Blobstore ACL if the validation is disabled

- storm-client/src/jvm/org/apache/storm/drpc/DRPCSpout.java
When the `DRPCSpout` cannot fetch a request it puts itself to sleep at the end of `nextTuple()`. After leaving this method the case that the spout did not emit any tuple is handled by `ISpoutWaitStrategy` - which in case of `SleepSpoutWaitStrategy` (the default) issues another sleep.
This causes unnecessary context switches in my opinion, especially with a high parallelism setting and many different `DRPCSpout`s.
Only the configured / active `ISpoutWaitStrategy` should decide the action.
> STORM-2705: DRPCSpout sleeps twice

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
[STORM-2231](https://issues.apache.org/jira/browse/STORM-2231) is an issue to report broken thread-safety on output collector. We mostly considered about grouper implementation, but there's a spot in other side as well.
In DisruptorQueue, each incoming threads have each ThreadLocalBatcher, meaning that 'synchronized' in add() can synchronize incoming thread and background flusher thread, but not among incoming threads.
Hopefully DisruptorQueue publish*() are implemented to respect thread-safety, but it relies on RingBuffer producer option (Sequencer in RingBuffer), and unfortunately we set producer to SINGLE, not MULTI for executor batch queue. It seems to be one of optimization but we seemed to miss a spot.  
So there're two simple options to choose: just using same ThreadLocalBatcher …
> STORM-2231 Fix multi-threads issue on executor send queue

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/EmptyKafkaTupleListener.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaTupleListener.java
This PR proposes an improvement to the KafkaSpout. A KafkaTupleListener interface can now be implemented to handle state changes of the tuple. 
Our primary use case is to put tuples, which are discarded by the RetryService into a dead letter queue.
> STORM-2694: Add KafkaTupleListener to storm-kafka-client

- docs/IConfigLoader.md
- pom.xml
- storm-server/pom.xml
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/scheduler/multitenant/MultitenantScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/ArtifactoryConfigLoader.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/ArtifactoryConfigLoaderFactory.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/ConfigLoaderFactoryService.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/FileConfigLoader.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/FileConfigLoaderFactory.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/IConfigLoader.java
- storm-server/src/main/java/org/apache/storm/scheduler/utils/IConfigLoaderFactory.java
- storm-server/src/test/java/org/apache/storm/scheduler/utils/ArtifactoryConfigLoaderTest.java
- storm-server/src/test/java/org/apache/storm/scheduler/utils/FileConfigLoaderTest.java
This adds an interface and two implementations, one that will load from a local file, and another
that will load a config from artifactory.
It also modifies the ResourceAwareScheduler and Multitenant schedulers to have a plugin interface and configuration entries for the plugin.
Unit tests are also added for the implementations.
See: https://github.com/apache/storm/pull/1785
Also fixed some checkstyle issues.
> [STORM-2201] Add dynamic scheduler configuration loading

- storm-client/src/jvm/org/apache/storm/daemon/worker/LogConfigManager.java
- storm-client/test/jvm/org/apache/storm/daemon/worker/LogConfigManagerTest.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
* Addressed below issues
* Nimbus throws error when changing log level on UI topology page
* Log configs in worker are removed even they're not timed out and never reset
* The unit of epoch between backend and frontend are different
* second in backend, millisecond in frontend
* millisecond is right so fixed it
The above issues seem to be only in master branch.
> STORM-2443 Fix issues on changing log level

- storm-dist/binary/final-package/pom.xml
Since storm-rename-hack is removed, I think we should remove the dependency.
> Quick fix: remove storm-rename-hack dependency

- storm-client/src/jvm/org/apache/storm/daemon/GrouperFactory.java
- storm-client/src/jvm/org/apache/storm/daemon/Task.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/ExecutorShutdown.java
- storm-client/src/jvm/org/apache/storm/executor/IRunningExecutor.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareCustomStreamGrouping.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareShuffleGrouping.java
- storm-client/test/jvm/org/apache/storm/grouping/LoadAwareShuffleGroupingTest.java
- storm-core/test/clj/org/apache/storm/grouping_test.clj
* construct ring which represents distribution of tasks based on load
* chooseTasks() just accesses the ring sequentially
* port related tests from Clojure to Java
I'm not expert of micro-benchmark but I also craft some of simple performance tests which you can see them from LoadAwareShuffleGroupingTest. They are `testBenchmarkLoadAwareShuffleGroupingEvenLoad` and `testBenchmarkLoadAwareShuffleGroupingUnevenLoad `, and I put `@Ignore` to avoid running unless we want to do performance test on.
Here's my observation on running them, using old and new LoadAwareShuffleGrouping:
> testBenchmarkLoadAwareShuffleGroupingEvenLoad (old)
Duration: 114470 ms
Duration: 115973 ms
Duration: 114807 ms
> testBenchmarkLoadAwareShuffleGroupingEvenLoad (new)
Duration: 106819 ms
Duration: 105857 ms
Duration: …
> STORM-2678 Improve performance of LoadAwareShuffleGrouping

- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/ui/public/js/script.js
- storm-core/src/ui/public/js/visualization.js
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/src/ui/public/topology.html
Please refer the issue link: 
https://issues.apache.org/jira/browse/STORM-2533
https://issues.apache.org/jira/browse/STORM-2534
* also fixed STORM-2534 Visualization API missing stats/instances for "system" components
* one thing which should be fixed in issue description is "__system" shouldn't be shown
* it is also addressed from this patch
> STORM-2533 Visualization API returns "spout" for system components

- examples/storm-kafka-client-examples/pom.xml
- examples/storm-kafka-examples/pom.xml
- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/Subscription.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutBatchMetadata.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutManager.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaque.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaqueCoordinator.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/TopicPartitionSerializer.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/trident/TridentKafkaState.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutBatchMetadataTest.java
- storm-client/src/jvm/org/apache/storm/trident/spout/IOpaquePartitionedTridentSpout.java
- storm-client/src/jvm/org/apache/storm/trident/topology/state/TransactionalState.java
See https://issues.apache.org/jira/browse/STORM-2675
This builds on https://github.com/apache/storm/pull/2268, so please ignore the first commit.
Trident uses json-simple under the hood to persist some objects to Zookeeper. This isn't mentioned on the API docs (or I missed it), so the current storm-kafka-client implementation returns a bunch of objects json-simple can't figure out how to serialize. The result is that json-simple writes the toString of the objects to Zookeeper, which can't be read back out. This causes the Trident Kafka spout to start over every time it's rebooted.
TransactionalState, which is used by Trident to read/write to/from Zookeeper, uses JSONValue.parse to read. That function fails quietly by returning null when there's a parsing error. There's a note in the code …
> STORM-2675: Fix storm-kafka-client Trident spout failing to serialize meta objects to Zookeeper

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
worker_hooks is an optional field in StormTopology struct (storm.thrift). So when we call get_worker_hooks(), we need to check is_set_worker_hooks().
We probably want to pay attention to optional fields when we write the code because this can be a common issue for all thrift structs. We should always check is_set_xxx before we call get_xxx if xxx is an optional field.
For details, see https://issues.apache.org/jira/browse/STORM-2729.
> [STORM-2729] Fix NPE in WorkerState runWorkerStartHooks and runWorkerShutdownHooks methods

- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/src/clj/org/apache/storm/ui/core.clj
First of all, AFAIK, it's just an issue of API output, and it doesn't hurt functionality although we don't fix it.
- when determining nimbus addresses from nimbus.seeds, filter out localhost addresses
- localhost address: 127.0.0.1, localhost, 0:0:0:0:0:0:0:1
- there may be a chance that nimbus (localhost) is not reachable so we can't get info from alive-nimbuses
- but it means ui process itself can't reach nimbus so we can ignore this case
- there may be another change that user specifies nimbus.seeds to both unreachable localhost address and other reachable nimbuses fqdn
- ui process can reach other nimbus and localhost itself is lost
- but I think we can treat it as configuration error
> STORM-1492 With nimbus.seeds set to default, a nimbus for localhost may appear "Offline"

- storm-server/src/main/java/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-server/src/test/java/org/apache/storm/blobstore/BlobStoreUtilsTest.java
- storm-server/src/test/java/org/apache/storm/blobstore/MockZookeeperClientBuilder.java
- storm-server/src/test/resources/log4j2.xml
`master` version of https://github.com/apache/storm/pull/2320, connected to https://issues.apache.org/jira/browse/STORM-2736.
Check for empty nimbus info list before attempting to update the blobstore.
> STORM-2736: fix o.a.s.b.BlobStoreUtils [ERROR] "Could not update the blob with key"

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java
[JIRA-STORM-2730](https://issues.apache.org/jira/browse/STORM-2730)
Add config options for acker cpu and memory.
A test:
Config: 
`topology.acker.resources.onheap.memory.mb: 100` `topology.component.resources.onheap.memory.mb: 128`
> [STORM-2730] Add in config options for acker cpu and memory

- examples/storm-loadgen/README.md
- examples/storm-loadgen/pom.xml
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/ExecAndProcessLatencyEngine.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/GenLoad.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/LoadBolt.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/LoadCompConf.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/LoadMetricsServer.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/NormalDistStats.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/OutputStream.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/SlowExecutorPattern.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/ThroughputVsLatency.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/TopologyLoadConf.java
- storm-client/src/jvm/org/apache/storm/daemon/Task.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/ExecutorShutdown.java
- storm-client/src/jvm/org/apache/storm/executor/IRunningExecutor.java
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareShuffleGrouping.java
- storm-client/test/jvm/org/apache/storm/grouping/LoadAwareShuffleGroupingTest.java
I have run several tests that show this works much better at big imbalances in processing latency than did the previous shuffle implementations.
I ran some simple performance tests and because `chooseTasks` didn't change the performance was more or less identical to what was here before.
The plan on how this would work with STORM-2686 (adding distance to shuffle) is that we would have 4 different weights (worker local, node local, rack local, and everywhere).  Each time we update the load we update all of the weights, for the min load currently in the locality group.  This is because executors may move from one group to another as things are rescheduled, so we need a way to keep it consistent.  
We can then test a few different ways of selecting the group we want to target.  Currently we …
> STORM-2733: Better load aware shuffle implementation

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/Constants.java
- storm-client/src/jvm/org/apache/storm/daemon/StormCommon.java
- storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java
[jira-STORM-2741](https://issues.apache.org/jira/browse/STORM-2741)
Similar to https://github.com/apache/storm/pull/2324 , add cpu and memory configs for metrics consumer.
> [STORM-2741] Add in config options for metrics consumer cpu and memory

- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraState.java
`CassandraState::batchRetrieve` does not report specific error messages when binding values or retrieving results goes wrong.
I think we should make exception message available to log in order to make debugging easier. Thank you.
> Quick fix: report cassandra error messages to logger

- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
**Problem**:
If `topology.acker.executors` is not set, the number of ackers will be equal to `topology.workers`. But on RAS cluster, we don't set `topology.workers` because the number of workers will be determined by the scheduler. So in this case, the number of ackers will always be 1.
For example, there are 5 workers but only 1 acker.
**Analysis**:
The number of ackers has to be computed before scheduling happens, so it knows how to schedule the topology. The number of workers is not set until the topology is scheduled, so it is a bit of a chicken and egg problem.
**Solution**:
We could probably use the total amount of requested memory when the topology is submitted divided by the memory per worker to get an estimate that is better than 1.
JIRA at …
> [STORM-2738] The number of ackers should default to the number of actual running workers on RAS cluster

- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/TridentResultSetValuesMapper.java
Current implementation in `TridentResultSetValuesMapper::map` restricts a SELECT query to return one row. In `StateQueryProcessor::finishBatch`, it checks the equality between the result size of `batchRetrieve` and input tuple size. When the number of result rows is less than 1 or greater than 1, it breaks the condition and an exception is thrown.
We should accept arbitrary number of rows by adjusting List dimensions.
> STORM-2712: accept arbitrary number of rows per tuple in storm-cassandra

- storm-client/src/jvm/org/apache/storm/topology/base/BaseWindowedBolt.java
There is also inconsistent and mixed used of Longs and Ints throughout the windowing code.  Perhaps we should just change all the numeric values to use longs?  Especially since all calculation of time is done in milliseconds.  It would also be nice to make clear in both the code and documentation that all timestamps and time based calculations is in milliseconds.
> [STORM-2731] - Simple checks in Storm Windowing

- bin/storm.py
If disk can not keep it up with all logging, the {{AsyncLoggingContext}} causes large heap memory be utilized causing the JVM to churn CPU.
> [STORM2751] Removing AsyncLoggerContext from Supervisor Configuration

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/cluster/ClusterUtils.java
- storm-client/src/jvm/org/apache/storm/cluster/IStormClusterState.java
- storm-client/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
[JIRA-STORM-2744](https://issues.apache.org/jira/browse/STORM-2744)
Backpressure mechanism relies on zookeeper to transfer signals. 
If at some point, the topology wants to turn off the throttle but zookeeper failed to delete the backpressure node, then the throttle will be on. And in that case, it's very likely that the znode will never be deleted and thus the throttle will always be on. The spouts will stop indefinitely. 
We want to add a restart timeout so that even the above case happens, the spouts can continue to work.
> [STORM-2744] add in restart timeout for backpressure

- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/ui/public/deep_search_result.html
- storm-core/src/ui/public/search_result.html
- storm-core/src/ui/public/templates/deep-search-result-page-template.html
- storm-core/src/ui/public/templates/search-result-page-template.html
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
jira: https://issues.apache.org/jira/browse/STORM-2757
We have HTTPS configs for UI and Logviewer. But it's not working properly.  
We should expect: 
| UI        | LogViewer           | scheme of log links  | port of log links
| ------------- |:-------------:| -----:|-----:|
|HTTP | HTTP | http | logviewer.port
|HTTP | HTTPS| https | logviewer.https.port
|HTTPS | HTTPS| https|  logviewer.https.port
|HTTPS | HTTP| should not work | should not work
> [STORM-2757] Fix broken log links when HTTPS is in use

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
JIRA: https://issues.apache.org/jira/browse/STORM-2758
logviewer_search page not found because the original code uses "./public" as the `BaseResource` for `ServletContextHandler`. The actual path of "./public" depends on where we run `storm logviewer` command. 
Manually tested.
> [STORM-2758] fix: logviewer_search page not found

- storm-client/src/jvm/org/apache/storm/blobstore/BlobStore.java
- storm-client/test/jvm/org/apache/storm/blobstore/ClientBlobStoreTest.java
- storm-core/src/jvm/org/apache/storm/command/Blobstore.java
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
We should disallow colons in blobstore key name.  HDFS prohibits the use of ":" in path name. 
[ Related code is here](https://github.com/apache/hadoop/blob/branch-2.6.1/hadoop-hdfs-project/hadoop-hdfs/src/main/java/org/apache/hadoop/hdfs/DFSUtil.java#L237)
Secondly, the original code uses two different functions to validate key names in different places. We probably just want to use one to avoid confusion.
> [STORM-2765] Disallow colons in blobstore key name

- storm-client/src/jvm/org/apache/storm/topology/OutputFieldsGetter.java
JIRA: https://issues.apache.org/jira/browse/STORM-2769
If streamId is null, we should throw an exception because thrift doesn't support null in map keys.
A test:
> [STORM-2769] Fast-fail if output streamId is null

- .gitattributes
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/jvm/org/apache/storm/utils/WebAppUtils.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
- storm-webapp/pom.xml
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerProfileHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogFileDownloader.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/WorkerLogs.java
- storm-webapp/src/main/java/org/apache/storm/daemon/utils/PathUtil.java
- storm-webapp/src/main/java/org/apache/storm/daemon/utils/UrlBuilder.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandlerTest.java
- storm-webapp/src/test/resources/log4j2.xml
See https://issues.apache.org/jira/browse/STORM-2716.
The tests run on Windows now at least. I haven't tested Logviewer beyond checking that I can search logs on my local machine from Storm UI, so there may still be some corners of Logviewer that don't work on Windows.
I also removed some constants that were making accessing the file.separator property easy. I don't think we need them since File.separator exists.
> STORM-2716: Fix logviewer tests on Windows.

- docs/Trident-API-Overview.md
This is a revival of #1018: It took a while, but I have now rebased the changes onto the current master and adjusted the base branch.
However, #1018 is in "missing common history" mode after force-pushing the new commits. Changing the base branch didn't cause the diff to be recomputed, so the Pull Request cannot be re-opened.
Therefore, this new PR is required.
> Improve mention of aggregate() in the partitionAggregate() docs

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryService.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoffTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
Please see https://github.com/apache/storm/pull/2277. I've put all the changes for this branch in their own commit for easy review.
> STORM-2666 (1.x)

- storm-client/src/jvm/org/apache/storm/generated/SupervisorSummary.java
- storm-client/src/py/storm/ttypes.py
- storm-client/src/storm.thrift
- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/ui/public/templates/index-page-template.html
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
The patch addresses following:
- Calculate fragmentation of CPU/memory
- Display it on UI under Cluster summary
- Add following guages:
-- fragmented_memory 
-- fragmented_cpu    
-- available_memory  
-- available_cpu     
-- total_memory      
-- total_cpu      
- Fix num_supervisors calculations.
> [STORM-2770] Add fragmentation metrics for CPU and Memory

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaUnitSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
This finishes up https://github.com/apache/storm/pull/2181, which has been blocked on a rebase for a while. It was suggested on the mailing list that we finish this up quickly since the fix should ideally go in 1.1.2.
I've squashed the commits as much as possible without mixing up which changes were made by @tiodollar and which were made by me. Let me know if squashing is not okay in this case, and I'll rebase on the commits in the original PR.
> STORM-2607: Storm-kafka-client never commits the last message on a partition.

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareShuffleGrouping.java
- storm-client/src/jvm/org/apache/storm/task/GeneralTopologyContext.java
- storm-client/src/jvm/org/apache/storm/task/WorkerTopologyContext.java
- storm-client/test/jvm/org/apache/storm/grouping/LoadAwareShuffleGroupingTest.java
A redesign of https://github.com/apache/storm/pull/2270 . This adds the locality awareness to LoadAwareShuffleGrouping. It applies the concept of Bang–bang control (credit to @revans2 ).
I didn't change the critical function like chooseTasks(). So the performance should be good. 
I am doing some performance testing. Hope to get some feedback first. Thanks.
> [STORM-2686] Add locality awareness to LoadAwareShuffleGrouping

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
1.x version of https://github.com/apache/storm/pull/2367. The changes are in the last commit, will squash once review is done.
> STORM-2607 1.x

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
JIRA: https://issues.apache.org/jira/browse/STORM-2777
https://github.com/apache/storm/pull/2325 introduced a bug that  the number of ackers doesn't default to the number of workers in non-RAS cases.
Manually tested on both non-RAS case and RAS case.
> [STORM-2777] The number of ackers should default to the number of workers

- storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
* waterMarkEventGenerator could be null when timestamp field is not specified
> STORM-2779 NPE on shutting down WindowedBoltExecutor

- storm-core/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
* waterMarkEventGenerator could be null when timestamp field is not specified
> STORM-2779 NPE on shutting down WindowedBoltExecutor (1.x)

- storm-core/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
* waterMarkEventGenerator could be null when timestamp field is not specified
> STORM-2779 NPE on shutting down WindowedBoltExecutor (1.1.x)

- external/storm-eventhubs/pom.xml
- external/storm-kafka-monitor/pom.xml
- external/storm-kafka/pom.xml
- external/storm-kinesis/pom.xml
- pom.xml
- storm-core/pom.xml
- storm-core/test/clj/org/apache/storm/transactional_test.clj
- storm-core/test/clj/org/apache/storm/trident/state_test.clj
- storm-server/pom.xml
- storm-server/src/test/java/org/apache/storm/blobstore/BlobSynchronizerTest.java
https://issues.apache.org/jira/browse/STORM-2706
I've tested this with storm-starter running on a distributed mode single-node cluster. I attempted to use storm-perf to see if there was a performance difference, but metrics seem broken on Windows. Might try it out on a Linux box.
I'm hoping people will try this out so we can decide if we want to upgrade.
> STORM-2706: Upgrade to Curator 4.0.0

- external/storm-eventhubs/pom.xml
- external/storm-kafka-monitor/pom.xml
- external/storm-kafka/pom.xml
- external/storm-kinesis/pom.xml
- pom.xml
- storm-core/pom.xml
- storm-core/test/clj/org/apache/storm/transactional_test.clj
- storm-core/test/clj/org/apache/storm/trident/state_test.clj
- storm-core/test/jvm/org/apache/storm/blobstore/BlobSynchronizerTest.java
Ran tests locally and they passed. The only change from the master version is that there was no storm-server pom to modify.
> STORM-2706: Upgrade to Curator 4.0.0 (1.x)

- storm-client/src/jvm/org/apache/storm/daemon/Acker.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
This does some minor optimizations for the ackers, but for the most part it just turns Ticks back on for ackers.
I will be putting up a pull request for 1.x as well.  If someone wants a 0.10 or 0.9 pull request I can do it, but I think those lines are mostly not supported any more.
> STORM-2786: Turn ticks back on for ackers (2.x)

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
The patch apply cleanly to 1.1.x and 1.0.x too
> STORM-2786: Enable tick tuples for ackers (1.x)

- docs/storm-kafka-client.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java
- Define processing guarantees as AT_LEAST_ONCE, AT_MOST_ONCE, NONE
- Refactor method name from setForceEnableTupleTracking to setTupleTrackingEnforced
- Throw IllegalStateException instead of IllegalArgumentException if spout attempts to emit an already committed message
- Update documentation to reflect these changes
> STORM-2781: Refactor storm-kafka-client KafkaSpout Processing Guarantees

- docs/storm-kafka-client.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java
The commit for STORM-2787 is on top of STORM-2781 to make it easier to merge later. Please review only STORM-2787. Once the code reviews for STORM-2781 have been agreed upon I will incorporate them in this patch as well.
> STORM-2787: storm-kafka-client KafkaSpout method onPartitionsRevoked(...) should set initialized flag independently of processing guarantees

- storm-core/src/jvm/org/apache/storm/testing/FixedTupleSpout.java
[JIRA - STORM 2791](https://issues.apache.org/jira/browse/STORM-2791)
Also deprecated existing constructor that accepts a `String`.
> STORM-2791: Add Fields constructor to FixedTupleSpout for multiple output field support. (1.x)

- storm-client/src/jvm/org/apache/storm/testing/FixedTupleSpout.java
[JIRA - STORM 2791](https://issues.apache.org/jira/browse/STORM-2791)
Also deprecated existing constructor that accepts a `String`.
> STORM-2791: Add Fields constructor to FixedTupleSpout for multiple output field support.

- external/storm-hbase/pom.xml
- external/storm-solr/pom.xml
- pom.xml
See https://issues.apache.org/jira/browse/STORM-2799.
This excludes jdk.tools from a few dependencies. I also upgraded hbase to the latest patch release of the current version, since the 1.1.0 version leaks jdk.tools https://issues.apache.org/jira/browse/HBASE-13963 and versions prior to 1.1.11 don't work with Java 9 https://issues.apache.org/jira/browse/HBASE-17944.
> STORM-2799: Exclude jdk.tools for JDK 9 compatibility

- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java
https://issues.apache.org/jira/browse/STORM-2794
In order to support running workers of older version, when we schedule a topology of older version, the confs in TopologyDetails could be "backtype.storm". To make scheduler work, we need to translate "backtype.storm" to "org.storm" for Config.TOPOLOGY_SCHEDULER_STRATEGY
> [STORM-2794] Translate backtype to org.apache for topology.scheduler.strategy if scheduling older version topologies

- external/storm-hbase/README.md
I was looking through the README for the HBase bolt and noticed that a couple of tables and some headers were not formatted correctly. I've cleaned it up a bit to at least display well through Github's web interface and look a bit nicer in a text editor.
> Fixing markdown for HBase bolt README in Storm

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/TopoCache.java
https://issues.apache.org/jira/browse/STORM-2804
The ACLs might change during `store.createBlob()` but it's not populated to `topos.put()`, which leads to permission problem.
> [STORM-2804] Fix TopoCache is not caching ACLs correctly problem

- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImpl.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestFixedAvroSerializer.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestGenericAvroSerializer.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/blobstore/BlobStoreTest.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImplTest.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBoltTest.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestSequenceFileBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestDirLock.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestFileLock.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSemantics.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestProgressTracker.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterRule.java
https://issues.apache.org/jira/browse/STORM-2810
The tests are leaking at least threads and HDFS file locks. Instead of cleaning up everything manually, I've made sure threads are cleaned up, and have switched the tests that use locks to start a new DFS cluster per test instead of per test class. 
I ran the tests on Travis 3 times without failure, and 100 times on a local Ubuntu VM.
> STORM-2810: Fix resource leaks in storm-hdfs tests

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
Kafka understands booleans in this property just fine, there's no reason to use strings instead.
> MINOR: Use booleans instead of strings for 'enable.auto.commit' setting

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
https://issues.apache.org/jira/browse/STORM-2829
```
2017-11-21 21:06:19.369 o.e.j.s.HttpChannel qtp1471948789-17 [WARN] /api/v1/deepSearch/wc-1-1511188542
javax.servlet.ServletException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: org.apache.storm.daemon.logviewer.handler.Matched["matches"]->java.util.ArrayList[0]->java.util.HashMap["port"]->sun.nio.fs.UnixPath["fileSystem"]->sun.nio.fs.LinuxFileSystem["rootDirectories"]->sun.nio.fs.UnixPath["root"])
```
We are having the above exception because 
`truncatePathToLastElements(firstLogAbsPath, 2).getName(0)` returns a Path object. Then `OBJECT_MAPPER.writeValueAsString()` (in `Matched` `toJSONString()`) somehow interprets the path to …
> [STORM-2829] fix logviewer deepSearch direct self-reference leading to cycle exception

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
https://issues.apache.org/jira/browse/STORM-2827
The logviewer search returns "http" url no matter whether logviewer is using https or not, which could lead to 404 not found error.
Tested it manually
> [STORM-2827] fix Logviewer search returning incorrect logviewerUrl problem

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
Somehow this change got reverted during a merge in 1.x-branch. It is fine in master, so we should just merge this patch here.
> STORM-2784: storm-kafka-client KafkaTupleListener method onPartitionsReassigned() should be called after initialization is complete

- .travis.yml
This is just to get builds working again. I've raised https://issues.apache.org/jira/browse/STORM-2856 to figure out why it's broken on the new image.
The patch probably needs to go on master, 1.x and 1.1.x.
> STORM-2855: Revert to 2017Q4 Ubuntu image in Travis to fix build

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
>  STORM-2826: Set key/value deserializer fields when using the convenience builder methods in KafkaSpoutConfig

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscription.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutLogCompactionSupportTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutReactivationTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaUnitSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscriptionTest.java
See https://issues.apache.org/jira/browse/STORM-2847.
The cause of the bug here is that we are shutting down the KafkaConsumer when the spout is deactivated, but aren't returning to a "clean" state in the spout fields. When the spout is reactivated and we call Subscribe in the ManualPartitionSubscription, it skips doing the assignment because the new assignment is the same as the assignment it has cached from before the deactivation.
The fix is to not cache the assignment in ManualPartitionSubscription, but just ask the consumer what its assignment is.
There are some other related changes in this as well:
* Removed the initialized flag in the spout. Initialization is always synchronous, and happens in the call to KafkaSpout.activate, which happens before Storm starts calling nextTuple. …
> STORM-2847: Ensure spout can handle being activated and deactivated

- conf/storm.yaml.example
- docs/Eventlogging.md
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/metric/EventLoggerBolt.java
- storm-core/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
- storm-core/src/jvm/org/apache/storm/metric/IEventLogger.java
- storm-core/src/jvm/org/apache/storm/validation/ConfigValidation.java
* expose option to register IEventLogger similar to metrics consumer
* change the interface of IEventLogger slightly
* allow argument
* the change is technically not backward compatible but in real we can treat it's OK
* cause we don't provide a chance to implement custom IEventLogger and plug to topology
* open possibility to extend FileBasedEventLogger and provide different format of log message
* document the change
For master branch: #2457
> (1.x) STORM-2854 Expose IEventLogger to make event logging pluggable

- conf/storm.yaml.example
- docs/Eventlogging.md
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/daemon/StormCommon.java
- storm-client/src/jvm/org/apache/storm/metric/EventLoggerBolt.java
- storm-client/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
- storm-client/src/jvm/org/apache/storm/metric/IEventLogger.java
- storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
* expose option to register IEventLogger similar to metrics consumer
* change the interface of IEventLogger slightly
* allow argument
* the change is technically not backward compatible but in real we can treat it's OK
* cause we don't provide a chance to implement custom IEventLogger and plug to topology
* Fix EventInfo to contain origin type of values instead of String-converted values
* open possibility to extend FileBasedEventLogger and provide different format of log message
* document the change
This is in reality backward compatible change (though it is 'technically' not backward compatible), and I'd like to get it in 1.x version as well.
For 1.x-branch: #2458
> STORM-2854 Expose IEventLogger to make event logging pluggable

- storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
Some explanation in https://issues.apache.org/jira/browse/STORM-2857
I have been thinking about some solutions for this problem. For example, the customized classLoader for version specific classpath; or translate the configs before validation. But I think the simplest way that I can come up with is to loosen some constraints for the `@isImplementationOfClass`.
When users submit a topology with older version configs (containing `backtype.storm.XXX` ), if the newest version of the class (ie `org.apache.XXX`) is found, we let the validation pass. And we replace the class name with `org.apache` when we use it if needed, for example, https://github.com/apache/storm/pull/2397 .
For now it's really just about `TOPOLOGY_SCHEDULER_STRATEGY` config. This is not really elegant but as discussed in …
> [STORM-2857] Loosen some constraints to support running topologies of older version

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/trident/TridentKafkaState.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/trident/TridentKafkaStateFactory.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/trident/TridentKafkaStateUpdater.java
Make TridentKafkaState a template class to eliminate warning messages in eclipse, and a minor optimisation that use StringBuilder.append instead of string concat operation.
> STORM-2864: Minor optimisation about trident kafka state

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
This commit fixes the storm-mesos integration for the interaction between the Storm core's Supervisor daemon and the MesosSupervisor that implements the ISupervisor interface.
> [STORM-2690] resurrect invocation of ISupervisor.assigned() & make Supervisor.launchDaemon() accessible

- examples/storm-starter/multilang/resources/randomsentence.js
- flux/flux-wrappers/src/main/resources/resources/randomsentence.js
- storm-core/src/dev/resources/tester_spout.js
- storm-multilang/javascript/src/main/resources/resources/storm.js
- storm-multilang/python/src/main/resources/resources/storm.py
- storm-multilang/ruby/src/main/resources/resources/storm.rb
As it is now required to answer to the activation and deactivation, I added those to the javascript files because the examples stopped working.
I updated ruby and python as well, but they don't have that issue because they always send sync without waiting for a callback.
But now you should be able to implement those as well in your code depending on those libs.
> [STORM-2868] Address handling activate/deactivate in multilang module files

- storm-client/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
* extract local variable 'scheduler' to one of fields
* gracefully shutdown the scheduler
I followed the guide of Javadoc for implementing `closeFlushScheduler()` properly.
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ExecutorService.html
> STORM-2870 Properly shutdown ExecutorService in FileBasedEventLogger

- storm-core/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
* extract local variable 'scheduler' to one of fields
* gracefully shutdown the scheduler
PR for master branch: #2482 
I think this can be easily cherry-picked to 1.1.x-branch and 1.0.x-branch.
> (1.x) STORM-2870 Properly shutdown ExecutorService in FileBasedEventLogger

- .travis.yml
- DEVELOPER.md
Since the issues breaking the build have been fixed, we should switch to using the new Ubuntu image on Travis.
> STORM-2856: Make Storm build work on post-2017Q4 Travis Trusty image

- storm-core/pom.xml
- storm-core/src/resources/compile-worker-launcher.sh
1.x version of https://github.com/apache/storm/pull/2462
I didn't think we needed this initially since asprintf isn't used in 1.x, but it looks like the build is failing on 1.x after upgrading to the newest Travis image (e.g. https://travis-ci.org/apache/storm/builds/324620269).
This only contains the replacement of make-maven-plugin. Make-maven-plugin fails to run autoreconf on Travis. The error log is
```
[DEBUG] Executing: /bin/sh -l -c cd /home/travis/build/srdo/storm/storm-core/target/native/worker-launcher && autoreconf -i
[DEBUG] /bin/sh: 14: /opt/jdk_switcher/jdk_switcher.sh: [[: not found
[DEBUG] /bin/sh: 21: /opt/jdk_switcher/jdk_switcher.sh: [[: not found
[DEBUG] /bin/sh: 28: /opt/jdk_switcher/jdk_switcher.sh: [[: not found
[DEBUG] /bin/sh: 35: …
```
> STORM-2858 1.x

- external/storm-druid/pom.xml
https://github.com/apache/storm/pull/2498 applied to 1.x branch.
> STORM-2881: Explicitly specify the curator dependencies in storm-druid pom

- external/storm-hdfs/pom.xml
- external/storm-hive/pom.xml
- external/storm-kafka-client/pom.xml
- external/storm-mqtt/pom.xml
- integration-test/pom.xml
- pom.xml
The actual fix is just the changes in storm-hdfs/pom.xml  But this added 1 min to the build time on a decently powerful box.  So to combat that I made as many of the test run in parallel.  Some of the tests didn't work well in this mode, so I disabled the parallelism for storm-hive, storm-kafka-client, and integration-test.  Storm-hdfs and storm-hive have some issues with where data is stored, and we could probably make it work with the right settings.  storm-kafka-client mostly works, but occasionally I would see a test hang and I didn't have time to debug it.
> STORM-2876: Work around memory leak, and try to speed up tests

- external/storm-hdfs/README.md
Makes it easier to jump to the HDFS Spout documentation. The HDFS Bolt link isn't really needed but is done for consistency's sake.
> Add anchor links to the README

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Slot.java
Supervisor collapse continuously when there is a expired assignment for overdue storm for invalid LocalAssignment.
2.0 patch [#2439](https://github.com/apache/storm/pull/2493).
This is patch for 1.x-branch.
> [STORM-2879] Supervisor collapse continuously when there is a expired assignment for overdue storm [fix for 1.x-branch]

- examples/storm-starter/README.markdown
A typical use case for somebody trying this is, first setting up a working storm installation and then running the example. If the storm-starter code is cloned from github directly, it may not match the version of storm they just installed, and giving rise to an error like `Error: Could not find or load main class org.apache.storm.starter.ExclamationTopology` when the topology is submitted.
The README doesn't make it clear that the storm-starter code is also available inside the version they had downloaded from http://storm.apache.org/downloads.html
Hopefully this edit will bring more clarity.
> Updated how to get the storm-starter code

- storm-dist/binary/final-package/pom.xml
There is a known issue with the maven-assembly-plugin version 2.5+ where it fails with errors like the following:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single (default) on project final-package: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.6:single failed: group id '906175167' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
```
This became an issue with change 84a4314d96b9e4e377a3d5d81d0a042d96a0625e when the maven-assembly-plugin
was upgraded from version 2.2.2 to 2.6, as inherited from the apache pom version 18.
To fix this we set the assembly plugin's `tarLongFileMode` configuration setting to `posix`.
> [STORM-2893] fix storm distribution build by using POSIX tar

- flux/flux-core/src/test/resources/configs/substitution-test.yaml
The tests fail when the PATH environment variable has a trailing colon, despite that being a valid PATH.
This happens because it is substituted directly into the resultant YAML file, which results in invalid
YAML (since you cannot end a map's value with ":" in the raw text).
So the solution is to wrap the map value with double-quotes.
Also fix 2 typos in comments in this file.
> [STORM-2892] fix PATH substitution in flux tests

- conf/defaults.yaml
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/index.html
- storm-core/src/ui/public/topology.html
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
The current pagination default value for Storm UI is hard-coded to be 20. Pagination has been introduced in `Storm 1.x`. Having 20 items in the list restricts searching through the page. It will be beneficial to have a configuration option, `ui.pagination`, which will set the pagination value when Storm UI loads. This option can be added to storm.yaml along with other configurations.
Changed the value of `ui.pagination` in `storm.yaml` to test the following cases :
| Value in `storm.yaml`        | Result    
| ------------- |:-------------:| 
|  No `ui.pagination`     | defaults to 20 entries |
|  `“All”`     | Throws error, expects integer |
|  `-10`     | List doesn't have any items in it |
|  `30`     | Populates list with 30 entries as default |
|  `10`     | Populates list with 10 …
> STORM-2877: Add an option to configure pagination in Storm UI

- external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractHadoopNimbusPluginAutoCreds.java
STORM-2900 Always return non null collection for config keys in `AbstractHadoopNimbusPluginAutoCreds`.
Closes STORM-2900
> STORM-2900 Always return non null collection for config keys in AbstractHadoopNimbusPluginAutoCreds.

- external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractAutoCreds.java
STORM-2900 Always return non null collection for config keys in `AbstractAutoCreds`.
@HeartSaVioR pinging for review.
Respective PR for master: #2515
> STORM-2900 Always return non null collection for config keys in AbstractAutoCreds.

- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/spout/ShellSpout.java
- storm-core/src/jvm/org/apache/storm/task/ShellBolt.java
- storm-core/src/jvm/org/apache/storm/utils/DefaultShellLogHandler.java
- storm-core/src/jvm/org/apache/storm/utils/ShellLogHandler.java
- storm-core/src/jvm/org/apache/storm/utils/ShellUtils.java
- storm-core/test/jvm/org/apache/storm/utils/DefaultShellLogHandlerTest.java
- storm-core/test/jvm/org/apache/storm/utils/ShellUtilsTest.java
Connected to https://issues.apache.org/jira/browse/STORM-2862.
Put contextual information in the ThreadContext for multilang logging.
I've updated the Python and Ruby resources in multilang, but not the JS one. That's because the JS one is written to support variable arguments (probably because of [STORM-2435](https://issues.apache.org/jira/browse/STORM-2435)). I can't see a way to support optional IDs without breaking the current behaviour.
> STORM-2862: More flexible logging in multilang

- storm-core/src/clj/org/apache/storm/command/shell_submission.clj
- storm-core/src/jvm/org/apache/storm/command/AdminCommands.java
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-core/test/clj/org/apache/storm/security/auth/auth_test.clj
- storm-server/src/main/java/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-server/src/main/java/org/apache/storm/blobstore/BlobSynchronizer.java
- storm-server/src/main/java/org/apache/storm/blobstore/KeySequenceNumber.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/zookeeper/LeaderElectorImp.java
- storm-server/src/main/java/org/apache/storm/zookeeper/Zookeeper.java
Reuse connections for nimbus blob-store keys registration when restarting.
Also for storm-code setup.
This is the JIRA: [#STORM-2901](https://issues.apache.org/jira/browse/STORM-2901)
> [STORM-2901] Reuse ZK connection for getKeySequenceNumber [for 2.0.0 storm]

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
* since it incurs side effect and messes metrics
More detail: https://issues.apache.org/jira/browse/STORM-2912
We must cherry-pick this into 1.1.x-branch and 1.0.x-branch as well, and I guess it will be no conflict.
Will also craft a patch for master branch shortly.
> STORM-2912 Revert optimization of sharing tick tuple (1.x)

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
* since it incurs side effect and messes metrics
More detail: https://issues.apache.org/jira/browse/STORM-2912
> STORM-2912 Revert optimization of sharing tick tuple

- storm-core/src/clj/org/apache/storm/command/shell_submission.clj
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/clj/org/apache/storm/zookeeper.clj
- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
- storm-core/src/jvm/org/apache/storm/blobstore/KeySequenceNumber.java
- storm-core/src/jvm/org/apache/storm/zookeeper/LeaderElectorImp.java
- storm-core/src/jvm/org/apache/storm/zookeeper/Zookeeper.java
@HeartSaVioR 
This is the 1.x-branch patch.
The original PR is here: [#2522](https://github.com/apache/storm/pull/2522).
> [STORM-2901]: Reuse ZK connection for Nimbus [for 1.x-branch]

- conf/defaults.yaml
- storm-core/src/clj/org/apache/storm/cluster.clj
- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/test/clj/org/apache/storm/cluster_test.clj
- Do not delete backpressure ephemeral node frequently
- Add backpressure timeout.
- Cleanup backpressure znodes .
- Add in "restart timeout" for backpressure.
> [STORM-2873] Do not delete backpressure ephemeral node frequently

- external/storm-autocreds/pom.xml
storm-autocreds brings in the curator 4.0 jars via transitive dependency of storm-core. Even though storm-core is listed as provided scope, the app assembler plugin puts the dependency (curator 4.0) into external/storm-autocreds directory. This conflicts with the storm-druid tranquility library which depends on curator 2.6.0. 
There could be other conflicts if storm-autocreds is included in class path. 
Excluding curator dependency from storm-core resolves this.
> STORM-2907: Exclude curator dependencies from storm-core in storm-autocreds pom

- conf/defaults.yaml
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/index.html
- storm-core/src/ui/public/topology.html
Backporting this Storm UI change which has already been merged in master. 
JIRA ticket: https://issues.apache.org/jira/browse/STORM-2877
Merged PR in master branch: https://github.com/apache/storm/pull/2505
> STORM-2877: Backport for 1.0.x-branch

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
* this prevents newly-initializing executor in deactivated topology to show high CPU usage
* this is based on the fact that all the tasks in executor are for same component
I guess it would be clean cherry-pick among branches regarding 1.x version lines. (1.1.x/1.0.x)
> STORM-2853 Initialize tick tuple after initializing spouts/bolts (1.x version lines)

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
* this prevents newly-initializing executor in deactivated topology to show high CPU usage
Please refer https://issues.apache.org/jira/browse/STORM-2853 for more details.
Please also note that we assume all the tasks in executor are for same component.
> STORM-2853 Initialize tick tuple after initializing spouts/bolts

- pom.xml
Ran `mvn clean install -DskipTests` on the parent project
ran `mvn clean install` on storm-core
got the following error, is the test flaky? Build ran successfully
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running org.apache.storm.serialization.SerializationTest
Running org.apache.storm.command.TestCLI
Running org.apache.storm.command.RebalanceTest
Running org.apache.storm.command.SetLogLevelTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in org.apache.storm.command.RebalanceTest
Running org.apache.storm.stats.TestStatsUtil
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.056 sec - in org.apache.storm.command.SetLogLevelTest
Tests run: 1, Failures: 0, …
```
> STORM-2918 Update Netty version

- docs/storm-kafka-client.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/CommitMetadataManager.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java
https://issues.apache.org/jira/browse/STORM-2913
This builds on STORM-2914.
I believe we can resolve STORM-2913 by committing metadata in all processing guarantee modes, rather than just AT_LEAST_ONCE. This change simply adds metadata to the AT_MOST_ONCE and NONE commit statements.
>  STORM-2913: Add metadata to at-most-once and at-least-once commits 

- examples/storm-perf/README.markdown
- examples/storm-perf/pom.xml
- examples/storm-perf/src/main/conf/KafkaClientSpoutNullBoltTopo.yml
- examples/storm-perf/src/main/java/org/apache/storm/perf/KafkaClientSpoutNullBoltTopo.java
- examples/storm-perf/src/main/java/org/apache/storm/perf/utils/MetricsSample.java
There are a couple of minor unrelated changes, mainly a fix for an NPE in the MetricsSample file if the tested topology does not use acks, and seemingly outdated documentation in the README talking about running the perf topologies in local mode.
> STORM-2933: Add a storm-perf topology that uses storm-kafka-client

- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
Currently, only Nimbus uses STORM_METRIC_STORE_CLASS.  
If the RocksDB jar is missing on Daemons other than Nimbus, they should be able to startup successfully.  
If the jar is missing on Nimbus, the metricStore will fail to initialize, and an ERROR will be logged. Nimbus will still be able to run; it just ignores using the metricStore.
> STORM-2934 - fix startup ClassNotFoundException when missing RocksDB jar

- conf/defaults.yaml
- docs/storm-metricstore.md
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
- storm-server/src/main/java/org/apache/storm/metricstore/MetricStoreConfig.java
- storm-server/src/main/java/org/apache/storm/metricstore/NimbusMetricProcessor.java
- storm-server/src/main/java/org/apache/storm/metricstore/WorkerMetricsProcessor.java
- storm-server/src/test/java/org/apache/storm/daemon/supervisor/SlotTest.java
This adds the WorkerMetricsProcessor interface.  The default implementation executes the current code that sends metric data to Nimbus for insertion, now done by NimbusMetricProcessor.
The intent is that we can replace this class for other metricstore implementations (HBase is what I am currently working on) that can instead do insertion directly.
> STORM-2939 add WorkerMetricsProcessor interface

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareShuffleGrouping.java
- storm-client/test/jvm/org/apache/storm/grouping/LoadAwareShuffleGroupingTest.java
https://issues.apache.org/jira/browse/STORM-2932
The names are confusing. I think we should delete "percent"
> [STORM-2932] the naming of topology localityaware configs are confusing

- pom.xml
> [STORM-2948] add -XX:+HeapDumpOnOutOfMemoryError for maven-surefire-plugin

- storm-client/src/jvm/org/apache/storm/utils/TupleUtils.java
https://issues.apache.org/jira/browse/STORM-2950
listHashCode(keys) might return Integer.MIN_VALUE (-2147483648). Math.abs(-2147483648) equals to -2147483648.
And as @HeartSaVioR  pointed out,  to be consistent with 1.x version:
```
(mod listHashCode(keys) numTasks)
```
We should use
```
Math.floorMod(listHashCode(keys), numTasks) 
```
> [STORM-2950] Making FieldsGrouper.chooseTasks be consistent with 1.x version line

- storm-client/src/jvm/org/apache/storm/coordination/BatchSubtopologyBuilder.java
- storm-client/src/jvm/org/apache/storm/drpc/LinearDRPCTopologyBuilder.java
- storm-client/src/jvm/org/apache/storm/topology/BaseConfigurationDeclarer.java
- storm-client/src/jvm/org/apache/storm/topology/ComponentConfigurationDeclarer.java
- storm-client/src/jvm/org/apache/storm/topology/TopologyBuilder.java
- storm-client/src/jvm/org/apache/storm/transactional/TransactionalTopologyBuilder.java
- storm-client/src/jvm/org/apache/storm/trident/topology/TridentTopologyBuilder.java
In duplicated code, `TransactionalTopologyBuilder.addResource` method implementation caused NPEs, motivating this cleanup.
> [STORM-2961] Refactor addResource and addResources Methods in BaseConfigurationDeclarer

- docs/SECURITY.md
While the explanation of last statement implicitly says that setting up proper OS account is needed, but explicitly mentioning it should help end-users to understand the importance while setting up OS account for Storm cluster.
This change should be clean cherry-pick for 1.x version lines.
> STORM-2960 Stress importance of setting up proper OS account for Storm processes

- storm-client/src/jvm/org/apache/storm/Config.java
https://issues.apache.org/jira/browse/STORM-2969
get rid of @isDerivedFrom validation for wait strategies so that users can supply their own strategies.
> [STORM-2969] remove @isDerivedFrom validation for topology.spout/bolt/backpressure.wait.strategy

- external/storm-autocreds/pom.xml
1.x version of  https://github.com/apache/storm/pull/2569
> STORM-2968: Exclude avro and commons-beanutils dependency from storm-autocreds

- external/storm-eventhubs/pom.xml
- external/storm-kafka-migration/pom.xml
- external/storm-kafka-monitor/pom.xml
- external/storm-kafka/pom.xml
- external/storm-kinesis/pom.xml
- pom.xml
- storm-core/pom.xml
https://issues.apache.org/jira/browse/STORM-2978
This fix also has to go on 1.1.x, I'm hoping it'll cherry pick cleanly. If not I'll open another PR.
> STORM-2978 1.x: Fix Zookeeper transitive dependency version to 3.4.6

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/timer/SupervisorHealthCheck.java
- storm-server/src/main/java/org/apache/storm/healthcheck/HealthChecker.java
The couple of issues with Supervisor HealthCheck functionality.
1. `ClassCastException` while reading configuration.
2.  The supervisor should die if healthchecks fail.
> [STORM-2976] Fix Supervisor HealthCheck validations

- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/LoadMetricsServer.java
- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/ThroughputVsLatency.java
[https://issues.apache.org/jira/browse/STORM-2998](https://issues.apache.org/jira/browse/STORM-2998)
If we use LoggerFactory.getLogger method in a class,the most accurate approach is use this class as a parameter.
> [STORM-2998]Wrong className in LoggerFactory.getLogger method

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java
https://issues.apache.org/jira/browse/STORM-2989
Preserve current worker.log.metrics
> [STORM-2989] LogCleaner should preserve current worker.log.metrics

- examples/storm-elasticsearch-examples/pom.xml
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/bolt/EsIndexTopology.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/bolt/package-info.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/common/EsConstants.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/common/EsTestUtil.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/common/package-info.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/trident/TridentEsTopology.java
- examples/storm-elasticsearch-examples/src/main/java/org/apache/storm/elasticsearch/trident/package-info.java
I'd like to share my hands-on reflection on whether it makes sense to take over you checkstyle-config for some of my projects. The approx. 100 violations cost about 1,5h to fix which seems a realistic indicator for the time needed for similar fixes.
> [STORM-3004] storm-elasticsearch-examples: fixed all checkstyle warnings

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
The TimedRotation should synchronize so that the bolt does not attempt to write to a stale writer.
> STORM-2993: Storm HDFS bolt throws ClosedChannelException when Time rotation policy is used

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
The TimedRotation should synchronize so that the bolt does not attempt to write to a stale writer.
> STORM-2993: Storm HDFS bolt throws ClosedChannelException when Timed rotation policy is used

- storm-client/src/jvm/org/apache/storm/drpc/LinearDRPCTopologyBuilder.java
Users may still want to use LinearDRPCTopologyBuilder even though they don't use Trident.
> STORM-3005-Removed deprecation from LinearDRPCTopologyBuilder.

- storm-client/src/jvm/org/apache/storm/security/serialization/BlowfishTupleSerializer.java
- storm-client/test/jvm/org/apache/storm/security/serialization/BlowfishTupleSerializerTest.java
https://issues.apache.org/jira/browse/STORM-2977
Tries to use Config.STORM_ZOOKEEPER_TOPOLOGY_AUTH_PAYLOAD before  throwing exceptions. Making it simpler to use
> [STORM-2977] BlowfishTupleSerializer tries to use zookeeper secret if blowfish.key is not present

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
https://issues.apache.org/jira/browse/STORM-2983
Because the number of workers are dynamically calculated on RAS and is not populated to SupervisorStormConf, by default `topologyConf.get(Config.TOPOLOGY_WORKERS)`  returns 1 and the transferThread is not launched. Some topologies like 
```
bin/storm jar storm-loadgen-*.jar org.apache.storm.loadgen.ThroughputVsLatency --spouts 1 --splitters 2 --counters 1 -c topology.debug=true
```
on RAS cluster are not working properly.
> [STORM-2983] fix the issue that the inter-worker transfer thread is not spun up on some cases on RAS cluster

- storm-core/src/jvm/org/apache/storm/drpc/LinearDRPCTopologyBuilder.java
Removed deprecation from LinearDRPCTopologyBuilder.
> STORM-3005-removed-deprecation-LinearDRPCTopologyBuilder

- storm-core/src/jvm/org/apache/storm/drpc/LinearDRPCTopologyBuilder.java
Removed deprecation from LinearDRPCTopologyBuilder.
> STORM-3005-1.1.x-removed-deprecation-LinearDRPCTopologyBuilder

- storm-core/src/jvm/org/apache/storm/drpc/LinearDRPCTopologyBuilder.java
Removed deprecation from LinearDRPCTopologyBuilder.
> STORM-3005-1.0.x-removed-deprecation-LinearDRPCTopologyBuilder

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocalizedResource.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
There were a number of places in AsyncLocalizer that were using synchronized to try and protect some maps.  When we added in support for restarting a worker if specific blobs change one of the places that was protected before moved to a background thread and lost that protection.
Now that we are java 8 we can use lambdas to provide the same protection without the need for the locks so I removed all of the course grained locking in AsyncLocalizer.  Now the only locking is on a per-blob basis.
I tested this manually by launching topologies with lots of different types of blobs, modified the blobs and verified that everything worked correctly.  I shot things, including the supervisor, various times and verified that it was able to recover in each case.
> STORM-3020: fix possible race condition in AsyncLocalizer

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
Add in WorkerState an internal list of deserialized workerHooks and use it to
start/stop
> fix STORM-2979 (master branch)

- storm-client/src/jvm/org/apache/storm/stats/StatsUtil.java
- storm-core/src/clj/org/apache/storm/ui/core.clj
https://issues.apache.org/jira/browse/STORM-3023
(1) The component page of the UI is showing a blank for requested resources (CPU and Memory).
(2) for the topology page what is being showed for them is the total for the entire topology, not individual components.
It's because the storm rest api code is using wrong keys. The component `requestedMemOnHeap` is null and then the `Mustache` in ui code uses `requestedMemOnHeap` from the parent (which is the total sum)
(3) And the executors of components in topology page shows wrong numbers. 
This is a bug introduced when porting clojure to java https://github.com/apache/storm/pull/1147
The number of executors of components gets accumulated incorrectly
> [STORM-3023] fix the issue that Storm UI not showing correct values for component CPU, Memory and Executors

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/SimpleRecordTranslator.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/ByTopicRecordTranslatorTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SimpleRecordTranslatorTest.java
A null List<Object> is a valid return value from RecordTranslator.apply() if the ConsumerRecord is invalid.
> [STORM-3043] Fix NullPointerException when apply() returns null

- pom.xml
This is taken care of in master via jackson-bom dependency.
> STORM-2985: Explicitly add jackson-annotations dependency in pom dependency management

- storm-client/src/jvm/org/apache/storm/messaging/netty/Server.java
When worker is killed slot port remains in TIME_WAIT state. Since worker process is killed it is secure to start a new worker process on the same port.
> STORM-3039 handle slot ports in TIME_WAIT state

- docs/storm-kafka-client.md
As per @srdo and @ptgoetz's replies on the Storm Dev mailing list, I am adding the spout configuration map in the `storm-kafka-client` document . 
[The gist](https://gist.github.com/srishtyagrawal/850b0c3f661cf3c620c27f314791224b), with initial changes, had comments from @srdo and questions from me which I am pasting here for convenience:
Last comment by @srdo:
Thanks, I think this is nearly there. The maxOffsetBehind section says that "If a failing tuple's offset is less than maxOffsetBehind, the spout stops retrying the tuple.". Shouldn't it be more than? i.e. if the latest offset is 100, and you set maxOffsetBehind to 50, and then offset 30 fails, 30 is more than maxOffsetBehind behind the latest offset, so it is not retried.
Regarding the links, I think we should try to use links that …
> STORM-3060: Map of Spout configurations from storm-kafka to storm-kafka-client

- pom.xml
- storm-core/pom.xml
https://issues.apache.org/jira/browse/STORM-3063
> STORM-3063: Fix minor pom issues

- bin/storm.py
- storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java
* add submit option: '--mavenLocalRepositoryDirectory'
* passed arg will be used to maven local repository directory in resolving transitive dependencies
For 1.x-branch: #2672 
Please refer https://issues.apache.org/jira/browse/STORM-3069 for more details.
> STORM-3069 Allow users to specify maven local repository directory for storm submit tool

- pom.xml
- storm-client/src/jvm/org/apache/storm/testing/PerformanceTest.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/ISchedulingState.java
- storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignmentImpl.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOffer.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceRequest.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResources.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourcesWithMemory.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/ResourceMapArrayBridge.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/GenericResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestUtilsForResourceAwareScheduler.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
There are a lot of different scheduler improvements.  Mostly these are either caching, storing data in multiple ways so we can look it up quickly, and finally lazily sorting nodes in a rack only when it is needed, instead of all ahead of time.
I also added in performance tests.  They currently pass on travis, but I would like to hear from others on if this solution looks good or if there is a better way for us to do performance testing.
> STORM-3040: Improve scheduler performance

- examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/LoadSpout.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
https://issues.apache.org/jira/browse/STORM-3073
The first commit contains the changes I made to ExclamationTopology to provoke the error. I'll remove it after review, it is just included so it's easier to understand the error.
There are two changes in this PR. The first is to uncap the pendingEmits queue for bolt executors. It's currently capped at 1024 elements, which makes it dangerous for bolts to emit more than 1024 tuples in an execute invocation. If the bolt executor is experiencing backpressure and tries to add the tuples to pendingEmits, the queue size will be exceeded and the worker will crash.
The second change is to make LoadSpout emit failed tuples from nextTuple instead of doing it from fail. Since the spout executor is also limited to 1024 tuples in the pending queue, it is …
> STORM-3073: Uncap pendingEmits for bolt executors, and prevent LoadSpout from overflowing pendingEmits in spout executors

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceUtils.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOffer.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceRequest.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResources.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOfferTest.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceRequestTest.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourcesTest.java
TOPOLOGY_ACKER_CPU_PCORE_PERCENT and other similar settings in adjustResourcesForExec() were orphaned accidentally by a previous pull request.  This adds the functionality back.
When we deployed the change to clusters that were near full with some topologies that had this setting, because we were not previously honoring it, the nodes now looked over 100% full and were throwing exceptions during scheduling.  
The fix for this was to instead zero out the resources and track that the issue is occurring.  We had also logged that the error was occurring, and found that the logging became excessive, which also slowed scheduling.  A further change was added by @revans2 to limit the logging.
> STORM-3042 restore topology.acker.cpu.pcore.percent

- external/storm-jdbc/pom.xml
* Please refer https://issues.apache.org/jira/browse/STORM-3083 for more details
This can be safely ported back to 1.x-branch as well.
> STORM-3083 Upgrade HikariCP version to 2.4.7

- storm-client/src/jvm/org/apache/storm/messaging/IContext.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Client.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Context.java
workerState has already cache connection use supervisor_id + port
and if context and worker both cache connection, there can be some problem describe in jira
jira link: https://issues.apache.org/jira/browse/STORM-3055
> [STORM-3055] remove conext connection cache

- storm-core/src/jvm/org/apache/storm/messaging/IContext.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/Client.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/Context.java
worker has already cache connection use supervisor_id + port
and if context and worker both cache connection, there can be some problem describe in jira
> [STORM-3055] 1.1.x remove conext connection cache

- conf/defaults.yaml
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/test/java/org/apache/storm/daemon/nimbus/NimbusTest.java
When submitting a toplogy, the jar first gets uploaded, and then the topology is submitted.  Between these two events, a nimbus timer can go off and it finds that the jar belongs to a topology that does not exist, and removes it, causing topology submission to fail.
This change logs when a blob is first detected for deletion.  It then waits a period of time (defaulting to 5 minutes) before considering it idle.
> STORM-3053 prevent race deleting blobs before topologies can be submitted

- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/test/java/org/apache/storm/daemon/nimbus/NimbusTest.java
My previous attempt at fixing this addressed the race in store.storedTopoIds().  But state.idsOfTopologiesWithPrivateWorkerKeys() will also return a topology as ready to clean up while the topology is being submitted.
The fix is to delay deletion on all topologies found for all the state and store checks.
I was able to reproduce the issue and validate the fix properly this time by forcing a Nimbus cleanup to be called as part of topology submission.
> STORM-3096 prevent race condition during topology submission

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/blobstore/BlobStore.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
Current Behavior : Execute topology with invalid topology name is throwing exception after uploading the jar.
Improvement : Validating topology name at client side before uploading the jar.
> [STORM-3094] : Added topology name validation at client side

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
In kafka >0.10.2 this check became expensive, causing large performance
decreases.
> STORM-3102 Remove check for partition offset before every emit.

- storm-client/src/jvm/org/apache/storm/StormTimer.java
Nimbus registers exitProcess() for the StormTimer.onKill routine.  This does not return once called.  This basically locks up the timer with active being set.
Then when Nimbus shuts down, it calls timer.close().  Since the timer is stuck in the onKill routine forever with active set on, timer close is deadlocked waiting for the join() to occur here:
https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/StormTimer.java#L173
The proposed fix is to just set active to false before calling the onKill() for the timer.
> STORM-3103 allow nimbus to shutdown properly

- storm-core/src/jvm/org/apache/storm/command/KillWorkers.java
See issue: https://issues.apache.org/jira/browse/STORM-3109
> STORM-3109: Fixed incorrect conversion from relative path to absolute path for STORM_LOCAL_DIR

- pom.xml
not too much is using hdrhistogram.
storm-metrics,
storm-loadgen,
storm-starter,
storm-elasticsearch,
storm-elasticsearch-examples
The ES code is not running because of what appear to be issues with the version of guava.  when we shade guava it should take care of that, and I will be able to test these changes better.
I think I am going to change focus for a while and put in shading so we can fix some of these issues and actually test these things.  I manually tested the others and the code works.
> STORM-3061: Upgrade version of hdrhistogram

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Container.java
- storm-core/src/jvm/org/apache/storm/daemon/supervisor/RunAsUserContainer.java
- storm-core/test/jvm/org/apache/storm/daemon/supervisor/ContainerTest.java
While running in secure mode, supervisor sets the worker user (in workers local state) as the user that launched the topology.
However the worker OS process does not actually run as the user (instead runs as storm user) unless `supervisor.run.worker.as.user` is also set.
If the supervisor's assignment changes, the supervisor in some cases checks if all processes are dead by matching the "pid+user". Here if the worker is running as a different user (say storm) the supervisor wrongly assumes that the worker process is dead.
Later when supervisor tries to launch a worker at that same port, it throws a bind exception
We can skip the user check while determining if the worker processes are alive.
> STORM-3110: Skip the user while checking isProcessAlive

- storm-server/src/main/java/org/apache/storm/LocalCluster.java
Turns out Rocksdb doesn't handle creating parent directories, so https://github.com/apache/storm/pull/2728 doesn't prevent it from throwing an exception when Nimbus is started.
That said, we're still getting an exception when Nimbus is started from https://github.com/apache/storm/blob/4137328b75c06771f84414c3c2113e2d1c757c08/storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/StringMetadataCache.java#L64, so this doesn't by itself prevent the metrics store from failing to initialize in tests.
> MINOR: Mkdir for storm.home when running LocalCluster

- pom.xml
- storm-core/pom.xml
- storm-core/test/clj/org/apache/storm/metrics_test.clj
- storm-core/test/resources/log4j2-test.xml
https://issues.apache.org/jira/browse/STORM-3121
> STORM-3121: Fix flaky metrics tests in storm-core

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
Current implementation uses System.currentTimeMillis() instead of Time.currentTimeMillis() to get state start time. This may create problem in unit test as it uses simulated time controlled by Storm Time util.
> [STORM-3129]: Fixed startTime assignment to using Storm Time util.

- examples/storm-jms-examples/pom.xml
- examples/storm-mqtt-examples/pom.xml
- examples/storm-mqtt-examples/src/main/java/org/apache/storm/mqtt/examples/CustomMessageMapper.java
- examples/storm-rocketmq-examples/pom.xml
- examples/storm-rocketmq-examples/src/main/java/org/apache/storm/rocketmq/topology/WordCountTopology.java
- examples/storm-rocketmq-examples/src/main/java/org/apache/storm/rocketmq/trident/WordCountTrident.java
- external/storm-jms/pom.xml
- external/storm-mqtt/pom.xml
- pom.xml
This updates some dependencies for the jms examples, mqtt examples, rocketmq examples, and updates activemq implementation used for testing jms, rocketmq, and activemq.
I ran some manual tests of the example topologies that I could find. I couldn't make all of them really work, because there was no clear documentation about most of them on how to setup or run the example topologies.
mqtt examples using flink had no documentation at all so I wasn't able to successfully run anything. storm-jms-examples fails with what appears to be a JNI issue, but it fails exactly the same way on 1.2.3-SNAPSHOT too.
If someone with more experience with these could improve the documentation about how to run them that would be great.
>  STORM-3061: rocket, jms, and mqtt updates

- .travis.yml
- dev-tools/travis/travis-script.sh
- external/storm-opentsdb/pom.xml
- integration-test/config/Vagrantfile
- integration-test/config/storm-java9.yaml
- integration-test/run-it.sh
- pom.xml
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-webapp/pom.xml
https://issues.apache.org/jira/browse/STORM-3119
There are some changes in this PR that are only tangentially related to building with JDK10, namely fixes to some flaky tests that would have made it a pain to add extra test runs to every PR.
Changes:
* Add Java 10 to the Travis build matrix. Storm-cassandra and storm-hive are excluded, because Cassandra and Hive aren't Java 9+ compatible yet.
* Add relevant Java EE APIs to components that use Jersey. The Java EE APIs aren't available without add-modules in Java 9+, so we should include them explicitly as dependencies. This is already done in most of the components, but missed a few spots.
* The integration test Vagrant box has been updated so the user's name is vagrant rather than ubuntu, fix this in the scripts
* Added environment …
> STORM-3119: Build Storm with Java 10

- external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkCoordinator.java
- external/storm-kafka/src/test/org/apache/storm/kafka/TestUtils.java
- external/storm-kafka/src/test/org/apache/storm/kafka/ZkCoordinatorTest.java
In the current implementation of `ZkCoordinator` deleted partition managers are used as state holders for newly created partition managers. Such behaviour was introduced in the scope of [this](https://issues.apache.org/jira/browse/STORM-2296) ticket. However existing lookup is based only on partition number.
```
Map<Integer, PartitionManager> deletedManagers = new HashMap<>();
for (Partition id : deletedPartitions) {
deletedManagers.put(id.partition, _managers.remove(id));
}
for (PartitionManager manager : deletedManagers.values()) {
if (manager != null) manager.close();
}
LOG.info(taskPrefix(_taskIndex, _totalTasks, _taskId) + " New partition managers: " + newPartitions.toString());
for (Partition id : newPartitions) {
PartitionManager man = new PartitionManager(
_connections, …
```
> STORM-3090 - Fix bug when different topics use the same offset for a partition

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
There is a problem with all the storm-hdfs junit tests. The test results may not be valid.
> STORM-3028 HdfsSpout: handle empty file in case of ackers

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
`FindNMatches()` didn't correctly filter out empty match result in `substringSearch()` and hence send back an empty map to user. I don't know if this the desired behavior but a fix to current behavior will make metrics for logviewer easier to implement.
An example of current behavior:
```Json
{
"fileOffset": 1,
"searchString": "sdf",
"matches": [
{
"searchString": "sdf",
"fileName": "word-count-1-1530815972/6701/worker.log",
"matches": [],
"port": "6701",
"isDaemon": "no",
"startByteOffset": 0
}
]
}
```
Desired behavior:
```Json
{
"fileOffset": 1,
"searchString": "sdf",
"matches": []
}
```
> STORM-3143: Fixed bug of unnecessary inclusion of empty search result

- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
The file is not properly put in the try-with-resource/try-finally block.
> STORM-3159: Fixed a potential file resource leak.

- storm-server/src/main/java/org/apache/storm/LocalCluster.java
When topology.min.replication.count is set to more than 1, nimbus in local mode
never achieve condition for replication, hence stuck on handling blobs.
We should force set it to 1 in local mode to avoid this situation.
Will also submit patch for 1.x-branch.
> STORM-3161 Local mode should force setting min replication count to 1

- pom.xml
- storm-core/pom.xml
- storm-core/test/clj/org/apache/storm/metrics_test.clj
- storm-core/test/resources/log4j2-test.xml
This ports back #2735 to 1.x-branch since I can see flaky metrics tests from 1.x-branch.
https://travis-ci.org/apache/storm/jobs/408847970#L1079-L1082
I also fixed merge conflict so would like to review rather than pushing the change without notice.
@srdo Could you take a look? Thanks in advance!
> (1.x) STORM-3121: Fix flaky metrics tests in storm-core

- storm-multilang/python/src/main/resources/resources/storm.py
Misuse of `traceback.format_exc` was causing exceptions thrown in python bolts to throw `TypeError`s during attempts to handle them. Fixing the calls results in expect behaviour.
Examples of the change can be seen below where the Storm side messages have been mocked so as to directly inspect the python side response. Lines prefixed with `#` are the prompt, `>` are `stdin` (manually entered) and `>` denotes `stdout`. Unprefixed lines are `stderr`.
https://issues.apache.org/jira/browse/STORM-3164
**Test Code**
```py
from storm import Bolt
class TestBolt(Bolt):
def process(self, tup):
raise Exception('harakiri!')
if __name__ == '__main__':
TestBolt().run()
```
```sh
while true; do
printf '> ' > /dev/tty
read line
echo "$line"
sleep 0.1
printf '\n' # trigger sigpipe if python is dead
done | …
```
> STORM-3164: Fix usage of traceback.format_exc in multilang

- storm-multilang/python/src/main/resources/resources/storm.py
> STORM-3164: Fix usage of traceback.format_exc in multilang (BACKPORT)

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
- storm-server/src/main/java/org/apache/storm/metric/StormMetricsRegistry.java
- storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/MetricsCleaner.java
- storm-server/src/main/java/org/apache/storm/pacemaker/Pacemaker.java
- storm-server/src/main/java/org/apache/storm/scheduler/blacklist/BlacklistScheduler.java
> STORM-3150: Improve Gauge registration methods and refactored code

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
Just catching and logging any error that may be occurring.
> STORM-3168 prevent AsyncLocalizer cleanup from crashing

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/testsupport/MockRemovableFileBuilder.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/utils/LogCleanerTest.java
https://issues.apache.org/jira/browse/STORM-3170
> STORM-3170: Fixed bug to eliminate invalid file deletion

- storm-client/src/jvm/org/apache/storm/daemon/supervisor/ClientSupervisorUtils.java
- storm-client/src/jvm/org/apache/storm/utils/ShellUtils.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/TimedWritableByteChannel.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/TimerDecoratedAssignment.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/main/java/org/apache/storm/localizer/PortAndAssignmentImpl.java
- storm-server/src/main/java/org/apache/storm/localizer/TimePortAndAssignment.java
- storm-server/src/main/java/org/apache/storm/metric/StormMetricsRegistry.java
- storm-server/src/main/java/org/apache/storm/metric/timed/Timed.java
- storm-server/src/main/java/org/apache/storm/metric/timed/TimedResource.java
- storm-server/src/main/java/org/apache/storm/metric/timed/TimerDecorated.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
- storm-server/src/test/java/org/apache/storm/localizer/LocalizedResourceRetentionSetTest.java
- storm-webapp/src/main/java/org/apache/storm/daemon/drpc/DRPCServer.java
- storm-webapp/src/main/java/org/apache/storm/daemon/drpc/webapp/DRPCResource.java
This PR depends on #2743 and #2771.
New supervisor level metrics: 
- Worker Kill/Restart Statistics
- The metrics records the duration machine spent in each state (in histogram) and how many times it transitions into/out from a certain state.
- This does not tracks `storm kill_workers` as it's a client-side command and does not invoke StormMetricsRegistry.
- This does not tracks duration for `cleanupForRelaunch`.
- Simply report every time it restarts.
- I assume this to be [the complete process] from initiating download to commit download to local blob cache and inform relative workers
- This is tracks the actual download rate of a blob retrieval, in MB/s
- I put this inside async localizer as it turns out to be better suited for purpose. This tracks the time for a topology blob download …
> STORM-3099: Extend metrics on supervisor, workers and DRPC

- storm-client/src/jvm/org/apache/storm/scheduler/WorkerSlot.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/SupervisorUtils.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/main/java/org/apache/storm/metric/StormMetricsRegistry.java
- storm-server/src/main/java/org/apache/storm/nimbus/LeaderListenerCallback.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/ExecutorDetails.java
- storm-server/src/test/java/org/apache/storm/metric/StormMetricsRegistryTest.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogPageHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DeletionMeta.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/ExceptionMeters.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogCleaner.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogFileDownloader.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogviewerResponseBuilder.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/WorkerLogs.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/webapp/LogviewerResource.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandlerTest.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/utils/LogCleanerTest.java
This PR is based on #2743, #2771 , #2787 , and #2788 and implements the following metrics:
LogViewer:
- Does not track common IO exceptions thrown by File#getCanonicalFile/File#getCanonicalPath(), as it's common but does not actually try to open or read file content
- Does not track meta file IO exception
Nimbus:
> STORM-3133: Extend metrics on Nimbus and LogViewer

- external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractAutoCreds.java
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java
- storm-core/src/jvm/org/apache/storm/utils/ConfigUtils.java
- storm-core/src/jvm/org/apache/storm/validation/ConfigValidationAnnotations.java
- storm-core/test/jvm/org/apache/storm/utils/ConfigUtilsTest.java
Introduce a `Password` config annotation and use it to mark configs that are
sensitive and mask the values while logging.
> STORM-3184: Mask the plaintext passwords from the logs

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/Config.java
The topology submission can fail since redact-value expects a clojure map. We don't need redact-value, it can be replaced with ConfigUtils.maskPasswords. This is already done in master.
> STORM-3184: Replace the usage of redact-value with ConfigUtils.maskPasswords

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedTopologyBlob.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
This adds back in some permission updates and a directory creation that was missed previously.
I have manually tested it and it works.
The old code is at
https://github.com/apache/storm/blob/d2d6f40344e6cc92ab07f3a462d577ef6b61f8b1/storm-core/src/jvm/org/apache/storm/localizer/AsyncLocalizer.java#L101-L165
> STORM-3203: add back in the permission updates

- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStore.java
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/test/jvm/org/apache/storm/utils/ConfigUtilsTest.java
https://issues.apache.org/jira/browse/STORM-3131
With this feature, we can set 
```
blobstore.hdfs.principal: <headless-user>/HOSTNAME@domain
```
on nodes(nimbi, supervisors) the `HOSTNAME` will be replaced with the actual hostname on that host.
> [STORM-3131] Support hostname-substitution for blobstore.hdfs.principal

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Fix
```
2018-09-05 16:15:24.927 o.a.s.t.ProcessFunction pool-21-thread-55 [ERROR] Internal error processing getComponentPageInfo
java.lang.RuntimeException: java.lang.NullPointerException
at org.apache.storm.daemon.nimbus.Nimbus.getComponentPageInfo(Nimbus.java:4238) ~[storm-server-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:4577) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.generated.Nimbus$Processor$getComponentPageInfo.getResult(Nimbus.java:4556) ~[storm-client-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.thrift.ProcessFunction.process(ProcessFunction.java:38) [shaded-deps-2.0.0-SNAPSHOT.jar:2.0.0-SNAPSHOT]
at org.apache.storm.thrift.TBaseProcessor.process(TBaseProcessor.j …
```
> [STORM-3213] fix server error on system component page on storm UI

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Storm should only validate client-side conf when user submits a topology. 
Otherwise settings like `logviewer.https.port=-1` will fail the submission.
> [STORM-3206] validate topoConf only against Config.java during submission

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/component.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/deep_search_result.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/index.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/js/script.js
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/logviewer_search.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/search_result.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/supervisor.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/topology.html
Some of this was motivated for cases where nimbus was down the UI would not report any errors.  The goal here is to make sure that errors in as many cases as possible appear on the UI when they happen.
> STORM-3219:  Update javascript to report errors consistently

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
KafkaSpout internally maintains a waitingToEmit list per topic partition and keeps removing the first item to emit during each nextTuple. The implementation uses an ArrayList which results in un-necessary traversal and copy for each tuple.
> STORM-3222: Fix KafkaSpout internals to use LinkedList instead of ArrayList

- storm-client/pom.xml
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
- storm-client/src/jvm/org/apache/storm/stats/BoltExecutorStats.java
- storm-client/src/jvm/org/apache/storm/stats/ClientStatsUtil.java
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-server/pom.xml
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/HeartbeatCache.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java
This is an alternative to #2800 
@zd-project I had such trouble really understanding what was happening with the heartbeat cache, because it was spread throughout so many files that I couldn't really be sure that #2800 would fix the issues or not.
I decided that I needed to refactor the code to really understand how it worked, and provide a clean interface to the cache, which is what I did.  Once I had that it became clear to me that #2800 would fix the immediate issue, but there were other races in the code, especially with the caches for the executors.  This is probably not a big deal but I felt it would be best to just fix it too.
> STORM-3162: Cleanup heartbeats cache and make it thread safe

- pom.xml
Updated zookeeper client to version 3.4.13 which fixes various issues including ZOOKEEPER-2184 that prevents ZooKeeper Java clients working in dynamic IP (container / cloud) environment.
> STORM-3233 Update zookeeper client to version 3.4.13

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/security/auth/workertoken/WorkerTokenManager.java
- storm-server/src/test/java/org/apache/storm/security/auth/workertoken/WorkerTokenTest.java
- Fix broken condition to validate if new `WorkerToken` should be added.
- Refactor code out of `Nimbus` into `WorkerTokenManager`
- Updated `WorkerTokenTest` to ensure `WorkerTokenManager` recognizes token ready for renewal.
> [STORM-3235] Fix WorkerToken renewal criteria and refactor

- docs/Command-line-client.md
Noticed a typo in the CLI docs.
> Fix typo: indifinitely => indefinitely

- DEVELOPER.md
- dev-tools/travis/travis-install.sh
- dev-tools/travis/travis-script.sh
- pom.xml
The existing modules have been moved into like-named Maven profiles that
are enabled by default.
They can be disabled, for example, with:
```
mvn clean install -DskipTests=true -P '!examples,!externals'
```
> STORM-3242: Adds "examples" and "externals" profiles

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/search_result.html
https://www.w3schools.com/js/js_this.asp
> In a function definition, this refers to the "owner" of the function.
When we wrapped this in an anonymous function, the data that `this` pointed to changed. So it is a simple fix to pull the variable from the outer scope.
> STORM-3238: Reduces scope of wrapper, corrects variable

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java
- external/storm-hive/src/main/java/org/apache/storm/hive/trident/HiveState.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-server/src/main/java/org/apache/storm/blobstore/LocalFsBlobStore.java
- storm-server/src/main/java/org/apache/storm/daemon/drpc/DRPC.java
Turns out there are two things blocking nimbus from shutting down.
1) some timer (that turns out to be from the local fs blobstore.
2) The thread that was waiting for the timeout before calling halt was also stopping us from shutting down :)
> STORM-3249: Make sure times shut down and so does shut down thread

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
Delay in blobstore can cause slot to become unusable.
> [STORM-3254] Don't wait for localization of blobs if assignments change.

- docs/FAQ.md
- storm-client/src/jvm/org/apache/storm/topology/TopologyBuilder.java
ISpout has an `open` method instead of a `prepare` method.
> Clarify spout non-serializable field exception message

- docs/Kestrel-and-Storm.md
- docs/SECURITY.md
- docs/Understanding-the-parallelism-of-a-Storm-topology.md
- docs/index.md
I stumbled across some Markdown syntax errors in the documentation and fixed them, as well as minor typos which I found. I thought this was nothing I should open an issue for first, or should I?
> Fix Markdown errors and minor typos in the documentation.

- .travis.yml
https://issues.apache.org/jira/browse/STORM-3267
We can add Java 11 at some later point, but for now we need to disable the Java 10 build.
> STORM-3267: Disable Java 10 build

- .travis.yml
- integration-test/src/main/java/org/apache/storm/ExclamationTopology.java
- integration-test/src/main/java/org/apache/storm/st/topology/TestableTopology.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/IncrementingSpout.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/SlidingTimeCorrectness.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/SlidingWindowCorrectness.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/TimeDataIncrementingSpout.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/TumblingTimeCorrectness.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/TumblingWindowCorrectness.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/VerificationBolt.java
- integration-test/src/main/java/org/apache/storm/st/topology/window/data/TimeDataWindow.java
- integration-test/src/main/java/org/apache/storm/st/utils/StringDecorator.java
- integration-test/src/test/java/org/apache/storm/st/DemoTest.java
- integration-test/src/test/java/org/apache/storm/st/tests/window/SlidingWindowTest.java
- integration-test/src/test/java/org/apache/storm/st/tests/window/WindowVerifier.java
- integration-test/src/test/java/org/apache/storm/st/wrapper/TopoWrap.java
https://issues.apache.org/jira/browse/STORM-3268
Basically the integration test can't handle logs rolling during the test. To fix this we added a bit of time between spout emits, but I don't think it was enough. I've put a limit on how many tuples the spouts will emit during the tests, which should prevent the logs from growing too much.
Some tests use multiple bolt/spout tasks, and don't wait for all executors to be started. In some cases tests could fail because e.g. two spout instances were supposed to run, but one executor was slow to start so the log for that executor wasn't picked up when the test asked Nimbus for logs for the spout component. The tests now check that Nimbus has all expected executors listed.
The tests extract spout/bolt logs by looking for a magic string. If …
> STORM-3268: Improve integration test stability

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/js/script.js
See the jira for the before/after screenshot. I tested with the following in the chrome console: 
```
myData = $('#owner-summary-table').DataTable().data()
$('#owner-summary-table').DataTable().destroy()
$.extend( $.fn.dataTableExt.oSort, {
"resource-num-pre": function(raw) {
if (raw == 'N/A') {
return Number.NEGATIVE_INFINITY;
} else {
return $.fn.dataTableExt.oSort['num-pre'](raw);
}
},
"resource-num-asc": $.fn.dataTableExt.oSort['num-asc'],
"resource-num-desc": $.fn.dataTableExt.oSort['num-desc']
});
// paste in new definition of makeOwnerSummaryTable as myOwnerTable...
myOwnerTable('#owner-summary-table', '#owner-summary')
```
> [STORM-3263] Fix sorting by owner resources in the UI

- storm-core/src/native/worker-launcher/impl/worker-launcher.c
When a topology folder contains a symlink to a missing file, the worker-launcher would not remove the symlink.  This prevents force delete from deleting the folder when cleaning up a topology.  
When a cluster is short on resources, this can cause all sorts of issues on the supervisor when rescheduling the same topology when this folder still exists.
> STORM-3272 allow worker-launcher to delete dead symlinks

- bin/flight.bash
https://issues.apache.org/jira/browse/STORM-3278
Without the change, the permission on the heap dump file is `-rw-------`. And it belongs to the topology submitter. Logviewer is not able to read it.
> [STORM-3278] Fix permissions issue on logviewer downloading for heap dump

- bin/flight.bash
https://issues.apache.org/jira/browse/STORM-3265
If JAVA_HOME is not set, or `/usr/bin/java` not available, we should just use java directly
> [STORM-3265] flight.bash fall back to use java utils directly if $JAVA_HOME not set or java not avaialble in $BINPATH

- storm-client/src/jvm/org/apache/storm/topology/ConfigurableTopology.java
The ConfigurableTopology can take configuration files where the values are put under a single config element to be compatible with Flux. This PR fixes a bug when multiple configs are set, the last one will overwrite any preexisting value as everything is put under the same key 'config'
> bugfix ConfigurableTopology completely overwrites preexisting config

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
The Jprofiler start action, requires calculating timeout in milliseconds, while input is in minutes. Also, the logic works to say, STOP at timeout instead of start. This was I think clojure to java translation error.
> [STORM-3275] Fix UIHelpers timeout while starting profiler

- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedTopologyBlob.java
Turns out that python has a common directory called `/pkg_resources/` which gets mangled badly without this fix.
> STORM-3288: Fix issue with reources in jar files

- docs/storm-kafka-client.md
See https://issues.apache.org/jira/browse/STORM-3289.
>  STORM-3289: Add note about KAFKA-7044 to storm-kafka-client compatibility documentation

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
- storm-client/src/jvm/org/apache/storm/utils/InprocMessaging.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/src/jvm/org/apache/storm/zookeeper/ClientZookeeper.java
- storm-core/pom.xml
- storm-core/test/jvm/org/apache/storm/integration/TestingTest.java
- storm-core/test/jvm/org/apache/storm/integration/TopologyIntegrationTest.java
- storm-server/pom.xml
- storm-server/src/main/java/org/apache/storm/LocalCluster.java
- storm-server/src/test/java/org/apache/storm/AssertLoop.java
- storm-server/src/test/java/org/apache/storm/TickTupleTest.java
- storm-server/src/test/resources/log4j2.xml
https://issues.apache.org/jira/browse/STORM-3309
I've made the following changes:
* When message timeout is disabled, the acker shouldn't time out tuples. Disable ticks for the acker if message timeouts are disabled
* The spout and bolt executors don't integrate with time simulation, in the sense that they don't require simulated time to increment in order to run. This is fine, but if they aren't going to pause for simulated time to increase, they also shouldn't potentially pause during initialization, waiting for Nimbus to activate the topology.
* InProcMessaging (used by the FeederSpout) will wait for the receiver to show up when sending the initial message. It waits at most 20 seconds, but if time simulation is enabled, it only waits 2. This is not enough for the topology/spout to …
> STORM-3309: Fix flaky tick tuple test

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/RecordTranslator.java
According to KafkaSpout implementation, record is discarded if
Builder.setEmitNullTuples is set to `false`, instead of `true`.
> Doc clarification on returning `null` from RecordTranslator.apply()

- examples/storm-kafka-client-examples/README.markdown
The kafka_artifact_id parameter is not used anymore.
> MINOR: Remove unused parameter from storm-kafka-client-example docs

- storm-client/src/jvm/org/apache/storm/task/IBolt.java
- storm-core/test/clj/org/apache/storm/scheduler/multitenant_scheduler_test.clj
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/scheduler/IScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/blacklist/BlacklistScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/GenericResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/IStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/blacklist/TestBlacklistScheduler.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/eviction/TestDefaultEvictionStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/priority/TestFIFOSchedulingPriorityStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
This is based on a couple of internal PRs @govind-menon committed to our older version of storm.
> STORM-3335 allow timing out when scheduling a topology

- dev-tools/rc/verify-release-file.sh
Apache Storm's release process has changed to use sha512 instead of sha, but it is not reflected to release verify script. This patch applies to the change.
> [MINOR] Update release verify script - 'sha' to 'sha512'

- examples/storm-starter/pom.xml
https://jira.apache.org/jira/browse/STORM-3347
> STORM-3347: Don't use maven-exec-plugin in storm-starter

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocalizedResource.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedTopologyBlob.java
- storm-server/src/test/java/org/apache/storm/daemon/supervisor/SlotTest.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
https://issues.apache.org/jira/browse/STORM-3319
In addition to fixing the failing assertion, I've also fixed a deadlock between AsyncLocalizer and Slot.
The latch AsyncLocalizer is waiting for is counted down by Slot, but Slot may be stuck trying to enter other synchronized methods on the blob instance.
> STORM-3319: Fix failing assertion in Slot

- pom.xml
https://issues.apache.org/jira/browse/STORM-3352
The dependency tree for storm-cassandra previously showed
```
org.apache.storm:storm-cassandra:jar:2.0.1-SNAPSHOT
[INFO] +- com.datastax.cassandra:cassandra-driver-core:jar:3.1.2:provided
[INFO] |  +- io.netty:netty-handler:jar:4.0.37.Final:provided
[INFO] |  |  +- io.netty:netty-buffer:jar:4.0.37.Final:provided
[INFO] |  |  |  \- io.netty:netty-common:jar:4.0.37.Final:provided
[INFO] |  |  +- io.netty:netty-transport:jar:4.0.37.Final:provided
[INFO] |  |  \- io.netty:netty-codec:jar:4.0.37.Final:provided
...
- io.netty:netty-all:jar:4.1.30.Final:test
```
which is likely to cause issues.
> STORM-3352: Lock Netty versions using Netty BOM

- bin/storm.py
- pom.xml
- storm-submit-tools/pom.xml
- storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/RepositorySystemFactory.java
Please refer [STORM-3363](https://issues.apache.org/jira/browse/STORM-3363) for more details.
Other than migrating Aether to maven-resolver, this patch also contains a minor fix which storm cli incorrectly parses `artifacts` and `artifactRepositories`. Looks like STORM-3274 changed the behavior but not tested the case.
(Oddly my local dev. cannot run tests because of somewhat issue with `mock` and `python3`. I'll see whether the change breaks cli test in Travis CI build, and fix it if any.)
> STORM-3363: Migrate Aether to maven-resolver as Aether is donated to ASF

- conf/defaults.yaml
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
While testing supporting a fixed maximum CPU limit, we found that workers with small amounts of CPU failed to start within the configured timeout period.  This PR allows configuring a minimum threshold of CPU for a worker to allow them to come up within a reasonable amount of time.
> STORM-3366 allow configuring workers to have a minimum cpu percentage

- conf/defaults.yaml
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
Sometimes Kafka broker is unreachable/security can cause issue..making UI hang for too long.  So adding feature to allow disabling Topology Lag monitoring.
> [STORM-3365] Configuration to disable Topology Lag Monitoring

- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/mapper/DelimitedRecordHiveMapper.java
- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/mapper/JsonRecordHiveMapper.java
new Date() is just a thin wrapper around System.currentTimeMillis(). Using System.currentTimeMillis() can help avoid to create a new Date object and the system can speed up.
>  STORM-3375 change Date.getTime() to System.currentTimeMillis()

- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOffer.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResources.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
Fixed issue with RAS_Node couldEverFit() and check within Cluster. wouldFit() with minWorkerCpu set.
> STORM-3377 fix scheduling bug with min worker cpu enabled

- storm-core/src/clj/org/apache/storm/command/set_log_level.clj
https://issues.apache.org/jira/browse/STORM-3384
Fix
```
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: IllegalArgumentException for class java.lang.String
```
> [STORM-3384] set-log-level command throws wrong exception if the topology is not running

- pom.xml
https://issues.apache.org/jira/browse/STORM-3386
Checked that the build now won't run on 3.3.9, but will run on 3.5.0 and 3.6.1.
> STORM-3386: Require Maven version 3.5.0 for Storm's build

- examples/storm-perf/src/main/java/org/apache/storm/perf/JCQueuePerfTest.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/format/TestSimpleFileNameFormat.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
- storm-client/src/jvm/org/apache/storm/daemon/Task.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerTransfer.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
- storm-client/src/jvm/org/apache/storm/metrics2/TaskMetrics.java
- storm-client/src/jvm/org/apache/storm/task/IMetricsContext.java
- storm-client/src/jvm/org/apache/storm/task/TopologyContext.java
- storm-client/src/jvm/org/apache/storm/trident/operation/TridentOperationContext.java
- storm-client/src/jvm/org/apache/storm/utils/JCQueue.java
- storm-client/test/jvm/org/apache/storm/utils/JCQueueBackpressureTest.java
- storm-client/test/jvm/org/apache/storm/utils/JCQueueTest.java
- storm-server/src/main/java/org/apache/storm/Testing.java
https://issues.apache.org/jira/browse/STORM-3371
Adds on to STORM-3370.
Metrics v2 is currently inaccessible from Trident operations. This should fix that.
> STORM-3371: Metrics v2 in Trident operations

- dev-tools/travis/requirements.txt
https://issues.apache.org/jira/browse/STORM-3390
> STORM-3390: Lock python test dependency versions

- storm-client/src/jvm/org/apache/storm/daemon/supervisor/ClientSupervisorUtils.java
https://issues.apache.org/jira/browse/STORM-3385
This is not causing any problem so far. But having two threads are reading from the same input stream doesn't seem right.
> [STORM-3385] Avoid two threads reading from the same input stream of a process

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Placeholder system components now filtered by Show/Hide System Stats. Always filters out the **__system** bolt since this is suppressed on the non-placeholder web page.
> STORM-3394 Fix placeholder system bolt filtering for Topology page

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/dependency/DependencyUploader.java
when storm client and server is locating in different IDC(one is in Beijing, while another in Shanghai), uploading dependency jars may take a very long long time(in my case, 31minutes!)...
when I digged into this, I found that in DependencyUploader,  method "uploadDependencyToBlobStore" using JDK NIO's Files.copy to upload local jars to remote Blob server. In Files.copy(Path, OutputStream), the buffer size is 8k by default, given that latency between Beijing and Shanghai is about 20ms, a dependency fat jar of 360M finally cost me 'a lunch time' to finish uploading!!!
> STORM-3396:fix uploading dependency jars too slow when storm client and server located in different IDC

- docs/metrics_v2.md
In the documentation about metrics v2, the class name of the csv is `CsvReporter`, when it actually should be `CsvStormReporter`.
Is it enough to merge this into master, or should I also ask to merge this into a branch like `1.1.x`, such that it can be fixed on all relevant online docs?
> Fix class name of CsvStormReporter

- storm-checkstyle/src/main/resources/storm/storm_checkstyle.xml
Remove JavadocMethod checkstyle rule because it requires tons of Javadocs to be invented on files which have not been touched for years and whose Javadoc can be covered with clean code.
> [STORM-3414] Remove JavadocMethod checkstyle rule

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
When click into topology page from Storm UI, the issue-tracker and central-log icons located on top-right corner will disappear even if the links exist in config.
> [STORM-3412] Fix Jira And Centrol Log links in topology page

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/WorkerLogs.java
Used to be:
2019-06-20T20:38:11.626Z gsbl839n04.blue.ygrid.yahoo.com [logviewer][99056] No more files able to delete this round, but this directory is over quota by 5269.828259999999 MB
2019-06-20T20:38:11.626Z gsbl839n04.blue.ygrid.yahoo.com [logviewer][99056] No more files able to delete this round, but this directory is over quota by 5269.828259999999 MB
2019-06-20T20:38:11.626Z gsbl839n04.blue.ygrid.yahoo.com [logviewer][99056] No more files able to delete this round, but this directory is over quota by 5269.828259999999 MB
Now:
2019-06-25 20:00:02.135 o.a.s.d.l.u.DirectoryCleaner logviewer-cleanup [WARN] No more files eligible to be deleted this round, but worker directory: /home/y/var/storm/workers-artifacts/wc-1-1560810826/6700 is over per-worker quota by 77.559234 MB
2019-06-25 …
> [STORM-3423] improve logviewer directory cleaner logging

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogDownloadHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerProfileHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogFileDownloader.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogviewerResponseBuilder.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/webapp/LogviewerResource.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogDownloadHandlerTest.java
- storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/handler/LogviewerProfileHandlerTest.java
Add more information to worker.log download response builder. This can help facilitate debugging efficiency.
> [STORM-3411] add parent dir name to downloaded worker log file

- bin/storm-kafka-monitor
issue link : [STORM-3466](https://issues.apache.org/jira/browse/STORM-3466)
In storm 2.0.0, there was a "not find jar error" when running storm-kafka-monitor.
I solved this by adding "" to the jar file classpath.
> STORM-3466: storm-kafka-monitor: fix not found jar

- RELEASING.md
- pom.xml
This is adapted from Taylor's description of how to release. I think we should have a document like this in the repo. Suggestions are welcome.
> MINOR: Add release process document

- storm-client/src/jvm/org/apache/storm/security/auth/sasl/SimpleSaslServerCallbackHandler.java
Fixes a possible null dereference in the case that nid is null on line 183. Switch to using a more flexible method of comparison (Objects.compare()) which will correctly compare one null on one non-null or two null values.
> STORM-3470: fix null dereference in SimpleSaslServer authentication

- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
If you're not very familiar with Kerberos, having more explicit instructions in these error messages can be helpful.
> MINOR: Clarify error message when TGT has problems

- external/storm-hdfs-blobstore/pom.xml
- external/storm-hdfs-blobstore/src/test/java/org/apache/storm/hdfs/blobstore/BlobStoreTest.java
- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/format/TestSimpleFileNameFormat.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSemantics.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterExtension.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterRule.java
- external/storm-hdfs/src/test/resources/log4j.properties
- external/storm-hdfs/src/test/resources/log4j2.xml
- pom.xml
… not running
https://issues.apache.org/jira/browse/STORM-3372
https://issues.apache.org/jira/browse/STORM-2810 broke storm-hdfs tests by forgetting to run them. The MiniDFSClusterRule doesn't invoke the test, so all the tests just pass. Oops.
> STORM-3372: Fix NPE when shutting down HdfsBolt, fix storm-hdfs tests not running

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
https://issues.apache.org/jira/browse/STORM-3481
1. Use cluster.getConf for daemon configs.
2. remove invalid code block that was introduced by mistake.
> [STORM-3481] fix IllegalArgumentException for ConstraintSolverStrategy

- storm-client/src/jvm/org/apache/storm/task/ShellBolt.java
Refer to https://issues.apache.org/jira/browse/STORM-3491
> [STORM-3491] BoltReaderRunnable shouldn't throw IllegalArgumentException for sync command

- pom.xml
I think this is not needed. And it can be confusing when it's not updated correctly
> MINOR: remove scm tag in pom.xml

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-server/pom.xml
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/TopologyResources.java
- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignment.java
- storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignmentImpl.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourcesExtension.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
Implements One Worker Per Executor Option
In the process of implementing, also encountered and fixed 2 bugs
- typo in `Cluster:: calculateWorkerResources` incorrectly adds wrong type of memory `totalResources.addOnHeap(shared.get_off_heap_worker());' https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java#L507
- bad cached worker resource value. `Cluster::nodeToScheduledResourcesCache` maps from node to WorkerSlot -> NormalizedResourceRequest. In `Cluster::updateCachesForWorkerSlot` value added was incorrectly adding shared OffHeapNode memory. This could result in overcounting used memory, and subsequent reporting negative resources in  `RAS_Node::getTotalAvailableResources.
> STORM-3480 Implement One Worker Per Executor RAS Option

- bin/storm
This is specially needed on FreeBSD because there is no "python" = there is python2.7
>  STORM-3493: Allow overriding python interpreter by environment variable

- storm-core/src/jvm/org/apache/storm/command/KillTopology.java
Adds a new `-i` parameter to `storm kill`. When passed, we will attempt to kill all listed topologies even if an error occurs.
> [STORM-3257] 'storm kill' command line should be able to continue on error

- storm-client/src/jvm/org/apache/storm/daemon/supervisor/AdvancedFSOps.java
- storm-client/src/jvm/org/apache/storm/daemon/supervisor/IAdvancedFSOps.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedTopologyBlob.java
- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
Creating resources directory if it does not exist in resources jar or in classpath.
Moved a bit of code to make mocking easier.
Happy to hear about your thoughts.
> [STORM-3501] local cluster worker restarts because of missing resources folder

- storm-client/src/jvm/org/apache/storm/utils/LocalState.java
- storm-server/src/test/java/org/apache/storm/LocalStateTest.java
When a windows machine has a power failure, the local state file can
become corrupted with repeated NUL characters. On restart, when the
supervisor attempts to get the worker's heartbeat it will fail to
deserialized the LocalStateData (because it is all NUL characters) and
it will fail to start the workers.
> STORM-1515: Fix LocalState Corruption

- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
increase scheduling timeout in TestConstraintSolverStrategy.testScheduleLargeExecutorConstraintCount() to 120 seconds, overriding prior default of 60 seconds. Some VMs takes longer than 60 seconds when parallelismMultiplier=20.
> [STORM-3525] Increase timeout TestConstraintSolverStrategy.testScheduleLargeExecutorConstraintCount

- RELEASING.md
- dev-tools/rc/verify-release-file.sh
This creates a checklist so new devs have a better idea on reviewing a release
> MINOR: create a checklist for testing a new Storm release

- flux/flux-core/src/main/java/org/apache/storm/flux/parser/FluxParser.java
- flux/flux-core/src/test/java/org/apache/storm/flux/TCKTest.java
- flux/flux-core/src/test/resources/configs/substitution-test.yaml
This MR adds support for accessing elements of list properties in configurations of FluxParser.
The reference of list items can be done as:
```yaml
list.element.property.target: ${a.list.property[0]}
```
Additionally, refactors the code a bit more efficient and lighter on memory.
> STORM-3066: Implement support for using list elements in properties in FluxParser

- storm-client/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
- storm-client/test/jvm/org/apache/storm/topology/WindowedBoltExecutorTest.java
Avoid NPE in WindowedBoltExecutor when the wrapped bolt returns a null configuration.
> STORM-3211: Fix NPE in WindowedBoltExecutor on getComponentConfiguration

- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/IStrategy.java
When topology fails to schedule due to insufficient resources, add to topology status message:
1. Specific scheduling failure text
2. Include available resources along with required
> STORM-3530 Improve scheduling failure messages

- SECURITY.md
- docs/SECURITY.md
I spent a whole lot of time trying to figure out why my workers wouldn't start, and it ended up being that i had to open port 6628 (thrift.supervisor.port) on the workers.
This caused me a lot of headache as it is omitted from the documentation.
Can someone confirm that i have the client for this port correct?  I put Nimbus but it might be Zookeeper or other workers, i'm not sure exactly how it works
> Add thrift.supervisor.port to documentation

- storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClientHandler.java
- storm-client/src/jvm/org/apache/storm/pacemaker/codec/ThriftNettyClientCodec.java
"Exception occurred in Pacemaker" message was not logging cause properly until I changed the message for some reason.
Problem:
1) ThriftNettyClientCodec.initChannel() is called, which we map to PacemakerClient.channelReady().
2) We get a pacemaker message to write
3) We see the channel as ready and write/flush the message
4) The flush causes a NotYetConnected exception
5) This triggers a reconnect
6) The reconnect causes us to go to step 1) and we get stuck in a loop failing to talk to Pacemaker
The solution I think is more appropriate:
PacemakerClientHandler.channelActive() should be the one calling PacemakerClient.channelReady().
> STORM-3540 fix Pacemaker connection issues

- docs/Setting-up-a-Storm-cluster.md
- docs/flux.md
Due to argparse in the storm.py script, we actually need at least 2.7
> MINOR: Bump required python version in documentation

- storm-client/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyClient.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyServer.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java
- storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java
- storm-client/src/jvm/org/apache/storm/security/auth/ClientAuthUtils.java
- storm-client/src/jvm/org/apache/storm/security/auth/ITransportPlugin.java
- storm-client/src/jvm/org/apache/storm/security/auth/SimpleTransportPlugin.java
- storm-client/src/jvm/org/apache/storm/security/auth/ThriftClient.java
- storm-client/src/jvm/org/apache/storm/security/auth/ThriftServer.java
- storm-client/src/jvm/org/apache/storm/security/auth/digest/DigestSaslTransportPlugin.java
- storm-client/src/jvm/org/apache/storm/security/auth/digest/JassPasswordProvider.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/ClientCallbackHandler.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/ServerCallbackHandler.java
- storm-client/src/jvm/org/apache/storm/security/auth/sasl/SaslTransportPlugin.java
- storm-client/test/jvm/org/apache/storm/security/auth/ClientAuthUtilsTest.java
- storm-server/src/main/java/org/apache/storm/pacemaker/PacemakerServer.java
- storm-server/src/test/java/org/apache/storm/security/auth/AuthTest.java
Previous to this change, client code would fetch a Configuration from a jaas conf file provided in the topo conf, set the Configuration globally, and then call Login. The Login code would fetch the singleton Configuration and use that to determine the jaas conf entries.
The problem with this is that for external services such as Kafka, if they see a Configuration is set, they could default to using the set Configuration, which may not match the custom jaas conf specified by the user. Rather than setting the Configuration, when we call Login, we should just specify which jaas conf file to use for logging in and read that jaas file Configuration without setting it.
Since the Configuration is now just being read when needed and not set, we do not need to pass it around. The file to use is …
> STORM-3549 allow use of custom jaas conf files for Kafka

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
After a topology is killed, blob updates continue until a cleanup occurs on the supervisor, which also must fall after the nimbus performs a cleanup on the blobs.  Each update fails and retries, even though the blob no longer exists.  
It seemed to me the easiest solution to just not do a blob update for unused blobs.  Testing of this seemed fine.  No more errors in the log file.
> STORM-3545 don't update unused blobs

- .travis.yml
1. maven-3.6.1 got removed from the mirror which breaks the travis build. Change to point to  archive.apache.org.
2. Cache apache-maven directory to avoid frequent download.
> [STORM-3563] Fix broken link for apache-maven download and cache maven directory

- storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java
- storm-server/src/main/java/org/apache/storm/scheduler/blacklist/BlacklistScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/blacklist/strategies/DefaultBlacklistStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/blacklist/TestBlacklistScheduler.java
* Add greylist to cluster state
* When releasing supervisors due to low resources, put these released supervisors to greylist
* When scheduling, these greylisted supervisors will be scheduled only after having gone through other supervisors
> [STORM-3507] add greylist for superviosrs which are forced out of blacklist due to low resources

- docs/metrics_v2.md
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/daemon/Task.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
We would like to be able to report v2 metrics api through the metrics tick, like v1 metrics.  
The main reason (besides keeping one reporter) is to reduce connection load on our openTSDB monitoring service.  Having one node doing reporting for a topology decreases the number of connections.
This also allows an easy migration path for users to the new v2 API.
> STORM-3541 report v2 metrics api in metrics tick

- docs/storm-eventhubs.md
This PR fixes a typo "Azue" -> "Azure" in the title of the `storm/docs/storm-eventhubs.md` page.
cc @krichter722 as author.
> MINOR: Fix typo in storm/docs/storm-eventhubs.md

- .travis.yml
> MINOR: Maven upgrade to 3.6.3

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/topology.html
A minor fix to topo UI. This change alert user when they try to change log level on topology page without providing a logger name.
Currently user can do this and get a 500 Server Error at the bottom which could be confusing.
> [STORM-3568] prevent user from changing log level with empty logger name from topo UI

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
Add topo info whenever killing container could be helpful when debugging issue like worker restarting.
> [STORM-3571] add topo id to log when handle running dynamic state

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java
Explained in the Jira: https://issues.apache.org/jira/browse/STORM-3579
The problem here (and other places as well) is it's not using the correct config (daemon conf vs topology conf). 
`worker.childopts` and `topology.worker.childopts` are JVM parameters used to launch workers. Users can supply their own `java.security.auth.login.config` to the worker. And it should be used for the thrift client used by the worker.
> [STORM-3579]  use the topo conf for thrift client in Worker code

- storm-core/src/jvm/org/apache/storm/command/Rebalance.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
storm.py passes utf encoded "-c" parameters as csv jvm property "storm.options". This system property is not being used in rebalance client command when passing information to Nimbus. Change Rebalance to use this system property.
> [STORM-3580] Processs -c option to storm.py for Rebalance

- storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
So in daemon log (e.g. supervisor), we can see 
```
o.a.s.v.ConfigValidation main [INFO] Will use [class org.apache.storm.DaemonConfig, class org.apache.storm.Config] for validation
```
In worker log, we can see
```
o.a.s.v.ConfigValidation main [INFO] Will use [class org.apache.storm.Config, class org.apache.storm.hdfs.spout.Configs] for validation
```
> [STORM-3581] change log level to INFO to show the config classes being used for validation

- storm-client/src/jvm/org/apache/storm/utils/VersionInfo.java
https://issues.apache.org/jira/browse/STORM-3584
Current VersionInfo.getFromClasspath method only tries to get version info from the specific property file under a directory, or jar/zip files. It should support a classpath entry like `/<parent-path>/*`.
> [STORM-3584] Support getting version info from a wildcard classpath entry

- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
Prevent the problem that consecutive hasNext() calls will lose elements in nodeIterator without using it.
Prevent the problem that consecutive next() calls will skip to post iterator since _nextValueFromNode_ is null even if nodeIterator still have available elements.
> [STORM-3589] Prevent inconsistent results from consecutive hasNext and next calls in LazyNodeSortingIterator

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
- storm-client/src/jvm/org/apache/storm/validation/ConfigValidationAnnotations.java
- storm-client/test/jvm/org/apache/storm/TestConfigValidate.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RasNode.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
Config.TOPOLOGY_RAS_CONSTRAINTS for use by ConstraintSolverStrategy can be specified in a new
compact format that will allow specification of MaxCoLocationCnt.
Config.TOPOLOGY_SPREAD_COMPONENTS is deprecated (and is equivalent to specifying 1 as the MaxNodeCoLocationCnt for the components.
New style Config.TOPOLOGY_RAS_CONSTRAINTS is map where each component has a list of other 
incompatible components and an optional number that specifies the maximum co-location count for the component on a node, example:
<pr/>
{ "comp-1":  { "maxNodeCoLocationCnt": 2, # at most 2 comp-1 on same node
"incompatibleComponents": ["comp-2", "comp-3" ] }, #comp-1 cannot co-exist on same worker with comp-2, comp-3
"comp-2": 
{ "incompatibleComponents": [ "comp-4" ] }, # comp-1 is implied from comp-1 constraint …
> [STORM-3585] New compact Constraint config including maxNodeCoLocationCnt and incompatibleComponents

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
https://issues.apache.org/jira/browse/STORM-3599
A special rocksdbjni version for aarch64 has been released by rocksdb community. [1][2]
This patch bumps the rocksdbjni version to 5.18.4 to make the Storm can be built in aarch64.
[1] https://github.com/facebook/rocksdb/releases/tag/v5.18.4
[2] https://github.com/facebook/rocksdb/pull/6250
> [STORM-3599] Bump the rocksdbjni to 5.18.4

- storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/User.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java
ResourceAwareScheduler creates a FutureTask with timeout specified in DaemonConfig.
ConstraintSolverStrategy uses the the another configuration variable to determine when to terminate its effort. Limit this value so that it terminates at most slightly before TimeoutException. This graceful exit allows result (and its error) to be available in ResourceAwareScheduler.
> [STORM-3587] Allow Scheduler futureTask to gracefully exit before TimeoutException.

- docs/distcache-blobstore.md
- external/storm-blobstore-migration/src/main/java/org/apache/storm/blobstore/ListHDFS.java
- external/storm-blobstore-migration/src/main/java/org/apache/storm/blobstore/MigrateBlobs.java
- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStore.java
- external/storm-hdfs-blobstore/src/test/java/org/apache/storm/hdfs/blobstore/BlobStoreTest.java
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/utils/HadoopLoginUtil.java
- storm-client/test/jvm/org/apache/storm/utils/ConfigUtilsTest.java
`HadoopLoginUtil.loginHadoop(conf);` should be used when login to hadoop from Storm daemons.
Rework https://github.com/apache/storm/pull/3189 by using reflections. This avoids breaking backwards compatibility.
> [STORM-3494] Use UserGroupInformation to login to HDFS only once per process

- storm-client/src/jvm/org/apache/storm/utils/Utils.java
all 15 usages of method were already sending in componentId as first argument, streamId as second argument - so only naming inside of method needed to be changed
> [STORM-2483] misnamed parameters

- docs/ClusterMetrics.md
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
Supervisor relies on AsyncLocalizer to download blobs from blob store. 
AsyncLocalizer uses downloadService pool to process CompletableFuture objects in parallel.
We have noticed a case that while the downloading task is waiting for a thread to execute, new assignment changes will try to release the slot by dereferences all of the related local resources.
However, reading local resources assumes two base blob downloading task have been completed which is not always true.
> [STORM-3583] Handle exceptions when AsyncLocalizer tries to get local resources

- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
An example run:
```
2020-03-25 18:36:59.391 o.a.s.s.a.k.AutoTGT main [INFO] Populating TGT from credentials
2020-03-25 18:36:59.763 o.a.h.u.NativeCodeLoader main [WARN] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-03-25 18:36:59.763 o.a.h.s.JniBasedUnixGroupsNetgroupMappingWithFallback main [INFO] Falling back to shell based
2020-03-25 18:36:59.798 o.a.s.s.a.k.AutoTGT main [INFO] Invoking Hadoop UserGroupInformation.loginUserFromSubject.
2020-03-25 18:36:59.808 o.a.s.s.a.k.AutoTGT main [WARN] UserGroupInformation.loginUserFromSubject will spawn a TGT renewal thread ("TGT Renewer for <username>") to ex
ecute "kinit -R" command some time before the current TGT expires. It will fail because TGT is not in the local TGT cache and …
```
> [STORM-3607] Add warnings about exceptions from hadoop TGT renewal thread

- bin/storm.py
- storm-client/test/py/test_storm_cli.py
Explained in https://issues.apache.org/jira/browse/STORM-3613
> [STORM-3613] storm.py should include lib-worker instead of lib directory in the classpath while submitting a topology

- bin/storm.py
- docs/Command-line-client.md
- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
- storm-core/src/jvm/org/apache/storm/command/UploadCredentials.java
```
-bash-4.1$ storm upload-credentials ec2 -c "password=password"
Running: /home/y/share/yjava_jdk/java/bin/java -client -Ddaemon.name= -Dstorm.options=password%3Dpassword -Dstorm.home=/home/y/lib64/storm/2.2.0.y -Dstorm.log.dir=/home/y/lib64/storm/2.2.0.y/logs -Djava.library.path=/home/y/lib64:/usr/local/lib64:/usr/lib64:/lib64: -Dstorm.conf.file= -cp /home/y/lib64/storm/2.2.0.y/*:/home/y/lib64/storm/2.2.0.y/lib/*:/home/y/lib64/storm/2.2.0.y/extlib/*:/home/y/lib64/storm/2.2.0.y/extlib-daemon/*:/home/y/lib64/storm/current/conf:/home/y/lib64/storm/2.2.0.y/bin org.apache.storm.command.UploadCredentials ec2
03:31:54.653 [main] INFO o.a.s.m.n.Login - Successfully logged in to context StormClient using /etc/grid-keytabs/jaas.conf
03:31:54.662 [Refresh-TGT] INFO o.a.s.m.n.Login - TGT refresh …
```
> [STORM-3616] add optional flag to fail upload-credentials cmd if no creds were uploaded

- storm-server/src/main/java/org/apache/storm/healthcheck/HealthChecker.java
explained at https://issues.apache.org/jira/browse/STORM-3604
Example after fix:
```
19:33:15.633 [main] WARN  o.a.s.h.HealthChecker - The healthcheck process check_1 exited with code 2 and message ERROR: /dir/xxx is owned by incorrect user:group : xxx:yyy
19:33:15.633 [main] INFO  o.a.s.h.HealthChecker - The healthcheck script [ check_1 ] exited with status: failed
```
> [STORM-3604] HealthChecker should print out error message when it fails

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
https://issues.apache.org/jira/browse/STORM-3619
With this change,  submitting a topology with a `null` name will fail with clear message
```
Exception in thread "main" java.lang.IllegalArgumentException: Topology name 'null' is not valid. It can't be null and it must match ^[^/.:\\]+$
```
> [STORM-3619] Add null check for topology name

- storm-client/src/jvm/org/apache/storm/metric/SystemBolt.java
explained in https://issues.apache.org/jira/browse/STORM-3622
> [STORM-3622] use ThreadStatesGaugeSet instead of CachedThreadStatesGaugeSet to avoid race condition in CachedGauge

- external/storm-kafka-migration/pom.xml
https://issues.apache.org/jira/browse/STORM-3626
> [STORM-3626] storm-kafka-migration should ull in storm-client as provided instead of compile dependency

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
This is not a bug. But changing it to make the code more clear.
Orignal message "topology with name xx is not allowed" can be interpreted as some permission issue. But it only means the name is not valid/accepted.
> [MINOR] makes the exception message more clear in StormSubmitter

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
- storm-client/src/jvm/org/apache/storm/task/IMetricsContext.java
- storm-client/src/jvm/org/apache/storm/task/TopologyContext.java
- storm-client/src/jvm/org/apache/storm/trident/operation/TridentOperationContext.java
Saving a mapping of registered metrics to taskId and using this to pass metrics back to an Executor.
> STORM-3623 executors should only report their metrics for V2 metric tick

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogPageHandler.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/ResourceAuthorizer.java
Explained in https://issues.apache.org/jira/browse/STORM-3629
Also fixed a translation error from clojure: 
https://github.com/apache/storm/blob/1.x-branch/storm-core/src/clj/org/apache/storm/daemon/logviewer.clj#L454-L457
> [STORM-3629] Logviewer should always allow admins to access logs

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/security/auth/authorizer/SimpleACLAuthorizer.java
- storm-client/src/jvm/org/apache/storm/security/auth/authorizer/SupervisorSimpleACLAuthorizer.java
- storm-client/src/jvm/org/apache/storm/utils/ObjectReader.java
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java
- storm-server/src/main/java/org/apache/storm/utils/ServerConfigUtils.java
- storm-server/src/test/java/org/apache/storm/daemon/supervisor/ContainerTest.java
Fix the bugs including:
1. submitting topology with logs.users as a string instead of a string list can cause supervisor to terminate due to ClassCastException
2. submitting topology with logs.users as string list with null member in the list can cause logviewer to terminate due to NPE
Detailed explained in https://issues.apache.org/jira/browse/STORM-3631
1. Tested with
`storm jar storm-starter.jar org.apache.storm.starter.WordCountTopology wc -c logs.groups="fake-groups" -c logs.users="fake-users" and made sure there is no ClassCastException in supervisor.
2. Tested with 
`storm jar storm-starter.jar org.apache.storm.starter.WordCountTopology wc -c logs.groups='[null, "fake-groups"]' -c logs.users='[null, "fake-users"]'`
and made sure there is no NPE in logviewer. Checked `worker.yaml` …
> [STORM-3631] Fix possible ClassCastException and NullPointerException caused by configs like logs.users/groups

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/SupervisorUtils.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandler.java
It's currently possible to have a numa port configured that is not in supervisor.slots.ports.  When a supervisor restarts, any worker running on numa ports not in supervisor.slots.ports will be killed.  We should consider this an invalid configuration.
Tested starting up a supervisor with no numa ports and numa ports matching supervisor.slots.ports successfully.  Verified supervisor with numa ports not in supervisor.slots.ports fails to start.
> STORM-3634 validate numa ports contained in supervisor.slots.ports

- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-webapp/src/main/java/org/apache/storm/daemon/common/FileWatcher.java
- storm-webapp/src/main/java/org/apache/storm/daemon/common/ReloadableSslContextFactory.java
- storm-webapp/src/main/java/org/apache/storm/daemon/drpc/DRPCServer.java
- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIServer.java
This enables ssl auto reload without restarting servers.
Tested with replacing keystore with empty file and replace back. 
Example:
1. At start up:
```
2020-05-13 14:55:11.896 o.a.s.d.c.ReloadableSslContextFactory main [INFO] Enabling reloading of SSL credentials without server restart
2020-05-13 14:55:11.921 o.a.s.d.c.FileWatcher main [INFO] Starting FileWatcher on <keystore-path>
2020-05-13 14:55:11.923 o.a.s.d.c.ReloadableSslContextFactory main [WARN] TrustStore is null; it won't be watched/reloaded
2020-05-13 14:55:11.928 o.e.j.s.AbstractConnector main [INFO] Started ServerConnector@2b2954e1{SSL,[ssl, http/1.1]}{0.0.0.0:4443}
2020-05-13 14:55:11.928 o.e.j.s.Server main [INFO] Started @4645ms
```
2. Replace the keystore with a empty file 
```
2020-05-13 14:55:39.962 …
```
> [STORM-3636] Enable SSL credentials auto reload

- storm-server/src/main/java/org/apache/storm/healthcheck/HealthChecker.java
Make sure hung health checks do not continue using CPU.
Created a health check with an infinite loop.  Validated process continued to run on old code and was killed after timeout with the change.
> STORM-3640 kill timed out health check processes

- conf/defaults.yaml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-server/src/main/java/org/apache/storm/scheduler/Component.java
- storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
This change provides an option to schedule executors based on network-proximity based topological order.
This is a re-work from @Ethanlm's previous PR #2623
This PR only provides this new sorting algorithm as a configurable option. Per Ethan's previous plan, we will remove this config and integrate this sorting method to our current default method as a follow-up once we decide to completely replace current executors sorting method with this new algorithm.
A simple wordcount test:
> [STORM-2687] Add network proximity needs based executor sorting method

- examples/storm-starter/src/jvm/org/apache/storm/starter/MultiThreadWordCountTopology.java
- examples/storm-starter/src/jvm/org/apache/storm/starter/WordCountTopology.java
- examples/storm-starter/src/jvm/org/apache/storm/starter/bolt/WordCountBolt.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerTransfer.java
- storm-client/src/jvm/org/apache/storm/executor/ExecutorTransfer.java
- storm-client/src/resources/mockito-extensions/org.mockito.plugins.MockMaker
- storm-client/test/jvm/org/apache/storm/executor/ExecutorTransferMultiThreadingTest.java
Users might want to launch extra threads within bolts ; because the serializer is not thread safe, there will be race conditions causing data corruption. The change here is to make the serializer thread-local, add unit test, and add a MultiThreadWordCount example. 
1. Added unit test
2. submit the MultiThreadWordCount example and validated that the threadlocal serializer fixed the data corruption issue.
There is another known issue https://issues.apache.org/jira/browse/STORM-3646 when 
```
topology.producer.batch.size
topology.transfer.batch.size
```
are not 1 (by default is 1). Make sure don't change the values to something else for now.
> [STORM-3620] fix data corruption in the case of multi-threaded bolts caused by non thread-safe serializers

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java
Fix then bug that when supervisor medium.memory case happens, the logic about grace period is wrong. The code related is: 
https://github.com/apache/storm/blob/2.2.x-branch/storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java#L758
```
if (memoryLimitExceededStart < 0) {
memoryLimitExceededStart = Time.currentTimeMillis();
} else {
long timeInViolation = Time.currentTimeMillis() - memoryLimitExceededStart;
if (timeInViolation > mediumMemoryGracePeriodMs) {
LOG.warn(
"{} is using {} MB > memory limit {} MB for {} seconds",
typeOfCheck,
usageMb,
memoryLimitMb,
timeInViolation / 1000);
return true;
}
}
```
The problem here is `memoryLimitExceededStart` is initialized to 0. The initial value should be less than 0. So we will see something like this in the log:
``` …
```
> [STORM-3649] fix logic error regarding storm.supervisor.medium.memory.grace.period.ms

- storm-client/test/jvm/org/apache/storm/executor/ExecutorTransferMultiThreadingTest.java
Give producerTasks more time to finish to avoid unnecessary test failures in case of lack of cpu resources.
Ran the unit test
> [STORM-3651] Give producerTasks in ExecutorTransferMultiThreadingTest.testExecutorTransfer more time to finish

- storm-client/src/jvm/org/apache/storm/Config.java
Update javadoc to indicate behavior when node is duplicated in FAVORED and well as UNFAVORED lists.
Adding a node to unfavored list did not seem to change the behavior of GenericResourceAwareStrategy since the node was also on the preferred list.
Built project to ensure no warnings.
> [STORM-3653] Update javadoc for favored/unfavored nodes in scheduling.

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
* _StormTimer_ threads are not names properly on Supervisor.
Running unit test and jstack shows Thread names
```"EventTimer" #22 daemon prio=10 os_prio=0 tid=0x00007f92cce67800 nid=0x58a3 waiting on condition [0x00007f92b59d6000]
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.apache.storm.utils.Time.sleep(Time.java:100)
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:236)
"WorkerHBTimer" #21 daemon prio=10 os_prio=0 tid=0x00007f92cce62800 nid=0x58a2 waiting on condition [0x00007f92b5ad7000]
java.lang.Thread.State: TIMED_WAITING (sleeping)
at java.lang.Thread.sleep(Native Method)
at org.apache.storm.utils.Time.sleep(Time.java:100)
at org.apache.storm.StormTimer$StormTimerTask.run(StormTimer.java:236)
"HBTimer" #20 daemon …
```
> MINOR: Adding Supervisor StormTimer thread names

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/StormServerHandler.java
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
Prevent worker from dying from Hadoop auto renewal thread NPE while reducing use of reflection.
Tested on our internal clusters by reducing TGT ticket lifetime and uploading credentials before auto renewal thread triggers.  Validated Hadoop exception is triggered and handled by the worker, allowing it to remain up.
> STORM-3656 handle worker NPE from Hadoop auto renewal thread

- examples/storm-perf/src/main/java/org/apache/storm/perf/queuetest/JCQueuePerfTest.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerTransfer.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/utils/JCQueue.java
- storm-client/src/jvm/org/apache/storm/utils/JCQueueMetrics.java
- storm-client/test/jvm/org/apache/storm/executor/ExecutorTransferMultiThreadingTest.java
- storm-client/test/jvm/org/apache/storm/utils/JCQueueBackpressureTest.java
- storm-client/test/jvm/org/apache/storm/utils/JCQueueTest.java
This name is mainly used in two places:
1. JCQueue metric name: Add unique executor id to metric name could be bad if we want to aggregate metrics across multiple executors/components. Also, executor id is already present in metrics dimension info such as `metricRegistry.gauge(queueName + "-capacity", cap, topologyId, componentId, taskId, port);`.
2. JCQueue name: queue name was only used in debug level log in back-pressure usecase. It would be useful to know which executor is experiencing back-pressure when tuning topologies.
In order to retain this info, we add a new field called `owner` of the JCQueue as we know it is only used in worker transfer queue or executor receive queue. Owner will just be the executor id or worker id.
Tested with WordCount topology with LoggingMetricsConsumer. …
> [STORM-3654] remove executor id from JCQueue receive-queue name

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
In most of times of conf merging, we simply prefer topo conf over daemon conf. But as for netty authentication, we believe we want to set it true either cluster or topo owner want it.
We did notice some strange cases where we set this setting true in cluster side while user set it false when submitting topology. And when host-ip mapping changed, netty server of the worker with false setting receive message from other topology with true setting. The ControlMessage received at StormServerHandler can not be processed properly since false setting only expects `List<TaskMessage>`.
In the future, we should probably handle config better in storm since it would be weird for some config to be different between server and topo. 
Tested with setting server side to true and submit a WordCount topo …
> [STORM-3657] set storm.messaging.netty.authentication to topoConf OR daemonConf

- docs/Metrics.md
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
Add a meter to allow users to track/alert on slowdown of worker heartbeat rate.
built code.
> STORM-3648 add meter to track worker heartbeat rate

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
The assignment change should lead to worker suicide. This is specially critical if Supervisor is down for some reason
1. Launcher WordCountTopology, wait for worker to start
2. Stop the supervisor
3. Re-balance topology so worker is assigned to next supervisor
4. Worker should kill itself with worker.log entries similar to below.
```
2020-06-22 06:55:40.527 o.a.s.d.w.WorkerState refresh-connections-timer [INFO] Found conflicting assignments. We shouldn't be alive! Assigned: [[-1, -1]], Current: [[-1, -1], [14, 14], [12, 12], [10, 10], [8, 8], [6, 6], [4, 4], [2, 2], [7, 7], [5, 5], [3, 3], [1, 1], [13, 13], [11, 11], [9, 9]]
2020-06-22 06:55:40.529 o.a.s.u.Utils refresh-connections-timer [ERROR] Halting process: Worker died
java.lang.RuntimeException: Halting process: Worker died
at …
```
> STORM-3655: Worker should die if its assignment has changed

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/executor/ExecutorShutdown.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
Details explained in https://issues.apache.org/jira/browse/STORM-3658.
In short, the problem here is 
1. there could be a race condition between registering the shutdown hooks and invoking shutdown hooks
2. There is a possible deadlock between a thread like executor thread that invokes shutdown hook (when it invokes Runtime.getRuntime().exit) and the shutdown hook/thread itself that tries to terminate threads like the executor thread.
1. The deadlock and race condition can be reproduced with a WordCountTopology whose WordCountBolt simply throws a RuntimeException in `prepare` method.  Use it to validate the change. The race condition and deadlock is not happening. 
The log below shows shutdown hook waited for 100ms and continue. This avoids the deadlock.
```
2020-06-29 20:33:44.237 …
```
> [STORM-3658] Avoid deadlock and race condition caused by shutdown hooks

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/templates/owner-page-template.html
*Owner Topologies table on User page of Storm UI should display Storm Version.*
*Build and run storm-server and UI. Submit topology and look at the user page in Storm UI*
> [STORM-3659] Add StormVersion to OwnerTopologies table on User page

- storm-client/src/jvm/org/apache/storm/messaging/netty/Server.java
In some (rare) cases, we observed netty-server might receive messages other than a List<TaskMessage> from a wrong source, and it will throw ClassCastException and terminate the worker process. 
Set netty server side to not using Sasl related ServerHandler while making client send sasl message, we observe the following message without worker getting killed
```
2020-06-26 15:10:41.086 o.a.s.m.n.Server Netty-server-localhost-6701-worker-1 [ERROR] Worker netty server receive message other than the expected class List<TaskMessage>
java.lang.ClassCastException: org.apache.storm.messaging.netty.ControlMessage cannot be cast to java.util.List
at org.apache.storm.messaging.netty.Server.received(Server.java:266) [storm-client-2.3.0.y.jar:2.3.0.y]
at …
```
> [STORM-3661] handle exception when netty server receive unexpected message

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
The callback method to request credentials in the _loadWorker_ method is not required as it receives _initialCredentials_ as parameter. and within _TASK_CREDENTIALS_POLL_SECS_ schedule recurring call to _checkCredentialsChanged_ is setup. Also, all executors at init time receive initial credentials so no need for this additional call. 
Manually launched topology to verify if _setCredentials_ is called on all executors correctly on the start of workers.
> MINOR: Remove unwanted creds update check at worker start

- storm-webapp/pom.xml
Changing to use `${project.version}` property.
Re-ran build.
> [MINOR] use project.version for storm-core dep in storm-webapp

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
If the underlying scheduler is not _ResourceAwareScheduler_ and scheduler has no resources to register, then it does not have to calculate or report  any resources.
local unit tests.
> MINOR PATCH: Avoid fragmented resources on supervisor creation in nimbus

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/test/java/org/apache/storm/daemon/nimbus/NimbusTest.java
https://issues.apache.org/jira/browse/STORM-3667
When submitting a topology failed because of incorrect max worker heap size config, the exception returned to submitter is not easy to understand: "Internal error processing submitTopology"
With 
```
bin/storm jar /home/y/lib64/jars/storm-starter.jar  org.apache.storm.starter.WordCountTopology -c topology.worker.max.heap.size.mb=100  -c topology.component.resources.onheap.memory.mb=120 wc
```
the exception message is much more clear to submitters now:
```
22:34:43.683 [main] ERROR o.a.s.StormSubmitter - Topology submission exception: Topology will not be able to be successfully scheduled: Config TOPOLOGY_WORKER_MAX_HEAP_SIZE_MB=100.0 < 120.0 (Largest memory requirement of a component in the topology). Perhaps set …
```
> [STORM-3667] make exceptions more understandable to submitters when topology submission fails due to incorrect worker max heap size config

- dev-tools/travis/travis-install.sh
Try to make Storm support running tests with Travis CI on ARM platform.
In Travis ARM building, the "pip" command refer to the "pip3" binary,
that will cause the python2 packages installation missed. This change
modify the travis-install.sh to explicitly specify pip2 and pip3.
I have tried to config Storm with Travis CI ARM platform, please see:
https://github.com/liusheng/storm/pull/4/checks
> STORM-3674 Explicitly specify pip2 and pip3 in travis-install.sh

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
In refresh-connection thread, if we do get localAssignment, we try to get it from Zookeeper, if assignment is still null it suggests the worker should not exist.
Manually tested this:
1. Launch topology.
2. Stop supervisor, validate that worker stays up - as it reads assignment from ZK
3. Kill topology
4. Worker suicide function recognizes null assignment and kills itself.
Here is worker log after change..
```
2020-07-17 17:53:24.494 o.a.s.d.w.WorkerState refresh-connections-timer [WARN] Failed to read assignment. This should only happen when topology is shutting down.
java.lang.RuntimeException: Failed to read worker assignment. Supervisor client threw exception, and assignment in Zookeeper was null
2020-07-17 17:53:24.503 o.a.s.d.w.WorkerState refresh-connections-timer [INFO] Assigment …
```
> STORM-3677: Fix suicide function if assignment is null

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/grouping/LoadAwareShuffleGrouping.java
- storm-client/src/jvm/org/apache/storm/task/WorkerTopologyContext.java
- storm-client/test/jvm/org/apache/storm/grouping/LoadAwareShuffleGroupingTest.java
LoadAwareShuffleGrouping misuses nodeId as the hostname to cause consistent invalid DNS queries for "hostnames" like 2a1f2cf3-c701-4621-9e93-640b4e63be48-10.215.73.209.
This causes excessive unnecessary loads on nscd and DNS. Also because of this bug, every target tasks will be treated as at least RACK_LOCAL because if an ip address can't be determined, YahooDNSToSwitchMapping treats it as DEFAULT_RACK. This doesn't impact WORKER_LOCAL and HOST_LOCAL though.
Before the change,
added logs and showed that the "hostname" is actually an ID. And tcp dump
```
18:42:21.913688 IP <host1>.42462 > <dns>: 43104+ A? 2a1f2cf3-c701-4621-9e93-640b4e63be48-<ip1>. (68)
18:42:21.914181 IP <dns> > <host1>.42462: 43104 NXDomain 0/1/0 (143)
```
After the change, 
determined from additional added debug logs …
> [STORM-3679] Fix the misuse of nodeId as hostname in LoadAwareShuffleGrouping

- .travis.yml
This change propose to add a basic ARM64 CI job into Travis configuration. 
After the rocksdb version up[1] and some minor fixes[3], now the STROM can be built and test successfully, So we propose to added a basic ARM64 CI task as first step, which only run the "Client" module of Storm. As the JIRA STORM-3681 descirbed, there are some existed problems of Travis CI itself about ARM64 support, which will cause some other modules of Storm run failed. We will continue to track the issues of Travis ARM support, once the issues solved, we will try to enable all the Storm modules for ARM CI.
[1] https://issues.apache.org/jira/browse/STORM-3599
[2] https://issues.apache.org/jira/browse/STORM-3674
[3] https://issues.apache.org/jira/browse/STORM-3401
[4] …
> [STORM-3681] Enable basic ARM64 CI task

- storm-client/src/jvm/org/apache/storm/daemon/StormCommon.java
Add a warning about possible issues on a mixed cluster if the StormCommon.systemTopology implementation is changed. For example https://issues.apache.org/jira/browse/STORM-3687
N/A
Only changed comments
> [STORM-3687] Add a warning about possible issues on a mixed cluster if the StormCommon.systemTopology implementation is changed

- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
When registering receive-queue V2 metrics for each executor, we should use the its correspondent component Id instead of constant system component Id.
Launch a local cluster with a WordCount topology. Enable `org.apache.storm.metrics2.reporters.ConsoleStormReporter` to output metrics to worker log. We will see the long name as :
`storm.worker.<topoName>.<hostname>.<compId>.<taskId>.<port>.<metric-name>`
The compId part now reflects the correct component for the taskId.
```
2020-08-04 14:22:44.911 c.c.m.ConsoleReporter metrics-console-reporter-1-thread-1 [INFO] storm.worker.wc1-1-1596568923.192_168_0_19.count.10.6700-receive-queue-pct_full
2020-08-04 14:22:44.911 c.c.m.ConsoleReporter metrics-console-reporter-1-thread-1 [INFO]              value = 0.0
2020-08-04 14:22:44.912 …
```
> [STORM-3684] use real compId instead of constant _system for receive-queue V2 metrics

- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceRequest.java
Fix the UI null pointer error if resource aware scheduler is not used.
Launch a local cluster and a word count topology.
UI error was fixed.
> [STORM-3690] fix Ui index page null pointer error

- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
- storm-server/src/test/java/org/apache/storm/utils/ServerUtilsTest.java
*This function can replace a system "ps" command with existence/ownership check on /proc/ directory. In additional, on loaded nodes, ps command can take a few seconds. java.io.File.exists() is expected to be much faster. Note that File watcher does not work on /proc file system and the event based approach was coded/tested and then discarded.*
*new test methods in ServerUtilsTest. Also run storm, kill worker and observe log to ensure proper detection*
> [STORM-3675] Check worker process death using /proc/<pid> directory

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/daemon/StormCommon.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/test/jvm/org/apache/storm/utils/UtilsTest.java
*Topology is expected to be a Directed Acyclic Graph. Cycles in component flow can cause unexpected behavior, for example a deadlock when one of the loop components signals a back-pressure. Or properly detecting proximity when scheduling.*
*New test to create topology with and without cycles and test detection.*
> [STORM-3685] Detect and prevent cycles when Topology is submitted.

- storm-client/src/jvm/org/apache/storm/daemon/supervisor/ClientSupervisorUtils.java
It's not safe to assume InterruptedException is ignorable.
Rebuilt storm-client
> STORM-3696 don't ignore InterruptedException

- bin/storm.py
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Rebalance command completes successfully when --executor option has invalid component name. This gives
the impression that command was successful. Change this behavior to throw an exception. In addition, fix the help
text for --executor options to show correct format.
Run storm and rebalance using various correct and incorrect formats like:
bin/storm rebalance --help   # to show corrected help text
bin/storm rebalance --executor spout:3 -w 1 word-count ## fail because of spout:3
bin/storm rebalance --executor spout=3 -w 1 word-count ## verify correct rebalance in Storm UI with spout=3
bin/storm rebalance -e spout=4 -w 1 word-count  ## verify correct rebalance in Storm UI with spout=4
> [STORM-3666] Validate component name in rebalance command

- bin/flight.bash
JFR on openJDK8u262 or newer is different from oracle jdk-1.8.0_131 or older. flight.bash needs to updated to support both old and new commands.
Tested by running start/dump/stop commands using flight.bash
**openJDK8u262**
```
bash-4.2$ java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.262-b10, mixed mode)
bash-4.2$ jcmd 20 JFR.check
20:
No available recordings.
Use jcmd 20 JFR.start to start a recording.
bash-4.2$ ./flight.bash 20 start
/<root-dir>/share/jdk/java/bin/java found. Will use java utils from /<root-dir>/share/jdk/java/bin/
20:
Started recording 4. No limit specified, using maxsize=250MB as default.
Use jcmd 20 JFR.dump name=storm-recording-20200915204300 filename=FILEPATH …
```
> [STORM-3699] fix flight.bash to support flight recording on openJDK8u262 or newer

- docs/metrics_v2.md
- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
- storm-client/src/jvm/org/apache/storm/metrics2/DimensionalReporter.java
- storm-client/src/jvm/org/apache/storm/metrics2/MetricRegistryProvider.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
- storm-client/src/jvm/org/apache/storm/metrics2/TaskMetricDimensions.java
- storm-client/src/jvm/org/apache/storm/metrics2/TaskMetricRepo.java
- storm-client/src/jvm/org/apache/storm/metrics2/reporters/ConsoleStormReporter.java
- storm-client/src/jvm/org/apache/storm/metrics2/reporters/ScheduledStormReporter.java
Allow V2 metric reporters to report metrics with long names or with a short name and set of dimensions.  ConsoleStormReporter was modified to allow both options.
Long metric names get stored in a metrics registry as previously.  Additionally, we create a map of Task/component/stream dimensions to a TaskMetricRepo that contains task specific metrics.  
If a reporter supports and is configured for short metric names, it will receive the metrics one repo at a time, first setting the dimensions for the repo, and then reporting the metrics for that Task set.
Ran a topology with ConsoleStormReporters set to report both long and short metrics.
./bin/storm jar ~/storm/storm-starter.jar org.apache.storm.starter.WordCountTopology wc -c topology.metrics.consumer.register="[{\"argument\":null,\"class\ …
> STORM-3694 allow reporting V2 metrics with dimensions and short names

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
When AsyncLocalizer cleanup happens, make sure it check against the latest topology cache information.
Currently, the `safeTopologyIds` set might become stale due to delay at around https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java#L641 . Newly created topology entries might not appear here and clean-up will delete them by fault and cause further FNF issue.
Reproduce the FNF issue with additional sleep. After the change, same delay won't cause the FNF anymore.
> [STORM-3701] clean-up topo directory with the check against latest topo blob cache

- docs/ClusterMetrics.md
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
Have a metric so we can alert when blobs are failing to update.
Built storm-server
> STORM-3707 add meter to track update blob exceptions

- DEPENDENCY-LICENSES
- LICENSE-binary
Currently, the CI job of "Check-Updated-License-Files" has failed due to
the dependency "org.glassfish:javax.el" version out-of-date.
This change will be tested by Travis CI
> [STORM-3712] Update version of dependency in license file

- .travis.yml
Previously, we have enabled the ARM 64 CI with only "Client" module
configured, because there are some issues about Travis CI due to its ARM
resources performance, now Travis CI has the new ARM resources
"arm64-graviton2" provided by AWS, please see[1]. Now we can switch to
use the "arm64-graviton2" resources and enable all the modules on ARM
CI.
https://docs.travis-ci.com/user/multi-cpu-architectures
> [STORM-3711] ARM CI switch to use arm64-graviton2 and enable all modules

- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
*Prior to refactoring of Resource Aware Scheduler, Cluster.needsSchedulingRas() would always return true. Call this method in tests to ensure that the correct value (true/false as appropriate) is returned.*
*Run unit tests, especially TestResourceAwareScheduler and TestBackwardCompatibility*
> [STORM-3706] Add Cluster.needsSchedulingRas() to tests

- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/test/jvm/org/apache/storm/TestStormSubmitter.java
*Topology without spout cannot be scheduled. We should just not allow this to be submitted if we will never schedule it.*
*New unit test TestStormSubmitter.invalidTopologyWithoutSpout()*
> [STORM-3709] Topology without spout should fail submission.

- conf/defaults.yaml
- docs/distcache-blobstore.md
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
Add a config option to change updateBlob interval for the AsyncLocalizer.
Checked interval changes with debug on with and without a value set on a supervisor.  Ran storm-server unit tests.
> STORM-3719 add config option for updateBlob interval

- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverConfig.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
*Log messages in ConstraintSolverConfig do not show the TopologyId. This makes it harder to track problems when there are several topologies running on the cluster.*
*Run unit tests in storm-server package*
> [STORM-3708] Add TopologyID to log messages in ConstraintSolverConfig

- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreFile.java
- external/storm-hdfs-blobstore/src/test/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImplTest.java
- storm-server/src/main/java/org/apache/storm/blobstore/LocalFsBlobStoreFile.java
If we call getModTime() multiple times before and after a blobstore file changes, we will get an incorrect timestamp.
Built storm.  Ran HdfsBlobStoreImplTest.
> STORM-3720 get correct results for BlobStoreFile getModTime()

- .travis.yml
- integration-test/run-it.sh
In # apache/storm/pull/3344, we have enabled ARM CI with all Storm
modules enabled and switched to use the "arm64-graviton2" resources, but
I have made a mistak that the ARM CI actually still run on x86 than
ARM even the CI job shows the label "arm64-graviton2", details can be
found in the CI job logs[1]. Because the "arm64-graviton2" requires
explicit virt: [lxd|vm] tag, see[2].
Addtionally, we have skip the increasing swap space statement in
intergration test because it will raise error on ARM. And we only
enabled openjdk11 for ARM jobs because the jdk8 is unsupported, see[3].
[1] https://travis-ci.org/github/apache/storm/jobs/741780900
[2] https://docs.travis-ci.com/user/multi-cpu-architectures#testing-on-multiple-cpu-architectures
[3] …
> [STORM-3711] Fix ARM CI with wrong usage of "arm64-graviton2" resources

- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
- storm-server/src/test/java/org/apache/storm/utils/ServerUtilsTest.java
*Fix isAnyPosixProcessPidDirAlive to return correct value when all PIDs are reassigned to different user*
*Modify ServerUtilsTest to add this new condition*
> [STORM-3723] Fix isAnyPosixProcessPidDirAlive for PID reassignment

- storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
Described in https://issues.apache.org/jira/browse/STORM-3728. Workers have issue connecting to pacemaker when pacemaker.auth.method is KERBEROS
This issue is easy to reproduce when pacemaker is set up with Kerberos and `pacemaker.auth.method` set to `KERBEROS`.
Applied this change and validated that workers can heartbeat to Pacemakers properly.
> [STORM-3728] Fix Worker LoginException issue with pacemaker when pacemaker.auth.method is KERBEROS

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/SupervisorUtils.java
Apparently it is possible for supervisorConf.getOrDefault(DaemonConfig.SUPERVISOR_SLOTS_PORTS) to return a list of Long values, which caused a ClassCastException.
Built storm-server jar.
> STORM-3727 handle long values for SUPERVISOR_SLOTS_PORTS

- storm-client/src/jvm/org/apache/storm/metrics2/RateCounter.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
- storm-client/src/jvm/org/apache/storm/metrics2/TaskMetrics.java
Add RateCounter class to have a metric with a count and one minute rate without the performance impact of a Meter.  The code is based on Flink's MeterView, which updates the rate in a background thread.  Switch TaskMetrics to use this to report the rate.
Ran word count topology and validated metric was reported and looked valid.  Ran storm-client unit tests.
> STORM-3714 add rate tracking to TaskMetrics

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/main/java/org/apache/storm/localizer/PortAndAssignment.java
- storm-server/src/main/java/org/apache/storm/utils/EquivalenceUtils.java
- storm-server/src/test/java/org/apache/storm/daemon/supervisor/SlotTest.java
- storm-server/src/test/java/org/apache/storm/localizer/LocalizedResourceRetentionSetTest.java
- storm-server/src/test/java/org/apache/storm/utils/EquivalenceUtilsTest.java
When a local assignment changes for a slot, the blob references are not updated. This causes a mismatch between the slot PNA and the blob reference PNA. When the topology is killed, the blob tries to remove the slot PNA and cannot find the reference. The AsyncLocalizer still has the old slot PNA as a reference, so cannot release the blob.
The local assignment could change due to a reordering of the same executors on a nimbus restart or something similar.
The fix is basically removeReference() changes in LocallyCachedBlob.  We make sure that we are checking for an equivalent PNA object instead of equals.  Additional logging was also added to track down this issue.  I think it's not excessive and considering how long this problem has existed, important to have.
Ran storm-server unit tests. …
> STORM-3733 fix AsyncLocalizer from updating dead topology blobs

- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStore.java
- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImpl.java
- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsClientBlobStore.java
- storm-client/src/jvm/org/apache/storm/blobstore/BlobStore.java
- storm-client/src/jvm/org/apache/storm/blobstore/ClientBlobStore.java
- storm-client/src/jvm/org/apache/storm/blobstore/LocalModeClientBlobStore.java
- storm-client/src/jvm/org/apache/storm/blobstore/NimbusBlobStore.java
- storm-client/test/jvm/org/apache/storm/blobstore/ClientBlobStoreTest.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
- storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java
- storm-server/src/main/java/org/apache/storm/utils/ServerConfigUtils.java
- storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
- storm-server/src/test/java/org/apache/storm/localizer/LocallyCachedBlobTest.java
Reduce the impact of listing files on a Hadoop name node by checking a single timestamp first when updating blobstores.  The Hadoop blobstore will update the modTime on the base blobstore directory anytime a blob is updated.  Supervisors will fetch that timestamp once during AsyncLocalizer updateBlobs().  For each local blob, if the last check matches this modTime, they will not query the remote Hadoop blob.  This reduces polling on the namenode.
Ran code with debug logs on internal dev clusters with Hadoop and ran blobstore related integration tests with topologies.  Ran storm-client/server/hdfs-blobstore unit tests.  Ran a word count topology on a local cluster setup for 15 minutes.
> STORM-3724 use blobstore modtime to prevent querying each remote file on update

- storm-client/src/jvm/org/apache/storm/serialization/SerializationFactory.java
Explained in https://issues.apache.org/jira/browse/STORM-3735. 
```
2021-01-13 20:16:37.030 o.a.s.u.Utils Thread-16-__system-executor[-1, -1] [ERROR] Async loop died!
java.lang.RuntimeException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Class is not registered: org.apache.storm.generated.NodeInfo
Note: To register this class use: kryo.register(org.apache.storm.generated.NodeInfo.class);
Serialization trace:
value (org.apache.storm.metric.api.IMetricsConsumer$DataPoint)
at org.apache.storm.executor.Executor.accept(Executor.java:294) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consumeImpl(JCQueue.java:113) ~[storm-client-2.3.0.y.jar:2.3.0.y]
at org.apache.storm.utils.JCQueue.consume(JCQueue.java:89) …
```
> [STORM-3735] Register NodeInfo class to Kyro

- docs/Metrics.md
- storm-client/src/jvm/org/apache/storm/daemon/metrics/BuiltinMetricsUtil.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-client/src/jvm/org/apache/storm/messaging/IContext.java
- storm-client/src/jvm/org/apache/storm/messaging/TransportFactory.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Client.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Context.java
- storm-client/src/jvm/org/apache/storm/metrics2/RateCounter.java
- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
- storm-client/src/jvm/org/apache/storm/metrics2/TaskMetricRepo.java
- storm-core/test/jvm/org/apache/storm/messaging/netty/NettyTest.java
This change switches the Netty Client send connection metrics to the V2 metrics API.  
Ran storm-client/storm-core unit tests.  Ran topology and validated metrics were logged.  Killed some workers and validated clients on others properly deregistered metrics for the killed client.
> STORM-3682 Upgrade netty client metrics to use V2 API

- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
When a worker slot is released, there could still be downloading blobs running in background threads.  These can add references to a blob after the worker is killed, causing the AsyncLocalizer to look for updates on the blob infinitely.
Ran storm-server unit tests and various internal blob/scheduling integration tests.
> STORM-3740 cancel downloading blobs when releasing worker slot

- pom.xml
*Older version causes corruption in STDOUT and copious output with reuseForks=true*
*Run "mvn test"*
> [STORM-3741] change version of surefire plugin to 2.22.2

- storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
Prevent ConcurrentModificationExceptions when reporting metrics while adding a new metric.
built storm-client
> STORM-3748 use ConcurrentHashMap for taskId metrics

- storm-client/src/jvm/org/apache/storm/messaging/netty/StormServerHandler.java
Improve the error message when a server error occurs/
built storm-client
> STORM-3749 improve logging for server error

- storm-server/src/main/java/org/apache/storm/scheduler/ISchedulingState.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/RasNodes.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOffer.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResources.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ObjectResourcesItem.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/sorter/INodeSorter.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/sorter/NodeSorter.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/sorter/NodeSorterHostProximity.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/TestUtilsForResourceAwareScheduler.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/sorter/TestNodeSorterHostProximity.java
*When using numa zones, nodes should be sorted by host groups for scheduling*
*Added new tests for confirm successful host grouping in storm-server*
> [STORM-3739] Scheduling should sort numa zones by host groups

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/templates/topology-page-template.html
As part of STORM-3534 (https://github.com/apache/storm/pull/3163) new column was added to this table, however the header for it was added outside "if schedulerDisplayResource" logic while rows are inside, causing misalignment.
The change is cosmetic and was tested in a local installation.
> [STORM-3704] - Cosmetic: fix table header alignment in "Topology summary" table.

- DEPENDENCY-LICENSES
- LICENSE-binary
Travis build failed due to 
```
Checking DEPENDENCY-LICENSES
DEPENDENCY-LICENSES and target/DEPENDENCY-LICENSES are different. Please update DEPENDENCY-LICENSES by running 'mvn license:aggregate-add-third-party@generate-and-check-licenses -Dlicense.skipAggregateAddThirdParty=false -B' in the project root
Dependencies in LICENSE-binary that appear unused: 
org.glassfish:javax.el:3.0.1-b11
Dependencies missing from LICENSE-binary: 
org.glassfish:javax.el:3.0.1-b12
LICENSE-binary needs to be updated. Please remove any unnecessary dependencies from LICENSE-binary, and add any that are missing. You can copy any missing dependencies from DEPENDENCY-LICENSES
Some license files are not up to date, see above for the relevant error message
``` …
> [MINOR] Fix dependency licenses

- storm-client/src/jvm/org/apache/storm/messaging/IContext.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Server.java
Explained in details in https://issues.apache.org/jira/browse/STORM-3763
Tested with a word-count topology and reproduced the bug.
> [STORM-3763] send initial message to remote client only after authentication completes

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
The time unit doesn't match.
This change is trivial. But ran with a topology and we can have the following logs.
```
2021-04-23 19:40:15.039 o.a.s.d.n.Nimbus timer [DEBUG] Scheduling took 85 ms for 1 topologies
```
> [MINOR] fix time unit of scheduling time

- storm-client/src/jvm/org/apache/storm/security/auth/authorizer/DRPCSimpleACLAuthorizer.java
- storm-client/test/jvm/org/apache/storm/security/auth/authorizer/DRPCSimpleACLAuthorizerTest.java
When drpc.authorizer.acl is set up with no values, like below,
```
-bash-4.2$ cat drpc-auth-acl.yaml
drpc.authorizer.acl:
```
DRPCSimpleACLAuthorizer will have NPE
Tested with different setup, including 
```
2021-04-22 15:31:32.746 o.a.s.t.ProcessFunction pool-9-thread-3 [ERROR] Internal error processing fetchRequest
java.lang.RuntimeException: Config file drpc-auth-acl.yaml doesn't have any valid storm configs
at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:xxx) 
```
```
drpc.authorizer.acl :
```
it worked well. 
If `drpc.authorizer.acl.strict` is set `true`, we will see
```
2021-04-22 15:27:27.871 o.a.s.s.a.a.DRPCSimpleACLAuthorizer pool-9-thread-1 [WARN] Requiring explicit ACL entries, but none given. Therefore, all operations will be denied.
```
```
-bash-4.2$ cat …
```
> [STORM-3765] fix NPE when drpc.authorizer.acl has no values

- conf/defaults.yaml
- docs/cgroups_in_storm.md
- storm-client/src/jvm/org/apache/storm/container/cgroup/core/CpuCore.java
- storm-client/src/jvm/org/apache/storm/metric/SystemBolt.java
- storm-client/src/jvm/org/apache/storm/metric/cgroup/CGroupCpu.java
- storm-client/src/jvm/org/apache/storm/metric/cgroup/CGroupCpuGuaranteeByCfsQuota.java
- storm-client/src/jvm/org/apache/storm/metrics2/WorkerMetricRegistrant.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupCpu.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupCpuGuarantee.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupCpuGuaranteeByCfsQuota.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupCpuStat.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupMemoryLimit.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupMemoryUsage.java
- storm-client/src/jvm/org/apache/storm/metrics2/cgroup/CGroupMetricsBase.java
Able to monitor Cgroup usage on RHEL systems using V2 metrics.
Metrics tested on internal clusters.  Ran V2 metric reporting on mac and validated no errors occur.
> STORM-3774 add V2 Cgroup metrics

- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/test/jvm/org/apache/storm/TestConfigValidate.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/SupervisorUtils.java
Prevent invalid blobstore map conf settings from restarting supervisors.
Ran new unit tests.  Validated submission of invalid boolean setting fails topology submission.
> STORM-3775 validate optional boolean fields in topology.blobstore.map

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/executor/Executor.java
Prevent under/over reporting of v2 metrics tick.
Ran storm-client unit tests.  Validated LoggingMetricsConsumer logged v2 metrics on worker.
> STORM-3786 ensure v2 metrics tick reporting occurs at specified interval

- docs/ClusterMetrics.md
- storm-client/src/jvm/org/apache/storm/security/auth/workertoken/WorkerTokenAuthorizer.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java
Be able to alert based on repeated failures to getPassword for workers.
Ran storm-client/storm-server unit tests.  Launched a word count topology.  Validated new meter reports values on internal dev cluster.
> STORM-3790 add meter to track getPassword failures

- external/storm-hdfs-oci/src/main/java/org/apache/storm/container/oci/HdfsOciResourcesLocalizer.java
When deployed to a new node, `<parent-path>/supervisor/oci-resources/config/` might  not exist, so `mkdir("<parent-path>/supervisor/oci-resources/config/working")` will fail:
```
2021-08-09 19:17:34.047 o.a.s.d.s.Slot SLOT_6702 [ERROR] Failed launching container
java.io.IOException: Couldn't create the directory: /home/y/var/storm/supervisor/oci-resources/config/working
at org.apache.storm.container.oci.HdfsOciResourcesLocalizer.localize(HdfsOciResourcesLocalizer.java:94)
```
We just need to make sure parent directories are always created by using `mkdirs`
Tested to a newly deployed node and applied the path, submitted a word-count topology and verified that the supervisor was able to create the directories and run the topology properly.
> [STORM-3388] Followup fix: HdfsOciResourcesLocalizer should create necessary nonexistent parent directoires

- docs/Metrics.md
- storm-client/src/jvm/org/apache/storm/daemon/worker/BackPressureTracker.java
- storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
- storm-client/test/jvm/org/apache/storm/daemon/worker/BackPressureTrackerTest.java
Be able to track which task is causing backpressure.
Built code, ran storm-client unit tests, validated metric reports on a dev cluster.
> STORM-3793 add metric to track backpressure status for tasks

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
Stop converting V2 rate metrics when adding to V1
Unit test
> [STORM-3785] Stop converting V2 rate metrics when adding to V1

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Don't allow deleting blobs if they are required for an active topology
Tested on local cluster. Verified that it works as expected. Got the following error message:
"org.apache.storm.utils.WrappedIllegalStateException: Attempting to delete active blob test-delete16acbcb7-91f3-4497-a9bb-67dbfb786948.jar used by topology blob-3-1635454702"
> STORM-3804 Don't allow deleting blobs if they are required for an active topology

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/component.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/index.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/owner.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/supervisor.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/topology.html
*Large numbers for emitted, transferred, acked, failed, cpu, mem, etc are hard to read. Format the
integers with commas after three digits for readability.*
*Build code, deploy locally, and then view the changed pages in a web browser*
- index.html
- component.html
- owner.html
- supervisor.html
- topology.html
> [STORM-3803] Format large integers with commas after three digits in Storm UI

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
*Acked and Fixed columns in topology page of Storm UI display NaN.*
*Compiled and run locally. Submit a new wordcount topology. Navigate to topology page and view "Topology Stats" section*
> [STORM-3807] Topology Stats columns show NaN

- pom.xml
To bump log4j 2.15.0 for CVE-2021-44228
> bump log4j 2.16.0

- pom.xml
Similarly to https://github.com/apache/storm/pull/3426, bumping log4j.version to 2.16.0 and consequently disruptor.version to 3.4.4 on 1.x-branch
> STORM-3810: bumping log4j.version to 2.17.0 and disruptor.version to 3.4.4 (CVE-2021-44228, CVE-2021-45046)

- docs/Metrics.md
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Client.java
Add option to disable reporting of __send-iconnection metrics.
built storm code.
> STORM-3815 add option to disable reporting of __send-iconnection metrics

- pom.xml
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832
Mitigation of https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44832
As recommended in https://logging.apache.org/log4j/2.x/security.html
> CVE-2021-44832: Bumping log4j version to 2.17.1

- storm-client/test/py/test_storm_cli.py
*While running a release preparation, the test in storm-client/test/py/test_storm_cli.py fails because the directories in classpath have "/\*" appended after storm.py runs.*
*Rebuild storm using "mvn release:prepare -P dist,rat,externals,examples "*
> [STORM-3823] Change expected classpath dirs to end with "/*"

- storm-core/pom.xml
*Log4j version 1.2.17 is no longer used in testing and can be removed*
*run "mvn test" and "mvn dependency:tree | grep -b2 -a2 log4j" to verify that only log4j2 is used*
> [STORM-3829] Remove log4j 1.2.17 as a test dependency.

- DEPENDENCY-LICENSES
- LICENSE-binary
- external/storm-autocreds/pom.xml
- external/storm-blobstore-migration/pom.xml
- external/storm-hdfs-blobstore/pom.xml
- external/storm-hdfs-oci/pom.xml
- external/storm-hdfs/pom.xml
- external/storm-hive/pom.xml
- external/storm-solr/pom.xml
- pom.xml
- sql/storm-sql-external/storm-sql-hdfs/pom.xml
- storm-core/pom.xml
https://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.26 updated due to vulnerbilities.  See link.
> STORM-3831 exclude older log4j

- storm-client/pom.xml
*Python version 2 has been EOL since January 1, 2020 (https://www.python.org/doc/sunset-python-2/).*
*mvn clean install with python2 removed*
> [STORM-3832] Remove python2 execution.

- storm-client/src/jvm/org/apache/storm/utils/ShellUtils.java
To be able to tell what commands are failing when the meter updates.
Built storm-client.  Validated logging on internal dev supervisor.
> STORM-3835 log command that is failing

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/test/java/org/apache/storm/daemon/nimbus/NimbusTest.java
storm.workers.artifacts.dir is not a topology setting.  Users should not be allowed to set.
Built storm.  Validated user topology setting this does not make it to the topology conf on the UI on an internal dev cluster.
> STORM-3838 prevent topology from setting storm.workers.artifacts.dir

- storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
- storm-webapp/src/test/java/org/apache/storm/daemon/ui/UIHelpersTest.java
This fixes [STORM-3822](https://issues.apache.org/jira/browse/STORM-3822), making the Topology Visualization UI render correctly when a streamId contains a colon character.
I have tested with a modified version of WordCountTopology where I used a custom streamId ("my:stream") containing a colon and verified the UI loads successfully.  I have also tested with some of my team's real topologies that utilize streamIds containing colons.
Further, I have added a unit test for the function of the sanitizeStreamName() method modified in this PR.
The sanitizeStreamName() method body was a bit cryptic and hard to follow.  I refactored it in an attempt to make it more readable.  I could have gone a little further.  In the initial version in the PR I have just added comments, renamed variables, and …
> STORM-3822 fix visualization when streamId contains colon

- bin/storm.ps1
- bin/storm.py
Fixing the python version check in storm.ps1, that always fails due to wrong handling of a string.
Otherwise every windows user has to fix this file by themselves.
(& python -V 2>&1) already returns a string. Accessing it with `(& python -V 2>&1)[0]` returns a char. Therefore the script always fails with a NullPointerException at `[int]$PythonVersion.Split(".")[0]`.
I ran the script ([storm_python_check_test.zip](https://github.com/apache/storm/files/6776823/storm_python_check_test.zip)) and the modified storm.ps1 on my Windows 10 Pro Machine (With Python 3.9.1, OpenJDK 15).
When you execute the attached script you get the following console output:
> Original Version:
> 
> PythonVersion=
> error
> Es ist nicht möglich, eine Methode für einen Ausdruck aufzurufen, der den NULL hat.
> In …
> [STORM-3847] Fix various problems in the python PowerShell execution

- storm-shaded-deps/pom.xml
*mvn build warns about missing version for build-helper-maven-plugin in storm-shaded-deps*
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.apache.storm:storm-shaded-deps:jar:2.5.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:build-helper-maven-plugin is missing. @ line 309, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```
*Rebuild and confirm that this warning message goes away*
> [STORM-3848] Add version for build-helper-maven-plugin.

- dev-tools/validate-license-files.py
- pom.xml
*When license file is different from expected, dump contents of both files. This output will appear in Travis build be easier to debug/fix*
*Run the new python method separately in python2 and python3 environment*
> [STORM-3846] Dump actual and expected license files upon mismatch

- pom.xml
*mvn build report WARNING for each submodule build*
```
[WARNING] Unable to locate Source XRef to link to - DISABLED
[WARNING] Unable to locate Source XRef to link to - DISABLED
```
*Rebuild project, capture output into file and then search for the WARNING to confirm the fix*
> [STORM-3849] Add maven-jxr-plugin to eliminate XREF build warnings.

- dev-tools/travis/print-errors-from-test-reports.py
*Errors in travis build are not always printed properly*
If errors are encountered in Travis build, then  script dev-tools/travis/print-errors-from-test-reports.py is used to examine the reports in target/test-reports and print the errors in test.
However, the script itself has syntax errors and therefore fails to load, especially under python3.
Fix the script so that it can properly parse and print.
*Ran this script against storm-core/target/test-reports.*
Old code gave an error:
```
(oath_tools) bprasad@C02XG0WLJGH8 storm-core % python3 ../dev-tools/travis/print-errors-from-test-reports.py target/test-reports
Traceback (most recent call last):
File "/Users/bprasad/sources/community/bipinprasad/storm/storm-core/../dev-tools/travis/print-errors-from-test-reports.py", line 77, in <module> …
```
> [STORM-3851] Fix syntax errors and modify to run under python3

- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreFile.java
- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImpl.java
STORM-3862 HdfsBlobStoreImpl should check permission after mkdirs
HdfsBlobStoreImpl and HdfsBlobStoreFile will create directory with 700 permission, we need to check if permission is set as expected. Because of the influence of settings such as umask, we need to check whether the permissions are set as expected. If not, we should give them the correct permissions to ensure subsequent normal operation.
> STORM-3862 HdfsBlobStoreImpl should check permission after mkdirs

- DEPENDENCY-LICENSES
- examples/storm-jms-examples/pom.xml
- examples/storm-mqtt-examples/pom.xml
- external/storm-jms/pom.xml
- external/storm-mqtt/pom.xml
- pom.xml
*Upgrade to ActiveMQ version 5.16.5 (highest for Jdk8) and undo com.google..guava version downgrade*
*Build, test, and check licenses*
> [STORM-3867] Bump activemq to 5.16.5 (highest for Jdk8) and undo guava downgrade

- DEVELOPER.md
- RELEASING.md
- bin/docker-to-squash.py
- bin/storm.py
- bin/test_docker_to_squash.py
- bin/test_storm.py
- dev-tools/find-checkstyle-issues.py
- dev-tools/github/__init__.py
- dev-tools/jira-github-join.py
- dev-tools/jira_github/__init__.py
- dev-tools/release_notes.py
- dev-tools/report/formatter.py
- dev-tools/report/report.py
- dev-tools/report/report_builder.py
- dev-tools/storm-merge.py
- dev-tools/travis/ratprint.py
- dev-tools/travis/save-logs.py
- dev-tools/travis/travis-install.sh
- dev-tools/travis/travis-script.sh
- dev-tools/validate-license-files.py
- storm-multilang/python/src/main/resources/resources/storm.py
*Python2 has been EOLed since 2020. When new storm release is made, independent verifiers cannot install python2 to verify the release. Remove python2 and replace with pytho3*
*Run syntax analyzers; run changed python scripts*
> [STORM-3855] Remove python2 support and move to python3.

- storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java
We should be able to search supervisor logs for actual errors.  This seems like it should be a WARN.
Tested ..prints log : "2021-11-01 22:22:54.696 [main] WARN  org.apache.storm.localizer.AsyncLocalizerTest - Could not update blob (org.apache.storm.utils.NimbusLeaderNotFoundException), will retry again later."
> STORM-3805 Changing error to warn for retry update operations

- docs/distcache-blobstore.md
Adding documentation for workerRestart option in the blobstore documentation.
> MINOR: add blobstore documentation for workerRestart

- DEPENDENCY-LICENSES
- LICENSE-binary
- external/storm-autocreds/pom.xml
- external/storm-hdfs/pom.xml
- external/storm-hive/pom.xml
- external/storm-solr/pom.xml
Excluding some unused packages to enable compiling with maven versions >= 3.8.1 
built locally.
> Storm 3872 Excluding some unused packages to enable compiling with maven versions >= 3.8.1 

- DEPENDENCY-LICENSES
- external/storm-hdfs-blobstore/pom.xml
- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterExtension.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterExtensionClassLevel.java
- storm-client/test/py/test_storm_cli.py
Remove junit4 from storm-hdfs and storm-hdfs blobstore to completely remove junit4 from Storm.
built locally
> STORM-3873: Remove junit4 dependency

- conf/defaults.yaml
Issue:
- Many of the default worker JVM parameters is no longer supported in java versions > 11. This will result in the worker process getting crashed. eg: https://github.com/31z4/storm-docker/issues/32
- The official storm docker hub (https://hub.docker.com/_/storm) now ships jdk-11 and worker process fails with Error: Could not create the Java Virtual Machine.
To make storm workers run in jdk-11 and above
Storm workers are not able to start in jdk-11 and above
Tested by running " storm supervisor -c worker.childopts= .. " with open-jdk11 and see that the topology is working as expected and worker process is getting started.
before fix:
2022-12-07 17:38:27.653 o.a.s.d.s.BasicContainer …
> Adding IgnoreUnrecognizedVMOptions to make worker start with jdk-11

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
*Dependabot recommendation*
*Run unit and integration test*
> [STORM-3889] Bump snakeyaml from 1.26 to 1.32

- .github/workflows/maven.yaml
- DEPENDENCY-LICENSES
- examples/storm-starter/pom.xml
- integration-test/pom.xml
- Adds GitHub actions on the basis of the old travis script (and similar to them)
- Downgrades TestNG as it isn't compatible with Java 8
- Fixes license files
Note: `integration-tests` are failing as the related `.sh` is highly Travis specific and needs some rework. IMHO, we should fix it in a separate Jira. Wdyt?
It superseeds https://github.com/apache/storm/pull/3519
- GitHub Actions
> STORM-3897 Replace Travis with GitHub Actions

- dev-tools/validate-license-files.py
in DEPENDENCY-LICENSES
*Usual update to the build process occurs in small increments, and therefore the license differences are usually small to none. If just the summary of differences is printed then it is faster to spot and correct the differences and speeds up the iteration - as apposed to downloading the two files and doing a local diff.*
*Running the script locally. Also this script automatically gets executed for every pull request*
> [STORM-3902] Print summary of differences between expected and actual licenses

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
*Based on dependabot PR that did not trigger a rebuild https://github.com/apache/storm/pull/3511 and add changes to license files*
*Trigger rebuild with this new PR*
> [STORM-3903] Bump commons-fileupload from 1.3.3 to 1.5

- DEPENDENCY-LICENSES
- pom.xml
- storm-client/test/jvm/org/apache/storm/executor/ExecutorTransferMultiThreadingTest.java
*FieldSetter class has been deprecated in minor version of Mockito, replace with reflection API*
*Build and test*
> [STORM-3906] Remove org.mockito.internal.util.reflection.FieldSetter and set mockito.version to 3.11.2

- dev-tools/gitact/gitact-script.sh
*Sometimes github actions get out-of-memory exception. Since the Github Action Runners as bigger VMs that Travis used in the past, the heap can be made bigger.*
*Pull request will run this build and test using Github Runners*
> [STORM-3908] Increase heap memory for MAVEN_OPTS used in github actions

- storm-core/test/clj/org/apache/storm/metrics_test.clj
*Ensure that python version 3 is used*
*Run test*
> [STORM-3909] Use python3 in metrics test

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
- storm-clojure/pom.xml
*Carbonite:1.5.0 jar hasn't been changed since 2012 and includes some very old dependencies and java version. Create a new carbonite jar with version 1.6.0, update compiler and dependencies. Then reference this new version 1.6.0 jar in storm*
*Build and run tests.*
> [STORM-3912] Reference new clojar for carbonite version 1.6.0

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
- storm-server/pom.xml
*Version 6.27.3 does not have Mac OSX JNI Library. Some tests fail to load because of this missing dependency on Mac.*
*Run junit tests*
> [STORM-3913] Update rocksdb to version 8.1.1 that has Mac OSX JNI lib

- storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java
An infinite loop can occur when the worker directory takes too much space, but no files are found to remove.
I have not independently tested this change.
> Fix infinite loop when no files are left to remove

- storm-server/pom.xml
- storm-server/src/main/java/org/apache/storm/metricstore/MetricStoreConfig.java
- storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/RocksDbStore.java
- storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/StringMetadataCache.java
*Rocksdb requires a platform specific JNI library. This library is included in the rocksdbjni jar but is not loaded unless the dynamic library is in a location specified by environment variable ROCKSDB_SHAREDLIB_DIR is set and points to directory where the native JNI library is extracted to.
*Run the code on Mac*
> [STORM-3910] Enhanced logging for rocksdb metrics store.

- flux/README.md
- flux/flux-core/src/test/resources/configs/bad_shell_test.yaml
- flux/flux-core/src/test/resources/configs/kafka_test.yaml
- flux/flux-core/src/test/resources/configs/shell_test.yaml
- flux/flux-core/src/test/resources/configs/substitution-test.yaml
- flux/flux-examples/src/main/resources/kafka_spout.yaml
- flux/flux-examples/src/main/resources/multilang.yaml
- flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/bolts/FluxShellBolt.java
- flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/spouts/FluxShellSpout.java
*Python2 has been deprecated. However many systems still activate python2 when only using python. Change it to python3 to ensure Python version 3 is used.*
*Run the example python scripts through Python 3 syntax checks*
> [STORM-3928] Use python3 in flux test, examples and wrappers

- examples/storm-starter/src/jvm/org/apache/storm/starter/BlobStoreAPIWordCountTopology.java
- examples/storm-starter/src/jvm/org/apache/storm/starter/WordCountTopology.java
*Python2 has been deprecated. However many systems still activate python2 when only using python. Change it to python3 to ensure Python version 3 is used.*
*Run the example python scripts through Python 3 syntax checks*
> [STORM-3927] Change python to python3 in examples

- pom.xml
*While doing "mvn release:perform", the checkout times out at the end when using the https connection. Also the url is old. Use the new url (change from gitbox to github) that is the target of redirect.*
*Pull Request checks (github actions)*
> [STORM-3930] Change the source code control URI 

- .github/workflows/maven.yaml
- external/storm-cassandra/pom.xml
- pom.xml
- storm-server/pom.xml
*Add JDK-17 Build*
*Let the github actions run*
> [STORM-3895] Add JDK-17 build

- external/storm-autocreds/pom.xml
- external/storm-hive/pom.xml
Storm can't be built because the dependency pentaho-aggdesigner-algorithm is not available. 
This dependency is excluded in some places of the poms but not systematically, excluding it everywhere allows the code to be built.
`mvn clean install -DskipTests`
> Missing dependency prevents Storm from being built, fixes #3940

- .asf.yaml
- Adds an `.asf.yaml` for GitHub configuration.
- Updates the titles of the auto generated messages from GitHub like described in https://community.apache.org/contributors/mailing-lists.html#configuring-the-subject-lines-of-the-emails-being-sent
- Make it human readable like in https://lists.apache.org/list?dev@streampipes.apache.org:lte=4M (Note: As per discussion on comdev, the defaults might change anyway to this one)
- Prevent force pushed on master
> STORM-3941 - Add .asf.yaml to GitHub repository

- .github/workflows/maven.yaml
- external/storm-blobstore-migration/pom.xml
- external/storm-cassandra/pom.xml
- pom.xml
- storm-server/pom.xml
*Drop support for JDK8, set minimum JDK level to 11 - in order for new JDK and packaging features to be used*
*mvn test; also allow githun actions to run.*
> [STORM-3939] Remove gitact build for JDK 8, set class format to JDK11 and allow introspection in test

- storm-client/src/jvm/org/apache/storm/metric/api/MultiCountMetric.java
- storm-client/src/jvm/org/apache/storm/metric/api/MultiReducedMetric.java
See https://issues.apache.org/jira/browse/STORM-3944
Also marks fields as final
> [STORM-3944] Synchronize access to map in Multi*Metric

- pom.xml
Hive 2.3.9 declares an offline repository in its parent pom.  Leading to timeouts resolving that repository during a local build. We can work around by re-declaring this repository until 2.3.10 is hopefully released (which removed that repo on their side).
* Local Build
> [STORM-3948] Hive 2.3.9 declares an offline / unmaintained maven repository

- dev-tools/gitact/gitact-script.sh
- We are testing everything for Java 17, so we should also test everything with Java 11
- Run GH actions
> [STORM-3914] Several External Modules as not being tested for JDK 11

- DEPENDENCY-LICENSES
- external/storm-jdbc/pom.xml
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/AbstractJdbcBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcInsertBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcLookupBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/common/HikariCPConnectionProvider.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/common/JdbcClient.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/mapper/SimpleJdbcLookupMapper.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/mapper/SimpleJdbcMapper.java
- external/storm-jdbc/src/test/java/org/apache/storm/jdbc/bolt/JdbcInsertBoltTest.java
- external/storm-jdbc/src/test/java/org/apache/storm/jdbc/bolt/JdbcLookupBoltTest.java
- Modernize external module storm-jdbc with newer dependency versions
- Local test run with Maven
- GH actions
Our dependency stack (mostly from hadoop / external) includes a lot of super old stuff. We also have some libraries multiple times in our dependency stack, so it would be a good thing to clean it up at some point.
> [STORM-3950] Modernize storm-jdbc

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
- storm-shaded-deps/pom.xml
Zookeeper 3.9.0 pulls in logback. However, we are using slf4j + log4j2, so we can remove that dependency. 
Note: Some of our tests already complained about multiple logger bindings.
GH Actions
> [STORM-3954] Remove Logback pulled in by Zookeeper

- bin/storm.py
The `component` value is a string, not a number, see [Monitor.java](https://github.com/apache/storm/blob/master/storm-core/src/jvm/org/apache/storm/utils/Monitor.java#L156).
Attempting to use a number throws a stacktrace like such:
```
~/apache-storm-2.3.0/bin/storm monitor -m wordGenerator production-topology
topology	component	parallelism	stream	time-diff ms	emitted	throughput (Kt/s)
Available components for production-topology :
------------------
__acker
wordGenerator
intermediateRanker
counter
finalRanker
------------------
Exception in thread "main" java.lang.IllegalArgumentException: component: wordGeneratotor not found
at org.apache.storm.utils.Monitor.metrics(Monitor.java:128)
at org.apache.storm.utils.Monitor.metrics(Monitor.java:83)
at …
```
> [STORM-3956] Fix cli monitor component's argument type

- pom.xml
*Specify the default location of generated sources. This allows IDEs like eclipse to generate, detect, and load generated classes*
*Loaded Storm into Eclipse as a maven project and very that storm-sql-core loads classes properly and org.apache.storm.sql.parser.impl.StomParserImpl is detected and loaded automatically*
> [STORM-3967] Specify generated sources directory.

- storm-core/pom.xml
*Missing groupId for maven-dependency-plugin leads to errors in processing storm-core module in eclipse*
*Change pom.xml and refresh project in eclipse*
> [STORM-3968] Add missing groupId in storm-core/pom.xml for maven-dependency-plugin

- external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreFile.java
```java
public OutputStream getOutputStream() throws IOException {
FsPermission fileperms = new FsPermission(BLOBSTORE_FILE_PERMISSION);
try {
out = fileSystem.create(path, (short) this.getMetadata().get_replication_factor());
fileSystem.setPermission(path, fileperms);
fileSystem.setReplication(path, (short) this.getMetadata().get_replication_factor());
} catch (IOException e) {
......
out = fileSystem.create(path, (short) this.getMetadata().get_replication_factor());
fileSystem.setPermission(path, dirperms);
fileSystem.setReplication(path, (short) this.getMetadata().get_replication_factor());
}
......
}
```
We can see that there are permission settings for path in both try and catch, but the permission in catch is different from that in try. In catch, the permission `dirperms` is given …
> STORM-3888 HdfsBlobStoreFile set wrong permission for file

- sql/storm-sql-core/pom.xml
*storm-sql-core extract javacc parser definition from Calcite jar, adds it to distribution, then used javacc to generate classes that parser definition file. These java classes are then used in storm-sql-core. Eclipse does not properly recognize and execute these steps and then shows errors because of missing generated classes.*
*Review the project in project explorer tab in eclipse and ensure that errors are gone. Also do a "mvn clean install" to ensure that maven build is not broken.*
> [STORM-3970] Changes to storm-sql-core/pom.xml to avoid errors in Eclipse

- conf/defaults.yaml
- storm-server/src/main/java/org/apache/storm/DaemonConfig.java
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/component.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/index.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/js/script.js
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/owner.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/supervisor.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/templates/title-template.html
- storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/topology.html
Currently, the string "Storm UI" is hard-coded in Storm's UI pages. 
When one is managing different Storm deployments, say for example for pre-production vs. production purposes, it's hard to tell which Storm UI is for which deployment just looking at brower's tabs names.
The change allows defining a replacement value for "Storm UI" in conf/storm.yaml with "ui.title" property.
The default value of this property remains "Storm UI", for compatibility purposes.
I tested this change by first patching an already deployed Storm cluster with my changes, with and without setting "storm.ui" property in storm.yaml (having to restart storm and storm-ui for the changes to be taken into account).
I ran 'mvn' commands to have compilation / checkstyle stuff to be applied to my changes.
> STORM-3958: Capacity to set Storm UI's title in conf/storm.yaml

- README.markdown
- RELEASING.md
- doap_Storm.rdf
- pom.xml
- Removes outdated developer information from README. Project's roster can be found on Storm's website
- Removes the `developer` section in the ROOT Pom for the same reason.
- Updates DOAP file with latest release
- Move links to HTTPS
- POM formatting
> [STORM-3982] Updates README, POM.xml and DOAP file

- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
- storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/SchedulingSearcherState.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
*While backtracking in scheduling code, Ackers are skipped. However, under certain circumstances a null WorkerSlot is passed as parameter to SchedulingSearcherState.backtrack(). This null key is used to retrieve an entry from Map. The returned null map value causes NPE*
*new unit test TestGenericResourceAwareStrategy.testScheduleLeftOverAckers()*
> [STORM-3764] Fix NPE in SchedulingSearcherState.backtrack()

- DEPENDENCY-LICENSES
- LICENSE-binary
- pom.xml
- storm-server/pom.xml
- Updates rocksdbjni as 8.1.1 is a broken release regarding Windows (cf. https://github.com/facebook/rocksdb/issues/11420)
- CI
> STORM-3994 - LocalCluster init fails on Windows because of missing librocksdbjni-win64.dll

- external/storm-kafka-monitor/pom.xml
When running Storm UI with Java 17 runtime, the lag of Kafka consumers is not visible in the topology view for the topologies which are consuming Kafka topics. Based on exceptions found in ui.log, this is because storm-kakfa-monitor is missing JAXB API.
Using Storm 2.6.0 snapshot dated 2023/11/14, doing a copy of  jakarta.xml.bind-api-2.3.2.jar from lib-worker/ to lib-tools/storm-kafka-monitor/ then restarting Storm UI process solves the problem.
> [STORM-4003] add missing jakarta.xml.bind dependency to storm-kafka-monitor

- .github/workflows/snapshots.yaml
With STORM-4006 we are now publishing the tar.gz / zip files every day to https://nightlies.apache.org/storm/
In addition, we should publish SNAPSHOT artifacts to the nexus repository as well so people get a chance to test these SNAPSHOT builds.
Related INFRA ticket is open: https://issues.apache.org/jira/browse/INFRA-25234
After INFRA has added the secrets, we can move on with this PR.
> STORM-4008 - Implement timed GH actions to publish SNAPSHOTS

- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
*In AWS EKS environment, the nimbus log seems to be flooded with heartbeat time exception messages for dead topologies*
*Test run as part of this Pull Request*
> [STORM-4022] Do not log Exception when getting heartbeat timeout for dead topologies

- storm-client/src/jvm/org/apache/storm/utils/VersionedStore.java
This changes slightly simplifies the heartbeat cleanup code so it no longer tries to delete the heartbeat files twice. It also removes an unneeded directory listing (and possible race) by truncating the versions list and using it for removal instead of for keeping.
Removing the double delete attempt is important because it removes a lookup for now non-existent files. Looking up non existent files, especially highly unique (like timestamped) ones can adversely affect many operating systems as these lookups are cached as negative dentries.
https://lwn.net/Articles/814535/
When cleanup runs, it iterates over the heartbeat directory that contains a token and version file for each heartbeat. It calls deleteVersion for each file in the directory which attempts to delete both files associated …
> STORM-4052 - Simplify/Remove double delete/lookup in heartbeat cleanup code.

- DEPENDENCY-LICENSES
- external/storm-hdfs-blobstore/pom.xml
- external/storm-hdfs/pom.xml
- sql/storm-sql-external/storm-sql-hdfs/pom.xml
Followed advice from Hadoop Devs: https://lists.apache.org/thread/f47s6bxrtslkxbc8s2gybwrxps8vk63x
> STORM-4053 - Include Client API / Runtime for HDFS

- docs/Metrics.md
- storm-client/src/jvm/org/apache/storm/metric/SystemBolt.java
Allow reporting of worker cpu usage if no cgroups are configured.
run on internal storm clusters.
I have been unable to log into Storm JIRA to create a related JIRA.
> STORM-4054 -Add Worker CPU Metric

- storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java
Validate the user associated with the id command for scenarios where the user running Storm in a container is not listed in the /etc/passwd file when a Worker process is to be terminated, e.g. with a custom securityContext in Kubernetes:
securityContext:
runAsUser: 1000620005
fsGroup: 1000620005
supplementalGroups: [ 64000 ]
Without this change the Supervisor container itself dies rather than terminating the Worker process.
I have tested the change locally running a Kubernetes cluster with this fix in place.  The Worker process is successfully terminated and the Supervisor container does not die.
> STORM-4057 - Validate user with the id cmd

- conf/defaults.yaml
- storm-client/pom.xml
- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/utils/CuratorUtils.java
- storm-client/test/jvm/org/apache/storm/utils/CuratorUtilsTest.java
> STORM-4075 Supprt mTLS between Storm and ZK

- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/test/jvm/org/apache/storm/utils/UtilsTest.java
Fixes STORM-4104 to improve the stability of Pacemaker server (and Netty Server in Workers) bringing it closer to the stability it had in Storm1. This is done by changing the behaviour of Utils.handleUncaughtException to also swallow exceptions derived from those in the supplied ALLOWED_EXCEPTIONS list instead of only the exact exceptions defined in there (i.e. instead of only 'swallowing' IOException, this change will allow SocketException (derived from IOException) to also be 'swallowed')
Before this change it is easy to see Pacemaker server shut down when simply killing a topology:
2024-11-06 15:21:13.251 [o.a.s.m.n.StormServerHandler] ERROR: server errors in handling the request from /10.44.19.106:59691
java.net.SocketException: Connection reset	at …
> STORM-4104 Fix Pacemaker server stability issues

- bin/storm.ps1
Addresses STORM-4106. Stdout\Stderr feedback when launching Storm.ps1 in Powershell ISE now works with this change
Feedback from regular Powershell cmd prompt continues to work with this fix too.
Open Powershell ISE and run Storm.ps1 to run a command (e..g show usage with ./storm1.ps1 -h)
Before the fix the Powershell ISE returns nothing output from Storm.ps1
With this fix the output Storm.ps1 is seen in Powershell ISE command window (and continues to be seen in regular Powershell cmd prompt)
See attached screenshots from before and after fix for both Powershell ISE and regular Powershell command prompts
Before Fix
After Fix
> STORM-4106 Fix Storm.ps1 stdout/stderr feedback in Powershell ISE

- storm-client/src/jvm/org/apache/storm/executor/Executor.java
- storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
- storm-client/test/jvm/org/apache/storm/executor/SpoutExecutorTest.java
StormExecutor: adding an unit test to check if the RotatingMap' `rotate` is called only once when timing out tuples.
`StormExecutor` requires a considerable effort to mock and the `pending` map (which is RotatingMap) is an internal attribute. JUnit's reflection was used to mock the RotationMap and verify how many times `rotate` was called.
This test is far from optimal and I'm not a fan of using reflection, but will make it easier to detect regressions. 
The test should be refactored in the future.
Additionally, refactored the changes introduced in https://github.com/apache/storm/pull/3828: `boolean isSpout = this instanceof SpoutExecutor;` should not be in Executor. A parent class should not have references to subclasses
`mvn clean install`. All tests are passing.
> StormExecutor: adding an unit test to changes introduced in STORM-3693 

- docs/SECURITY.md
Doc for https://issues.apache.org/jira/browse/STORM-4070
> STORM-4079: SSL Setup Doc
