- external/storm-kafka/src/jvm/storm/kafka/KafkaUtils.java
PR for [STORM-613](https://issues.apache.org/jira/browse/STORM-613)
When judge getOffset return value, use 0 not NO_OFFSET as invalid offset return value.
> STORM-613: Fix wrong getOffset return value

- storm-core/src/jvm/backtype/storm/utils/ShellProcess.java
@d2r , @harshach , @HeartSaVioR ,  I closed the old pull request by accident, so I opened a new one, and move all the comments to here.
------------------------------------------------------------------------------------------------
In ShellBolt, the _readerThread read command from python/shell process, and handle like this:
try
{ 
ShellMsg shellMsg = _process.readShellMsg(); 
... 
} catch (InterruptedException e) {
} catch (Throwable t) { 
die(t); 
}
And in the die function, getProcessTerminationInfoString will read getErrorsString() from processErrorStream.
private void die(Throwable exception) { 
String processInfo = _process.getProcessInfoString() + _process.getProcessTerminationInfoString(); 
_exception = new RuntimeException(processInfo, exception); 
}
so when ShellBolt got …
> [STORM-442] multilang ShellBolt/ShellSpout die() can be hang when Exception happened

- storm-core/test/clj/backtype/storm/supervisor_test.clj
These tests are causing null reference errors when executor-id->tasks is called on these erroneous executor ids.
> Fix calls to submit-mocked-assignment: executor id should be of the form [first-task last-task]

- pom.xml
Fix duplicate maven-javadoc-plugin declaration in pom.xml reporting section
> [STORM-620] Duplicate maven plugin declaration

- pom.xml
- storm-core/src/clj/backtype/storm/util.clj
Through upgrading clojure 1.6.0, there are name space conflicts in `zip-contains-dir?`. Renamed it.
It looks there is no other dependencies of `some?` function and a topology, `ExclamationTopology` seems fine on my test cluster. If there is any other concern about upgrading clojure, please let me know.
> [STORM-630] Support for Clojure 1.6.0

- docs/documentation/Contributing-to-Storm.md
- docs/downloads.html
Attach some links to GitHub repository on download page and contributing page.
> [STORM-629] Place Link to Source Code Repository on Webpage

- docs/README.md
- docs/documentation/Home.md
- pom.xml
There is no latest javadoc on official site now.
https://storm.apache.org/documentation/Home.html
In addition to this, current javadocs are hosted outside of apache domain.
Maven build pipeline includes generation process of javadoc.
> [STORM-623] Generate latest javadocs

- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchExecutor.java
Close the spout when the emitter of TridentSpout closed.
> Fix spout close: close spout when emitter closed

- storm-core/src/clj/backtype/storm/daemon/task.clj
Update "get-task-object" function, change the type of first param "topology" from ^TopologyContext to ^StormTopology. the "get-task-object" function in task.clj,the type of first param "topology" should be ^StormTopology not ^TopologyContext.
the "get-task-object" is called by "mk-task-data" function in task.clj, "mk-task-data" is defined as following:
(defn mk-task-data [executor-data task-id]
(recursive-map
:executor-data executor-data
:task-id task-id
:system-context (system-topology-context (:worker executor-data) executor-data task-id)
:user-context (user-topology-context (:worker executor-data) executor-data task-id)
:builtin-metrics (builtin-metrics/make-data (:type executor-data))
:tasks-fn (mk-tasks-fn <>)
:object (get-task-object (.getRawTopology ^TopologyContext …
> Update "get-task-object" function, change the type of first param "topology" from ^TopologyContext to ^StormTopology.(JIRA [STORM-554])

- SECURITY.md
There is no description about DRPC HTTP port in SECURITY.md.
This port is used by DRPC Client as default 3774
> [STORM-653] missing DRPC HTTP port in SECURITY.md

- storm-core/src/jvm/backtype/storm/topology/BoltDeclarer.java
- storm-core/src/jvm/backtype/storm/topology/InputDeclarer.java
Add a link to stream grouping for BoltDeclarer which define the API of grouping.
And more specific explanation about grouping API to javadoc.
> [STORM-663] Create javadocs for BoltDeclarer

- external/storm-kafka/src/jvm/storm/kafka/ExponentialBackoffMsgRetryManager.java
Not sure how long we want to cling to 1.6 compatibility, but this is a very small change.
> STORM-670: restore java 1.6 compatibility (storm-kafka)

- dev-tools/test-ns.py
Adding test-ns.py
test-ns.py accepts a single argument, the name of a test namespace to run. Run it from the storm project root.
```
~/storm $ dev-tools/test-ns.py backtype.storm.config-test
...
Ran 11 tests containing 52 assertions.
0 failures, 0 errors.
{:type :summary, :fail 0, :error 0, :pass 52, :test 11}
user=> Bye for now!
```
> [STORM-696] Single Namespace Test Launching

- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Context.java
- Adding tracking of netty connection by key and reuse whenever client is available.
- Fix included original changes from #455.
> [STORM-625] Don't leak netty clients when worker moves or reuse netty client.

- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
These logging statements are not on a hot path, and `INFO` is the default log level of Storm.  These logging statements are filling a gap that facilitates understanding connection woes in a Storm cluster (cf. our work on STORM-329).
> STORM-707: Client (Netty): improve logging to help troubleshooting connection woes

- external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisMapState.java
This commit fixes a bug whereby if the state updater is constructed with a hash key (ie, the state will be stored as a key in a redis hash, versus as a key in the top-level redis space), each call to multiGet would request the entire hash and iterate to extract only the values in the hash relevant to the batch.
This can cause an inordinate amount of network traffic (and actually caused our interfaces to fall over) for states with either a moderately high cardinality or large values. Instead, the call to Redis should be an hmget (hash multiget) that takes the hash key as its first argument and an array of strings as the keys to fetch from that key, thereby retrieving only the requested values.
The change also deprecates and removes buildValuesFromMap.
> [STORM-703] With hash key option for RedisMapState, only get values for keys in batch

- external/storm-kafka/src/jvm/storm/kafka/KafkaUtils.java
Currently, Kafka metrics are emitted with partition information, but no information about which topic that partition belongs to. This patch includes the topic information in the Storm metrics emitted by the Kafka spout so that multiple input topics may be tracked from a single topology.
> STORM-713: Include topic information with Kafka metrics

- DEVELOPER.md
- storm-buildtools/storm-maven-plugins/pom.xml
maven compile is fail due to missing storm-maven-plugin. 
This plugin should be installed before compiling storm-core project.
> [STORM-639] storm-maven-plugin not found

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
Storm fails to compile sometimes because of bad imports. 
The import of SupervisorInfo in this file depends on compilation order to succeed. Removing it and using the clojure constructor for SupervisorInfo fixes the issue.
> STORM-694: java.lang.ClassNotFoundException: backtype.storm.daemon.common.SupervisorInfo

- storm-core/src/clj/backtype/storm/ui/core.clj
Built this and saw two different values, proc-lat < exec-lat, while running word_count.
> [STORM-788] Fix key for process latencies

- external/storm-kafka/src/jvm/storm/kafka/bolt/KafkaBolt.java
- external/storm-kafka/src/test/storm/kafka/bolt/KafkaBoltTest.java
[STORM-512](https://issues.apache.org/jira/browse/STORM-512) (KafkaBolt doesn't handle ticks properly) adds special-casing of tick tuples. What is missing in the patch is that the input tuple, when it is a tick tuple, should be properly acked like normal tuples.
> STORM-786: KafkaBolt should ack tick tuples

- docs/documentation/Multilang-protocol.md
- storm-core/src/jvm/backtype/storm/task/TopologyContext.java
This PR adds the following keys to the "context" JSON dictionary sent to multi-lang tasks as part of their handshake with ShellBolt/ShellSpout:
-  `componentid`: the component ID for this task, so you no longer have to look it up in `task->component` by `taskid`
-  `streams`: a list of all of the streams for this task
-  `stream->outputfields`:  a mapping from stream names to output fields for that stream
-  `stream->target->grouping`: a mapping from stream names to the targets for this task to the kind of grouping they use.
-  `source->stream->grouping`:  a mapping from the component IDs of the sources to their streams to their groupings.
Note on groupings:  groupings are represented as a dictionary containing a required `type` key (e.g., `"SHUFFLE"`) and an optional `fields` key (for …
> [STORM-789] Send more topology context to Multi-Lang components via initial handshake

- dev-tools/test-ns.py
Slightly more complicated clojure.
The only thing really changing here is that it checks the values for the `:fail` and `:error` keys in the return value of `run-tests`
In case of error, `System.exit(1)`. 
In the python, propagate the exit code.
> [STORM-787]: test-ns should announce test failures with 'BUILD FAILURE'

- storm-core/src/clj/backtype/storm/daemon/executor.clj
See [STORM-746](https://issues.apache.org/jira/browse/STORM-746) for the description.
> [STORM-746] Skip ack init when there are no output tasks

- storm-core/src/clj/backtype/storm/daemon/drpc.clj
- storm-core/src/clj/backtype/storm/daemon/logviewer.clj
- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/util.clj
- storm-core/src/jvm/backtype/storm/drpc/DRPCSpout.java
- storm-core/src/jvm/backtype/storm/security/auth/SaslTransportPlugin.java
- storm-core/src/jvm/backtype/storm/utils/ExtendedThreadPoolExecutor.java
- storm-core/src/jvm/backtype/storm/utils/Utils.java
- Creating `ExtendedThreadPoolExecutor` to pass uncaughtExceptions as part of `afterExecute`
- All daemon main threads set `uncaughtExceptionHandler`.
> [STORM-712] Storm daemons shutdown if OutOfMemoryError occurs in any thread 

- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueTest.java
The test had two race conditions in it.  The first was that the data returned by the Consumer was not volatile.  The second was that run gave no time for the consumer to actually receive anything so under heavy load it was possible for it to not actually complete.
> STORM-797: DisruptorQueueTest has some race conditions in it.

- external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/mapper/SimpleTridentHBaseMapMapper.java
- external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/mapper/TridentHBaseMapMapper.java
- external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/state/HBaseMapState.java
In HBaseMapState, user can specific hbase-qualifier by Options, and the hbase-key is composed by all the keys by multiPut's  keys.
for example, If I have stream with (deal_id, date, pv ), grouped by (deal_id, date), then, the hbase-key is composed by(deal_id, date), the hbase-qualifier is pv.
But when I want hbase-key is deal_id, and hbase-qualifier is pv+date, HBaseMapState can not support this.
==================================================================================
With this patch, user can customize the hbase-key & hbase-qualifier by interface TridentHBaseMapMapper. 
As a old user, can use the old style like this:
HBaseMapState.Options hbaseOptions = new HBaseMapState.Options();
hbaseOptions.mapMapper = new SimpleTridentHBaseMapMapper("pv");
Also, you can customize the …
> [STORM-607] storm-hbase HBaseMapState should support user to customize the hbase-key & hbase-qualifier

- external/storm-kafka/src/jvm/storm/kafka/DynamicBrokersReader.java
- external/storm-kafka/src/test/storm/kafka/DynamicBrokersReaderTest.java
https://issues.apache.org/jira/browse/STORM-603
I was upgrading our topologies to storm-0.9.3 this [commit](https://github.com/apache/storm/commit/2596e335f27a57784a93a57823bd93dde587909f) introduced a change that threw me for a loop. When submitting my topology I got the following error.
```
[main] ERROR storm.kafka.DynamicBrokersReader - Couldn't connect to zookeeper
java.lang.IllegalArgumentException: Don't know how to convert null to int
at backtype.storm.utils.Utils.getInt(Utils.java:301) ~[storm-core-0.9.3.jar:0.9.3]
at storm.kafka.DynamicBrokersReader.<init>(DynamicBrokersReader.java:47) ~[gambit-storm-threads-0.0.1-SNAPSHOT-jar-with-dependencies.jar:na]
at com.pearson.gambit.threads.storm.ThreadsTopology.main(ThreadsTopology.java:45) …
```
> STORM-603 Log errors when required kafka params are missing

- bin/storm.cmd
Please refer https://issues.apache.org/jira/browse/STORM-745 to see more details.
The problem is, shift doesn't evaluated before calling goto.
I found the hint from http://ss64.com/nt/shift.html.
The SHIFT command will not work within parenthesis/brackets, so place all your command line arguments in variables before running any FOR commands or other bracketed expressions. Or use the CALL syntax as explained in this forum thread.
Just calling goto first resolves it.
> [STORM-745] fix storm.cmd to evaluate 'shift' correctly with 'storm jar'

- storm-core/src/jvm/backtype/storm/spout/ShellSpout.java
Addresses JIRA issue [STORM-796](https://issues.apache.org/jira/browse/STORM-796). 
The symptoms a multi-lang user will see here is that if their Spout throws an error and their multi-lang implementation sends an "error" command up to the ShellSpout, the ShellSpout will respond saying that it doesn't recognize the "error" command, and thus it will crash (while swallowing the exception thrown by the underlying multi-lang component).
ShellBolt already supports the error command, and ShellSpout already has a way of reporting errors -- so this was just a matter of adding similar logic to the ShellSpout.
> [STORM-796] Add support for "error" command in ShellSpout

- pom.xml
GPG 2.1 changed some security things involving password entry, and it looks like our version of the plugin doesn't work with it.
We should upgrade.
> [STORM-816] maven-gpg-plugin does not work with gpg 2.1

- storm-core/src/clj/backtype/storm/daemon/worker.clj
When task is null in transfer-fn, creating TaskMessage leads NPE.
Please refer https://issues.apache.org/jira/browse/STORM-770 and https://issues.apache.org/jira/browse/STORM-790.
Thanks!
> STORM-790 Log "task is null" instead of let worker died when task is null in transfer-fn

- storm-core/src/ui/public/templates/component-page-template.html
The column headers were consistent with other UI tables, so I swapped the data.
> [STORM-728] Put emitted and transferred stats under correct columns

- storm-core/src/ui/public/templates/component-page-template.html
This was missing only from the Bolt case.
> [STORM-729] Include Executors (Window Hint) if the component is of Bolt type

- external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterMapState.java
- external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisMapState.java
This is much the same as the mechanism already available via `RedisStateUpdater` for `RedisState` instances.  Users can now set `expireIntervalSec` in their `RedisMapState.Options` instance, to set an expiry timeout on each Redis key updated by the state.
> STORM-761: An option for new/updated Redis keys to expire in RedisMapState

- storm-dist/binary/src/main/assembly/binary.xml
storm-redis is not added to storm binary distribution while other externals are added.
Since it's a small patch so I didn't file an issue.
@ptgoetz @revans2 
Please review and merge to 0.10.x-branch and master so that storm-redis could be included to storm binary distribution.
Thanks in advance!
> STORM-849 Add storm-redis to storm binary distribution

- external/flux/flux-core/pom.xml
- external/storm-hdfs/pom.xml
- external/storm-jdbc/pom.xml
- external/storm-kafka/pom.xml
- pom.xml
- storm-core/pom.xml
- storm-dist/binary/src/main/assembly/binary.xml
Shading following dependencies:
org.apache.httpcomponents:http*
org.apache.zookeeper:zookeeper
org.apache.curator:*
com.twitter:carbonite
com.twitter:chill-java
org.objenesis:objenesis
org.tukaani:xz
org.yaml:snakeyaml
org.jgrapht:jgrapht-core
commons-httpclient:commons-httpclient
org.apache.commons:commons-compress
org.apache.commons:commons-exec
commons-io:commons-io
commons-codec:commons-codec
commons-fileupload:commons-fileupload
commons-lang:commons-lang
com.googlecode.json-simple:json-simple
org.clojure:math.numeric-tower
org.clojure:tools.cli
org.clojure:tools.macro
joda-time:joda-time
> [STORM-848] Shade external dependencies

- storm-core/test/resources/log4j2-test.xml
In order to prevent Travis CI complaining about log exceeding, we need to apply this.
Please review and comment. Thanks in advance!
> STORM-850 Convert storm-core's logback-test.xml to log4j2-test.xml

- examples/storm-starter/README.markdown
New multilang packages rely on supervisor deploy or maven dependency plugin.
Therefore, storm-starter README should remove example which is not working now. 
Btw, actually storm-core shows that it could be possible to unpack multilang artifacts with maven plugin and run multilang topology with mvn exec:java, and I confirmed that can work with storm-starter.
```
<plugin>
<artifactId>maven-dependency-plugin</artifactId>
<version>2.8</version>
<executions>
<execution>
<id>copy-dependencies</id>
<phase>compile</phase>
<goals>
<goal>copy-dependencies</goal>
</goals>
<configuration>
<overWriteReleases>false</overWriteReleases>
<overWriteSnapshots>false</overWriteSnapshots>
<overWriteIfNewer>true</overWriteIfNewer>
<includeScope>runtime</includeScope>
</configuration>
</execution>
<execution> …
```
> STORM-813 Change storm-starter's README so that it explains mvn exec:java cannot run multilang topology

- storm-core/src/clj/backtype/storm/converter.clj
- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
* Use serialized values for delay in rebalance and kill topology actions, in case nimbus has initialized sometime after the action was given
* Fix logic in deserialization of topology action options
> [STORM-856] use serialized value of delay secs for topo actions

- dev-tools/travis/print-errors-from-clojure-test-reports.py
- dev-tools/travis/travis-build.sh
- storm-core/test/clj/backtype/storm/security/auth/drpc_auth_test.clj
Please refer https://issues.apache.org/jira/browse/STORM-864 to see why I'm trying to exclude storm-kafka from Travis CI.
After applying this patch, we can get rid of random test failures on storm-kafka with Travis CI.
Please note that there's small probabilities to random test failures on storm-core yet.
> STORM-864 Exclude storm-kafka tests from Travis CI build

- storm-core/src/ui/public/js/script.js
When we activate topology while it is rebalancing or killed from UI, UI shows that "Error while communicating to nimbus".
Based on these, "Activate" only makes sense while inactivated.
> STORM-860 disable "Activate" button when topology status is not "inactivate"

- storm-core/src/clj/backtype/storm/ui/helpers.clj
PR for [STORM-867](https://issues.apache.org/jira/browse/STORM-867)
There are two error about mk-ssl-connector in storm-core/src/clj/backtype/storm/ui/helpers.clj
1. set trustStore password with setTrustStoreType
2. need-client-auth and want-client-auth are boolen, but use as function
> STORM-867: fix bug with mk-ssl-connector

- docs/documentation/Concepts.md
- docs/documentation/Troubleshooting.md
* Concepts.md: Correct document
* Troubleshooting.md: Add stack trace for other NPE case caused by same issue
* Related to STORM-770
> STORM-841 Correct doc that OutputCollector is not thread-safe

- bin/storm.py
This adds a check in the python script to ensure that JAVA_HOME points to an installation of storm, and prints an error message if it is not properly set.
> [STORM-477]  Add warning for invalid JAVA_HOME

- external/storm-kafka/pom.xml
- external/storm-kafka/src/jvm/storm/kafka/bolt/KafkaBolt.java
- external/storm-kafka/src/test/storm/kafka/KafkaUtilsTest.java
- external/storm-kafka/src/test/storm/kafka/bolt/KafkaBoltTest.java
1. Modify KafkaBolt to use the new KafkaProducer API (8.2 up) and long term supported kafka APIs
2. Support asynchronous message sending with callback
3. Update KafkaBoltTest and KafkaUtilsTest correspondingly
> [STORM-826] Update KafkaBolt to use the new kafka producer API 

- log4j2/cluster.xml
- log4j2/worker.xml
PR for [STORM-866](https://issues.apache.org/jira/browse/STORM-866)
The config log4j2 use storm.home as log dir, but not storm.log.dir, we should use storm.log.dir instead.
> STORM-866: Use storm.log.dir instead of storm.home in log4j2 config

- external/storm-kafka/src/jvm/storm/kafka/PartitionManager.java
PR for [STORM-810](https://issues.apache.org/jira/browse/STORM-810)
When KafkaSpout refresh with kafka partitions, it will remove patitions that no longer served by this spout and close the connection. But before close the connection, PartitionManager don't commit the latest offset. As a result some other spout that serve the removed partition will replay some tuple that between last commit and close.
> STORM-810: PartitionManager should commit latest offset before close

- storm-core/src/jvm/backtype/storm/spout/ShellSpout.java
- storm-core/src/jvm/backtype/storm/task/ShellBolt.java
- storm-core/src/jvm/backtype/storm/utils/ShellProcess.java
Support to allow ShellBolt to set environment variables
Example :
WordCountTopology.java builder.setBolt("split", (IRichBolt) new SplitSentence().setEnv(envMap) ,  8).shuffleGrouping("spout");
where envMap is a map of environment variables to be exported.
Map<String, String> envMap = new HashMap<>(); 
envMap.put("PATH","/usr/local"); // append to PATH variable 
envMap.put("HOME", "/usr/local"); // override HOME variable
NOTE: PATH variable is appended by default while others are overridden.
> STORM-160 Allow ShellBolt to set env vars (particularly PATH)

- docs/documentation/Multilang-protocol.md
- storm-core/src/jvm/backtype/storm/task/TopologyContext.java
This pull request adds a `source->stream->fields` mapping to the topology context sent to multi-lang components as part of the handshake.
It also clears up a few minor type issues in TopologyContext.java, and fixes the Multi-Lang protocol doc to note that the additions I made in #525 are in 0.10.0 and not 0.11.0.
> [STORM-928] Add source->stream->fields mapping to multi-lang context

- conf/defaults.yaml
- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Context.java
- storm-core/src/jvm/backtype/storm/messaging/netty/MessageBatch.java
- storm-core/src/jvm/backtype/storm/messaging/netty/MessageBuffer.java
- storm-core/src/jvm/backtype/storm/messaging/netty/SaslStormClientHandler.java
- storm-core/src/jvm/backtype/storm/messaging/netty/StormClientHandler.java
- storm-core/src/jvm/backtype/storm/messaging/netty/StormClientPipelineFactory.java
This is a port of PR #568 from 0.9.x to 0.11.x. It fixes STORM-839 (Deadlock) and STORM-763 (Establish Netty reconnects asynchronously and reduce verbosity of error logs)
@revans2 This is the PR for master. I ran the performance test against master's HEAD and the results were in-line with the results I got in #568 . I'll create a separate PR for 0.10.x
> Storm 763/839 0.11.x

- docs/documentation/Understanding-the-parallelism-of-a-Storm-topology.md
Closing quotes was missing in a code sample. Fixed that.
> Added closing quotes(") in the documentation

- docs/documentation/Understanding-the-parallelism-of-a-Storm-topology.md
Two tiny things I noticed while reading [Understanding the Parallelism of a Storm Topology](https://storm.apache.org/documentation/Understanding-the-parallelism-of-a-Storm-topology.html):
1. Instead of a `?` for parallelism hint config, mention parameter on methods.
2. A quote typo in a code listing.
Docs are very useful, thanks. I especially appreciate the diagrams.
> Touch up parallelism doc: typo, config for hint.

- README.markdown
- docs/documentation/Structure-of-the-codebase.md
* Remove the old webpage link in README.markdown
* Correct the link pointing to the thrift definition of bolts
> Fix a few links in the documentation

- examples/storm-starter/pom.xml
- external/flux/flux-core/pom.xml
- external/flux/flux-examples/pom.xml
- external/storm-eventhubs/pom.xml
- storm-core/pom.xml
1: fix external/flux/flux-examples duplicated classes warings 
```
[WARNING] commons-collections-3.2.1.jar, commons-beanutils-core-1.8.0.jar, commons-beanutils-1.7.0.jar define 3 overlappping classes: 
[WARNING]   - org.apache.commons.collections.ArrayStack
[WARNING]   - org.apache.commons.collections.BufferUnderflowException
[WARNING]   - org.apache.commons.collections.Buffer
[WARNING] javax.servlet-3.1.jar, servlet-api-2.5-6.1.14.jar, javax.servlet-api-3.0.1.jar, servlet-api-2.5.jar define 17 overlappping classes: 
[WARNING]   - javax.servlet.ServletInputStream
[WARNING]   - javax.servlet.Filter
[WARNING]   - javax.servlet.http.HttpSession
[WARNING]   - javax.servlet.FilterConfig
[WARNING]   - javax.servlet.FilterChain
[WARNING]   - javax.servlet.http.Cookie
[WARNING]   - …
```
> STORM-926:change pom to use maven-shade-plugin:2.2 and minimize the size of shade jar and fix duplicated classes warnings of flue-examples

- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
fix the dismatch between doc and source code in function read-all-supervisor-details
> fix the dismatch between doc and code for read-all-supervisor-details

- external/storm-eventhubs/src/test/java/org/apache/storm/eventhubs/spout/SpoutOutputCollectorMock.java
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/jvm/backtype/storm/spout/ISpoutOutputCollector.java
- storm-core/src/jvm/backtype/storm/spout/SpoutOutputCollector.java
- storm-core/src/jvm/backtype/storm/testing/SpoutTracker.java
- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchExecutor.java
- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchTriggerer.java
Changes made to expose the pending tuple count saved inside the RotatingMap [ 
https://github.com/apache/storm/blob/master/docs/documentation/Acking-framework-implementation.md#pending-tuples-and-the-rotatingmap ]
> STORM-67 Provide API for spouts to know how many pending messages there are

- bin/storm.py
Storm commands that mandate proper args to be passed would now throw
the function's doc string as help rather than exiting out with error after creating the JVM
process.
Example : 
./storm kill
Syntax: [storm kill topology-name [-w wait-time-secs]]
Kills the topology with the name topology-name. Storm will
first deactivate the topology's spouts for the duration of
the topology's message timeout to allow all messages currently
being processed to finish processing. Storm will then shutdown
the workers and clean up their state. You can override the length
of time Storm waits between deactivation and shutdown with the -w flag.
./storm get-errors
Syntax: [storm get-errors topology-name]
Get the latest error from the running topology. The returned result contains
the key value pairs for …
> STORM-918 Storm CLI could validate arguments/print usage

- log4j2/cluster.xml
- log4j2/worker.xml
```
-> storm-current  bin/storm nimbus
Running: /usr/share/jdk-current/bin/java -server -Ddaemon.name=nimbus ... ...
2015-07-17 10:23:36,776 ERROR Policies has no parameter that matches element DefaultRolloverStrategy
2015-07-17 10:23:36,787 ERROR Policies has no parameter that matches element DefaultRolloverStrategy
2015-07-17 10:23:36,795 ERROR Policies has no parameter that matches element DefaultRolloverStrategy
```
> STORM-945:<DefaultRolloverStrategy> element is not a policy,and should not be putted in the <Policies> element

- storm-core/test/clj/backtype/storm/nimbus_test.clj
Confirmed that it fails on 27bc183c0f1e33fefb19b640f8a91f563c60ce61 (before merging STORM-856), and succeeds on current master.
Please review and comment. Thanks!
> STORM-859 Add regression test of STORM-856

- README.markdown
- external/storm-elasticsearch/README.md
- external/storm-elasticsearch/pom.xml
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/AbstractEsBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsIndexBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsPercolateBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/common/EsConfig.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/trident/EsState.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/trident/EsStateFactory.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/trident/EsUpdater.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/AbstractEsBoltTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsIndexBoltTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsIndexTopology.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsPercolateBoltTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/common/EsConstants.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/common/EsTestUtil.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/trident/TridentEsTopology.java
- pom.xml
- storm-dist/binary/src/main/assembly/binary.xml
This PR is about introducing another external module, storm-elasticsearch.
At this moment, it contains two basic bolt, namely, EsIndexBolt and EsPercolatorBolt, and trident state, also basic test cases for them.
It will be very nice to have it included in Storm, since ElasticSearch is one of the greatest open source search & storage engine which is widely used.
Please review this and merge to master.
> STORM-845 Storm ElasticSearch connector

- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/ConfigValidation.java
- storm-core/test/clj/backtype/storm/config_test.clj
ConfigValidation.DoubleValidator doesn't really validate whether the type of the object is a double.
ConfigValidation.DoubleValidator code only checks if the object is null whether if the object is a instance of Number which is a parent class of Double.
DoubleValidator is only used once in Config.java and in that instance:
public static final Object TOPOLOGY_STATS_SAMPLE_RATE_SCHEMA = ConfigValidation.DoubleValidator;
can just be set to:
public static final Object TOPOLOGY_STATS_SAMPLE_RATE_SCHEMA = NUMBER.class;
Then we can just get rid of the misleading function ConfigValidation.DoubleValidator since it doesn't really check if a object is of double type thus the validator function doesn't really do anything and the name is misleading. In previous commit …
> STORM-966 ConfigValidation.DoubleValidator is misleading and not neccessary

- external/storm-hive/pom.xml
Hive 0.14 depends on apache calcite 0.9.2-incubating-SNAPSHOT, which causes a conflict with the 0.9.2-incubating dependency further down in this pom.  Excluding it from the Hive dependencies resolves a minor conflict.
> STORM-944 storm-hive: Fix apache calcite dependency conflict

- dev-tools/travis/travis-script.sh
Please refer https://issues.apache.org/jira/browse/STORM-980 to more details.
We should resolve storm-hive build issue first (#609 may help to resolve), so that Travis CI has a chance to run unit tests on storm-kafka.
For confirmation, I merged #609 and current PR into another branch on my fork and built it from Travis CI.
https://travis-ci.org/HeartSaVioR/storm/builds/75071270
> STORM-980 Re-include storm-kafka to Travis CI build

- conf/defaults.yaml
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/jvm/backtype/storm/Config.java
The log writer process that writes out stderr and stdout should have a config that controls it's memory usage and it should default to a very small value, probably 50MB in most cases.
To address above issue, one new parameter is defined for logwriter's jvmopts: "topology.worker.lw.childopts".
The default heap size of logwriter is set as 64M, or user can override it through "-c topology.worker.lw.childopts='xxxx " when submitting a topology.
> STORM-964, add config for worker logwriter to restrict its mem usage

- storm-core/src/jvm/backtype/storm/task/ShellBolt.java
It's for avoiding design constraint being introduced from STORM-513.
ShellSpout is already applied.
> STORM-742 Let ShellBolt treat all messages to update heartbeat

- external/storm-hdfs/README.md
- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/HdfsState.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/rotation/FileRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/rotation/FileSizeRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/rotation/NoRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/rotation/TimedRotationPolicy.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/trident/HdfsStateTest.java
Changes to support exactly once semantics in HdfsState.
1. Moved the file rotation and sync to commit()
2. In pre-commit, if we have previously seen the txnid, recover the data up to that point by copying to a new file and discard the current data file.
3. In pre-commit atomically update [current txid, the datafile path and the current offset] in a (per partition) index file.
4. To keep it simple, automatically turn off exactly once semantics if TimedRotation policy is in use.
Have tested with the normal flow and simulating the recovery scenario, with both regular Hdfs file and sequence files. Appears to work fine.
> [STORM-837] Support for exactly once semantics in HdfsState

- storm-core/src/jvm/backtype/storm/security/auth/SaslTransportPlugin.java
- storm-core/src/jvm/backtype/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java
- storm-core/src/jvm/backtype/storm/security/auth/kerberos/NoOpTTrasport.java
The reason for this pull request is that when a non-secure client tries to connect to nimbus host in a secure cluster, an exception was being thrown and a null transport object was being returned. This null object in turn was being used by thrift library class and threw a null pointer exception. Both the classes where exception was thrown and caught were logging this exception, creating unnecessary lengthy log statements. Disabling logging in storm code by changing it from error to debug took care of one part but to work around the issue of exception being logged in the thrift jar a NoOpTTrasport.java had to be created. Two main things to consider during review
1. Change from Logger.error to Logger.debug in KerberosSaslTransportPlugin.java
2. Early return false in SaslTransportPlugin.java …
> STORM-965: Fix excessive logging

- examples/storm-starter/pom.xml
- examples/storm-starter/src/jvm/storm/starter/trident/TridentKafkaWordCount.java
- pom.xml
A sample word count trident topology to illustrate the use of Transactional Kafka spout and Kafka bolt. This has the following components
1. KafkaBolt that receives random sentences from RandomSentenceSpout and publishes the sentences to a kafka "test" topic.
2. TransactionalTridentKafkaSpout that consumes sentences from the "test" topic, splits it into words, aggregates and stores the word count in a MemoryMapState.
3. DRPC query that returns the word counts by querying the trident state (MemoryMapState).
> [STORM-975] Storm-Kafka trident topology example

- storm-core/src/clj/backtype/storm/ui/core.clj
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/src/ui/public/topology.html
Current on the topology summary UI page and tells you the last error and highlights it red if it happened within the last 30 min.  However, I think its useful if there was a column that told you the time that has elapsed since the most recent error occurred.  I found this useful for monitoring the well being of my storm cluster.
> [STORM-949] On the topology summary UI page, added Elapsed time since error column.

- storm-core/src/jvm/backtype/storm/utils/RotatingMap.java
- storm-core/src/jvm/backtype/storm/utils/TimeCacheMap.java
This should allow current users of the TimeCacheMap to progressively migrate off the deprecated TimeCacheMap to the simpler RotatingMap.
This also improves code reuse since many of the methods were shared.
> [STORM-990] Refactored TimeCacheMap to extend RotatingMap.

- storm-core/src/clj/backtype/storm/timer.clj
Issue description: The timer thread calculates the delay to schedule the head of the queue and sleeps accordingly. However, if a new event with high priority is inserted at the head of the queue during the sleep, this event cannot be scheduled in time. 
Solution: Give a upper bound to the sleeping time, to guarantee a bounded response time for detecting new events.
> [STORM-992] Fixed a bug in the timer.clj that might cause unexpected delay to schedule new event

- storm-core/src/jvm/backtype/storm/utils/Utils.java
This pull request to fix STORM-994 to avoid resource leaks between nimbus and supervisors.
Could you please review ?
Thanks
> STORM-994 Close download clients and channels to avoid resource leaks

- storm-core/src/jvm/storm/trident/spout/ITridentSpout.java
- storm-core/src/jvm/storm/trident/spout/OpaquePartitionedTridentSpoutExecutor.java
- storm-core/src/jvm/storm/trident/spout/PartitionedTridentSpoutExecutor.java
- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchExecutor.java
- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchTriggerer.java
- storm-core/src/jvm/storm/trident/spout/TridentSpoutCoordinator.java
- storm-core/src/jvm/storm/trident/spout/TridentSpoutExecutor.java
- storm-core/src/jvm/storm/trident/topology/TridentBoltExecutor.java
Generally added generics to classes within the storm.trident.spout package. This generally removes some of the casts that were in place, and simplifies the code slightly. 
A typical example of what was done is 
ITridentSpout _spout;
was converted to:
ITridentSpout<Object> _spout;
> [STORM-991] General cleanup of the generics.

- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
I created an inner class QueueMetrics for DisruptorQueue. The QueueMetrics class handles metric collection logics and exposes metric retrieval methods.
The benefits of such modification are twofold: 
1. It improves the readability of the metric code.
2. It facilitates to add more metrics, such as average throughput and element sojourn time.  (That is because the data  maintained for such "stateful" metrics can reside in QueueMetrics rather than in DisruptorQueue. )
> [STORM-1008] Isolate the code for metric collection and retrieval from DisruptorQueue

- external/storm-hive/pom.xml
For future maintaining 0.10.x-branch.
> STORM-944: storm-hive pom.xml has a dependency conflict with calcite (backport to 0.10.x)

- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
Netty calls notifyInterestChanged which causes a race condition in flushMessages.
> STORM-996: netty-unit-tests/test-batch demonstrates out-of-order delivery

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
The log4j variable `${sys:storm.log.dir}` is used in `worker.xml` to set the fileName however the system property was not being set while launching worker (via LogWriter) causing a directory by the name ${sys:storm.log.dir} to be created under `STORM_HOME` dir.
This fix is to pass the system property while launching LogWriter
> [STORM-1024] Pass -Dstorm.log.dir arg to LogWriter

- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/src/jvm/backtype/storm/utils/RateTracker.java
- storm-core/test/jvm/backtype/storm/utils/RateTrackerTest.java
I added two important metrics, namely *arrival time* and *sojourn time*, to QueueMetrics. 
Modification Summary:
1. Created a new RateTracker utility, which could report instantaneous rate upon certain event;
2. Added test cases for RateTracker;
3. Added arrival rate and sojourn time metrics to QueueMetrics; 
4. Use sampling in QueueMetrics to reduce the metric maintenance cost. 
Such metrics are very useful to performance tuning, especially for application with strong constraint on processing latency such as threat detection and smart traffic. A high sojourn time, for example, indicates that a higher degree of parallelism should be applied to the current bolt in order to reduce processing delay. 
Any comment or suggestion regarding to this pull request is welcomed. 
Thanks.
> [STORM-1007] Added tuple arrival rate and tuple sojourn time to QueueMetrics

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
nimbus maybe reschedule topology to this supervisor later, so supervisor need not to re-download code.
Signed-off-by: Xinze Chi <xmdxcxz@gmail.com>
> [STORM-1037] do not remove storm-code in supervisor until kill job

- conf/defaults.yaml
- storm-core/src/clj/backtype/storm/cluster.clj
- storm-core/src/clj/backtype/storm/daemon/builtin_metrics.clj
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/disruptor.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/utils/DisruptorBackpressureCallback.java
- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/src/jvm/backtype/storm/utils/WorkerBackpressureCallback.java
- storm-core/src/jvm/backtype/storm/utils/WorkerBackpressureThread.java
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueBackpressureTest.java
This new feature is aimed for automatic flow control through the topology DAG since different components may have unmatched tuple processing speed. Currently, the tuples may get dropped if the downstream components can not process as quickly, thereby causing a waste of network bandwidth and processing capability. In addition, it is difficult to tune the max.spout.pending parameter for best backpressure performance. Therefore, an automatic back pressure scheme is highly desirable.
Recently, Heron proposed a form of back pressure that does not rely on acking or max spout pending. Instead spouts throttle not only when max.spout.pending is hit, but also if any bolt has gone over a high water mark in their input queue, and has not yet gone below a low water mark again. There is a lot of room …
> [STORM-886] Automatic Back Pressure (ABP)

- docs/documentation/Tutorial.md
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/trident/TridentEsTopology.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/trident/OpaqueTridentEventHubSpout.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/trident/TransactionalTridentEventHubSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/trident/FixedBatchSpout.java
- external/storm-hive/src/test/java/org/apache/storm/hive/trident/TridentHiveTopology.java
- storm-core/src/jvm/backtype/storm/coordination/BatchSubtopologyBuilder.java
- storm-core/src/jvm/backtype/storm/drpc/LinearDRPCTopologyBuilder.java
- storm-core/src/jvm/backtype/storm/topology/BaseConfigurationDeclarer.java
- storm-core/src/jvm/backtype/storm/topology/ComponentConfigurationDeclarer.java
- storm-core/src/jvm/backtype/storm/topology/TopologyBuilder.java
- storm-core/src/jvm/backtype/storm/transactional/TransactionalTopologyBuilder.java
- storm-core/src/jvm/storm/trident/spout/BatchSpoutExecutor.java
- storm-core/src/jvm/storm/trident/spout/IBatchSpout.java
- storm-core/src/jvm/storm/trident/spout/IOpaquePartitionedTridentSpout.java
- storm-core/src/jvm/storm/trident/spout/IPartitionedTridentSpout.java
- storm-core/src/jvm/storm/trident/spout/ITridentSpout.java
- storm-core/src/jvm/storm/trident/spout/RichSpoutBatchExecutor.java
- storm-core/src/jvm/storm/trident/testing/FeederBatchSpout.java
- storm-core/src/jvm/storm/trident/testing/FeederCommitterBatchSpout.java
- storm-core/src/jvm/storm/trident/testing/FixedBatchSpout.java
- storm-core/src/jvm/storm/trident/topology/TridentTopologyBuilder.java
The getComponentConfiguration methods currently return a simple Map object. In fact they should be returning a Map<String, Object>. 
By changing this, it will make it slightly clear what is being returned by the method and potentially pick up some issues at compile time.
> [STORM-1032] Add generics to component configuration methods

- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
When a topology is submitted repeatedly very closely, or nimbus is too busy to response the  repeated submit RPC calls from same topology, there is very high probability that nimbus receive the repeatedly calls of the same topology, and finally several topologies with same name will be running on storm cluster.
> STORM-1050:Topologies with same name run on one cluster

- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
STORM-763 introduced a situation in which flushMessages could receive batch = null, in which case, an NPE is thrown because we weren't validating != null
> [STORM-1051] Fix for flushMessagse NPE

- bin/storm.py
For the storm-on-mesos project there are multiple Storm Supervisors on
every worker host.  Each of these Supervisors is dedicated to a
particular topology.  A challenge with this design is that the shared
supervisor log file contains logs from every single topology that
has run on a particular host.  We instead want the option to have
separate supervisor log files for each topology, so that topology owners
can more easily debug their own problems.
This change allows having configurable log files for every launch of
the Supervisor, since we will be able to embed the topology ID into the
supervisor log filename.
Notably, storm-0.10 already includes a similar change for the worker
log filenames (came in with Yahoo!'s multi-tenant changes).
> configurable supervisor log filename

- external/sql/README.md
- external/sql/pom.xml
- external/sql/storm-sql-core/pom.xml
- external/sql/storm-sql-core/src/codegen/config.fmpp
- external/sql/storm-sql-core/src/codegen/data/Parser.tdd
- external/sql/storm-sql-core/src/codegen/includes/license.ftl
- external/sql/storm-sql-core/src/codegen/includes/parserImpls.ftl
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/ColumnConstraint.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/ColumnDefinition.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/SqlCreateTable.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/StormParser.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/UnparseUtil.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/parser/TestSqlParser.java
- pom.xml
This PR supersedes https://github.com/apache/storm/pull/731.
Based on the discussion in STORM-1040, this PR takes the approach to extend the Calcite SQL parser to parse the CREATE TABLE statement. On a very high level it does the following:
* Extract the template of Parser.jj from the calcite jar
* Instantiate the template with the code in src/codegen
* Invoke javacc to generate the parser
The approach is similar to the one in Apache Drill.
> STORM-1045. Parse CREATE TABLE statements.

- external/storm-kafka/src/test/storm/kafka/KafkaUtilsTest.java
configure request.required.acks to be 1 in KafkaUtilsTest to make sure that the send() function gets synchronized to the broker for avoiding potential offset-out-of-range error.
> [STORM-1068], configure request.required.acks in KafkaUtilsTest

- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/HdfsBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java
A few notes about this PR:
- I updated the storm-hdfs pom.xml to align with other external modules.  Most significant change was probably going from hdfs version 2.2 to ${hadoop.version} (i.e. currently 2.6)
- Many errors are recovered by forcing a file rotation which opens a new, valid File.  So the rotation now occurs either according to rotation policy or when a serious error happens.  Work could probably be done to reopen the same file name to reduce the number of rotations.
- Added unittests with MiniDFSCluster
> STORM-969: HDFS Bolt can end up in an unrecoverable state

- pom.xml
- storm-core/src/clj/backtype/storm/util.clj
All tests passed for me, and ran sample topologies without trouble.
> STORM-1059: Upgrade Storm to use Clojure 1.7.0

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/CalcitePlanSerializer.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprSerializer.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/PostOrderRelNodeVisitor.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/TypeSerializer.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCalcitePlanSerializer.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestUtils.java
This PR provides an implementation to serialize the results of Calcite to JSON strings. The JSON strings will be passed down to the optimizers and code generators to generate the Storm bolts or Trident functions.
> STORM-1060. Serialize Calcite plans into JSON format.

- bin/storm.py
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/jvm/backtype/storm/Config.java
An easier fix might be dropping the default configuration of "log4j" and force users to provide complete path, however, we still prefer to support relative path of log4j conf dir.
> [STORM-1063] support relative log4j conf dir for both daemons and workers

- bin/storm.py
- storm-core/src/clj/backtype/storm/command/kill_workers.clj
- storm-core/src/clj/backtype/storm/daemon/executor.clj
Kill all the workers running on this supervisor. 
Currently there is no direct way to kill all the running workers on a supervisor node from a command line. In addition, if the supervisor dies, the workers will not suicide automatically. 
Also, this CLI can be called by future node health-check script to cleanly shutdown a supervisor on an problematic node.
> [STORM-1058] create CLI kill_workers to kill workers on a supervisor node

- external/storm-kafka/README.md
correct readme file: new producer link & configs
> [STORM-1053] Correct storm-kafka readme file because of using new kafka-clients api

- storm-core/src/clj/backtype/storm/config.clj
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/clj/backtype/storm/util.clj
Currently, when supervisor launches a worker, the current directory of the worker process is not specified. In that case, the worker will be launched with a current directory as ".", which is a random directory. It can cause problems especially when the worker needs to dump something to its current directory.
To fix this, we should enable ProcessBuilder to specify worker's current directory as worker-root/worker-uuid.
Secondly, this pull request fixes one bug in absolute-storm-local-dir function. If STORM-LOCAL is configured as nil or not configured, "(is-absolute-path? path)" can cause NPE.
> [STORM-1066] add current directory for worker process launcher and fix absolute-storm-local-dir bug

- external/storm-kafka/src/test/storm/kafka/KafkaUtilsTest.java
- external/storm-kafka/src/test/storm/kafka/bolt/KafkaBoltTest.java
rename "request.required.acks" to "acks", delete the obsoleted "serializer.class"
> STORM-1082 fix nits for properties in kafka tests

- .travis.yml
- external/sql/storm-sql-core/src/native/CMakeLists.txt
- external/sql/storm-sql-core/src/native/cmake/FindLLVM.cmake
- external/sql/storm-sql-core/src/native/lib/compiler/CMakeLists.txt
- external/sql/storm-sql-core/src/native/lib/compiler/expr_compiler.cc
- external/sql/storm-sql-core/src/native/lib/compiler/expr_compiler.h
- external/sql/storm-sql-core/src/native/lib/compiler/expr_visitor.cc
- external/sql/storm-sql-core/src/native/lib/compiler/expr_visitor.h
- external/sql/storm-sql-core/src/native/lib/compiler/typesystem.cc
- external/sql/storm-sql-core/src/native/lib/compiler/typesystem.h
- external/sql/storm-sql-core/src/native/test/CMakeLists.txt
- external/sql/storm-sql-core/src/native/test/compiler/CMakeLists.txt
- external/sql/storm-sql-core/src/native/test/compiler/expr_compiler_test.cc
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCalcitePlanSerializer.java
This PR establishes the basic structure of the expression compiler. It compiles SQL literals to LLVM constants. It provides the building block to compile arithmetic expressions, etc..
> STORM-1080. Compiler SQL literals to LLVM constants

- external/storm-kafka/src/jvm/storm/kafka/PartitionManager.java
also removes some tab-indenting in the surrounding code.  
When a custom scheme returns an empty list of object-lists to the partition manager, it should be handled the same as null.  Otherwise, the partition reader will be stuck at that offset.
> advance kafka offset when deserializer yields no object

- storm-core/src/jvm/backtype/storm/nimbus/NimbusInfo.java
Nimbus HA's `NimbusInfo` class relies on each nimbus's hostname for network reachability. This is a show-stopper in situations that utilize Config.STORM_LOCAL_HOSTNAME / `storm.local.hostname`.
> [STORM-1090] Nimbus HA should support `storm.local.hostname`

- examples/storm-starter/pom.xml
- examples/storm-starter/test/jvm/storm/starter/bolt/IntermediateRankingsBoltTest.java
- examples/storm-starter/test/jvm/storm/starter/bolt/RollingCountBoltTest.java
- examples/storm-starter/test/jvm/storm/starter/bolt/TotalRankingsBoltTest.java
- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java
- external/storm-hive/pom.xml
- external/storm-hive/src/test/java/org/apache/storm/hive/bolt/TestHiveBolt.java
- storm-core/pom.xml
- storm-core/test/jvm/backtype/storm/utils/MockTupleHelpers.java
As I mentioned in the JIRA, I relocated MockTupleHelpers from storm-starter to the test module of storm-core.  This required some pom changes in storm-core and the modules that use the MockTupleHelpers class.
> STORM-1091: Add tick tuple unit tests for hdfs and hive bolts

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/test/clj/backtype/storm/supervisor_test.clj
This fixes the bug by changing supervisor.clj to operate on any sequential, not just a list.  
A unit test was added to verify that this works.  I ran the unit test without the supervisor change, and it did fail.
> [STORM-1099]  Fix worker childopts as arraylist of strings

- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
Nimbus HA using Local File System code distribution is broken. We seem to be "caching" the return value of `(code-ids (:conf nimbus))` in the sync-code method, by overriding the `code-ids` var from a method ([nimbus.clj#854](../blob/master/storm-core/src/clj/backtype/storm/daemon/nimbus.clj#L854) `defn code-ids`), to a local var ([nimbus.clj#1669](../blob/master/storm-core/src/clj/backtype/storm/daemon/nimbus.clj#L1669) `code-ids (set (code-ids (:conf nimbus)))`).
The problem is, that after downloading code for missing topologies, sync-code doesn't realize it has gotten the new missing topology files.
> [STORM-1104] Nimbus HA fails to find newly downloaded code files

- storm-core/src/clj/backtype/storm/daemon/common.clj
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/stats.clj
- storm-core/src/clj/backtype/storm/ui/core.clj
- Remove redundant method `system-id?` - as is calls into static `Utils/isSystemId`
- All System components are of type bolts.
> [STORM-1110] Fix Component Page for system components

- pom.xml
From the issue:
```
I believe this curator bug is what's in play causing the above described situation.
https://issues.apache.org/jira/browse/CURATOR-202
```
> [STORM-1115] Stale leader-lock key effectively bans all nodes from becoming leaders

- conf/defaults.yaml
- storm-core/src/clj/backtype/storm/config.clj
- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
- storm-core/src/clj/backtype/storm/testing.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/test/clj/backtype/storm/integration_test.clj
- storm-core/test/clj/backtype/storm/multilang_test.clj
- storm-core/test/clj/backtype/storm/nimbus_test.clj
- storm-core/test/clj/backtype/storm/supervisor_test.clj
- storm-core/test/clj/backtype/storm/testing4j_test.clj
- storm-core/test/clj/backtype/storm/transactional_test.clj
Nimbus calls mk-assignments from SubmitTopology within lock is causing it to wait for processing of all heartbeats. This conflicts with recurring mk-assignments call. Topology can be submitted without making assignments, since for new topology the assignments would be made available as part of next scheduling cycle.). This gives more consistent response time as avoid locking within nimbus.
> [STORM-1121] Remove method call to avoid overhead during topology submission time

- examples/storm-starter/src/jvm/storm/starter/ThroughputVsLatency.java
- storm-core/src/clj/backtype/storm/daemon/builtin_metrics.clj
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/task.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/stats.clj
- storm-core/src/jvm/backtype/storm/metric/internal/CountStatAndMetric.java
- storm-core/src/jvm/backtype/storm/metric/internal/LatencyStatAndMetric.java
- storm-core/src/jvm/backtype/storm/metric/internal/MetricStatTimer.java
- storm-core/src/jvm/backtype/storm/metric/internal/MultiCountStatAndMetric.java
- storm-core/src/jvm/backtype/storm/metric/internal/MultiLatencyStatAndMetric.java
- storm-core/src/jvm/backtype/storm/metric/internal/RateTracker.java
- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/src/jvm/backtype/storm/validation/ConfigValidation.java
- storm-core/test/jvm/backtype/storm/metric/internal/CountStatAndMetricTest.java
- storm-core/test/jvm/backtype/storm/metric/internal/LatencyStatAndMetricTest.java
- storm-core/test/jvm/backtype/storm/metric/internal/RateTrackerTest.java
The metrics in my profiling are contributing significantly to the CPU utilization of storm, which slows it down.  With this patch I was able to go from 6,500 sentences/second fully counted to 11,000 on a Mac Book Pro running two workers in the Throughput vs. Latency test.  If I turn off sub-sampling of metrics the performance goes back to about where it was before.  There is still more optimizations that could be done with the metrics, like having the latency metric also report counts, so we don't have to do an extra lookup and inc operation on the critical path, but for now this is good enough, and allows me to start looking at the next bottleneck.
These changes also compliment the batching changes very well.  The batching went from 6,500 sentences/second to 15,000 by itself.  This patch …
> STORM-1128: Make metrics fast

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/HdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/SequenceFileBolt.java
STORM-969 changed the execution of HdfsBolt to be more robust to errors.  This change moves that logic up to AbstractHdfsBolt and adds two new abstract methods to AbstractHdfsBolt: writeTuple and syncTuples.  In other words AbstractHdfsBolt contains all of the error handling and retry logic for writing to HDFS, and its implementing classes will specify how to write specific content to HDFS.
> STORM-1073: Refactor AbstractHdfsBolt

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBoltTest.java
This creates a new concrete subtype of AbstractHdfsBolt that can write avro Generic Records directly to HDFS.
> STORM-1074: Add Avro HDFS bolt

- conf/defaults.yaml
- examples/storm-starter/src/jvm/storm/starter/FastWordCountTopology.java
- examples/storm-starter/src/jvm/storm/starter/InOrderDeliveryTest.java
- pom.xml
- storm-core/pom.xml
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/disruptor.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/src/jvm/backtype/storm/utils/MutableObject.java
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueBackpressureTest.java
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueTest.java
This replaces #750 because I rebased.
@HeartSaVioR I think I found the bug that you saw.  @kishorvpatil was doing scale testing and found an NPE issue.  There was a race condition when a read was timing out and I badly tried to read after the timeout instead of just returning.
> STORM-350: Upgrade to newer version of disruptor

- storm-core/src/jvm/backtype/storm/Config.java
Some configs that is declared as @isPositiveNumber should be @isPositiveNumber(includeZero=true) based on the comments
> fixing some config validation annotations

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestExprCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestPlanCompiler.java
This PR implements the AND, OR and NOT operators in StormSQL. Both AND and OR operator supports the short-circuit semantics.
> STORM-1130. Support AND, OR, NOT operators in StormSQL.

- conf/defaults.yaml
- log4j2/worker.xml
- storm-core/src/clj/backtype/storm/config.clj
- storm-core/src/clj/backtype/storm/daemon/logviewer.clj
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/clj/backtype/storm/ui/core.clj
- storm-core/src/clj/backtype/storm/ui/helpers.clj
- storm-core/src/clj/backtype/storm/util.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/metric/FileBasedEventLogger.java
- storm-core/src/jvm/backtype/storm/utils/Utils.java
- storm-core/test/clj/backtype/storm/logviewer_test.clj
- storm-core/test/clj/backtype/storm/supervisor_test.clj
Originally all logs (both for workers and daemons) are under storm-home/logs, this causes name confusion ("wc22-1-1445957152-worker-6700.log") and difficulty for debugging (hard to store and manage heapdump and gc log files for all topologies' workers in a single directory). 
For better management, we present the Worker Artifacts Directory for Hierarchical Log Management and Debugging: 
1. workers' logs and metadata are moved to the new directory "storm-local/workers-artifacts", while daemon logs are still placed in storm-home/logs. Note that each topology has a separate directory, holding one sub-directory for each worker within this topology.
2. Cleanup, view and list implementations are modified accordingly in logviewer and UI. Specifically, we add per-worker quota and total quota for …
> [STORM-901] Worker Artifacts Directory for Hierarchical Log Management and Debugging

- conf/defaults.yaml
- examples/storm-starter/src/jvm/storm/starter/FastWordCountTopology.java
- examples/storm-starter/src/jvm/storm/starter/InOrderDeliveryTest.java
- pom.xml
- storm-core/pom.xml
- storm-core/src/clj/backtype/storm/cluster.clj
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/task.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/disruptor.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/src/jvm/backtype/storm/utils/MutableObject.java
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueBackpressureTest.java
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueTest.java
I wanted to come up with an alternative to #694 that does batching at the queue level instead of at that spout level.  This is the result of that work, although it still needs some testing/cleanup before I consider it fully ready. This is based off of #750 using the latest version of disruptor, and has a few bug fixes for automatic back-pressure that I need to split out and include as a separate pull request.
The work here is driven by results I got from some micro benchmarks I wrote looking at what the bottlenecks are in storm and what the theoretical limit is for storm.  In this case doing a simple word count topology as represented by Q_SWC_X_04.  With the same batching here the throughput when from 300,000 sentences/second processed to around 1.5 million, as run on my Mac Book Pro …
> STORM-1151: Batching in DisruptorQueue

- conf/defaults.yaml
Since STORM-901 worker artifacts directory just gets merged in, it provides a private place for us to turn on the garbage collection and heapdump for each worker by default. 
Since user can easily view and download gc log and heapdump file from logviewer UI, this will greatly improve the debugging of storm. 
Welcome discussion on the setting details (default gc rollover size, number of files, whether we want pid in the gc log file name, etc.),
> [STORM-40] Turn worker garbage collection and heapdump on by default

- storm-core/src/native/worker-launcher/impl/worker-launcher.c
Created [STORM-1169](https://issues.apache.org/jira/browse/STORM-1169) for the TODO comment that was removed.
> [STORM-1168] removes noisy log message & a TODO

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
In supervisor/try-cleaup-worker
> [STORM-1163] use rmr rather than rmpath for remove worker-root

- conf/defaults.yaml
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/task.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/messaging/local.clj
- storm-core/src/clj/backtype/storm/timer.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/grouping/Load.java
- storm-core/src/jvm/backtype/storm/grouping/LoadAwareCustomStreamGrouping.java
- storm-core/src/jvm/backtype/storm/grouping/LoadAwareShuffleGrouping.java
- storm-core/src/jvm/backtype/storm/grouping/LoadMapping.java
- storm-core/src/jvm/backtype/storm/grouping/ShuffleGrouping.java
- storm-core/src/jvm/backtype/storm/messaging/IConnection.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
- storm-core/src/jvm/backtype/storm/messaging/netty/ISaslClient.java
- storm-core/src/jvm/backtype/storm/messaging/netty/ISaslServer.java
- storm-core/src/jvm/backtype/storm/messaging/netty/IServer.java
- storm-core/src/jvm/backtype/storm/messaging/netty/SaslStormClientHandler.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Server.java
- storm-core/src/jvm/backtype/storm/messaging/netty/StormClientHandler.java
- storm-core/src/jvm/backtype/storm/messaging/netty/StormClientPipelineFactory.java
- storm-core/test/clj/backtype/storm/grouping_test.clj
- storm-core/test/clj/backtype/storm/integration_test.clj
- storm-core/test/clj/backtype/storm/messaging/netty_integration_test.clj
- storm-core/test/clj/backtype/storm/messaging/netty_unit_test.clj
- storm-core/test/clj/backtype/storm/messaging_test.clj
I am recreating this pull request. Originally there was discussion about using the velocity of a bolt in addition to the queue size in determining the routing, but I didn't have time to implement that, and we have been running with this code in production for quite a while, so I decided to just put it up, as it has a really positive impact.  This is most pronounced on heterogeneous clusters where not all nodes have the same CPU.  But also this improves the performance of the groupings implementations significantly dropping the 99th and 99.9th %-lie latencies significantly for the Latency vs Throughput test case.
I would still like to explore using velocity and network distance in the routing calculations, but in a follow on JIRA.
> STORM-162: Load Aware Shuffle Grouping

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestExprCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestExprSemantic.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestRelNodeCompiler.java
This PR implements the support of the nullable semantics of the expressions available in StormSQL. 
It also implements the `IS_NULL`, `IS_NOT_NULL` operators.
Currently the `ExprCompiler` directly prints out Java source code with `printf`. A cleaner approach is to introduce the `Expression` class in the Apache Calcite project to avoid the printf statements. It'll be cleaned up in follow-up PRs.
> STORM-1159. Support nullable operations in StormSQL

- DEVELOPER.md
The Storm codebase was semantically indexed in Codota - available at
https://www.codota.com/xref/#/github_apache_storm_560da9ada8cb8703008bbfdc/findUsages
I believe it will be useful for developers who want to learn and explore the code.
> Add codota search for apache/storm to Readme

- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
- storm-core/src/clj/backtype/storm/messaging/loader.clj
- storm-core/src/clj/backtype/storm/messaging/local.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/messaging/AddressedTuple.java
- storm-core/src/jvm/backtype/storm/messaging/DeserializingConnectionCallback.java
- storm-core/src/jvm/backtype/storm/messaging/IConnection.java
- storm-core/src/jvm/backtype/storm/messaging/IConnectionCallback.java
- storm-core/src/jvm/backtype/storm/messaging/local/Context.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
- storm-core/src/jvm/backtype/storm/messaging/netty/Server.java
- storm-core/src/jvm/backtype/storm/tuple/AddressedTuple.java
- storm-core/test/clj/backtype/storm/messaging/netty_unit_test.clj
- storm-core/test/clj/backtype/storm/messaging_test.clj
This pull request is based off of #765 because it moved the overflow buffer into the disruptor queue itself, and we don't want the netty thread to block when doing routing.
This does not improve the maximum throughput much, but because it removes an extra thread and an extra queue that a tuple must go through when being sent to another worker the 99%-ile, 99.9%-ile and worst case latency goes down some.
>  STORM-1145: Have IConnection push tuples instead of pull them.

- storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java
- storm-core/test/clj/backtype/storm/metrics_test.clj
- storm-core/test/jvm/backtype/storm/utils/DisruptorQueueTest.java
This helps a fair amount at the low end, but not as much as I had hoped.  The spout seems to sleeping more with batching enabled which is offsetting some of the gains from updating the DisruptorQueue code.  I really have not idea why at this point.
> STORM-1190: System Load too high after recent changes

- storm-core/src/clj/backtype/storm/stats.clj
- storm-core/src/jvm/backtype/storm/metric/internal/LatencyStatAndMetric.java
- storm-core/src/jvm/backtype/storm/utils/Utils.java
* Removes malformed preconditions that don't do anything, and if they did work would throw Errors that would crash nimbus.
* When reading and writing average-type metrics, use `0` instead of `NaN`
* Avoid NPE accessing some maps by doing `(get m k)` instead of `(m k)`.
> [STORM-1208] Guard against NPE, and avoid using NaN values

- docs/documentation/Windowing.md
- examples/storm-starter/src/jvm/storm/starter/SlidingWindowTopology.java
- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/task/OutputCollector.java
- storm-core/src/jvm/backtype/storm/topology/IWindowedBolt.java
- storm-core/src/jvm/backtype/storm/topology/TopologyBuilder.java
- storm-core/src/jvm/backtype/storm/topology/WindowedBoltExecutor.java
- storm-core/src/jvm/backtype/storm/topology/base/BaseWindowedBolt.java
- storm-core/src/jvm/backtype/storm/windowing/CountEvictionPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/CountTriggerPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/Event.java
- storm-core/src/jvm/backtype/storm/windowing/EventImpl.java
- storm-core/src/jvm/backtype/storm/windowing/EvictionPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/TimeEvictionPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/TimeTriggerPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/TriggerHandler.java
- storm-core/src/jvm/backtype/storm/windowing/TriggerPolicy.java
- storm-core/src/jvm/backtype/storm/windowing/TupleWindow.java
- storm-core/src/jvm/backtype/storm/windowing/TupleWindowImpl.java
- storm-core/src/jvm/backtype/storm/windowing/Window.java
- storm-core/src/jvm/backtype/storm/windowing/WindowLifecycleListener.java
- storm-core/src/jvm/backtype/storm/windowing/WindowManager.java
- storm-core/test/jvm/backtype/storm/windowing/WindowManagerTest.java
Currently, topologies that needs windowing support requires writing custom logic inside bolts making it tedious to handle the windowing and acking logic with custom logic.
The PR proposes to add framework level support to core storm bolts to process tuples in a time or a count based window. Sliding and tumbling windows based on tuple count or time duration are supported.
A new bolt interface is added for bolts that needs windowing support.
```
public interface IWindowedBolt extends IComponent {
void prepare(Map stormConf, TopologyContext context, OutputCollector collector);
/**
* Process tuples falling within the window and optionally emit 
* new tuples based on the tuples in the input window.
*/
void execute(TupleWindow inputWindow);
void cleanup();
}
```
`TupleWindow` gives access to …
> STORM-1167: Add windowing support for storm core

- storm-core/src/jvm/storm/trident/TridentTopology.java
- storm-core/src/jvm/storm/trident/spout/IOpaquePartitionedTridentSpout.java
- storm-core/src/jvm/storm/trident/spout/IPartitionedTridentSpout.java
- storm-core/src/jvm/storm/trident/spout/ITridentDataSource.java
- storm-core/src/jvm/storm/trident/spout/ITridentSpout.java
This PR marks the trident spouts with a common interface. Such a common interface allows StormSQL to manage external data sources with a unified interface.
> STORM-1221. Create a common interface for all Trident spout.

- external/flux/flux-core/src/main/java/org/apache/storm/flux/model/ObjectDef.java
update:let constructorArgs support map type.
> Update ObjectDef.java for flux

- external/sql/pom.xml
- external/sql/storm-sql-kafka/pom.xml
- external/sql/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/JsonScheme.java
- external/sql/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/JsonSerializer.java
- external/sql/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/KafkaDataSourcesProvider.java
- external/sql/storm-sql-kafka/src/resources/META-INF/services/org.apache.storm.sql.runtime.DataSourcesProvider
- external/sql/storm-sql-kafka/src/test/org/apache/storm/sql/kafka/TestJsonRepresentation.java
- external/sql/storm-sql-kafka/src/test/org/apache/storm/sql/kafka/TestKafkaDataSourcesProvider.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/IOutputSerializer.java
- pom.xml
This PR adds the support of Kafka as external tables in StormSQL.
> STORM-1222. Support Kafka as external tables in StormSQL

- external/sql/storm-sql-core/src/codegen/data/Parser.tdd
- external/sql/storm-sql-core/src/codegen/includes/parserImpls.ftl
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/CompilerUtil.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/PlanCompiler.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/ColumnConstraint.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/SqlDDLKeywords.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestExprSemantic.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/standalone/TestPlanCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/standalone/TestRelNodeCompiler.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/AbstractChannelHandler.java
This PR allows users to specify collations on primary keys so that the query engines can use this as a hint when processing streaming aggregations.
> STORM-1200. Support collations of primary keys.

- external/storm-kafka/src/jvm/storm/kafka/KafkaUtils.java
- external/storm-kafka/src/jvm/storm/kafka/KeyValueScheme.java
- external/storm-kafka/src/jvm/storm/kafka/KeyValueSchemeAsMultiScheme.java
- external/storm-kafka/src/jvm/storm/kafka/MessageMetadataScheme.java
- external/storm-kafka/src/jvm/storm/kafka/MessageMetadataSchemeAsMultiScheme.java
- external/storm-kafka/src/jvm/storm/kafka/StringKeyValueScheme.java
- external/storm-kafka/src/jvm/storm/kafka/StringMultiSchemeWithTopic.java
- external/storm-kafka/src/jvm/storm/kafka/StringScheme.java
- external/storm-kafka/src/test/storm/kafka/StringKeyValueSchemeTest.java
- external/storm-kafka/src/test/storm/kafka/TestStringScheme.java
- storm-core/src/jvm/backtype/storm/spout/MultiScheme.java
- storm-core/src/jvm/backtype/storm/spout/RawMultiScheme.java
- storm-core/src/jvm/backtype/storm/spout/RawScheme.java
- storm-core/src/jvm/backtype/storm/spout/Scheme.java
- storm-core/src/jvm/backtype/storm/spout/SchemeAsMultiScheme.java
Currently the Kafka spout performs an extra copy for all payloads in Kafka when integrating with Storm. This PR proposes to avoid the extra copy to improve performance.
> STORM-1220. Avoid double copying in the Kafka spout.

- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/spout/ShellSpout.java
- storm-core/src/jvm/backtype/storm/task/ShellBolt.java
* config name: topology.subprocess.timeout.secs
* if it's not specified, supervisor.worker.timeout.secs will be used
> STORM-1341 Let topology have own heartbeat timeout for multilang subprocess

- bin/storm
This is a minor change to the shell scripts in the bin directory that use bash which switches them to find bash via /usr/bin/env which should provide more cross platform compatibility. Specifically it will allow these scripts to work out of the box on the various BSDs with bash is installed in the default manner, in /usr/local/bin instead of /bin and should remain compatible with other OSes that typically put most things in /bin
> MINOR: Use /usr/bin/env to find bash

- conf/defaults.yaml
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/task/ShellBolt.java
- storm-core/src/jvm/backtype/storm/utils/ShellBoltMessageQueue.java
- storm-core/test/clj/backtype/storm/multilang_test.clj
- storm-core/test/jvm/backtype/storm/utils/ShellBoltMessageQueueTest.java
This is the implementation of https://github.com/apache/storm/pull/532#issuecomment-158578419
Please refer comment to see purpose of this PR.
Message's priority was heartbeat > taskids = BoltMsg, but in this PR, I changed priority to heartbeat > taskids > BoltMsg.
In order to accomplish this, taskids and BoltMsgs use their own queue. Queue for taskids is unbounded but queue for BoltMsgs is bounded (fixed size) so that executor thread can be blocked and ABP comes into play.
Please note that BoltWriterRunnable polls message from both queues when it is only available. It's for minimizing wait for taskids, but it can spin CPU so CPU usage will be a bit higher than current.
I'd like to discuss about better / safer approach, for example, adding potential lag via poll with timeout.
@revans2 It's …
> STORM-756 Handle taskids response as soon as possible

- storm-core/src/clj/org/apache/storm/pacemaker/pacemaker_state_factory.clj
When using the new Pacemaker (which, you kind of have to, cos the alternative of not using it is abusing ZK to the point of deadlocking it...), you cannot submit topologies because submitTopology is calling ClusterState's delete_node_blobstore which never got implemented in pacemaker_state_factory.clj.
This PR introduces a basic implementation of delete-node-blobstore for pacemaker's clusterstate that passes it up to the underlying zk-state.
> [STORM-1375] Blobstore broke Pacemaker

- storm-core/src/jvm/backtype/storm/blobstore/BlobStore.java
- storm-core/test/jvm/backtype/storm/localizer/LocalizerTest.java
This clears up one incidental issue shown on STORM-1378, the one test failure due solely to "/" vs "\" in the path comparison.  This does _not_ solve the larger issue on STORM-1378.
> STORM-1378:  Use File.separator for OS independence in Blobstore LocalizerTest

- storm-core/src/clj/backtype/storm/stats.clj
Might cause divide by zero exception
> [STORM-1385] stats.clj divide by zero exception

- conf/defaults.yaml
- storm-core/src/clj/backtype/storm/config.clj
- storm-core/src/clj/backtype/storm/util.clj
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/test/clj/backtype/storm/supervisor_test.clj
Now, by default, log structure looks like this:
storm-home/logs/
------supervisor.log
------nimbus.log
------logviewer.log
------workers-artifacts/
-----------topo1/
-----------topo2/
------------------port1/
------------------port2/
------------------------worker.log
------------------------worker.log.err
------------------------worker.log.out
------------------------gc.log
> [STORM-1387] workers-artifacts directory configurable, and default to be under storm.log.dir.

- DEVELOPER.md
- external/storm-elasticsearch/pom.xml
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/AbstractEsBoltIntegrationTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsIndexBoltTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsLookupBoltIntegrationTest.java
- external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsPercolateBoltTest.java
- pom.xml
- storm-core/pom.xml
- storm-core/src/jvm/backtype/storm/testing/IntegrationTest.java
- storm-core/test/clj/integration/backtype/storm/integration_test.clj
- storm-core/test/clj/integration/backtype/storm/testing4j_test.clj
- storm-core/test/clj/integration/storm/trident/integration_test.clj
- storm-multilang/javascript/pom.xml
- storm-multilang/python/pom.xml
- storm-multilang/ruby/pom.xml
This patch has 3 commits. 
-  POM changes implementing profiles to separate integration tests and unit tests
- Two separate commits that illustrate how to migrate existing tests currently running as unit tests  to run as integration tests
> STORM-1179: Create Maven Profiles for Integration Tests

- storm-core/test/clj/backtype/storm/security/auth/ThriftClient_test.clj
- storm-core/test/clj/backtype/storm/security/auth/auth_test.clj
- storm-core/test/clj/backtype/storm/security/auth/drpc_auth_test.clj
- storm-core/test/clj/backtype/storm/security/auth/nimbus_auth_test.clj
Thrift client timeouts had been given in seconds, when java.net.Socket expects them in milliseconds.
> [STORM-1377] Correct timeouts for milliseconds

- conf/defaults.yaml
- log4j2/worker.xml
- storm-core/src/jvm/backtype/storm/blobstore/BlobSynchronizer.java
- storm-core/src/jvm/backtype/storm/blobstore/KeySequenceNumber.java
- storm-core/src/jvm/backtype/storm/blobstore/LocalFsBlobStore.java
- storm-core/test/clj/backtype/storm/nimbus_test.clj
- storm-core/test/jvm/backtype/storm/localizer/LocalizerTest.java
Uneccessary creation of client and closing of connections puts load on zookeeper.
Having a single client connection to perform reads helps
> [STORM-1376] Performance slowdown due excessive zk connections and log-debugging

- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/jvm/backtype/storm/utils/NimbusClient.java
- storm-core/src/jvm/backtype/storm/utils/NimbusLeaderNotFoundException.java
* Adds a new exception to differentiate the failure to find a nimbus leader from a network failure.
* Since blobs are scanned for updates periodically, do not crash the supervisor if nimbus is not available.
* Do not crash the supervisor if nimbus is unavailable when downloading topology resources for launch.
> [STORM-1383] Avoid supervisor crashing if nimbus is unavailable

- storm-core/src/clj/backtype/storm/daemon/executor.clj
- storm-core/src/clj/backtype/storm/daemon/nimbus.clj
- storm-core/src/clj/backtype/storm/daemon/supervisor.clj
- storm-core/src/clj/backtype/storm/daemon/worker.clj
When Pacemaker was merged, some calls got missed in nimbus.clj, supervisor.clj, worker.clj and executor.clj.
This merge error prevents nimbus from spawning separate read/write zookeeper clients since the ClusterState ends up with daemonType == DaemonType.UNKNOWN.
> STORM-1397: Merge conflict from Pacemaker merge

- external/storm-hdfs/README.md
Changing the **example code** and use **AvroGenericRecordBolt**  instead of
**SequenceFileBolt**…
Section “Support for Avro Files” starts by explained the use of org.apache.storm.hdfs.bolt.AvroGenericRecordBolt for Avro files.
However, the example code uses SequenceFileBolt instead, and that
doesn’t work, obviously because the method withSchemaAsString isn’t
part of SequenceFileBolt, but part of
org.apache.storm.hdfs.bolt.AvroGenericRecordBolt instead. So, the
change is nothing but changing the name of class SequenceFileBolt and
replace it with the correct AvroGenericRecordBolt.
> AvroGenericRecordBolt instead of SequenceFileBolt

- examples/storm-starter/README.markdown
The tutorial code was broken giving an error. See http://stackoverflow.com/questions/34467446/apache-storm-classnotfoundexception-on-storm-starter. I did not alter example 2 because I have not verified that alteration.
> STORM-1422 Remove broken example from the tutorial

- examples/storm-starter/README.markdown
Apache Storm doesn't support JDK 6 from 0.10.0 and later.
> storm-starter: Guide JDK version to later than 7

- external/storm-hdfs/pom.xml
- pom.xml
- storm-core/pom.xml
hadoop-auth is needed for storm ui in a secured cluster for
authentication. Adding the dependency back since it was removed in one
of the commits.
> STORM-1160: Add hadoop-auth dependency needed for storm-core

- conf/defaults.yaml
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/utils/Utils.java
This introduces optional exhibitor configuration properties to storm config--the options parallel the zookeeper options where relevant:
storm.exhibitor.servers:
- "localhost"
storm.exhibitor.port: 8080
storm.exhibitor.poll.millis: 1000
storm.exhibitor.retry.times: 5
storm.exhibitor.retry.interval: 1000
storm.exhibitor.retry.intervalceiling.millis: 30000
If exhibitor.servers are not provided, the behavior of storm is identical to prior. If exhibitor.servers are provided then the curator connection uses exhibitor, using any configured zookeeper.servers for the curator-exhibitor backup connection string.
I've tested this locally, will be deploying this patch in coming weeks in my own production environment/s.
> STORM-702: Exhibitor support

- storm-core/src/clj/backtype/storm/daemon/executor.clj
This would help lower heap memory usage when ```topology.debug``` is off.
> [STORM-1457] Avoid collecting pending tuples if topology.debug is off

- storm-core/src/jvm/backtype/storm/spout/RawMultiScheme.java
STORM-1220 introduced some changes where in one place it passes ByteBuffer as is instead of byte[].
Existing bolts (0.10.0) expects a byte[] and fails with
"java.lang.RuntimeException: java.lang.ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B "
This patch addresses the issue by emiting byte[] instead of ByteBuffer.
> [STORM-1499] Fix Kafka spout to maintain backward compatibility

- external/storm-kafka/src/test/storm/kafka/ExponentialBackoffMsgRetryManagerTest.java
ExponentialBackoffMsgRetryManagerTest.testMaxBackoff() fails sometimes, I think due to too small times. It can miss the mark on slow machines.
> STORM-1432: Spurious failure in storm-kafka test

- external/storm-hdfs/pom.xml
This tells the maven-clean-plugin to remove the build directory when clean:clean is executed.
> [STORM-1408] clean up the build directory created by tests

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java
- external/storm-hive/src/main/java/org/apache/storm/hive/common/HiveOptions.java
HDFS and Hive bolts were setting the default tick tuple interval in the
prepare() method, which was not taking effect. Correctly set a default
and return from getComponentConfiguration if the user does not
explicitly set a value.
> STORM-1219: Fix HDFS and Hive bolt flush/acking

- storm-core/src/clj/backtype/storm/daemon/logviewer.clj
- storm-core/src/clj/backtype/storm/util.clj
- storm-core/src/jvm/backtype/storm/daemon/DirectoryCleaner.java
- storm-core/test/clj/backtype/storm/logviewer_test.clj
Using DirectoryStream to replace File.listFiles will save logviewer memory usage since it does not require loading all files' metadata into memory. This avoids potential memory usage problem in extreme case (e.g., you have millions of small files in your log directory).
Also, a multi-phase PQ-based sorting and cleaning scheme is introduced in DirectoryCleaner for replacing the global in-memory sorting.
> [STORM-1206] Reduce logviewer memory usage through directory stream

- bin/storm.py
- dev-tools/cleanup.sh
- dev-tools/move_package.sh
- dev-tools/travis/travis-install.sh
- pom.xml
- storm-core/src/jvm/backtype/storm/Config.java
- storm-core/src/jvm/backtype/storm/daemon/ClientJarTransformerRunner.java
- storm-core/src/jvm/backtype/storm/daemon/JarTransformer.java
- storm-core/src/jvm/backtype/storm/utils/Utils.java
- storm-dist/binary/pom.xml
- storm-rename-hack/pom.xml
- storm-rename-hack/src/main/java/org/apache/storm/hack/DefaultShader.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/IOUtil.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/ShadeRequest.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/StormShadeRequest.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/StormShadeTransformer.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/relocation/Relocator.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/relocation/SimpleRelocator.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/resource/ClojureTransformer.java
- storm-rename-hack/src/main/java/org/apache/storm/hack/resource/ResourceTransformer.java
This is not a typical pull request, because changing the packages is a huge task, and keeping it upmerged while this is reviewed and other patches goes in is a huge task, and error prone.
Instead the actual changes to the package/namespace is done by running
```./dev-tools/move_packages.sh ./```
you can wipe all of the changes clean again (Including any modifications on your branch that you have not checked in) by running
```./dev-tools/cleanup.sh ./```
once the changes are approved/committed these two scripts should be removed.
The other code is intended to provide a single executable that can shade a user jar so instead of using `backtype.storm` and `storm.trident` it uses `org.apache.storm` and `org.apache.storm.trident`.
These are off by default by can be enabled by adding
``` …
```
> STORM-1202: Migrate APIs to org.apache.storm, but try to provide some form of backwards compatability

- examples/storm-starter/pom.xml
- examples/storm-starter/src/jvm/storm/starter/HdfsSpoutTopology.java
- external/storm-hdfs/README.md
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/CmpFilesByModificationTime.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/HdfsUtils.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/ModifTimeComparator.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/AbstractFileReader.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/Configs.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/DirLock.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/FileLock.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/FileOffset.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/FileReader.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/ParseException.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/ProgressTracker.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/SequenceFileReader.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/TextFileReader.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestDirLock.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestFileLock.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSemantics.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestProgressTracker.java
- external/storm-hdfs/src/test/resources/log4j.properties
- pom.xml
HDFS Spout  for initial review (no Trident support).
**Features:**
- Monitors directory. Picks up new files as they show up.
- Built-in  support for consuming Text and Sequence File formats 
- Extensible to other file formats. 
- Works with or without ACKers.
- Concurrent consumption: Each spout instance consumes a different file in parallel. 
- Zookeeper free synchronization: HDFS based synchronization mechanism enables each spout to concurrently decide which of the available files to consume next. Spout acquires a lock on a file before consuming it. The lock files are stored in a .lock subdirectory. Lock file is deleted once file is consumed.
- Archiving: Completed files are moved to a (configurable) 'done' folder 
- Easy progress tracking: Files being consumed are renamed with a …
> STORM-1199 : HDFS Spout Functionally complete. Not well tested. Some UTs

- storm-core/pom.xml
I would also like to see this applied to 1.x-branch, since it is a blocker.
> [STORM-1470] Applies shading to hadoop-auth, cleaner exclusions

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java
- external/storm-solr/src/main/java/org/apache/storm/solr/bolt/SolrUpdateBolt.java
- storm-core/src/jvm/org/apache/storm/utils/TupleUtils.java
This PR follow https://github.com/apache/storm/pull/977#discussion_r49160913 @hmcl 's comment:
>I noticed that the body of this method is exactly the same for AbstractHdfsBolt. Furthermore, it's very likely that many Storm connector bolts will use the same code. Can you please write a helper method in TupleUtils and call that method here and AbstractHdfsBolt.
> [STORM-1478] make bolt's getComponentConfiguration method cleaner/simpler

- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/jvm/org/apache/storm/scheduler/Cluster.java
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/templates/component-page-template.html
1. Checking the code, find a bug in storm-core/src/clj/backtype/storm/ui/core.clj
"time" changed to "errorTime", however the REST info is still "time".
Error log link can not show any info for time.
2. In the error log link of UI, long of millisecond dates makes little sense to user. It would be nice to change it to be readable date.
> [STORM-1472] Fix the errorTime bug and show the time to be readable

- conf/defaults.yaml
- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/templates/component-page-template.html
- storm-dist/binary/src/main/assembly/binary.xml
Ships the flight.bash script
Disables UI display of Profiling and Debugging if on windows
Changes worker.profiler.enabled to control only profiling, not other debugging actions
Changes default of worker.profiler.enabled to false
Adds missing UI REST API data.
Populates user context on profiler UI routes
I would also like to see this applied to the master branch.
> [STORM-1452] Fixes profiling/debugging out of the box

- external/storm-kafka/README.md
Fix storm-kafka documentation to reflect changes from STORM-1220 and also
document the version incompatiblity of pre 1.x kafka-spout with storm 1.0 and later.
> [STORM-1486] Fix storm-kafa documentation

- storm-core/src/jvm/org/apache/storm/drpc/ReturnResults.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyClient.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/KerberosSaslNettyServer.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/Login.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/ZookeeperSaslLogin.java
- storm-core/src/jvm/org/apache/storm/security/auth/TBackoffConnect.java
- storm-core/src/jvm/org/apache/storm/security/auth/ThriftClient.java
- storm-core/src/jvm/org/apache/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java
- storm-core/src/jvm/org/apache/storm/utils/DRPCClient.java
- ZK-Login-From-AutoTGT thread should not die if TGT in `AutoTGT` has expired. ( It gives grace 10 minutes before killing worker.) This required copying and modified `org.apache.zookeeper.Login` class. 
- `DRPCClient` should not give up connecting to DRPC after n-retries.
- `ReturnResults` Bolt should retry connection on failure to send results to DRPC.
> [STORM-1485] DRPC Connectivity Issues

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java
- Worker should catch and log Exception related to sending worker heartbeats to ZK/pacemaker.
- `PacemakerClient` should not leave open previous channels.. If successfully reconnected - made new `Channel`. This avoids worker having unused Channel open to Pacemaker around.
> [STORM-1503] Worker should not crash on failure to send heartbeats to Pacemaker/ZK

- external/storm-hdfs/README.md
- external/storm-hdfs/pom.xml
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/AbstractAvroSerializer.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/AvroSchemaRegistry.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/AvroUtils.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/ConfluentAvroSerializer.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/FixedAvroSerializer.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/avro/GenericAvroSerializer.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestFixedAvroSerializer.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestGenericAvroSerializer.java
- external/storm-hdfs/src/test/resources/FixedAvroSerializer.config
- pom.xml
This was new for me, so some questions I have:
- Would be better to automatically register this serializer instead of providing developer instructions?
- What's the best practice for exception handling in a serializer? Throwing a RunTimeException seemed like the best option.
Provided this PR is accepted, I would also vote for backporting this to 1.0.0 since the AvroGenericRecordBolt is unusable without it in a multi-worker topology.
> STORM-1504: Add Serializer and instruction for AvroGenericRecordBolt

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/daemon/task.clj
`stream->component->grouper` does only contain streams that are not consumed. Thus, I add entries for all streams (with key is `streamID` and `null` as value) to the computed `HashMap` in `outbound-components`.
> [storm-core] Added exception for emit to undeclared stream

- examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentMapExample.java
- storm-core/src/jvm/org/apache/storm/trident/Stream.java
- storm-core/src/jvm/org/apache/storm/trident/operation/FlatMapFunction.java
- storm-core/src/jvm/org/apache/storm/trident/operation/MapFunction.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/FlatMapFunctionExecutor.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/MapFunctionExecutor.java
- storm-core/src/jvm/org/apache/storm/trident/planner/processor/MapProcessor.java
`map` and `flatmap` and `filter` are common stream operations. 
Right now in trident this has to be implemented via each() which also sends the input field values
in addition to the mapped field values, so the map and flatmap should make things slightly
more efficient and easy.
> [STORM-1505] Add map, flatMap and filter functions in trident stream

- examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentMapExample.java
- storm-core/src/jvm/org/apache/storm/trident/Stream.java
- storm-core/src/jvm/org/apache/storm/trident/operation/Consumer.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/ConsumerExecutor.java
Similar to the Java 8 peek, the peek api can be used to examine trident tuples at
some point in the stream pipeline or execute some custom actions.
Note: this includes changes from https://github.com/apache/storm/pull/1050 and should go away once that gets merged.
> [STORM-1517] add peek api in trident stream

- storm-core/src/clj/org/apache/storm/cluster_state/zookeeper_state_factory.clj
- storm-core/src/jvm/org/apache/storm/utils/StormConnectionStateConverter.java
Please take a look at the mapping between Curator ConnectionState and Storm ConnectionState.
When pull request is merged, I'll craft the pull request which can be applied to 1.x-branch.
(It would be nearly same to this pull request but I've seen small conflict since we ported ZK to Java.)
> STORM-1520 [for master branch] Nimbus Clojure/Zookeeper issue ("stateChanged" method not found)

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
Implemented the ACK-ing logic in Java.
See Jira for profiler info on performance boost.
> STORM-1539 - Improve Storm ACK-ing performance

- bin/storm-config.cmd
- bin/storm.cmd
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
In Windows env, the storm.options are not url-encoded. The parsing logic needs to be fixed to not split in the middle of raw JSON objects.
> [STORM-1532]: Fix readCommandLineOpts to parse JSON correctly in windows

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
Whenever a topology is submitted, it creates respective workers on supervisor/s. These worker pids are stored as files in ${storm-localdir}/workers/{worker-id}/pids/ on supervisor. But there is an issue in storing worker pids. So, supervisor could not find respective worker pids when a topology is killed. Subsequent topology deployment workers are failed because of earlier workers are still alive and bound to the respective ports. 
Fixed worker.clj to have right checks while writing pids to respective locations.
> STORM-1516 Fixed issue in writing pids with distributed cluster mode.

- external/storm-hdfs/pom.xml
Since it affects 2.0.0 and 1.0.0, I'd like to apply both branches when vote for merging passes.
> STORM-1541 Change scope of 'hadoop-minicluster' to test

- bin/storm-config.cmd
- bin/storm.cmd
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
In Windows env, the storm.options are not url-encoded. The
parsing logic needs to be fixed to not split in the middle of
raw JSON objects.
> [STORM-1532]: Fix readCommandLineOpts to parse JSON correctly

- storm-core/src/clj/org/apache/storm/ui/core.clj
STORM-1522 should create error worker log location only when error-hOst and error-port are available
> STORM-1522 should create error worker log location only when error-host and error-port are available

- storm-core/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
Currently the events are logged under "storm-local/workers-artifacts/{storm-id}/{port}/events.log".
and the "events" link in UI does not display the log file.
The events.log should be kept under "logs/workers-artifacts/{storm-id}/{port}/events.log"
so that its viewable via logviewer.
This fix is for 1.x-branch. For master this would be addressed by https://github.com/apache/storm/pull/1123
> [STORM-1552] Fix topology event sampling log dir

- storm-core/src/jvm/org/apache/storm/command/CLI.java
- storm-core/test/jvm/org/apache/storm/command/TestCLI.java
$ storm kill test
Running: /data/nfs_share/soft/jdk1.7.0_79/bin/java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/data/nfs_share/soft/storm -Dstorm.log.dir=/home/admin/storm_logs -Djava.library.path=/usr/local/lib -Dstorm.conf.file= -cp /data/nfs_share/soft/storm/lib/servlet-api-2.5.jar:/data/nfs_share/soft/storm/lib/slf4j-api-1.7.7.jar:/data/nfs_share/soft/storm/lib/log4j-over-slf4j-1.6.6.jar:/data/nfs_share/soft/storm/lib/reflectasm-1.07-shaded.jar:/data/nfs_share/soft/storm/lib/log4j-api-2.1.jar:/data/nfs_share/soft/storm/lib/storm-core-2.0.0-SNAPSHOT.jar:/data/nfs_share/soft/storm/lib/log4j-core-2.1.jar:/data/nfs_share/soft/storm/lib/kryo-2.21.jar:/data/nfs_share/soft/storm/lib/clojure-1.7.0.jar:/data/nfs_share/soft/storm/lib/log4j-slf4j-impl-2.1.jar:/data/nfs_share/soft/storm …
> [STORM-1572] throw NPE when parsing the command line arguments by CLI

- storm-core/test/jvm/org/apache/storm/utils/staticmocking/package-info.java
Minor fix. Or it will cause a compilation error:
>The declared package "org.apache.storm.testing.staticmocking" does not match the expected 
package "org.apache.storm.utils.staticmocking"
> [STORM-1564] fix wrong package-info in org.apache.storm.utils.staticmocking

- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TridentKafkaEmitter.java
[STORM-1571](https://issues.apache.org/jira/browse/STORM-1571) System.currentTimeMillis to calculation time interval is better than System.nanoTime :)
> [STORM-1571]Improvment Kafka Spout Time Metric

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/HdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/SequenceFileBolt.java
When extending HdfsBolt it can be useful to be able to override the methods createOutputFile() or closeOutputFile(), for instance to add a header or footer to the files created. This is currently not possible when the class is outside the `org.apache.storm.hdfs.bolt` package. This patch makes it possible.
> storm-hdfs : change visibility of create and closeOutputFile methods to protected

- storm-core/src/jvm/org/apache/storm/serialization/SerializationFactory.java
- storm-core/src/jvm/org/apache/storm/trident/tuple/ConsList.java
When ConsList emitted by a trident spout has to be transferred over
the network, it fails during Serialization. The proposed fix is to make ConsList
kyro serializable.
> [STORM-1540] Fix Debug/Sampling for Trident

- storm-core/src/jvm/org/apache/storm/metric/FileBasedEventLogger.java
Use ConfigUtils.workerArtifactsRoot to determine correct path
> closes STORM-1545 and STORM-1552

- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/src/ui/public/topology.html
Note that the errorTime reported for the component/ path was previously in milliseconds, but the errorTime reported for the topology/ path was in seconds.  This inconsistency fixed, but we should also update the REST API example. The REST API doc currently does not specify the units.
This should also go to master branch.
> [STORM-1488] fix broken component error times

- storm-core/src/jvm/org/apache/storm/topology/TopologyBuilder.java
- storm-core/test/jvm/org/apache/storm/topology/TopologyBuilderTest.java
Proposed patch addresses the ConcurrentModificationException while
creating a topology with an IStatefulBolt having more than one
input.
> [STORM-1576] fix ConcurrentModificationException in addCheckpointInputs

- examples/storm-starter/src/jvm/org/apache/storm/starter/ThroughputVsLatency.java
Avoiding..
```
1701 [main] INFO  o.a.s.StormSubmitter - Submitting topology wc-test in distributed mode with conf {"topology.worker.metrics":{"CPU":"org.apache.storm.metrics.sigar.CPUMetric"},"storm.zookeeper.topology.auth.scheme":"digest","topology.worker.gc.childopts":"-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:NewSize=128m -XX:CMSInitiatingOccupancyFraction=70 -XX:-CMSConcurrentMTEnabled","topology.workers":4,"topology.builtin.metrics.bucket.size.secs":10,"topology.worker.childopts":"-Xmx2g","storm.zookeeper.topology.auth.payload":"-5601074936064852696:-8332153375154710952","topology.metrics.consumer.register":[{"argument":null,"class":"org.apache.storm.metric.LoggingMetricsConsumer","parallelism.hint":1},{"argument":"http:\/\/survivedlived.corp.ir2.yahoo.com:4 …
```
> [STORM-1587] Avoid NPE while prining Metrics

- storm-core/src/jvm/org/apache/storm/utils/Utils.java
THIS BREAKS MASTER because it stops masking errors in the master branch.
> STORM-1592: clojure code calling into Utils.exitProcess throws ClassCastException

- dev-tools/travis/print-errors-from-test-reports.py
the api "find(match)" of Python ElementTree finds the first sub element matching match. So the match is sub element, but not sub string
> [STORM-1606] print the  information of testcase which is on failure

- conf/defaults.yaml
- storm-core/src/jvm/org/apache/storm/security/auth/AbstractSaslClientCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/AbstractSaslServerCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/digest/ClientCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/digest/ServerCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/plain/PlainClientCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/plain/PlainSaslTransportPlugin.java
- storm-core/src/jvm/org/apache/storm/security/auth/plain/PlainServerCallbackHandler.java
- storm-core/src/jvm/org/apache/storm/security/auth/plain/SaslPlainServer.java
Since `org.apache.storm.security.auth.SimpleTransportPlugin` creates `TFramedTransport` with maxBufferSize, but that conflicts with serialized topology of size exceeded 16MB - default `THsHaServer` allowed max buffer size. So the better option is to implement `PlainSaslTransportPlugin` which avoids using any default values for max-buffer-size.
> [STORM-1469] Adding Plain Sasl Transport Plugin

- conf/log4j2.xml
Currently the -r option outputs the number of milliseconds elapsed from the construction of the layout until the creation of the logging event.
> Fix Log4j2.xml config to output the the timestamp in HH:mm:ss.SSS

- bin/storm
- bin/storm.py
Current python version check is hard-coded and it cannot detect python 2.7.x versions. Changed to /usr/bin/env to keep consistent with storm.py
> [STORM-1605] use '/usr/bin/env python' to check python version

- storm-core/src/jvm/org/apache/storm/messaging/netty/Client.java
If Worker-A has connection to Worker-B that is unused ( and if Worker-B restarted), we drop messages because Channel is not in good state. Can we avoid message drop until we succeed in making new connection or a timeout?
> [STORM-1609] Netty Client is not best effort delivery on failed Connection

- storm-core/test/clj/org/apache/storm/serialization_test.clj
- storm-core/test/jvm/org/apache/storm/TestConfigValidate.java
- storm-core/test/jvm/org/apache/storm/serialization/SerializationTest.java
1. Move `validate-kryo-conf-basic` and `validate-kryo-conf-fail` to `TestConfigValidate.java`, and merge this two tests into one
2. I'm not sure wether to translate `test-clojure-serialization`. So I translate it and commet it.
> [STORM-1250]: port backtype.storm.serialization-test to java

- examples/storm-starter/src/jvm/org/apache/storm/starter/spout/RandomIntegerSpout.java
- examples/storm-starter/src/jvm/storm/starter/StatefulTopology.java
- storm-core/src/jvm/org/apache/storm/topology/CheckpointTupleForwarder.java
- storm-core/src/jvm/org/apache/storm/topology/IStatefulBolt.java
- storm-core/src/jvm/org/apache/storm/topology/StatefulBoltExecutor.java
- storm-core/src/jvm/org/apache/storm/topology/TopologyBuilder.java
- storm-core/test/jvm/org/apache/storm/topology/StatefulBoltExecutorTest.java
Right now the acking is automatically taken care of for the non-stateful bolts in a stateful topology. This leads to double acking if BaseRichBolts are part of the topology and the acking does not complete and tuples are re-emitted.
For the non-stateful bolts, its better to let the bolt do the acking rather than automatically acking.
> [STORM-1608] Fix stateful topology acking behavior

- storm-core/src/clj/org/apache/storm/util.clj
- storm-core/src/jvm/org/apache/storm/utils/ConfigUtils.java
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/test/clj/org/apache/storm/messaging/netty_unit_test.clj
- storm-core/test/clj/org/apache/storm/security/auth/auth_test.clj
- storm-core/test/clj/org/apache/storm/security/auth/drpc_auth_test.clj
- storm-core/test/clj/org/apache/storm/security/auth/nimbus_auth_test.clj
Please note this is a small change when compared to a bigger util.clj to java PR.
It is being put first as the work needed to convert the entire file is taken care and will be up soon.
Just did not want to depend on other patches so putting this up first.
> [STORM-1523] util.clj available-port conversion to java

- external/storm-kafka/README.md
Removed an incorrect (outdated?) constructor of `SpoutConfig` from the README.
Just threw me for a quick loop until I [looked at the source](https://github.com/apache/storm/blob/master/external/storm-kafka/src/jvm/org/apache/storm/kafka/SpoutConfig.java#L41) and confirmed that, sure enough, `zkRoot` isn't optional (the constructor isn't ***actually*** overloaded like the README claims).
> Fixed incorrect storm-kafka documentation.

- storm-core/src/clj/org/apache/storm/clojure.clj
- storm-core/src/clj/org/apache/storm/daemon/acker.clj
- storm-core/src/clj/org/apache/storm/daemon/common.clj
- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/jvm/org/apache/storm/coordination/CoordinatedBolt.java
- storm-core/src/jvm/org/apache/storm/task/IOutputCollector.java
- storm-core/src/jvm/org/apache/storm/task/OutputCollector.java
- storm-core/src/jvm/org/apache/storm/topology/BasicOutputCollector.java
- storm-core/src/jvm/org/apache/storm/topology/IBasicOutputCollector.java
- storm-core/src/jvm/org/apache/storm/trident/topology/TridentBoltExecutor.java
- storm-core/test/clj/integration/org/apache/storm/integration_test.clj
See https://issues.apache.org/jira/browse/STORM-1549.
Other than implementing tuple timeout reset, I made a minor change to assert-loop in integration_test.clj so it doesn't hang on failing tests. It should now fail the test after 10 seconds. I hope that's okay.
> STORM-1549: Add support for resetting tuple timeout from bolts via the OutputCollector

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
Please refer https://issues.apache.org/jira/browse/STORM-1629 to see why Files/move with non-empty directory fails on Windows.
* Use FileUtils/moveDirectory on Windows
* It copies whole contents inside directory, and delete directory
* Keep using Files/move on non-Windows
* it's still better option since doesn't require copying contents inside directory
Since `on-windows?` is ported to Java, I'll create separate pull request for 1.x-branch.
> STORM-1629 Files/move doesn't work properly with non-empty directory in Windows

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
PR based on master is here: https://github.com/apache/storm/pull/1214
* Use FileUtils/moveDirectory on Windows
* It copies whole contents inside directory, and delete directory
* Keep using Files/move on non-Windows
* it's still better option since doesn't require copying contents inside directory
> STORM-1629 (For 1.x) Files/move doesn't work properly with non-empty directory in Windows

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
- storm-core/src/jvm/org/apache/storm/blobstore/BlobStore.java
- storm-core/test/jvm/org/apache/storm/blobstore/BlobStoreTest.java
- storm-core/test/jvm/org/apache/storm/localizer/LocalizerTest.java
* ensures objects of InputStream / OutputStream are closed after used
* clojure: with-open
* java: try-with-resource
* skip checking symbolic link in LocalizerTest when on Windows
* Windows seems not handle symbolic link in compressed file properly
Some integration tests are still failing on Windows, but it should be handled with another issues.
I'll also address this based on master immediately.
Please have a look. Thanks!
> STORM-1602 Blobstore UTs are failed on Windows

- storm-core/src/clj/org/apache/storm/cluster.clj
This doesn't appear to make a difference. When starting nimbus, I get 9 znodes inside of /storm either way. However, it was inconsistent.
> STORM-1641: make subtree node creation consistent

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
In function kill-existing-workers-with-change-in-components in supervisor.clj:
The function tries to detect whether there is a change in assignment. The bug in this function is that the ordering of the assignment matters but it shouldn't. For example, if a worker assignment is [[1 1] [2 2]] and it changed to [[2 2] [1 1]] it will cause the supervisor to restart the worker
> [STORM-1636] - Supervisor shutdown with worker id pass in being nil

- log4j2/cluster.xml
- log4j2/worker.xml
Currently the metrics.log file is always empty and it declared in the cluster.xml file whereas it should be in the worker one. The metrics end up in the log file which is not a huge issue but it would be cleaner to have them in a separate file, as originally intended. 
This patch addresses this and makes so that there is one metrics file per worker, as per the other log files, which should address the issues mentioned in [https://issues.apache.org/jira/browse/STORM-584].
> Fix logging for LoggingMetricsConsumer STORM-584

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
We do not go to count the number of jar-replication in local mode, but will count the number of conf-replication.
> [STORM-1556]: nimbus.clj/wait-for-desired-code-replication wrong reset for current-replication-count-jar in local mode

- storm-core/src/jvm/org/apache/storm/StormTimer.java
Most tests creating a cluster can be flaky because the supervisor threads can terminate out of order. The StormTimer's close should block until the thread is dead.
> Make StormTimer join task thread on close

- external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaUtils.java
Since all of the methods and fields are static, I think it is a good idea to add a private constructor to KafkaUtils to  avoid been constructed.
> add private constructor to KafkaUtils

- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java
- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/HBaseBolt.java
Please also refer #893 to see why this change is necessary.
Set 'default' flush interval seconds to HBaseBolt, since taking half of message timeout secs doesn't work, as #893 showed.
Since we should hardcode default flush interval seconds for now, I think we can change default flush interval to 1s since I guess it's enough for HBase, and anyone never set up tuple timeout seconds to 1. (When if this is happening, all bolts with batching manner using tick tuple should also fail.) 
I'll craft separate PR to be applied to 1.x-branch.
> STORM-1654 HBaseBolt creates tick tuples with no interval when we don't set flushIntervalSecs

- external/flux/flux-core/src/main/java/org/apache/storm/flux/Flux.java
* Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()
JVM sets exit code to 1 when exception is propagated to main() and even main() doesn't catch it.
```
...
606  [main] INFO  o.a.s.f.Flux - Running remotely...
606  [main] INFO  o.a.s.f.Flux - Deploying topology in an ACTIVE state...
619  [main] INFO  o.a.s.StormSubmitter - Generated ZooKeeper secret payload for MD5-digest: -5653047561138062924:-4997865894002296638
669  [main] INFO  o.a.s.s.a.AuthUtils - Got AutoCreds []
Exception in thread "main" java.lang.RuntimeException: Topology with name `yaml-topology` already exists on cluster
at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:230)
at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:288)
at …
```
> STORM-1655 Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster

- external/flux/flux-core/src/main/java/org/apache/storm/flux/Flux.java
* Modify Flux.runCli() to not catching exceptions so that exception can be propagated to main()
> STORM-1655 (1.x) Flux doesn't set return code to non-zero when there's any exception while deploying topology to remote cluster

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
We find a race condition in supervisor which can sometimes crash supervisor.
This race condition exists because: shutdown-worker is called by both sync-processes and synchronize-supervisor. One pid directory might have already been deleted when rmr-as-user tries to delete it. 
To avoid crashing the supervisor, we should log the exception rather than throw it.
> [STORM-1667] Log the IO exception when deleting worker pid dir

- conf/defaults.yaml
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/js/script.js
- storm-core/src/ui/public/templates/component-page-template.html
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/src/ui/public/topology.html
updating setting in defaults.yaml
> STORM-1632  Disable event logging by default

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/jvm/org/apache/storm/daemon/DirectoryCleaner.java
- storm-core/test/clj/org/apache/storm/logviewer_test.clj
For those old and dead worker directories, in some weird case, there is no yaml file in it. We should enable logviewer to delete them. 
Manually tested. It is able to delete an empty workers-artifacts/topo/port dir.
> [STORM-1671] Enable logviewer to delete a dir without yaml

- examples/storm-starter/pom.xml
- examples/storm-starter/src/clj/org/apache/storm/starter/clj/bolts.clj
- examples/storm-starter/src/clj/org/apache/storm/starter/clj/exclamation.clj
- examples/storm-starter/src/clj/org/apache/storm/starter/clj/rolling_top_words.clj
- examples/storm-starter/src/jvm/org/apache/storm/starter/FastWordCountTopology.java
- examples/storm-starter/test/clj/org/apache/storm/starter/clj/bolts_test.clj
- storm-core/src/clj/org/apache/storm/testing.clj
Add some more examples with Clojure, which show using parameters with config and global grouping.
Also add tests for all clojure bolts.
> STORM-515: Clojure documentation and examples

- external/storm-hdfs/README.md
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/HdfsBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/SequenceFileBolt.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/rotation/FileRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/rotation/FileSizeRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/rotation/TimedRotationPolicy.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/AbstractHDFSWriter.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/AvroGenericRecordHDFSWriter.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/HDFSWriter.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/NullPartitioner.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/Partitioner.java
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/common/SequenceFileWriter.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBoltTest.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestSequenceFileBolt.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestWritersMap.java
This PR will enable storm-hdfs to write to multiple files in a couple of different circumstances:
- If a bolt requires multiple output files.  For example, the avro bolt needs to write different Avro records with different schemas to different files.  Schema evolution is a common use of Avro so I expect this to be common use.
- Partitioning output of the HDFS bolt.  Based on mailing discussion, there is demand for this feature.
It does introduce a couple of incompatible changes.  The most obvious is adding a method to the FileRotationPolicy interface.  I tried to minimize other API changes at the expense of some less than elegant code in a couple of places.
> STORM-1464: Support multiple file outputs

- storm-core/src/jvm/org/apache/storm/stats/StatsUtil.java
uptime sometimes equals to zero which causes divide exception.
> [STORM-1687] divide by zero in StatsUtil

- storm-core/src/clj/org/apache/storm/stats.clj
This fixes the "divide by zero" error in stats/compute-agg-capacity.
> [STORM-1687]-1.x divide by zero in stats

- storm-core/src/jvm/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-core/test/jvm/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java
There is a bug in the bfs algorithm in RAS that does not correctly account for components already visited during the breadth first traveral
> [STORM-1681] - Bug in scheduling cyclic topologies when scheduling with RAS

- external/sql/storm-sql-core/src/codegen/data/Parser.tdd
- external/sql/storm-sql-core/src/codegen/includes/parserImpls.ftl
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/SqlCreateFunction.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/standalone/TestPlanCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/parser/TestSqlParser.java
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
This patch proposes to expose the user defined function support added
in STORM-1586 via DDL statements. 
Note: This includes changes from https://github.com/apache/storm/pull/1162
> [Storm-1585]  Add DDL support for UDFs in storm-sql

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/stats.clj
- storm-core/src/jvm/org/apache/storm/metric/internal/RateTracker.java
- storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java
Fresher task is cancelled right after 3 seconds when executor heartbeat is sent. getValueAndReset can rotate the buckets but it is not time bound. Metric tick is in same queue as the input tuples from spout. If processing input tuples is slow, it may take much more to generate metrics and call getValueAndReset and thus `System.currentTimeMillis() - _bucketStart` is more than 10 minutes.
> STORM-1693: Do not cancel the task after stats are rendered

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java
This is a fix for master branch.
When there is a zk exception happens during worker-backpressure!,
there is a bad state which can block the topology from running normally any more.
The root cause: in worker/mk-backpressure-handler
if the worker-backpressure! fails once due to zk connection exception,
next time when this method gets called by WordBackpressureThread, because (when (not= prev-backpressure-flag curr-backpressure-flag) will never be true, the remote zk node can not be synced with local state.
This problem can cause a topology to be blocked!
This also explains why we will not see any problem when testing in a stable (zk never fail) environment.
Solution is quite straightforward: first change the zk status, if succeeds, change local status.
> [STORM-1696] status not sync if zk fails in backpressure #1320 

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java
When there is a zk exception happens during worker-backpressure!,
there is a bad state which can block the topology from running normally any more.
The root cause: in worker/mk-backpressure-handler
if the worker-backpressure! fails once due to zk connection exception,
next time when this method gets called by WordBackpressureThread, because (when (not= prev-backpressure-flag curr-backpressure-flag) will never be true, the remote zk node can not be synced with local state.
This problem can cause a topology to be blocked!
This also explains why we will not see any problem when testing in a stable (zk never fail) environment.
Solution is quite straightforward: first change the zk status, if succeeds, change local status.
This change has been manually tested for a topology that causes …
> [STORM-1696]-1.x-branch status not sync if zk fails in backpressure

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/ui/public/logviewer_search.html
- storm-core/src/ui/public/templates/logviewer-search-page-template.html
- storm-core/test/clj/org/apache/storm/logviewer_test.clj
https://issues.apache.org/jira/browse/STORM-1704
For master please refer #1329.
* ensures that is-daemon parameter is passed around multiple searches
* set logviewerUrl to '/daemonlog' when search is done with is-daemon=yes
> STORM-1704 (1.x) When logviewer_search.html opens daemon file, next search always show no result

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/ui/public/logviewer_search.html
- storm-core/src/ui/public/templates/logviewer-search-page-template.html
- storm-core/test/clj/org/apache/storm/logviewer_test.clj
https://issues.apache.org/jira/browse/STORM-1704
* ensures that is-daemon parameter is passed around multiple searches
* set logviewerUrl to '/daemonlog' when search is done with is-daemon=yes
> STORM-1704 When logviewer_search.html opens daemon file, next search always show no result

- docs/Storm-Scheduler.md
- docs/index.md
> STORM-1679 (1.x): add storm Scheduler documents

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- Replace TreeMap with HashMap
> STORM-1725: Kafka Spout New Consumer API - KafkaSpoutRetryExponential Backoff method should use HashMap instead of TreeMap not to throw Exception

- storm-core/src/clj/backtype/storm/thrift.clj
> STORM-1645: convert nimbus.thrift.port to int to avoid ClassCastException

- storm-core/src/clj/backtype/storm/daemon/executor.clj
* preload the value of flags and use that value
* topology.debug
Pull request for 1.x version is here: #1362 
Please note that this pull request is NOT on top of STORM-1729 since STORM-1729 is not valid for 0.10.x.
I don't take performance tests on this pull request, since #1362 shows the benefit.
> STORM-1731 (0.10.x) Avoid looking up debug / backpressure enable flags within critical path

- storm-core/src/clj/org/apache/storm/stats.clj
* define MultiCount/LatencyStatAndMetric in let statement and set type hint to there
Before applying I got around 860,000 emitted/sec from BasicTopology, and after applying I got around 940,000~960,000 emitted/sec.
`topology.disruptor.batch.size=10000`
And it removes reflection warnings from lines which are recording stats.
Btw, though after applying this, `invokeMatchingMethod` is still on top 10. I'll track where it occurs.
> STORM-1729 (1.x) Get rid of reflections while recording stats

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/stats.clj
This pull request is on top of STORM-1729 (#1361) to avoid merge conflicts.
Even though we set topology.debug to false, we actually hit performance decrement at lookup flag.
Just emitting one tuple eventually hits multiple places on lookup which are all critical paths.
Let me summary the performance improvements with BasicTopology:
Patch | emitted/sec (around)
-------- | ----------------------------
STORM 1.0.1-SNAPSHOT | 860,000
STORM-1729 | 940,000~960,000
| STORM-1731 (including STORM-1729) | 1,500,000 ~ 1,600,000 |
Nearly 2x improvement observed from the start.
I measured the number with my dev. machine so numbers could be a bit unstable.
I really appreciated if someone takes a benchmark with stable environment and stable way and posts the number.
> STORM-1731 (1.x) Avoid looking up debug / backpressure enable flags within critical path

- bin/storm.py
bin/storm.py emits the following crucial information that is lost because we don't flush the stdout before exec. 
```
2016-04-25T08:23:43.17141 Running: java -server -Dstorm.options= -Dstorm.home= -Xmx1024m -Dlogfile.name=nimbus.log -Dlogback.configurationFile=logback/cluster.xml  backtype.storm.ui.core.nimbus
```
Observed Environment:
```
OS: CentOS release 6.5
Kernel: 2.6.32-431.el6.x86_64
Python version: Python 2.7.2
```
> STORM-1733 Flush stdout and stderr before calling "os.execvp" to prevent log loss.

- bin/storm.py
> STORM-1733 (0.1.x) Flush stdout and stderr before calling "os.execvp" to prevent log loss.

- bin/storm.py
> STORM-1733 (0.10.x) Flush stdout and stderr before calling "os.execvp" to prevent log loss

- docs/index.md
I think it is **important** to add the NOTE in the 1.0.0 release docs to let more storm users know this change.
The content is from Abhishek. Thanks @abhishekagarwal87 .
Preview:
> STORM-1727: add storm 1.0.0 rename note

- docs/Setting-up-a-Storm-cluster.md
Storm drops supporting JDK 1.6 in Apache Storm 0.10.0 and above.
> STORM-1739 (master) update the mini JAVA version dependency in 0.10.0 and above.

- docs/Setting-up-a-Storm-cluster.md
Storm drops supporting JDK 1.6 in Apache Storm 0.10.0 and above.
> STORM-1739 (1.x) update the mini JAVA version dependency in 0.10.0 and above.

- docs/Setting-up-a-Storm-cluster.md
Storm drops supporting JDK 1.6 in Apache Storm 0.10.0 and above.
> STORM-1739 (0.10.x) update the mini JAVA version dependency in 0.10.0 and above.

- pom.xml
* upgrade commons-io from 2.4 to 2.5 to resolve IO-378
Fix for 1.x : #1412 
Please refer http://issues.apache.org/jira/browse/STORM-1773 for more details.
> STORM-1773 Utils.javaDeserialize() doesn't work with primitive types

- storm-core/test/jvm/org/apache/storm/nimbus/LocalNimbusTest.java
This test is added to ensure plugin for `Config.STORM_TOPOLOGY_SUBMISSION_NOTIFIER_PLUGIN` works fine. [Atlas](https://github.com/apache/incubator-atlas/) uses this and we want to make sure it always works fine.
> STORM-1769 Added a test to check local nimbus with notifier plugin

- conf/defaults.yaml
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreAclHandler.java
With PlainSaslTransport, in scenarios where insecure environments pick a cluster user to launch the daemons and the topology is launched as an other user it might be a problem for acl validation. It is nice to have a config to switch off acl validation if used in insecure environments.
> [STORM-1661] Introduce ACL Validation config for insecure mode

- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java
- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/HBaseBolt.java
- external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java
- external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java
- storm-core/src/jvm/org/apache/storm/utils/BatchHelper.java
Some external projects(eg: `storm-hbase`, `storm-hive`, `storm-mongodb`) have the same batch processing logic.
Abstracting for that could make code simpler and cleaner.
> STORM-1678: abstract batch processing to common api `BatchHelper`

- external/storm-redis/src/main/java/org/apache/storm/redis/common/config/JedisPoolConfig.java
Using Jedis Protocol.DEFAULT_HOST to replace DEFAULT_HOST  see : [STORM-1715](https://issues.apache.org/jira/browse/STORM-1715)
> [STORM-1715] using Jedis Protocol.DEFAULT_HOST to replace DEFAULT_HOST

- examples/storm-starter/README.markdown
Correct java version in storm-starter, because we drop supporting JDK 1.6 since Storm 0.10.0.
> STORM-1754: Correct java version in 0.10.x storm-starter

- external/storm-solr/src/test/java/org/apache/storm/solr/topology/SolrTopology.java
Please cherry-pick this patch into 0.10.x-branch and 1.x-branch as well.
> STORM-1761: Storm-Solr Example Throws ArrayIndexOutOfBoundsException in Remote Cluster Mode

- storm-core/src/jvm/org/apache/storm/pacemaker/PacemakerServer.java
- storm-core/src/jvm/org/apache/storm/pacemaker/codec/ThriftDecoder.java
Pacemaker throws a handful of stack traces when the occasional weird thing happens. This fixes an IndexOutOfBounds exception, a very strange IllegalStateException, and a NullPointerException.
> STORM-1764: Pacemaker is throwing some stack traces

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- Replace TreeMap with HashMap
> STORM-1725: Kafka Spout New Consumer API - KafkaSpoutRetryExponentialBackoff method should use HashMap instead of TreeMap not to throw Exception

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
> fix typo in worker.clj

- docs/Windowing.md
- examples/storm-starter/src/jvm/org/apache/storm/starter/SlidingWindowTopology.java
- storm-core/src/jvm/org/apache/storm/topology/base/BaseWindowedBolt.java
1. Do not accept negative values for window length or sliding interval in BaseWindowedBolt
2. Added static factories for Count and Duration for ease of use
3. Explicitly call out the sliding behavior and when the first window is evaluated in the windowing doc.
> STORM-1841: Address a few minor issues in windowing and doc

- storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java
The thread pool executor used by the `DisruptorQueue.FlusherPool` is in a static context of the
DisruptorQueue.  To avoid major changes to how this queues lifecycle is
managed I added a simple fix is to create a thread pool factory which creates daemon
threads.  The threads are now also named with the 'disruptor-flush'
prefix to be consistent with the TimerTask.
> This closes #STORM-1730 #1730 LocalCluster#shutdown() does not terminate all storm threads/thread pools.

- storm-core/src/jvm/org/apache/storm/generated/HBMessageData.java
- storm-core/src/py/storm/ttypes.py
- storm-core/src/storm.thrift
For master: #1423 
Please refer STORM-1842 for more details.
* python doesn't support forward reference so ttypes.py has a problem regarding this issue
* reorder HBPulse, HBRecords, HBNodes to resolve forward reference issue
> STORM-1842 (1.x) Forward references in storm.thrift cause tooling issues

- storm-core/src/jvm/org/apache/storm/generated/HBMessageData.java
- storm-core/src/py/storm/ttypes.py
- storm-core/src/storm.thrift
For master: #1423
For 1.x: #1424 
Please refer STORM-1842 for more details.
* python doesn't support forward reference so ttypes.py has a problem regarding this issue
* reorder HBPulse, HBRecords, HBNodes to resolve forward reference issue
> STORM-1842 (1.0.x) Forward references in storm.thrift cause tooling issues

- external/flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/bolts/FluxShellBolt.java
- external/flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/spouts/FluxShellSpout.java
I need ability for FluxShellBolt/FluxShellSpout to emit into named streams.
This pull request maintains backward compatibility, while adding 2 new methods to set stream output.
In Flux YAML DLS the named streams can be created either the old way (default stream only) or by using the new methods:
```
bolts:
- className: org.apache.storm.flux.wrappers.bolts.FluxShellBolt
id: my_bolt
constructorArgs:
- [python, my_bolt.py]
configMethods:
- name: setNamedStream
args:
- first
- [word, count]
```
> FluxShellBolt/FluxShellSpout can now emit into named streams + YAML DSL example

- conf/defaults.yaml
- docs/SECURITY.md
"nimbus.impersonation.authorizer" is set to "ImpersonationAuthorizer" by default and this causes issues when a user tries to submit topology as a different user in secure mode since the "nimbus.impersonation.acl" configuration is not set by default. Users need to set nimbus.impersonation.acl first before they can submit topology as any user other than "storm" in secure mode.
Removing this config allows users to submit topologies in secure mode as any user by default. Users can set up impersonation by providing both authorizer and the acls via storm.yaml.
> [STORM-1851] Fix default nimbus impersonation authorizer config

- storm-core/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
The current implementation simply ignores late tuples without acking
them, which causes timeouts and replays after
TOPOLOGY_MESSAGE_TIMEOUT_SECS. A tuple which was late at a some time
is going to be late at any moment in the future, so there is no point
of replaying it, because the lingering late tuples will just block the
topology (especially if TOPOLOGY_MAX_SPOUT_PENDING is set).
> STORM-1859: Ack late tuples in windowed mode

- external/flux/flux-core/src/main/java/org/apache/storm/flux/FluxBuilder.java
- external/flux/flux-examples/README.md
- external/flux/flux-examples/src/main/java/org/apache/storm/flux/examples/StatefulWordCounter.java
- external/flux/flux-examples/src/main/resources/simple_stateful_wordcount.yaml
We noticed that Flux could not yet handle IStatefulBolts in a topology definition. With this small addition we can successfully build and deploy our topology.
> STORM-1878: Flux can now handle IStatefulBolts

- bin/storm.py
The help message didn't mention that topology-name was a required parameter, thus giving the following error when not passing it:
```
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: IllegalArgumentException for class java.lang.String
at clojure.lang.Reflector.getInstanceField(Reflector.java:271)
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:315)
at org.apache.storm.command.set_log_level$get_storm_id.invoke(set_log_level.clj:31)
at org.apache.storm.command.set_log_level$_main.doInvoke(set_log_level.clj:75)
at clojure.lang.RestFn.applyTo(RestFn.java:137)
at org.apache.storm.command.set_log_level.main(Unknown Source)
```
> STORM-1887: Fixed help message for set_log_level command

- docs/STORM-UI-REST-API.md
- storm-core/src/clj/org/apache/storm/ui/core.clj
* Path: /api/v1/topology/:id/metrics
* This API provides detailed metrics for topology
* shows metrics per component, which are aggregated by stream
* add documentation about new REST API
I don't address this for master yet since ui/core.clj is not converted to Java but stats.clj is converted to Java. 
If we want to move some methods in this patch to stats.clj, I'll follow up reviews, and start working on crafting patch against master when patch is ready to merge.
Sample output is here.
```json
{
"window":":all-time",
"window-hint":"All time",
"spouts":[
{
"id":"spout",
"emitted":[
{
"stream_id":"__metrics",
"value":20
},
{
"stream_id":"default",
"value":17350280
},
{
"stream_id":"__ack_init",
"value":17328160
},
{
"stream_id":"__system",
"value":20
}
],
"transferred":[
{ …
```
> STORM-1719 (1.x) Introduce REST API: Topology metric stats for stream

- docs/Metrics.md
Please keep in mind while reviewing that this is written by not native and good writing skill for English.
So you may want to correct many places which are wrong or weird use of vocabulary, grammar, nuance, and so on.
This PR is similar to master (#1354) / 1.x version (#1355) but remove non-exist classes (introduced at 1.0.0) and address package name difference.
> STORM-1724 (0.10.x) Fill up lacking contents to Metrics documentation

- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/TextFileReader.java
[STORM-1882](https://issues.apache.org/jira/browse/STORM-1882)
TextFileReader is package-private .Should make TextFileReader a public class to expose it to user and hdfs spout.
> [STORM-1882] Expose TextFileReader public

- external/storm-kafka/README.md
- external/storm-kafka/src/jvm/org/apache/storm/kafka/ExponentialBackoffMsgRetryManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/FailedMsgRetryManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/SpoutConfig.java
- external/storm-kafka/src/test/org/apache/storm/kafka/ExponentialBackoffMsgRetryManagerTest.java
This PR also makes retry strategy pluggable.
> STORM-1705: Cap number of retries for a failed message

- conf/defaults.yaml
- conf/storm.yaml.example
- log4j2/cluster.xml
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/metric/ClusterMetricsConsumerExecutor.java
- storm-core/src/jvm/org/apache/storm/metric/LoggingClusterMetricsConsumer.java
- storm-core/src/jvm/org/apache/storm/metric/api/DataPoint.java
- storm-core/src/jvm/org/apache/storm/metric/api/IClusterMetricsConsumer.java
- storm-core/src/jvm/org/apache/storm/metric/api/IMetricsConsumer.java
- storm-core/src/jvm/org/apache/storm/validation/ConfigValidation.java
Pull request for 1.x is here: #1352 
* ClusterMetricsConsumer publishes cluster-side related metrics into consumers
* like MetricsConsumer for topology metrics
* Users can implement IClusterMetricsConsumer and configure to cluster conf. file to take effect
* Please refer conf/storm.yaml.example for more details on configuring
* Nimbus should be launched with additional jars which are needed for IClusterMetricsConsumer
* Also did some refactor to nimbus.clj
> STORM-1723 Introduce ClusterMetricsConsumer

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
* to have consistency with IMetricsConsumer
PR for 1.x: #1499
> STORM-1911 IClusterMetricsConsumer should use seconds to timestamp unit

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
* to have consistency with IMetricsConsumer
PR for master: #1498
> (1.x) STORM-1911 IClusterMetricsConsumer should use seconds to timestamp unit

- examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentWordCount.java
- storm-core/src/jvm/org/apache/storm/trident/spout/PartitionedTridentSpoutExecutor.java
- Generify on Object rather than Integer because example is broken
- Fix TridentWordCount example to print more meaningful output
> STORM-1907: PartitionedTridentSpoutExecutor has incompatible types that cause ClassCastException

- external/storm-kafka-monitor/pom.xml
* set it back to 2.0.0-SNAPSHOT
> STORM-1920 version of parent pom for storm-kafka-monitor is set 1.0.2-SNAPSHOT in master branch

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
PR for 1.x: #1514
* Nimbus fails to start in secure mode since authrization is not passed
Extract the logic of getClusterInfo to new function 'get-cluster-info' and let both of callers call this function instead.
> STORM-1925 Remove Nimbus thrift call from Nimbus itself

- external/storm-kafka/README.md
- external/storm-kafka/src/jvm/org/apache/storm/kafka/bolt/selector/FieldIndexTopicSelector.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/bolt/selector/FieldNameTopicSelector.java
[STORM-1914](https://issues.apache.org/jira/browse/STORM-1914)
Support field name and field index to select which kafka topic will used as a downstream .
> [STORM-1914] Storm Kafka Field Topic Selector

- bin/storm.py
This can be cherry-picked to 1.x-branch.
> STORM-1888: add description for shell command

- storm-core/src/clj/org/apache/storm/cluster.clj
PR for master: #1535 
* delete ephemeral node first when reconnected handler is called
This also deletes node if session is alive but reconnected.
If we really need to avoid deleting node, we could check ephemeral owner before deleting. Zookeeper reconnect is not happening so often, so I guess it's fine to not applying. If you think we should, please let me know.
Btw, blobstore also uses ephemeral nodes so I'm curious they should be recreated too.
> STORM-1941 Nimbus discovery can fail when zookeeper reconnect happens. (1.x)

- storm-core/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java
* delete ephemeral node first when reconnected handler is called
PR for 1.x: #1534
Please read [STORM-1941](https://issues.apache.org/jira/browse/STORM-1941) before reviewing. I left full description from there.
> STORM-1941 Nimbus discovery can fail when zookeeper reconnect happens.

- docs/STORM-UI-REST-API.md
- storm-core/src/clj/org/apache/storm/ui/core.clj
* Path: /api/v1/topology/:id/metrics
* This API provides detailed metrics for topology
* shows metrics per component, which are aggregated by stream
* add documentation about new REST API
* please refer docs/STORM-UI-REST-API.md for details
This should be reviewed and merged since 1.x version (#1347) of STORM-1719 is already merged.
@harshach 
This is a pull request for STORM-1719 against master branch.
I have confirmed that it runs well with 2.0.0 SNAPSHOT. 
Please take a look. Thanks!
> STORM-1719 Introduce REST API: Topology metric stats for stream

- bin/storm-kafka-monitor
- storm-core/src/jvm/org/apache/storm/utils/TopologySpoutLag.java
- storm-dist/binary/src/main/assembly/binary.xml
PR for 1.x-branch: #1541
* Fix several spots which are throwing NPE on TopologySpoutLag
* Use a trick to get classname of Spout without requiring storm-kafka and storm-kafka-client
* Move storm-kafka-monitor jar to toollib directory
* since jars in extlib are added to worker classpath which we don't want for this jar
@priyank5485 @harshach Please take a look and comment. Thanks!
> STORM-1945 Fix NPE bugs on topology spout lag for storm-kafka-monitor

- bin/storm-kafka-monitor
- storm-core/src/jvm/org/apache/storm/utils/TopologySpoutLag.java
- storm-dist/binary/src/main/assembly/binary.xml
PR for master: #1540 
* Fix several spots which are throwing NPE on TopologySpoutLag
* Use a trick to get classname of Spout without requiring storm-kafka and storm-kafka-client
* Move storm-kafka-monitor jar to toollib directory
* since jars in extlib are added to worker classpath which we don't want for this jar
@priyank5485 @harshach Please take a look and comment. Thanks!
> STORM-1945 Fix NPE bugs on topology spout lag for storm-kafka-monitor (1.x)

- storm-core/src/jvm/org/apache/storm/task/ShellBolt.java
When storm stars a large number of ShellBolt-s that consume a lot of CPU time to initialize, it creates a lot of contention between processes for CPU resource. That leads to BoltHeartbeatTimerTask being fired up after 1 second delay before setHeartbeat() assigns initial value to lastHeartbeatTimestamp variable.
As a result when BoltHeartbeatTimeTask fires up for the first time, getLastHeartbeat() returns value of 0. This in turn leads bolt to die with "subprocess heartbeat timeout" message.
The fix is to place setHeartBeat() before BoltHeartbeatTimerTask is created. The patch for this is attached.
> STORM-1946: initialize lastHeartbeatTimestamp before starting heartbeat task

- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/jvm/org/apache/storm/daemon/Acker.java
- storm-core/src/jvm/org/apache/storm/daemon/StormCommon.java
PR for 1.x: #1379 
* Acker computes 'complete latency' and sends back to Spout
* start time: Acker receiving ACK_INIT from Spout
* end time: Acker receiving ACK message which make the tuple tree completed
* When Acker provides complete latency, Spout just uses this value to record that latency
* exception case: tuple timed out - Spout doesn't receive failed information from Acker
#1379 contains the result of functional test and performance test. Please refer that pull request.
> STORM-1742 More accurate 'complete latency'

- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java
- external/storm-hbase/src/main/java/org/apache/storm/hbase/common/HBaseClient.java
[STORM-1899](https://issues.apache.org/jira/browse/STORM-1899)
Release HBase connection when topology shutdown
> [STORM-1899] Release HBase connection when topology shutdown

- storm-core/src/clj/org/apache/storm/daemon/supervisor.clj
Please refer [STORM-1933](https://issues.apache.org/jira/browse/STORM-1933) and [STORM-1934](https://issues.apache.org/jira/browse/STORM-1934) to see reason of this issue and concept to fix.
* sync-supervisor just downloads new topology code and writes new local assignment
* shutting down workers and removing topology code is moved to sync-processes
* sync-processes does all of jobs based on local assignment and allocated workers
* remove unused / unneeded codes
PR for master: #1529 
Here's my test result for this patch:
* `mvn clean install` 5 times: not met supervisor intermittent failure (STORM-1933)
* will try more times
* kill worker via `kill`, `kill -9`, `restart worker` from UI: no issue on restarting worker
* rebalance topology to change workers (3 -> 2): to test that new …
> STORM-1934 Fix race condition between sync-supervisor and sync-processes (1.x)

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutStream.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutStreams.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutStreamsNamedTopics.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutStreamsWildcardTopics.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutTuplesBuilderNamedTopics.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutTuplesBuilderWildcardTopics.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainNamedTopics.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainWildcardTopics.java
- Interfaces for TuplesBuilder and KafkaSpoutStreams and implementations for named topics and wildcards
- Test topologies for named topics and wildcards
> STORM-1930: Kafka New Client API - Support for Topic Wildcards

- bin/storm-kafka-monitor
- external/storm-kafka-monitor/src/main/java/org/apache/storm/kafka/monitor/KafkaOffsetLagUtil.java
- external/storm-kafka-monitor/src/main/java/org/apache/storm/kafka/monitor/KafkaPartitionOffsetLag.java
- storm-core/src/jvm/org/apache/storm/utils/TopologySpoutLag.java
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/src/ui/public/topology.html
* bin/storm-kafka-monitor: guard classpath to only uses storm-kafka-monitor*.jar
* KafkaOffsetLagUtil: when succeed to get, output is keyed by topic and partition
* TopologySpoutLag: modify JSON response keyed by spoutId
* reflect changes on topology page
Here's sample JSON response from /lag API
```
{
"kafka-spout":{
"spoutLagResult":{
"myKafkaTopic":{
"0":{
"consumerCommittedOffset":749491,
"logHeadOffset":911511,
"lag":162020
},
"1":{
"consumerCommittedOffset":1168,
"logHeadOffset":1168,
"lag":0
},
"2":{
"consumerCommittedOffset":159339,
"logHeadOffset":159339,
"lag":0
}
}
},
"spoutId":"kafka-spout",
"spoutType":"KAFKA"
}
}
```
@harshach Please review and comment. Thanks!
> STORM-1950 Change response json of "Topology Lag" REST API to keyed by spoutId, topic, partition

- external/storm-kafka-monitor/src/main/java/org/apache/storm/kafka/monitor/KafkaPartitionOffsetLag.java
This is just an addition of missing license header (not code change), so I think it can be merged without waiting one day rule. I feel Travis CI pass and another one +1 by other committer are sufficient to check in.
It should be applied to also 1.x branch.
> STORM-1959 Add missing license header to KafkaPartitionOffsetLag

- external/storm-hive/pom.xml
- hive-hcatalog-streaming:jar depends on thrift 0.9.3
- storm-hive:jar depends on thrift 0.9.0
- Update storm-hive thrift version to 0.9.3
> TridentHiveTopology fails to run due to incompatibility between thrift dependencies

- storm-core/src/jvm/org/apache/storm/task/ShellBolt.java
InterruptedException makes false alarm for ShellBolt shutting down.
Since it's likely throwing InterruptedException when ShellBolt is shutting down, so we're ok to just consume that and continue.
Please see https://issues.apache.org/jira/browse/STORM-1939 for more details.
It should be applied to master, 1.x, 1.0.x branches.
> STORM-1939 Ignore InterruptedException on ShellBoltMessageQueue

- examples/storm-starter/src/jvm/storm/starter/HdfsSpoutTopology.java
- external/storm-hdfs/README.md
- external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
- external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java
Changing the way the spout is configured. Using member functions as the primary mode of config... still have to supporting the older mode  (via conf object ) for backward compatibility.
Updated test code.
> STORM-1910  One topology cannot use hdfs spout to read from two locations

- storm-core/src/clj/org/apache/storm/util.clj
- storm-core/test/clj/org/apache/storm/utils_test.clj
logviewer invokes "get-log-user-group-whitelist" which tries to get the worker metadata file by invoking "get-log-metadata-file". In the case of nimbus.log clojure-from-yaml-file  returns nil and the authorization fails.
Modify clojure-from-yaml-file to return an empty map in case of failures so that the authorization can continue.
> [STORM-1968] Storm logviewer does not work for nimbus.log in secure cluster

- conf/storm.yaml.example
- storm-core/src/clj/org/apache/storm/daemon/common.clj
- storm-core/src/jvm/org/apache/storm/metric/MetricsConsumerBolt.java
- storm-core/src/jvm/org/apache/storm/metric/api/IMetricsConsumer.java
- storm-core/src/jvm/org/apache/storm/metric/util/DataPointExpander.java
- storm-core/test/jvm/org/apache/storm/metric/util/DataPointExpanderTest.java
PR for master: #1560 
* populate metric before applying filter so that filter can play with populated metrics
* add relevant configs to metrics consumer registration and describe them to storm.config.yaml
* add unit test
Please refer https://issues.apache.org/jira/browse/STORM-1966 for more details.
> STORM-1966 Expand metric having Map type as value into multiple metrics based on entries (1.x)

- conf/storm.yaml.example
- storm-core/src/jvm/org/apache/storm/daemon/StormCommon.java
- storm-core/src/jvm/org/apache/storm/metric/MetricsConsumerBolt.java
- storm-core/src/jvm/org/apache/storm/metric/api/IMetricsConsumer.java
- storm-core/src/jvm/org/apache/storm/metric/util/DataPointExpander.java
- storm-core/test/jvm/org/apache/storm/metric/util/DataPointExpanderTest.java
PR for 1.x: #1561 
* populate metric before applying filter so that filter can play with populated metrics
* add relevant configs to metrics consumer registration and describe them to storm.config.yaml
* add unit test
Please refer https://issues.apache.org/jira/browse/STORM-1966 for more details.
> STORM-1966 Expand metric having Map type as value into multiple metrics based on entries

- external/storm-hive/src/test/java/org/apache/storm/hive/bolt/HiveTopology.java
There're some kinds of topology in storm-hive, but all of them uses partition so we don't have example for accessing non-partition table. It would be better to have one for automated tests.
Instead of creating a new topology, we can modify HiveTopology to not use partition at all. BucketTestHiveTopology and TridentHiveTopology also use DelimitedRecordHiveMapper.withTimeAsPartitionField() so I think usage of withTimeAsPartitionField() is covered.
It can be ported back easily so I don't create pull requests for other branches.
We would be better to have this to 1.x and maybe 1.0.x, too.
Please review and comment. Thanks!
> STORM-1969 Modify HiveTopology to show usage of non-partition table

- storm-core/src/clj/org/apache/storm/command/shell_submission.clj
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/clj/org/apache/storm/zookeeper.clj
PR for master: #1573 
* Nimbus H/A introduced condition for becoming a leader
* It got removed when BlobStore was introduced
* This patch is restoring previous logic with making logic compatible to BlobStore
> STORM-1977 Restore logic: give up leadership when elected as leader but doesn't have one or more topology codes on local (1.x)

- storm-core/src/clj/org/apache/storm/command/shell_submission.clj
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/jvm/org/apache/storm/zookeeper/LeaderElectorImp.java
- storm-core/src/jvm/org/apache/storm/zookeeper/Zookeeper.java
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
PR for 1.x: #1574 
* Nimbus H/A introduced condition for becoming a leader
* It got removed when BlobStore was introduced
* This patch is restoring previous logic with making logic compatible to BlobStore
Please refer [STORM-1977](issues.apache.org/jira/browse/STORM-1977) for more details.
Tested with the scenario I've described from STORM-1977
1. comment cleanup-corrupt-topologies! from nimbus.clj (It's a quick workaround for resolving STORM-1976), and patch Storm cluster
2. Launch Nimbus 1 (leader)
3. Run topology1
4. Kill Nimbus 1
5. Launch Nimbus 2 from different node
6. Nimbus 2 gains leadership but since it doesn't have topology1 it gives up leadership
> STORM-1977 Restore logic: give up leadership when elected as leader but doesn't have one or more of topology codes on local

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
For master branch: #1571 
* cleanup-corrupt-topologies! was born from non-H/A Nimbus age
* Keeping this with Nimbus H/A makes various issues which in result topology going away
Please refer [STORM-1976](https://issues.apache.org/jira/browse/STORM-1976) for more details.
> STORM-1976 Remove cleanup-corrupt-topologies! (1.x)

- bin/storm-kafka-monitor
Adding prefix and/or postfix between * just doesn't work on classpath, which I didn't recognize that.
Confirmed from CentOS6 with OpenJDK 1.8.0_91 / Oracle JDK 1.8.0_77 and OSX 10.11.5 with Oracle JDK 1.8.0_66.
Patch can be ported back to 1.x-branch easily.
> STORM-1988 Kafka Offset not showing due to bad classpath

- pom.xml
- storm-core/pom.xml
- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/clj/org/apache/storm/ui/helpers.clj
- storm-core/src/ui/public/component.html
- storm-core/src/ui/public/deep_search_result.html
- storm-core/src/ui/public/index.html
- storm-core/src/ui/public/js/script.js
- storm-core/src/ui/public/js/visualization.js
- storm-core/src/ui/public/logviewer_search.html
- storm-core/src/ui/public/search_result.html
- storm-core/src/ui/public/topology.html
- storm-dist/binary/pom.xml
- storm-dist/binary/src/main/assembly/binary.xml
Original pull request: https://github.com/apache/storm/pull/1486
I added in this PR the no-cache header for html pages in the / directory. To recap, this is to add cache-busting to Storm UI.
I also upgraded ring-core to 1.3.1 and compojure to 1.1.9 to match ring-core versions without changing too much. Versions above 1.1.9 seem to have issues with Clout not compiling for clojure 1.7. We could potentially go to a much newer version which fixes the issues (1.4.0), but that should be a different PR IMHO, and I am not sure how much we care since this is going away on conversion to Java.
> Storm 1890 ensure we refetch static resources after package build

- storm-core/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java
- storm-core/src/jvm/org/apache/storm/windowing/CountEvictionPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/CountTriggerPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/DefaultEvictionContext.java
- storm-core/src/jvm/org/apache/storm/windowing/EvictionContext.java
- storm-core/src/jvm/org/apache/storm/windowing/EvictionPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/TimeEvictionPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/TimeTriggerPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/WatermarkCountEvictionPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/WatermarkCountTriggerPolicy.java
- storm-core/src/jvm/org/apache/storm/windowing/WatermarkTimeTriggerPolicy.java
- storm-core/test/jvm/org/apache/storm/windowing/WindowManagerTest.java
Do not use timestamp to determine the event count in WatermarkCountEvictionPolicy
when count based trigger is used.
> [STORM-1964] Unexpected behavior when using count window together with timestamp extraction

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
When the input stream is being removed from its parent collection (after reading fully) in downloadChunk it isn't being closed, causing a leak.
Thanks to @tgravescs for making this change.
> STORM-1995: close input stream and other tweaks to downloadChunk

- external/storm-kinesis/pom.xml
Builds on PR for 1.x-branch are failing because of this.
> fix parent version of storm-kinesis module (1.x)

- external/storm-druid/pom.xml
It breaks the build against 1.x-branch pull requests, and it's not about code itself, I'll just merge this right now. Please revert if you think it should get +1.
(Same reason for kinesis)
> fix parent version of storm-druid pom in 1.x branch

- storm-core/src/jvm/org/apache/storm/executor/Executor.java
- storm-core/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java
- storm-core/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
* fix Executor, SpoutExecutor, BoltExecutor to not calling init() while creating Executor itself
* call init() for the first time in async loop
Please refer https://github.com/apache/storm/pull/1445#discussion_r72933087 and comment thread for this.
> STORM-2026 Inconsistency between (SpoutExecutor, BoltExecutor) and (spout-transfer-fn, bolt-transfer-fn)

- docs/Concepts.md
* Fix for 0.10.x
This should be also downmerged to 0.9.x branch, and applied to docs of 0.10.0, 0.10.1, 0.9.6.
NOTE: This is non-code change so lazy consensus is applied. (don't need to wait for +1 and also 24 hrs)
> STORM-841 Thread-safeness of OutputCollector has documented contrary to two official doc (0.10.x)

- external/sql/storm-sql-core/pom.xml
- external/sql/storm-sql-runtime/pom.xml
- storm-dist/binary/src/main/assembly/binary.xml
* also copy (transitive) dependencies to binary distribute, as storm-sql-core did
It can be easily applied to 1.x-branch, so I don't create pull request against 1.x-branch.
We can apply this to 1.0.x-branch but without STORM-2016 users still need to copy them to extlib directory which is bad.
> STORM-2023 Add calcite-core to dependency of storm-sql-runtime

- storm-core/src/jvm/org/apache/storm/security/auth/authorizer/SimpleACLAuthorizer.java
While enabling/disabling topology event logging, theres a call to assert-authorized-user with "debug" as the operation in ui/core.clj.
This needs to be whitelisted in SimpleAclAuthorizer to get it working in secure mode.
> [STORM-2037] debug operation should be whitelisted in SimpleAclAuthorizer

- external/storm-druid/pom.xml
- external/storm-kinesis/pom.xml
* during the rollback they still keep versions since it's manually fixed after the release process
> Fix parent version of storm-druid and storm-kinesis

- examples/storm-starter/README.markdown
Appended target directory to command. Previously resulted in ClassNotFound exception.
> Fix command to run RollingTopWords example

- docs/flux.md
- external/flux/README.md
Two Flux-related documents are outdated. This PR introduces new flux-wrappers library and fixes class names of `GenericShellSpout` and `GenericShellBolt`.
> adjusted Flux documentation to show new flux-wrapper library

- docs/storm-sql.md
- external/sql/README.md
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/trident/TridentLogicalPlanCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/trident/TestPlanCompiler.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/trident/functions/UDAFWrappedAggregator.java
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
NOTE: This pull request is on top of STORM-1434 (#1635)
After this patch, below sql statement runs fine for cluster mode (Trident).
(MyConcat is an user defined aggregate function.)
```
CREATE EXTERNAL TABLE ORDERS (ID INT PRIMARY KEY, NAME VARCHAR, UNIT_PRICE INT, QUANTITY INT) LOCATION 'kafka://localhost:2181/brokers?topic=orders' TBLPROPERTIES '{"producer":{"bootstrap.servers":"localhost:9092","acks":"1","key.serializer":"org.apache.storm.kafka.IntSerializer","value.serializer":"org.apache.storm.kafka.ByteBufferSerializer"}}'
CREATE EXTERNAL TABLE SUMMARY_ORDERS (ID INT PRIMARY KEY, ID_PLUS_3 INT, CNT INT, NAME_CONCAT VARCHAR) LOCATION 'kafka://localhost:2181/brokers?topic=large_orders' TBLPROPERTIES '{"producer":{"bootstrap.servers":"localhost:9092","acks":"1","key.serializer":"org.apa …
```
> STORM-2050 [storm-sql] Support User Defined Aggregate Function for Trident mode

- external/storm-kafka-client/README.md
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
This patch should be back-ported to 1.0.x branch and 1.x-branch. Thank you.
> STORM-2052: Kafka Spout - New Client API - Performance Improvements

- log4j2/worker.xml
Bring the change in:
https://github.com/apache/storm/pull/1652
To 2.x. Only the worker.xml, since we were already checking for empty thread names in 2.x
> STORM-2063: turn on thread name in worker.xml

- conf/defaults.yaml
- storm-core/src/clj/org/apache/storm/daemon/executor.clj
- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/src/jvm/org/apache/storm/Config.java
For 1.x branch, will submit a PR for 2.x branch.
@zhuoliu worked on the initial refactor. I added some due code review comments.
> STORM-2039: backpressure refactoring in worker and executor

- external/storm-kafka/src/jvm/org/apache/storm/kafka/ExponentialBackoffMsgRetryManager.java
- external/storm-kafka/src/test/org/apache/storm/kafka/ExponentialBackoffMsgRetryManagerTest.java
Use simulated time instead of wall clock time in test, as running this in virutual environments sometime causes failure.
Replaces https://github.com/apache/storm/pull/1335.
> [STORM-1646] Fix ExponentialBackoffMsgRetryManager test

- external/storm-metrics/pom.xml
* previous link goes 404, googlecode seems change archive url
This should be also merged back to 1.x, 1.0.x branches.
> STORM-2070 Fix sigar native binary download link

- external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/RepositorySystemFactory.java
- external/storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/DependencyResolverTest.java
* Fix Booter to handle the path with awareness of relative vs absolute
* Modify DependencyResolverTest to remove temporary directory after tests for that class are done
This breaks whole builds for master and 1.x branch due to RAT failing.
It should be also applied to 1.x-branch.
> STORM-2054 DependencyResolver should be aware of relative path and absolute path

- external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/RepositorySystemFactory.java
- external/storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/DependencyResolverTest.java
* Fix Booter to handle the path with awareness of relative vs absolute
* Modify DependencyResolverTest to remove temporary directory after tests for that class are done
This PR is just for leaving history. Since PR for master branch (#1648) received +1 and merged in, I'll merge this right now.
> STORM-2054 DependencyResolver should be aware of relative path and absolute path (1.x)

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
* force set type to Map when calling into-array with seq which has Maps
* Clojure optimization occurs type mismatch: PersistentArrayMap vs PersistentHashMap
Please refer http://issues.apache.org/jira/browse/STORM-2067 for more details.
This code only resides on master branch. No need to backport.
> STORM-2067 Fix "array element type mismatch" from compute-executors in nimbus.clj

- docs/storm-sql.md
- external/sql/README.md
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/trident/TridentLogicalPlanCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/trident/TestPlanCompiler.java
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/jvm/org/apache/storm/trident/JoinOutFieldsMode.java
- storm-core/src/jvm/org/apache/storm/trident/TridentTopology.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/JoinState.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/PreservingFieldsOrderJoinerMultiReducer.java
> * Note for merger
>
>This is on top of STORM-2067 which is not applicable for 1.x-branch. So in order to make porting back easier, STORM-2067 should be handled first and this pull request should be rebased to updated master.
This pull request accomplishes supporting JOIN statement in Storm SQL for Trident mode.
INNER, LEFT OUTER, RIGHT OUTER, FULL OUTER JOIN are supported.
Since this feature is based on Trident join, some limitations follow:
- Only equi-join is supported.
- Joining will be occurred for each batch, not across batches.
- http://storm.apache.org/releases/1.0.2/Trident-API-Overview.html
- Please refer `Merges & Joins` section
- Trident join provides only one value for joining fields (two)
- For inner join, that would be OK
- For outer joins, one of values should be null, …
> STORM-2057 Support JOIN statement in Storm SQL

- external/sql/storm-sql-core/pom.xml
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/trident/TestPlanCompiler.java
Issue link: [STORM-2100](https://issues.apache.org/jira/browse/STORM-2100)
The join doesn't guarantee preserving order (Trident and SQL itself) so we shouldn't rely on that.
Before this patch, tests are failing with JDK7 (with 1.x-branch). I confirmed that this patch makes tests succeed with 1.x-branch & JDK 1.7 (1.7.0_79) combination.
@satishd Could you please review this? Thanks.
> STORM-2100 Fix Trident SQL join tests to not rely on ordering

- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/AbstractRedisBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisClusterContainer.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisCommandsInstanceContainer.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisContainer.java
[STORM-1872](https://issues.apache.org/jira/browse/STORM-1872)  
Strom Redis connect should be release when topology shutdown .
> [STORM-1872]Release Jedis connection when topology shutdown

- external/storm-kafka/src/jvm/org/apache/storm/kafka/bolt/KafkaBolt.java
[STORM-2003 Make sure config contains TOPIC before get it](https://issues.apache.org/jira/browse/STORM-2003)
When topic selector is not specified, KafkaBolt will get topic name from storm config . We should make sure the topic name is not null .
> [STORM-2003] Make sure config contains TOPIC before get it

- bin/storm.cmd
Move version command from shellcommands to corecommands. VersionInfo.main() needs to be executed to print out the version information.
> Fix version command in storm.cmd

- docs/Guaranteeing-message-processing.md
There's a placeholder ticket in JIRA https://issues.apache.org/jira/browse/STORM-2088
Two minor typos in the "Guaranteeing Message Processing" documentation.
Thanks
Bruno
> Minor typos in documentation

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
Backport to 1.x of: https://github.com/apache/storm/pull/1694
> STORM-2101: fixes npe in compute-executors in nimbus

- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
Even though KafkaSpout.declareOutputFields declaresStream using outputStreamId (if present), the message gets emitted to a stream matching the Kafka topic it was read from. Looks like it may have been a merge conflict between the fix for STORM-1210 and STORM-1379.
> STORM-2120 - Emit to _spoutConfig.outputStreamId

- storm-core/src/jvm/org/apache/storm/localizer/AsyncLocalizer.java
* it extracts the resources directory to topology root directory instead of temporary directory
* it should be extracted to temporary directory since we will move that directory to topology root directory
It didn't make unit tests failing, but I ran the tests from IntelliJ manually, IntelliJ adds some jars which contains resources directory, and this happens.
@revans2 Please take a look. Thanks!
> STORM-2117 Supervisor V2 with local mode extracts resources directory to the wrong directory

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/trident/TridentLogicalPlanCompiler.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/trident/TestPlanCompiler.java
- external/sql/storm-sql-external/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/KafkaDataSourcesProvider.java
- external/sql/storm-sql-external/storm-sql-kafka/src/test/org/apache/storm/sql/kafka/TestKafkaDataSourcesProvider.java
- external/sql/storm-sql-runtime/pom.xml
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/FieldInfo.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/ISqlTridentDataSource.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/SimpleSqlTridentConsumer.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/json/JsonScheme.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/json/JsonSerializer.java
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestJsonRepresentation.java
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
* issue link: https://issues.apache.org/jira/browse/STORM-2089
This is for handling INSERT for tuples as batch if possible.
I also changed storm-sql-kafka to expose State directly, but this is effectively same as current since TridentKafkaState.updateState() does update via fully synchronous way.
(by looping each tuple and calling Future.get() immediately)
```
public void updateState(List<TridentTuple> tuples, TridentCollector collector) {
String topic = null;
for (TridentTuple tuple : tuples) {
try {
topic = topicSelector.getTopic(tuple);
if(topic != null) {
Future<RecordMetadata> result = producer.send(new ProducerRecord(topic,
mapper.getKeyFromTuple(tuple), mapper.getMessageFromTuple(tuple)));
try {
result.get();
} catch (ExecutionException e) {
String errorMsg = "Could not retrieve …
```
> STORM-2089 Replace Consumer of ISqlTridentDataSource with SqlTridentConsumer

- .travis.yml
- dev-tools/travis/travis-script.sh
* newly added integration test adds more and 20 mins in each build and sometimes makes build failing due to long running
* making it to separate build helps reducing build time
I and Bobby saw some builds failing due to long running. This fix should help that situation.
> Move new integration test to another build matrix

- storm-core/src/jvm/org/apache/storm/utils/ShellBoltMessageQueue.java
Moving taskIdsQueue inside the lock should remove the race condition.
> Fix STORM-2017

- external/flux/pom.xml
- external/storm-cassandra/pom.xml
- external/storm-hdfs/pom.xml
That setting makes some modules to apply language level for lower version of JDK.
It can be applied to 1.x-branch as well since flux refers JDK 1.6.
> Get rid of compiler plugin setting for external modules

- external/flux/flux-core/src/test/java/org/apache/storm/flux/TCKTest.java
- external/flux/flux-core/src/test/resources/configs/bad_shell_test.yaml
- external/flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/bolts/FluxShellBolt.java
- external/flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/spouts/FluxShellSpout.java
* add addComponentConfig methods to FluxShellSpout and FluxShellBolt
* address unit tests
This also addresses Parsely/streamparse#263 and Parsely/streamparse#266 
cc. @Darkless012
This can be easily backported to 1.x-branch, which means it can be included to upcoming 1.1.0 release.
> STORM-1870 Allow FluxShellBolt/Spout set custom "componentConfig" via yaml

- storm-core/src/clj/org/apache/storm/daemon/worker.clj
- storm-core/test/clj/integration/org/apache/storm/integration_test.clj
* type of element of tuple-batch is changed to AddressedTuple but not reflected to assert-can-serialize
* it only raises issue when topology.testing.always.try.serialize is true
This should also be ported back to 1.x and 1.0.x branches.
> STORM-2040 Fix bug on assert-can-serialize

- external/sql/pom.xml
- external/sql/storm-sql-external/storm-sql-redis/pom.xml
- external/sql/storm-sql-external/storm-sql-redis/src/jvm/org/apache/storm/sql/redis/RedisDataSourcesProvider.java
- external/sql/storm-sql-external/storm-sql-redis/src/resources/META-INF/services/org.apache.storm.sql.runtime.DataSourcesProvider
- external/sql/storm-sql-external/storm-sql-redis/src/test/org/apache/storm/sql/redis/TestRedisDataSourcesProvider.java
- storm-dist/binary/src/main/assembly/binary.xml
This patch is on top of [STORM-2089](https://issues.apache.org/jira/browse/STORM-2089) (#1682)
I moved JsonScheme and JsonSerializer to storm-sql-runtime since it's used from storm-sql-kafka and storm-sql-redis. In result, additional dependency (jackson-databind) for storm-sql-runtime is introduced.
Below is the example of defining Redis table:
```
CREATE EXTERNAL TABLE LARGE_ORDERS (ID INT PRIMARY KEY, TOTAL INT) LOCATION 'redis://localhost:7379' TBLPROPERTIES '{"data.type": "STRING", "data.additional.key": "addkey", "redis.timeout": "3000", "use.redis.cluster": "true"}'
```
LOCATION can be set to `redis://:[password]@[host]:[port]/[dbIdx]`.
Default mode is JedisPool (for single Redis). If you want to enable cluster mode you need to specify option "use.redis.cluster" to "true".
In …
> STORM-2099 Introduce new sql external module: storm-sql-redis

- bin/storm.py
- docs/storm-sql.md
- external/sql/README.md
- external/sql/storm-sql-core/pom.xml
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSql.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlRunner.java
* when '--explain' is specified to topology name, activate explain mode
* when explain mode is activated, it analyzes each query statement, and shows query plan
* it doesn't submit topologies
* Showing plan is provided by Calcite: it just uses that feature
As I also described to the doc, query plan for below query 
```
INSERT INTO LARGE_ORDERS SELECT ID, UNIT_PRICE * QUANTITY AS TOTAL FROM ORDERS 
WHERE UNIT_PRICE * QUANTITY > 50
```
is shown as: 
```
LogicalTableModify(table=[[LARGE_ORDERS]], operation=[INSERT], updateColumnList=[[]], flattened=[true]), id = 8
LogicalProject(ID=[$0], TOTAL=[*($1, $2)]), id = 7
LogicalFilter(condition=[>(*($1, $2), 50)]), id = 6
EnumerableTableScan(table=[[ORDERS]]), id = 5
```
FYI, $0 is column index 0 (starting from 0), and so on. Expression is printed …
> STORM-1444 Support EXPLAIN statement in StormSQL

- storm-core/src/jvm/org/apache/storm/executor/error/ReportErrorAndDie.java
* There seems to be a small bug while porting
> STORM-2142 ReportErrorAndDie runs suicide function only when InterruptedException or InterruptedIOException is thrown

- external/storm-eventhubs/pom.xml
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/bolt/EventHubBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/BinaryEventDataScheme.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventDataScheme.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventHubSpout.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventHubSpoutConfig.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/FieldConstants.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/IEventDataScheme.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/StringEventDataScheme.java
- pom.xml
Eventhub client library has few key fixes that need to be included in storm-eventhub jar.
Fixes:
1. Fix for EventHubSender may throw NullPointerException on .close()
2. EventHubsSender keeps failing to send messages once it hits ConnectionClosedException
> STORM-2127: Storm-eventhubs should use latest amqp and eventhubs-client versions

- docs/Trident-API-Overview.md
- examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentMapExample.java
- storm-core/src/jvm/org/apache/storm/trident/Stream.java
- storm-core/src/jvm/org/apache/storm/trident/operation/OperationAwareFlatMapFunction.java
- storm-core/src/jvm/org/apache/storm/trident/operation/OperationAwareMapFunction.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/FlatMapFunctionExecutor.java
- storm-core/src/jvm/org/apache/storm/trident/operation/impl/MapFunctionExecutor.java
* Introduce overloading methods of map and flatMap
* Now users can specify new output fields which replace origin fields
* Introduce OperationMapFunction and OperationFlatMapFunction
* which also extends Operation
* Trident will automatically determine this and handle properly
Also updated example code and docs page.
This change is needed for optimizing Storm SQL on Trident mode to have minimized steps.
I'll work on optimization on top of this and submit that as well.
> STORM-2072 Add map, flatMap with different outputs (T->V) in Trident

- storm-core/src/jvm/org/apache/storm/nimbus/NimbusInfo.java
- storm-core/src/jvm/org/apache/storm/utils/NimbusClient.java
* leave a log regarding leader Nimbus connection information when connecting to leader Nimbus
* also leave a log when Nimbus figures out its hostname without using storm.local.hostname
This should be also ported back to 1.x and 1.0.x.
> STORM-2145 Leave leader nimbus's hostname to log when trying to connect leader nimbus

- storm-core/src/jvm/org/apache/storm/scheduler/resource/RAS_Node.java
CPU trying to free should be ``_availCPU + amount`` rather than ``_availMemory + amount``.
> [STORM-2189] RAS_Node::freeCPU outputs incorrect info

- storm-core/src/jvm/org/apache/storm/security/auth/ThriftClient.java
- NimbusClient connections leak due to ThriftClient connection's leakage in case of errors.
> STORM 2197: NimbusClient connections leak due to ThriftClient connection's leakage in case of errors.

- storm-core/src/jvm/org/apache/storm/security/auth/AutoSSL.java
- storm-core/test/jvm/org/apache/storm/security/auth/AutoSSLTest.java
Allows you to send your SSL files with your topology and update them in a secure fashion such that they aren't stored in an intermediate on disk location. You enable it using the topology.auto-credentials config and specify org.apache.storm.security.auth.AutoSSL. The user can specify the keystore/truststore files when submitting the topology with  -c "ssl.credential.files=directory/YourFiles". The files will be serialized along with your credentials and written out into the storm workers current directory as the base filename specified (directory part is not included). You should reference them as ./filename in your topology config. 
For example:
storm jar myjar hadooptest.topologies.KafkaSpoutTopology testtopo -c "ssl.credential.files=/home/user1/kafka.server.keystore.jks,/home/user1/kafk …
> [STORM-2192] Add a new IAutoCredentials plugin to support SSL files

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/TopicKeyValueTupleBuilder.java
I am having issues with topologies that fail tuples. The kafka offsets seemed to get stuck and the kafka spout eventually halted even though the last committed offset was no where near the end of the topic. 
Here are a few unit tests that I believe replicate my situation. The last 2 are currently failing which is reflective of what I am seeing in my topologies. Let me know if I missed anything! This seems like a pretty big oversight, so I am getting the feeling that something in the test is wrong. Thanks!
I added tests for the following cases:
- All tuples being acked.
- A tuple being failed in order it was emitted
- A tuple being failed out of the order it was emitted
Update: Also Provided a fix now as well.
> STORM-2087: storm-kafka-client - tuples not always being replayed

- storm-core/src/clj/org/apache/storm/cluster.clj
Below Exception is thrown because of race condition explained in the suggested fix.
```
java.lang.NullPointerException
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301)
at org.apache.storm.daemon.nimbus$get_cluster_info$fn__11160.invoke(nimbus.clj:1397)
at org.apache.storm.daemon.nimbus$get_cluster_info.invoke(nimbus.clj:1396)
at org.apache.storm.daemon.nimbus$send_cluster_metrics_to_executors.invoke(nimbus.clj:1457)
at org.apache.storm.daemon.nimbus$fn__11415$exec_fn__3529__auto____11416$fn__11442.invoke(nimbus.clj:2257)
at org.apache.storm.timer$schedule_recurring$this__2156.invoke(timer.clj:105)
at org.apache.storm.timer$mk_timer$fn__2139$fn__2140.invoke(timer.clj:50)
at org.apache.storm.timer$mk_timer$fn__2139.invoke(timer.clj:42)
at …
```
> STORM-2205: Racecondition in getting nimbus summaries while ZK connections are reconnected.

- storm-core/src/jvm/org/apache/storm/grouping/ShuffleGrouping.java
- storm-core/test/jvm/org/apache/storm/grouping/ShuffleGroupingTest.java
This Collection.shuffle is problematic for 2 reasons.
(1) in the existing implementation, the code resets current to zero before doing the shuffle, which opens a window during which other threads may access the not-yet-reshuffled array (or the mid-shuffle array).
(2) If we call Collection.shuffle() before resetting current to zero, there is still a chance that some other thread is being slow and trying to access one of the upper indexes. E.g. choices.get(size - 3). Shuffling the array first could cause this thread to get the post-shuffle value instead of the pre-shuffle value.
> STORM-2210 - remove array shuffle from ShuffleGrouping when counter resets to zero

- examples/storm-starter/pom.xml
- external/flux/pom.xml
- external/storm-cassandra/pom.xml
- external/storm-eventhubs/pom.xml
- external/storm-hdfs/pom.xml
- external/storm-hive/pom.xml
- external/storm-jdbc/pom.xml
- external/storm-jms/examples/pom.xml
- external/storm-jms/pom.xml
- external/storm-kafka-client/pom.xml
- external/storm-kafka/pom.xml
- external/storm-metrics/pom.xml
- external/storm-solr/pom.xml
- storm-buildtools/maven-shade-clojure-transformer/pom.xml
- storm-buildtools/storm-maven-plugins/pom.xml
- storm-core/pom.xml
- storm-dist/binary/pom.xml
- storm-dist/source/pom.xml
- storm-multilang/javascript/pom.xml
- storm-multilang/python/pom.xml
- storm-multilang/ruby/pom.xml
- storm-rename-hack/pom.xml
- Remove redundant declarations cause warnings and make the build files harder to extend and maintain
> STORM-2212: Remove Redundant Declarations in Maven POM Files

- storm-core/src/jvm/org/apache/storm/spout/ShellSpout.java
* update heartbeat time before turn on flag 'waitingOnSubprocess'
I brought additional guard logic for long idle ShellSpout ([STORM-1928](https://issues.apache.org/jira/browse/STORM-1928)), which resolved the issue, but I found race condition from new logic.
Scenario:
1. lastHeartbeat is not updated more than timeout because of inactivity
1. querySubprocess() is called
1. waitingOnSubprocess is set to true
1. HeartbeatTimerTask.run() triggers faster than updating heartbeat (getting message from subprocess)
Simplest approach is updating heartbeat before set waitingOnSubprocess to true. Last heartbeat time is no longer only from subprocess, but it doesn't harm.
> STORM-2213 ShellSpout has race condition when ShellSpout is being inactive longer than heartbeat timeout

- docs/storm-sql-reference.md
Copy setting up external data sources to reference page, and add description on data sources (connectors) and formats.
@vesense Since you authored many of them, I'd be happy if you can take a look.
> STORM-2202 [Storm SQL] Document how to use supported connectors and formats

- external/storm-beam/pom.xml
- external/storm-beam/src/main/java/org/apache/storm/beam/RandomSentenceSource.java
- external/storm-beam/src/main/java/org/apache/storm/beam/StormPipelineOptions.java
- external/storm-beam/src/main/java/org/apache/storm/beam/StormRegistrar.java
- external/storm-beam/src/main/java/org/apache/storm/beam/StormRunner.java
- external/storm-beam/src/main/java/org/apache/storm/beam/StormWordCount.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/GroupByKeyTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/ParDoBoundTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/StormPipelineTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/TransformTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/TranslationContext.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/TranslatorRegistry.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/UnboundedSourceTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/WindowBoundTranslator.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/DoFnBolt.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/GroupByKeyCompleteBolt.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/GroupByKeyInitBolt.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/StormDoFnRunner.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/UnboundedSourceSpout.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/runtime/WindowBolt.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/util/DefaultSideInputReader.java
- external/storm-beam/src/main/java/org/apache/storm/beam/translation/util/DefaultStepContext.java
- external/storm-beam/src/main/java/org/apache/storm/beam/util/SerializedPipelineOptions.java
- pom.xml
This is an (very) initial pass at laying the foundation for a Beam runner for Storm. It currently only supports local mode, and is incomplete (and likely wrong in places) in terms of supporting the basic word count pipeline example.
The goal of getting this committed into a feature branch is to enable others to collaborate and contribute to the effort.
> STORM-2174: Initial Base for Storm Beam Runner

- docs/storm-sql-reference.md
- external/sql/storm-sql-runtime/pom.xml
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/datasource/socket/SocketDataSourcesProvider.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/datasource/socket/trident/SocketState.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/datasource/socket/trident/SocketStateUpdater.java
- external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/datasource/socket/trident/TridentSocketSpout.java
- external/sql/storm-sql-runtime/src/resources/META-INF/services/org.apache.storm.sql.runtime.DataSourcesProvider
- external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/runtime/datasource/socket/TestSocketDataSourceProvider.java
- Add Socket datasource (input/output) in storm-sql-runtime module
- only for test purpose, no guarantee
- scheme: 'socket'
Since Socket datasource is in storm-sql-runtime, it's registered to DataSourcesProvider by default.
So below SQL statements doesn't need any external artifacts at all and can be executed to below command:
```
./bin/storm sql apache_log_error_filtering_socket.sql apache_log_error_filtering_socket
```
```
CREATE EXTERNAL TABLE APACHE_LOGS (ID INT PRIMARY KEY, REMOTE_IP VARCHAR, REQUEST_URL VARCHAR, REQUEST_METHOD VARCHAR, STATUS VARCHAR, REQUEST_HEADER_USER_AGENT VARCHAR, TIME_RECEIVED_UTC_ISOFORMAT VARCHAR, TIME_US DOUBLE) LOCATION 'socket://localhost:8889'
CREATE EXTERNAL TABLE APACHE_ERROR_LOGS (ID INT PRIMARY KEY, REMOTE_IP VARCHAR, REQUEST_URL VARCHAR, …
```
> STORM-2170 [Storm SQL] Add built-in socket datasource to runtime

- bin/storm.py
- docs/Command-line-client.md
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/AetherUtils.java
- external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
* add '--artifactRepositories' option to pull the artifacts from other than Maven Central
In this example, we pull specific HDP version of storm-core (only for example). If we don't add HDPRepo to `--artifactRepositories`, it fails to pull the artifacts and also dependencies.
Below is the working example:
>./bin/storm sql order_filtering_mongo.sql sql-mongo --artifacts "org.apache.storm:storm-core:1.0.1.2.5.0.0-1245" --artifactRepositories "jboss-repository^http://repository.jboss.com/maven2,cloudera^https://repository.cloudera.com/artifactory/cloudera-repos/,HDPRepo^http://repo.hortonworks.com/content/groups/public/"
> STORM-2235 Introduce new option: 'add remote repositories' for dependency resolver

- docs/Structure-of-the-codebase.md
Moodified following two links in a document:
- "Thrift definition for bolts" indicates incorrect line, seems strange if open the link
- "acking framework" indicates broken link, if open redirected to root of Strom webpage
> modified incorrect and broken links

- integration-test/src/main/java/org/apache/storm/ExclamationTopology.java
The travis-ci constant build failure due to the following error:
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/travis/build/apache/storm/integration-test/src/main/java/org/apache/storm/ExclamationTopology.java:[80,11] error: cannot find symbol
```
> STORM-2245: integration-test constant compilation failure

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/jvm/org/apache/storm/daemon/nimbus/Nimbus.java
Changed the URL format for "Download full file" link under worker logs
from "download/URLENCODED(<filename>)" to "download?file=URLENCODED(<filename>)"
> STORM-2246: Logviewer download link has urlencoding on part of the URL

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/TopicKeyValueTupleBuilder.java
Backport STORM-2087 to 1.x
See https://github.com/apache/storm/pull/1679 for master version
> STORM-2087 1.x

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/BuiltinAggregateFunctions.java
Add built in support for sum function with different types in storm-sql standalone mode
> STORM-2257: Add built in support for sum function with different types

- bin/storm.py
When such configuration is not set, `confvalue` returns `nil` in 1.x branch, and `null` in master branch.
Such difference is based on whether language storm script runs: 
- for 1.x, it runs `org.apache.storm.command.config_value` which is Clojure file
- for master, it runs `org.apache.storm.command.ConfigValue` which is Java file
I accidentally changed that value from `nil` to `null` without recognized the difference between master and 1.x. 
Since it breaks all deployments on 1.x branch when client.jartransformer.class is not set, so it must be fixed before releasing.
> Fix storm.py which breaks when client.jartransformer.class is not set

- examples/storm-elasticsearch-examples/pom.xml
- examples/storm-hbase-examples/pom.xml
- examples/storm-hdfs-examples/pom.xml
- examples/storm-hive-examples/pom.xml
- examples/storm-jdbc-examples/pom.xml
- examples/storm-kafka-client-examples/pom.xml
- examples/storm-kafka-examples/pom.xml
- examples/storm-mongodb-examples/pom.xml
- examples/storm-mqtt-examples/pom.xml
- examples/storm-opentsdb-examples/pom.xml
- examples/storm-redis-examples/pom.xml
- examples/storm-solr-examples/pom.xml
- examples/storm-starter/pom.xml
- external/flux/flux-core/pom.xml
- external/flux/flux-examples/pom.xml
- external/storm-eventhubs/pom.xml
- external/storm-kafka-monitor/pom.xml
- external/storm-submit-tools/pom.xml
- storm-core/pom.xml
- storm-rename-hack/pom.xml
* Add filter option to all of shade plugin configurations
> STORM-2244 Some shaded jars doesn't exclude dependency signature files

- conf/defaults.yaml
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/security/auth/SaslTransportPlugin.java
- storm-core/src/jvm/org/apache/storm/security/auth/ThriftConnectionType.java
For DRPC we have seen during our integration tests that the connection needs to be up for more than 10 minutes so not adding any timeout for it.
> [STORM-2254] Provide Socket time out for nimbus thrift client

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/StandaloneSupervisor.java
The supervisor id is a simple UUID currently. If there are issues with the heartbeat messages from supervisor, looking at Zookeeper makes it hard to find which node is having issues. Adding the ip address to the supervisor id makes debugging these cases much simpler.
> STORM-2243: adds ip address to supervisor id

- storm-core/src/jvm/org/apache/storm/trident/topology/state/TransactionalState.java
* use JSONValue.parse() instead of JSONValue.parseWithException() in TransactionState
* this just rolls back to previous, doesn't provide better approach
Please note that this is just a quick and dirty fix given that the priority of STORM-2264 is critical.
Even after merging this, we should find better solution and apply soon. (#1844 is one of)
> STORM-2264 OpaqueTridentKafkaSpout failing after STORM-2216

- storm-core/src/jvm/org/apache/storm/ProcessSimulator.java
- storm-core/src/jvm/org/apache/storm/StormTimer.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
- storm-core/src/jvm/org/apache/storm/command/HealthCheck.java
- storm-core/src/jvm/org/apache/storm/container/cgroup/SystemOperation.java
- storm-core/src/jvm/org/apache/storm/daemon/drpc/BlockingOutstandingRequest.java
- storm-core/src/jvm/org/apache/storm/event/EventManagerImp.java
- storm-core/src/jvm/org/apache/storm/messaging/netty/StormClientHandler.java
There are several places in the code where we catch and ignore an interrupted exception (because it meant the process is shutting down).  We should also include ClosedbyInterruptException which is an IOException that can also be triggered by an interruptedexception in a few cases.
> [STORM-2271] ClosedByInterruptException should be handled in few cases and removing a confusing debug statement

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
I have added logic to wrap the negative indexes around effectively giving it a python like behaviour.
Same as pull #1866
> STORM-2279: Unable to open bolt page of storm ui

- external/sql/storm-sql-core/pom.xml
- external/sql/storm-sql-core/src/codegen/data/Parser.tdd
- pom.xml
* also update freemarker version since Calcite parser file requires that
* apply the change of Calcite parser file
Announcement will be held on tomorrow or so, but artifacts are already available in Maven.
> STORM-2280 Upgrade Calcite version to 1.11.0

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/TopicPartitionComparator.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/Timer.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/AutomaticKafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/KafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/KafkaRecordsFetchers.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/ManualKafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/KafkaPartitionReader.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/KafkaPartitionReaders.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/NamedTopicPartitionReader.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/WildcardTopicPartitionReader.java
> STORM-2236: Kafka Spout with manual partition management.

- external/storm-opentsdb/src/main/java/org/apache/storm/opentsdb/bolt/OpenTsdbBolt.java
- external/storm-opentsdb/src/main/java/org/apache/storm/opentsdb/client/OpenTsdbClient.java
* Expose OpenTsdbClient.Builder's constructor to public
* This allows Flux to initialize Builder instance which is needed for OpenTSDBBolt
* Add constructor for having single mapper instance to OpenTsdbBolt
* Flux doesn't support array of reference for now
* Also fix a bug on OpenTsdbBolt: it should refer the mapper interface for flexibility, not implemented one
Ideally it would be better for Flux to support these features, but given that it's easy fix and no harm, I decided to make this work first.
@satishd I saw you reviewed previous pull request. Could you review this again? Thanks in advance!
> STORM-2297 [storm-opentsdb] Support Flux for OpenTSDBBolt

- external/flux/README.md
- external/flux/flux-core/src/main/java/org/apache/storm/flux/FluxBuilder.java
- external/flux/flux-core/src/main/java/org/apache/storm/flux/model/BeanListReference.java
- external/flux/flux-core/src/main/java/org/apache/storm/flux/model/ConfigMethodDef.java
- external/flux/flux-core/src/main/java/org/apache/storm/flux/model/ObjectDef.java
- external/flux/flux-core/src/test/java/org/apache/storm/flux/TCKTest.java
- external/flux/flux-core/src/test/java/org/apache/storm/flux/test/TestBolt.java
- external/flux/flux-core/src/test/resources/configs/config-methods-test.yaml
Please refer [STORM-2300](https://issues.apache.org/jira/browse/STORM-2300) for more details.
* introduce reflist
* introduce BeanListReference which stores list of id of references
* handle BeanListReference properly
* modify unit test for testing reflist
This feature supports method which arguments contain List<Type>, Type[], Type... (varargs).
> STORM-2300 [Flux] support list of references

- conf/defaults.yaml
- log4j2/cluster.xml
- log4j2/worker.xml
* increase supervisor.worker.shutdown.sleep.secs to let workers kill themselves first even stuck
* disable shutdown hook for log4j2 to make sure logs are written after shutdown is started
Please note that I didn't touch JVM's shutdown hook (leaving it to sleep 1 sec and halt) given that 1 sec looks enough if there's no issue on the worker. In fact shutdown hook shouldn't take too much time.
Given that this is blocker for releasing 1.0.3 and 1.1.0, please review soon so that we can go ahead.
> STORM-2176 Workers do not shutdown cleanly and worker hooks don't run when a topology is killed

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/TopicPartitionComparator.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/Timer.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/AutomaticKafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/KafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/KafkaRecordsFetchers.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/fetcher/ManualKafkaRecordsFetcher.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/KafkaPartitionReader.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/KafkaPartitionReaders.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/NamedTopicPartitionReader.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/partition/WildcardTopicPartitionReader.java
> Storm-2236 Kafka Spout with manual partition management for 1.x-branch

- external/storm-opentsdb/src/main/java/org/apache/storm/opentsdb/bolt/OpenTsdbBolt.java
- external/storm-opentsdb/src/main/java/org/apache/storm/opentsdb/trident/OpenTsdbState.java
- external/storm-opentsdb/src/main/java/org/apache/storm/opentsdb/trident/OpenTsdbStateFactory.java
* use bounded wildcard type to fix invariant issue
I'll create pull request for 1.x separately to trigger Travis CI build for 1.x branch.
> STORM-2303 [storm-opentsdb] Fix list invariant issue for JDK 7

- external/storm-cassandra/pom.xml
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/impl/PreparedStatementBinder.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/impl/RoutingKeyGenerator.java
* Also modify the codebase since driver itself is not backward compatible with 2.1
Please refer [STORM-2301](http://issues.apache.org/jira/browse/STORM-2301) for more details. Cassandra driver 3.1.2 is compatible with Apache Cassandra 1.2, 2.0, 2.1, 2.2 and 3.0.
I tested this with Cassandra 3.0.9, but I'm beginner to Cassandra so there might be missing points in point of tuning's view. I'd really appreciated if someone who knows Cassandra reviews this pull request.
Thanks in advance!
> STORM-2301 [storm-cassandra] upgrade cassandra driver to 3.1.2

- storm-core/src/jvm/org/apache/storm/metric/ClusterMetricsConsumerExecutor.java
- storm-core/test/jvm/org/apache/storm/metric/ClusterMetricsConsumerExecutorTest.java
Please refer [STORM-2298](https://issues.apache.org/jira/browse/STORM-2298) for more details.
> STORM-2298 Don't kill Nimbus when ClusterMetricsConsumer is failed to initialize

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/test/clj/org/apache/storm/logviewer_test.clj
* consider storm.local.hostname first for creating link url in Logviewer
This should be easy to port back to 1.0.x branch.
> STORM-2325 Logviewer doesn't consider 'storm.local.hostname' (1.x)

- storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
- storm-core/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/test/clj/org/apache/storm/logviewer_test.clj
* consider storm.local.hostname first for creating link url in Logviewer
I'll create another pull request for 1.x branch. Backporting to 1.0.x branch will be easy on that pull request.
> STORM-2325 Logviewer doesn't consider 'storm.local.hostname'

- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/RexNodeToBlockStatementCompiler.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/StormSqlTypeFactoryImpl.java
- external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java
Storm-sql uses cacite's code generator. For UDAF with non standard return types, the generated code does not compile.
E.g. For an UDAF that returns a `List<T>` cacite converts the return type to SQL type "OTHER" and finally inserts a cast to Object[] in the returned code which fails to compile with "java.lang.ClassCastException: java.util.ArrayList cannot be cast to [Ljava.lang.Object;"
Use a custom type factory to return "ANY" as the type (instead of OTHER) if the java type cannot be mapped to a sql type.
> STORM-2330: Fix storm sql code generation for UDAF with non standard sql types

- storm-core/src/jvm/org/apache/storm/zookeeper/Zookeeper.java
* change the precondition for leader Nimbus
* it should have all active topology blobs locally
* it should also have all corresponding dependency blobs locally
* corresponding dependencies will be extracted from topology codes (via getBlob)
Since it tries to get blobs, probably leader listener can try to access other Nimbuses, and someone might think this is a bit dangerous.
I also have other branch which only checks all active topology blobs, not corresponding dependency blobs, so please feel free to share your opinions.
https://github.com/HeartSaVioR/storm/tree/STORM-2323-no-check-dependencies
I'll create pull request for 1.x when we select one of these branch and review and ready to merge.
> STORM-2323 Precondition for Leader Nimbus should check all topology blobs and also corresponding dependencies

- storm-core/src/clj/org/apache/storm/zookeeper.clj
- storm-core/src/jvm/org/apache/storm/zookeeper/Zookeeper.java
* change the precondition for leader Nimbus
* it should have all active topology blobs and corresponding dependencies locally
* change zookeeper.clj to use Zookeeper.leaderLatchListenerImpl
master branch: #1895
The difference between #1895 and this is due to zookeeper.clj. In 1.x branch it has both zookeeper.clj and Zookeeper.java. I don't want to make redundant efforts to get rid of zookeeper.clj, but not also want to modify both of code. So I change zookeeper.clj to refer Zookeeper's leader latch listener implementation.
@harshach 
Since you reviewed the PR for master branch, I would ask you to review this as well. Thanks in advance.
> STORM-2323 (1.x) Precondition for Leader Nimbus should check all topology blobs and also corresponding dependencies

- storm-multilang/javascript/src/main/resources/resources/storm.js
Currently emitting from JavaScript multilang bolt fails if trying to emit without anchor (ShellBolt will receive anchor list with one null item) or when trying to emit with multiple anchors (ShellBolt will receive nested array).
This fixes the handling of anchors in storm.js in a backwards compatible way.
> STORM-2331: Emitting from JavaScript should work when not anchoring

- storm-core/src/ui/public/js/visualization.js
Also fix another bug: stream table and graph box were created for each 'Show Visualization' click.
Please refer description of [STORM-2335](https://issues.apache.org/jira/browse/STORM-2335) for more details.
This can be ported back to 1.x and 1.0.x branches via cherry-picking.
> STORM-2335 Fix broken Topology visualization with empty ':transferred' in executor stats

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java
* this patch gets rid of alive non-daemon threads which prevent JVM process shutdown
This patch can be ported back to 1.x and 1.0.x branch via cherry-picking.
> STORM-2336 Close Localizer and AsyncLocalizer when supervisor is shutting down

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
- storm-core/src/jvm/org/apache/storm/blobstore/KeySequenceNumber.java
- storm-core/src/jvm/org/apache/storm/blobstore/LocalFsBlobStore.java
* If NoNodeException is thrown in getKeySequenceNumber, treat it as KeyNotFoundException
* Change callers to handle KeyNotFoundException accordingly
This can be easily cherry picked to 1.0.x branch.
For master branch: #1904
> STORM-2321 Handle blobstore zk key deletion in KeySequenceNumber (1.x)

- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
- storm-core/src/jvm/org/apache/storm/blobstore/KeySequenceNumber.java
- storm-core/src/jvm/org/apache/storm/blobstore/LocalFsBlobStore.java
- storm-core/src/jvm/org/apache/storm/daemon/nimbus/Nimbus.java
* If NoNodeException is thrown in getKeySequenceNumber, treat it as KeyNotFoundException
* Change callers to handle KeyNotFoundException accordingly
Race condition with a deletion is rare case, so instead of adding some locks to prevent race condition, it just allows error and handle it accordingly.
For 1.x branch: #1905
> STORM-2321 Handle blobstore zk key deletion in KeySequenceNumber

- docs/storm-sql.md
- external/sql/README.md
- external/sql/storm-sql-core/src/codegen/data/Parser.tdd
- external/sql/storm-sql-core/src/codegen/includes/parserImpls.ftl
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/calcite/ParallelStreamableTable.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/CompilerUtil.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/SqlCreateTable.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/planner/trident/rel/TridentStreamScanRel.java
- external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/planner/trident/rules/TridentScanRule.java
NOTE: This is on top of STORM-1446 (#1736). I can make a patch without STORM-1446 but it makes me putting same effort twice so didn't do it. Please let me know if we want to have this patch based on current master.
- Add 'PARALLELISM' to table definition
- default value is 1
- Set parallelism to new stream while creating stream with scan
- downstream operators will also have same parallelism unless repartitioned
- not apply parallelism to output table since it can trigger repartition
Below is the screenshot which runs SQL statement:
```
CREATE EXTERNAL TABLE APACHE_LOGS (id INT PRIMARY KEY, remote_ip VARCHAR, request_url VARCHAR, request_method VARCHAR, status VARCHAR, request_header_user_agent VARCHAR, time_received_utc_isoformat VARCHAR, time_us DOUBLE) LOCATION …
```
> STORM-1443 [Storm SQL] Support customizing parallelism in StormSQL

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Container.java
- storm-core/test/jvm/org/apache/storm/daemon/supervisor/ContainerTest.java
Skips creating symlink to the resources directory if there is no target resources directory. 
This avoids failure in setup_permissions() function in worker_launcher.c
> STORM 2324 - Fix toplogy deployment failure if resources directory is missing in topology jar

- examples/storm-elasticsearch-examples/pom.xml
- examples/storm-hbase-examples/pom.xml
- examples/storm-hdfs-examples/pom.xml
- examples/storm-hive-examples/pom.xml
- examples/storm-jdbc-examples/pom.xml
- examples/storm-kafka-client-examples/pom.xml
- examples/storm-kafka-examples/pom.xml
- examples/storm-mongodb-examples/pom.xml
- examples/storm-mqtt-examples/pom.xml
- examples/storm-opentsdb-examples/pom.xml
- examples/storm-redis-examples/pom.xml
- examples/storm-solr-examples/pom.xml
- examples/storm-starter/pom.xml
- external/flux/flux-core/pom.xml
- external/flux/flux-examples/pom.xml
- external/storm-eventhubs/pom.xml
- external/storm-kafka-monitor/pom.xml
- external/storm-submit-tools/pom.xml
- storm-core/pom.xml
- storm-rename-hack/pom.xml
* Add filter option to all of shade plugin configurations
PR for master branch (#1834) is already merged.
@harshach Could you review this as well? Thanks!
> STORM-2244 Some shaded jars doesn't exclude dependency signature files (1.x)

- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkCoordinator.java
- external/storm-kafka/src/test/org/apache/storm/kafka/ZkCoordinatorTest.java
Current behavior of Kafka spout emits duplicate tuples whenever Kafka topic leader's change.
In case of exception caused by leader changes, PartitionManagers are simply recreated losing the state about which tuples were already emitted and new PartitionManager re-emits them again.
This is fine as at-least-once is fulfilled, but still it would be better to not emit duplicate data if possible.
Moreover this could be easily avoided by moving the state related to emitted tuples from old PartitionManager to new one.
> STORM-2296 Kafka spout no dup on leader changes,  1.x-branch

- examples/storm-kafka-client-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaClientWordCountNamedTopics.java
- examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/LocalSubmitter.java
- examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaConsumerTopology.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutBatchMetadata.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutManager.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaque.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaqueCoordinator.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTopicPartition.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTopicPartitionRegistry.java
- Assign topic partitions to tasks running the instance of Kafka consumer that has assigned the same list of topic partitions
- Improve logging
- Minor code refactoring
> STORM-2281: Running Multiple Kafka Spouts (Trident) Throws Illegal State Exception

- external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
Kafka spout should consume from latest when ZK offset bigger than partition's latest offset[ an TopicOffsetOutOfRangeException thrown out ], especially when Kafka topic change it's leader and some data lost, if we consume from earliest offset, much meaningless duplicate records will be re-consumed. So, we should consume from latest offset instead.
This is the jira task: [STORM-2270](https://issues.apache.org/jira/browse/STORM-2270)
> STORM-2270 Kafka spout should consume from latest when ZK partition commit offset bigger than the latest offset

- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java
* since callers are able to handle KeyNotFoundException but not NoNodeException
This patch is addressing missed spot on [STORM-2321](https://issues.apache.org/jira/browse/STORM-2321).
It doesn't mean patch for STORM-2321 is broken (just found a missing case), so it doesn't hurt the release vote for 1.0.3 RC2.
> Convert NoNodeException to KeyNotFoundException in getNimbodesWithLatestSequenceNumberOfBlob

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/Timer.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/ByTopicRecordTranslatorTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/DefaultRecordTranslatorTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainNamedTopics.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainWildcardTopics.java
- pom.xml
- storm-core/src/jvm/org/apache/storm/utils/Time.java
Making these changes based on a discussion here https://github.com/apache/storm/pull/1826 and https://github.com/apache/storm/pull/1825 about the spout getting a bit large.
This PR makes the following changes:
* OffsetEntry was moved into a new class and renamed OffsetManager
* OffsetManager.commit now returns numCommittedOffsets, so it doesn't have to refer to a KafkaSpout internal variable.
* KafkaSpout.commitOffsetsForAckedTuples no longer iterates over acked twice. The second iteration was used to commit offsets to OffsetEntries, but we may as well use nextCommitOffsets for that iteration, since those were the offsets committed to Kafka. This also saves us a null check in OffsetManager.commit.
* OffsetManager.commit no longer checks if the parameter is null. It should no longer be …
> STORM-2250: Kafka Spout Refactoring to Increase Modularity and Testability

- storm-core/src/clj/org/apache/storm/pacemaker/pacemaker.clj
- storm-core/src/clj/org/apache/storm/pacemaker/pacemaker_state_factory.clj
Paths are not deleted correctly. Pacemaker's delete-path operates by matching a prefix against all the keys in the map.
The issue here is that the prefix is given a '/' on the end, but keys don't have a trailing '/' if there is no 'subkey'.
i.e. delete path `/foo/bar/baz/` doesn't match the key `/foo/bar/baz`
The path has to have the trailing '/' so that delete path `/foo/bar/baz` doesn't also delete `/foo/bar/bazoo`
The solution here is to tack on a '/' to every key when checking against the prefix.
We also want to send the delete command to every pacemaker server rather than just the normal write client.
> STORM-2372: Pacemaker client doesn't clean up heartbeats properly. (1.x)

- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/common/HikariCPConnectionProvider.java
…ilures
Minor addition to expose JDBC connection string through logging in Hikari CP implementation.  For debugability purposes only.
> STORM-2381: Add logging of JDBC connection string in storm-jdbc integration for debugging failures

- storm-core/src/jvm/org/apache/storm/bolt/JoinBolt.java
* replace String.join with Guava Joiner to keep compatible against JDK 7
I'm just fixing it from 1.x branch since storm-core on master branch and 1.x branch are already diverged.
> STORM-2388 JoinBolt breaks compilation against JDK 7

- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
Please refer [STORM-2386](https://issues.apache.org/jira/browse/STORM-2386) for more details.
This is against master branch, 
* 1.x-branch: #1975
> STORM-2386 Fail-back Blob deletion also fails in BlobSynchronizer.syncBlobs

- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
Please refer [STORM-2386](https://issues.apache.org/jira/browse/STORM-2386) for more details.
I'll submit patches for master soon. If we need to port back to 1.0.x as well, it should be easy to cherry-pick.
> STORM-2386 Fail-back Blob deletion also fails in BlobSynchronizer.syncBlobs (1.x)

- bin/storm.cmd
use org.apache.storm.daemon.supervisor.Supervisor instead
Signed-off-by: alexlehm <alexlehm@gmail.com>
> STORM-2395: storm.cmd supervisor calls the wrong class name

- storm-core/src/jvm/org/apache/storm/executor/error/ReportErrorAndDie.java
This is a translation of the fix recommended by @revans2 here:
https://github.com/apache/storm/pull/1767
> [STORM-2194]  Stop ignoring socket timeout error from executor

- storm-core/src/jvm/org/apache/storm/utils/Utils.java
As described in [JIRA](https://issues.apache.org/jira/browse/STORM-2396) the interrupted flag is not set back after catching InterruptedException and wrapping it into a RuntimeException so any code dependent on checking the interrupted status will not work properly in case the RuntimeException doesn't make it up the stack.
> STORM-2396: setting interrupted status back before throwing a RuntimeException

- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/BaseCassandraBolt.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/BatchCassandraWriterBolt.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/CassandraWriterBolt.java
- external/storm-druid/src/main/java/org/apache/storm/druid/bolt/DruidBeamBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/AbstractEsBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsIndexBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsLookupBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsPercolateBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/bolt/EventHubBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/samples/bolt/GlobalCountBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/samples/bolt/PartialCountBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/AbstractJdbcBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcInsertBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcLookupBolt.java
- external/storm-jms/core/src/main/java/org/apache/storm/jms/bolt/JmsBolt.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/bolt/KafkaBolt.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/bolt/KafkaBolt.java
- external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java
- external/storm-mqtt/core/src/main/java/org/apache/storm/mqtt/bolt/MqttBolt.java
- external/storm-pmml/src/main/java/org/apache/storm/pmml/PMMLPredictorBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/AbstractRedisBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisFilterBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisLookupBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisStoreBolt.java
- external/storm-solr/src/main/java/org/apache/storm/solr/bolt/SolrUpdateBolt.java
- storm-core/src/jvm/org/apache/storm/topology/base/BaseTickTupleAwareRichBolt.java
* also remove ack for tick tuples since it's not necessary
I also fixed some mixing indentations. We should introduce code style soon.
For master branch: #1978
> STORM-2387 Handle tick tuples properly for Bolts in external modules (1.x)

- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/BaseCassandraBolt.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/BatchCassandraWriterBolt.java
- external/storm-cassandra/src/main/java/org/apache/storm/cassandra/bolt/CassandraWriterBolt.java
- external/storm-druid/src/main/java/org/apache/storm/druid/bolt/DruidBeamBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/AbstractEsBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsIndexBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsLookupBolt.java
- external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsPercolateBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/bolt/EventHubBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/samples/bolt/GlobalCountBolt.java
- external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/samples/bolt/PartialCountBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/AbstractJdbcBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcInsertBolt.java
- external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/JdbcLookupBolt.java
- external/storm-jms/core/src/main/java/org/apache/storm/jms/bolt/JmsBolt.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/bolt/KafkaBolt.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/bolt/KafkaBolt.java
- external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoLookupBolt.java
- external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java
- external/storm-mqtt/core/src/main/java/org/apache/storm/mqtt/bolt/MqttBolt.java
- external/storm-pmml/src/main/java/org/apache/storm/pmml/PMMLPredictorBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/AbstractRedisBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisFilterBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisLookupBolt.java
- external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisStoreBolt.java
- external/storm-solr/src/main/java/org/apache/storm/solr/bolt/SolrUpdateBolt.java
- storm-core/src/jvm/org/apache/storm/topology/base/BaseTickTupleAwareRichBolt.java
* also remove ack for tick tuples since it's not necessary
I also fixed some mixing indentations. We should introduce code style soon.
For 1.x branch: #1979
> STORM-2387 Handle tick tuples properly for Bolts in external modules

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/KafkaUnit.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/KafkaUnitRule.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
This pr is for testing kafka-clients:0.10.1.1 on storm-kafka-client. I replace the kafka-unit by kafka_2.11 and kafka-clients, and add TestRule as suggested by @srdo.
> STORM-2353: Replace kafka-unit by kafka_2.11 and kafka-clients to test kafka-clients:0.10.1.1

- external/storm-kafka/src/test/org/apache/storm/kafka/bolt/KafkaBoltTest.java
* More detail: [STORM-2403](http://issues.apache.org/jira/browse/STORM-2403)
* This bug is introduced from [STORM-2387](http://issues.apache.org/jira/browse/STORM-2387)
**NOTE: It should be easy to cheery-pick to 1.x / 1.0.x branches, and we must cherry-pick to those branches since STORM-2387 is merged to those branches.**
> STORM-2403 Fix KafkaBolt test failure: tick tuple should not be acked

- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/KafkaUnit.java
The build will fail if mvn clean install -Dstorm.kafka.client.version=0.10.2.0 because of https://issues.apache.org/jira/browse/KAFKA-2247.
1. remove wildcard imports
2. use kafka.utils.MockTime instead of kafka.utils.Time
tested:
mvn clean install -Dstorm.kafka.client.version=0.10.0.0
mvn clean install -Dstorm.kafka.client.version=0.10.1.0
mvn clean install -Dstorm.kafka.client.version=0.10.1.1
mvn clean install -Dstorm.kafka.client.version=0.10.2.0
> STORM-2408: build failed if storm.kafka.client.version = 0.10.2.0

- storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
- storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java
- storm-core/src/jvm/org/apache/storm/blobstore/BlobSynchronizer.java
While using local FS blob store, nimbus goes into a state where it indefinitely waits for max replication (with max replication wait time set to -1). At this time its also observed that the nimbus that received the topology submission is no longer the leader.
While waiting for max replication, nimbus can also do the `isLeader` check and fail the topology submission if its no longer the leader.
Also added some debug logs to better troubleshoot the race conditions when it happens.
> STORM-2412: Nimbus isLeader check while waiting for max replication

- storm-core/src/jvm/org/apache/storm/daemon/supervisor/LocalContainer.java
This is a clean cherry-pick back to 1.x and 1.0.x too.
> STORM-2038:  No symlinks for local cluster

- conf/defaults.yaml
- docs/windows-users-guide.md
- storm-core/src/jvm/org/apache/storm/Config.java
- storm-core/src/jvm/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-core/src/jvm/org/apache/storm/daemon/supervisor/AdvancedFSOps.java
- storm-core/src/jvm/org/apache/storm/daemon/supervisor/Container.java
- storm-core/src/jvm/org/apache/storm/localizer/AsyncLocalizer.java
- storm-core/src/jvm/org/apache/storm/localizer/Localizer.java
This is built on top of #1972 but I have not ported it to other branches yet, so I would like to keep the two separate.  Once reviews are done on this version I will port it to 1.x and 1.0.x (as it apparently is a real pain for windows users)
> STORM-2038: Disable symlinks with a config option

- storm-core/src/jvm/org/apache/storm/trident/planner/SubtopologyBolt.java
For now I only plan to do this for master.  If someone else runs into this issue I am happy to backport it to other versions of storm.
> STORM-2422: Reduce the size of a serialized trident topology

- docs/Joins.md
- examples/storm-starter/src/jvm/org/apache/storm/starter/JoinBoltExample.java
- storm-core/src/jvm/org/apache/storm/bolt/JoinBolt.java
- storm-core/test/jvm/org/apache/storm/bolt/TestJoinBolt.java
Default anchoring will anchor each emitted tuple to every tuple in current window. This requires a very large numbers of ACKs from any downstream bolt. If topology.debug is enabled, it also worsens the load on the system significantly.
Letting the topo run in this mode (in particular with max.spout.pending disabled), could lead to the worker running out of memory and crashing.
*Fix* Join Bolt should avoid using default window anchoring, and explicitly anchor each emitted tuple with the exact matching tuples form each inputs streams. This reduces the complexity of the tuple trees and consequently the reduces burden on the ACKing & messaging subsystems.
Also added additional documentation.
> STORM-2423 - Join Bolt should use explicit instead of default window anchoring for emitted tuples

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutMessageId.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/RecordTranslator.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java
- Created config property to make emit null tuples configurable
- Ack directly null tuples that are not emitted
> STORM-2409: Storm-Kafka-Client KafkaSpout Support for Failed and NullTuples

- pom.xml
Add versions for maven-javadoc-plugin and maven-surefire-report-plugin to the parent pom.xml.
> STORM-2058: Fix Maven warnings about missing reporting.plugins.plugin.version

- docs/Setting-up-a-Storm-cluster.md
jekyll needs a newline before the code quotes, while e.g. the markdown preview in atom and the github md renderer doesn't
> fix md formatting for windows storm.local.dir example 

- docs/distcache-blobstore.md
[https://issues.apache.org/jira/browse/STORM-2431?filter=-2](url)
The default blobstore.dir is storm.local.dir/blobs which is different from distcache-blobstore.md.You can see the pictures below.The default blobstore.dir is set to storm.local.dir/blobs.
> [STORM-2431]the default blobstore.dir is storm.local.dir/blobs which is different from distcache-blobstore.md

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
[https://issues.apache.org/jira/browse/STORM-2454](url)
The configuration which named "enable.auto.commit" has been set to false when we create a instance of KafkaSpoutConfig via the method of "setDefaultsAndGetKafkaProps". And the logic of "isConsumerAutoCommitMode" makes the returned value is "false",but the annotation is "true".
> [STORM-2454] the default returned value of this method which named "isConsumerAutoCommitMode" in KafkaSpoutConfig.java should be false

- docs/storm-hbase.md
- external/storm-hbase/README.md
[https://issues.apache.org/jira/browse/STORM-2457](url)
the directory of storm-hbase's examples is incorrect in READEME.md, and the example in the document should be consistent with "examples/storm-hbase-examples/src/main/java/topology/PersistentWordCount.java" as this example having added "hbase.rootdir" with the method which named "withConfigKey". And storm-hbase.md should be consistent with README.md.
> [STORM-2457] update and modify storm/hbase/README.md and storm-hbase.md

- docs/storm-hdfs.md
- external/storm-hdfs/README.md
[https://issues.apache.org/jira/browse/STORM-2461](url)
"reqd" should be modified to "required" in storm-hdfs's README.md. And storm-hdfs.md is out of date,for example,the version of hadoop-client and hadoop-hdfs should be 2.6.1 and there isn't usage of HDFSSpout. So,storm-hdfs.md should be updated to be as same as storm-hdfs's README.md.
> [STORM-2461] modify storm-hdfs's READEME.md and update storm-hdfs.md

- storm-server/src/test/java/org/apache/storm/daemon/drpc/DRPCTest.java
This is the hot fix for travis-ci build failure.
error info:
```
classname: org.apache.storm.daemon.drpc.DRPCTest / testname: testDequeueAfterTimeout
java.lang.AssertionError: null
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.apache.storm.daemon.drpc.DRPCTest.testDequeueAfterTimeout(DRPCTest.java:129)
```
> STORM-2463: fix DRPCTest.testDequeueAfterTimeout test failure

- docs/storm-redis.md
- external/storm-redis/README.md
[https://issues.apache.org/jira/browse/STORM-2465](url)
There is a lack of "$" in the module of storm-redis's READEME.md which named "How do I use it".And storm-redis.md is out of date,for example,there is a new class named "RedisFilterBolt" which didn't be displayed in storm-redis.md. So,storm-redis.md should be updated to be as same as storm-redis's README.md.
> [STORM-2465] modify storm-redis's READEME.md and update storm-redis.md

- integration-test/pom.xml
This is the hot fix for integration-test dependencies issue
* add storm-server. since __the ExclamationTopology depends on LocalCluster__
* remove unused dependencies: selenium-firefox-driver, selenium-support, storm-solr, storm-starter, storm-hdfs
> STORM-2469: fix integration-test dependencies issue

- external/storm-kafka/src/jvm/org/apache/storm/kafka/StringScheme.java
We had the case that this broke encoding for us because it used the default
system locale. Given the fact that this code uses an explicit encoding for the
other case and that it evolved from something that always used an explicit
encoding I believe this is more correct.
> [STORM-2467] Use explicit charset when decoding from array backed buffer

- docs/State-checkpointing.md
- docs/Stream-API.md
- docs/Trident-API-Overview.md
- docs/storm-cassandra.md
- docs/storm-jdbc.md
- docs/storm-kafka-client.md
- docs/storm-kafka.md
- docs/storm-kinesis.md
- docs/storm-redis.md
- docs/storm-solr.md
Code blocks should always follow an empty line; otherwise, jekyll will
fail to properly format the code block. Also, github's code fencing (with triple backticks) does not work in the middle of item lists.
> Fix documentation code formatting

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
Here is why this bug happens: when ack is disabled, the ack method of spout will be called in the emit method, and that's why emitted message ids can not be found and moved to acked tuples.
> STORM-2315 Storm kafka client does not commit offsets when ack is disabled.

- docs/Storm-Scheduler.md
[https://issues.apache.org/jira/browse/STORM-2476](url)
The path for 4 kinds of built-in schedulers in Storm-Scheduler.md is wrong.And the link doesn't work.
> [STORM-2476] the path for 4 kinds of built-in schedulers in Storm-Scheduler.md is wrong

- docs/SECURITY.md
The UI user Must be HTTP. Otherwise, the UI page can not be authorized
> STORM-2488: The UI user Must be HTTP

- storm-client/pom.xml
@revans2 : typo I found while poking around and trying to understand the shaded kryo jar, as per [our discussion in STORM-2191](https://issues.apache.org/jira/browse/STORM-2191?focusedCommentId=15984124&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15984124).
> fix typo in storm-client pom file: kyro -> kryo

- bin/storm
@harshach &/or @hmcl &/or @revans2 &/or @HeartSaVioR : can you please review this when you get a chance?  I spoke to Hugo and Harsha about this last week.  I put a bunch of details into [STORM-2486](https://issues.apache.org/jira/browse/STORM-2486).  This should also be backported into every active branch.
> [STORM-2486] Prevent cd from printing target directory to avoid breaking classpath

- storm-multilang/javascript/src/main/resources/resources/storm.js
in case people have uses for it, like in unit testing for example (that's what I was using it for)
> expose Tuple for node.js 

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryService.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
This builds on https://github.com/apache/storm/pull/1832, sorry for the mixed diff
This makes the spout emit failed tuples even when numUncommittedOffsets has reached maxUncommittedOffsets. Previously the spout would fail to progress in that case. I haven't really been able to enforce maxUncommittedOffsets strictly without having to request extra messages from Kafka and throwing them away. The consumer doesn't allow the spout to limit how many tuples it requests dynamically, and I'd prefer that the spout doesn't truncate the list of records it receives.
Instead, maxUncommittedOffsets is now a soft cap on the number of tuples that can be emitted before some must be committed. In some cases (e.g. 10 partitions with 1 failed message emitted on each), the spout will exceed the limit. It …
> STORM-2343: New Kafka spout can stop emitting tuples if more than maxUncommittedOffsets tuples fail at once

- bin/storm.py
- docs/Classpath-handling.md
- docs/Command-line-client.md
- docs/Running-topologies-on-a-production-cluster.md
- docs/Setting-up-a-Storm-cluster.md
- docs/index.md
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java
Instead of fully enumerating all JARs in the lib directories, we just use
a Java classpath wildcard to allow the JVM to autodiscover all JARs in the
classpath.  This affects both the Worker and LogWriter processes, as well
as Storm daemons such as the Nimbus, UI, Logviewer, and Supervisor.
This change results in shorter commands, so that you can actually see
the full content of the Worker command in `ps` output on Linux.
Prior to this change Worker commands were easily longer than 4096 bytes,
which is the default Linux kernel limit for commands being recorded into
the process table.  Longer commands get truncated, though they do get
executed.
An example of the change in Worker classpath length can be seen here:
Before:
```
-cp STORM_DIR/lib-worker/asm-5.0.3.jar:STORM_DIR/lib-worker/carboni …
```
> [STORM-2191] shorten classpaths by using wildcards

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
[STORM-2505] Maintaining a emitted set in OffsetManager to handle the voids in the topic
[STORM-2505] Handling NPE in Boxed Long to primitive type comparison
[STORM-2505] Rephrased the log message when a non contiguous offset is acked by the spout
[STORM-2505] Updated comment
[STORM-2505] Renamed the methods ack/emit to addToAckMsgs and addToEmitMsgs in OffsetManager
> [STORM-2505] Spout to support topic compaction [1.x-branch]

- .travis.yml
- examples/storm-starter/src/jvm/org/apache/storm/starter/ReachTopology.java
- examples/storm-starter/src/jvm/org/apache/storm/starter/TransactionalGlobalCount.java
- external/storm-eventhubs/pom.xml
- external/storm-hbase/pom.xml
- external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java
- external/storm-hdfs/pom.xml
- external/storm-jms/src/test/java/org/apache/storm/jms/spout/JmsSpoutTest.java
- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTransactional.java
- external/storm-redis/pom.xml
- storm-client/src/jvm/org/apache/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java
- storm-client/src/jvm/org/apache/storm/stats/StatsUtil.java
- storm-client/src/jvm/org/apache/storm/testing/BatchNumberList.java
- storm-client/src/jvm/org/apache/storm/testing/CountingBatchBolt.java
- storm-client/src/jvm/org/apache/storm/testing/KeyedCountingBatchBolt.java
- storm-client/src/jvm/org/apache/storm/testing/KeyedSummingBatchBolt.java
- storm-client/src/jvm/org/apache/storm/trident/operation/impl/IdentityMultiReducer.java
- storm-client/src/jvm/org/apache/storm/trident/spout/BatchSpoutExecutor.java
- storm-client/src/jvm/org/apache/storm/trident/spout/RichSpoutBatchExecutor.java
- storm-client/src/jvm/org/apache/storm/trident/testing/FeederBatchSpout.java
- storm-client/src/jvm/org/apache/storm/trident/testing/FeederCommitterBatchSpout.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/test/jvm/org/apache/storm/TestConfigValidate.java
- storm-client/test/jvm/org/apache/storm/security/auth/AuthUtilsTest.java
- storm-client/test/jvm/org/apache/storm/security/auth/AuthUtilsTestMock.java
- storm-server/src/main/java/org/apache/storm/daemon/drpc/DRPC.java
- transform.sh
Because this touches so much of the code to avoid having to constantly upmerge I have a script that will transform most of the code automatically. transform.sh . I don't plan on checking it in.  If everyone is OK with the change I will run the script and just check those changes in.  The other changes and small updates to make the result of running the script not produce compile errors.  Overall this drops more than 800 warnings from the code base (according to eclipse).
> STORM-2477: Add generics to Config types

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutMessageId.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryService.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/test/KafkaSpoutTopologyMainNamedTopics.java
- external/storm-kafka-client/src/test/resources/log4j2.xml
Sorry about mixed diff, but https://github.com/apache/storm/pull/1924 had some changes I needed. Hopefully that one gets merged soon so the diff here is nicer. Only change from the other branch is https://github.com/srdo/storm/commit/86c39a349cdb053e1949ed1739feef0f6b2bcaf7
https://issues.apache.org/jira/browse/STORM-2413
> STORM-2413: Make new Kafka spout respect tuple retry limits

- examples/storm-starter/src/jvm/org/apache/storm/starter/TransactionalWords.java
- storm-client/src/jvm/org/apache/storm/container/cgroup/SubSystem.java
- storm-client/src/jvm/org/apache/storm/scheduler/SchedulerAssignmentImpl.java
- storm-client/src/jvm/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
- storm-client/src/jvm/org/apache/storm/trident/windowing/StoreBasedTridentWindowManager.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
- storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
This PR addresses STORM-2503, by fixing a number of alerts found by lgtm.com at https://lgtm.com/projects/g/apache/storm/alerts/ that indicate genuine bugs in comparison operations in the Storm code.
These rules are:
- Equals on incomparable types (due to typos, fixed here)
- Hashed value without hashCode definition
- Inconsistent equals and hashCode (together with the previous item, this indicates some missing hashCode implementations, which have been added here)
- Comparison of identical values (indicating a comparator logic typo in `DefaultResourceAwareStrategy`, which is fixed here along with a fix to the overall comparator logic, to consider components with fewer connections as being smaller)
- Useless comparison test (indicating a variable name typo, which is fixed here)
- …
> STORM-2503: Fix lgtm.com alerts on equality and comparison operations.

- storm-client/src/jvm/org/apache/storm/Config.java
- storm-client/src/jvm/org/apache/storm/StormSubmitter.java
- storm-client/src/jvm/org/apache/storm/daemon/StormCommon.java
- storm-client/src/jvm/org/apache/storm/generated/StormTopology.java
- storm-client/src/jvm/org/apache/storm/generated/TopologyInfo.java
- storm-client/src/jvm/org/apache/storm/generated/TopologyPageInfo.java
- storm-client/src/jvm/org/apache/storm/generated/TopologySummary.java
- storm-client/src/jvm/org/apache/storm/topology/TopologyBuilder.java
- storm-client/src/jvm/org/apache/storm/utils/LocalState.java
- storm-client/src/jvm/org/apache/storm/utils/SimpleVersion.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-client/src/jvm/org/apache/storm/utils/VersionInfo.java
- storm-client/src/py/storm/ttypes.py
- storm-client/src/storm.thrift
- storm-core/src/clj/org/apache/storm/ui/core.clj
- storm-core/src/ui/public/templates/index-page-template.html
- storm-core/src/ui/public/templates/topology-page-template.html
- storm-core/test/clj/org/apache/storm/nimbus_test.clj
- storm-server/src/main/java/org/apache/storm/LocalCluster.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
- storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java
- storm-server/src/test/java/org/apache/storm/daemon/supervisor/BasicContainerTest.java
This is based off of the local mode patch #2047 once it goes in I'll rebase it again, so it is simpler to see the changes.  All of the changes are in the last commit 7d1f346.
I'll be putting up pull requests to the other branches so that they can submit topologies with a version in them.
I have tested this with workers on the latest versions of branch-1.x, branch-1.0.x, and branch-0.10.x.
I am not totally sure how useful this will be for other groups so I would like feedback if we want the UI changes to stay or not, and how much documentation should I add.  Right now the docs are only in Config.java
> STORM-2448: Add in Storm and JDK versions when submitting a topology

- docs/storm-kafka.md
- external/storm-kafka/src/jvm/org/apache/storm/kafka/SpoutConfig.java
Add the ability to set the Kafka client.id property to storm-kafka and storm-kafka-client (https://issues.apache.org/jira/browse/STORM-2524).
storm-kafka example:
```
SpoutConfig spoutConfig = new SpoutConfig(
brokers,
topicConfs.topic,
+		"client_id-" + confs.consumerGroupId + "-" + topicConfs.topic,
"/consumers",
confs.consumerGroupId + "-" + topicConfs.topic
);
```
storm-kafka-client example:
```
KafkaSpoutConfig<String,String> kafkaSpoutConfig = KafkaSpoutConfig.builder(KAFKA_LOCAL_BROKER, TOPIC)
.setGroupId(confs.consumerGroupId + "-" + topicConfs.topic)
+		.setClientId("client_id-" + confs.consumerGroupId + "-" + topicConfs.topic)
.build();
```
> Add the option to set client.id to storm-kafka

- storm-client/src/jvm/org/apache/storm/generated/TopologyPageInfo.java
- storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
I regenerated all of the generated thrift files to be sure I hadn't mistakenly changed anything else.  Then I updated the one call to those APIs in the java code.
> STORM-2526: Revert changes mistakenly made to generated files

- pom.xml
Because of output log size policy for Travis CI, we can't print violation report to the console. Instead of that, we can just leave violation to the file. 
This would help to track and fix checkstyle violations.
> Leave checkstyle violation to each module's target directory

- external/storm-autocreds/pom.xml
* master patch: #2145
> dependency tree for 'storm-autocreds':
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ storm-autocreds ---
[INFO] org.apache.storm:storm-autocreds:jar:1.1.1-SNAPSHOT
[INFO] +- org.apache.storm:storm-core:jar:1.1.1-SNAPSHOT:provided
[INFO] |  +- com.esotericsoftware:kryo:jar:3.0.3:provided
[INFO] |  |  +- com.esotericsoftware:reflectasm:jar:1.10.1:provided
[INFO] |  |  |  \- org.ow2.asm:asm:jar:5.0.3:provided
[INFO] |  |  +- com.esotericsoftware:minlog:jar:1.3.0:provided
[INFO] |  |  \- org.objenesis:objenesis:jar:2.1:provided
[INFO] |  +- org.clojure:clojure:jar:1.7.0:provided
[INFO] |  +- ring-cors:ring-cors:jar:0.1.5:provided
[INFO] |  +- com.lmax:disruptor:jar:3.3.2:provided
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.8:provided
[INFO] …
```
> STORM-2536 excludes jersey 1.x from storm-autocreds (1.x)

- external/storm-autocreds/pom.xml
* 1.x patch: #2144 
depdendency tree:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ storm-autocreds ---
[INFO] org.apache.storm:storm-autocreds:jar:2.0.0-SNAPSHOT
[INFO] +- org.apache.storm:storm-client:jar:2.0.0-SNAPSHOT:provided
[INFO] |  +- uk.org.lidalia:sysout-over-slf4j:jar:1.0.2:provided
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.21:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.8:provided
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.8:provided
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.8:provided
[INFO] |  +- com.google.guava:guava:jar:16.0.1:compile
[INFO] |  +- org.apache.thrift:libthrift:jar:0.9.3:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
[INFO] |  +- …
```
> STORM-2536 excludes jersey 1.x from storm-autocreds

- storm-client/src/jvm/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java
This PR ensures consistent comparator ordering in the above class, using descending order in both `sortNeighbors` and `sortComponents` and adding comments to indicate descending order.
As requested by @jerrypeng on https://github.com/apache/storm/pull/2100.
@revans2
> STORM-2503: Restore comparator logic in `DefaultResourceAwareStrategy`.

- storm-client/src/jvm/org/apache/storm/messaging/IConnection.java
- storm-client/src/jvm/org/apache/storm/messaging/IContext.java
- storm-client/src/jvm/org/apache/storm/messaging/local/Context.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Client.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Context.java
- storm-client/src/jvm/org/apache/storm/messaging/netty/Server.java
- storm-client/src/jvm/org/apache/storm/utils/Utils.java
- storm-core/test/clj/org/apache/storm/messaging/netty_unit_test.clj
- storm-core/test/clj/org/apache/storm/security/auth/nimbus_auth_test.clj
- storm-server/src/main/java/org/apache/storm/LocalCluster.java
Followup for https://github.com/apache/storm/pull/2075
The only remaining uses of Utils.getAvailablePort are tests in netty_unit_tests.clj that are starting a client before the server it connects to. I think getAvailablePort is the best we can do in those tests.
> STORM-2532: Remove uses of Utils.getAvailablePort where possible

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryService.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaque.java
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTransactional.java
Most of the remaining violations are a couple of methods missing javadocs in the Trident code, which I don't feel familiar enough with Trident to write. The last couple are because there's a method in KafkaSpoutConfig that contains the SSL abbreviation. The rules only allow 2 capital letters in an abbreviation. Renaming is a breaking change, but maybe this isn't an issue for 2.0?
I also added a commit making a few other changes I thought made sense. The KafkaSpoutMessageId.getMetadata method was including the TopicPartition 3 times. The found variable in OffsetManager.findNextCommitOffset can be replaced with a null check of nextCommitMsg. They are in a separate commit for now, so this is easier to review.
> STORM-2515: Fix most checkstyle violations in storm-kafka-client

- conf/storm_jaas.conf
- conf/zookeeper_jaas.conf
[https://issues.apache.org/jira/browse/STORM-2466](https://issues.apache.org/jira/browse/STORM-2466)
This documentation lacks several section such as "Client" and "Server".The Client section is used by processes wanting to talk to ZooKeeper and really only needs to be included with nimbus and the supervisors.The Server section is used by the ZooKeeper servers. "jaas_kerberos.conf" should give users a good lead,so it should should give more details as SECURITY.md .Also,Having unused sections in the jaas is not a problem.So I think The example of jaas.conf in jaas_kerberos.conf should be the same as the PR.
> [STORM-2466] The example of jaas.conf in jaas_kerberos.conf should give more details

- external/storm-redis/src/main/java/org/apache/storm/redis/state/RedisKeyValueStateIterator.java
- external/storm-redis/src/test/java/org/apache/storm/redis/state/RedisKeyValueStateIteratorTest.java
* also don't expose TOMBSTONE keys
This implementation is for current Redis KV state.
I also have two State related pull requests #1970 and #1950 and I need to apply this patch to both of them. I'll update both after this patch is reviewed.
@arunmahadevan Please review and comment. Thanks in advance.
> STORM-2449 Ensure same key appears only once in State iterator

- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaUtils.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/StaticCoordinator.java
- external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkCoordinator.java
- external/storm-kafka/src/test/org/apache/storm/kafka/KafkaUtilsTest.java
- external/storm-kafka/src/test/org/apache/storm/kafka/ZkCoordinatorTest.java
- storm-client/src/jvm/org/apache/storm/daemon/Task.java
[Link to the ticket](https://issues.apache.org/jira/browse/STORM-2506)
> STORM-2506:  Print mapping between Task ID and Kafka Partitions

- external/storm-kafka-client/pom.xml
- external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/NamedSubscription.java
- external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/NamedSubscriptionTest.java
- String.valueOf returns square bracket, because 'topics' is Collection
- removed square bracket to use storm-kafka-monitor
> STORM-2568: Fix getTopicsString

- conf/defaults.yaml
[https://issues.apache.org/jira/browse/STORM-2559](https://issues.apache.org/jira/browse/STORM-2559)
There are three configurations,storm.auth.simple-acl.users: [],storm.auth.simple-acl.users.commands: [] and storm.auth.simple-acl.admins: [], in defaults.conf haven't been used in storm.So I think it should be removed from defaults.yaml.
> [STORM-2559] There are three configurations in defaults.yaml haven't been used in storm.

- conf/storm-cluster-auth.yaml.example
[https://issues.apache.org/jira/browse/STORM-2564](https://issues.apache.org/jira/browse/STORM-2564)
As the configuration which named storm.zookeeper.auth.payload should be filled in "storm-cluster-auth.yaml",and there isn't such a file.So, I think we should provide a template for storm-cluster-auth.yaml.
> [STORM-2564] We should provide a template for storm-cluster-auth.yaml

- docs/State-checkpointing.md
- examples/storm-redis-examples/pom.xml
- examples/storm-redis-examples/src/main/java/org/apache/storm/redis/tools/Base64ToBinaryStateMigrationUtil.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/adapter/RedisCommandsAdapterJedis.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/adapter/RedisCommandsAdapterJedisCluster.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/commands/RedisCommands.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/config/JedisClusterConfig.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/RedisClusterContainer.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/RedisCommandsContainerBuilder.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/RedisCommandsInstanceContainer.java
- external/storm-redis/src/main/java/org/apache/storm/redis/common/container/RedisContainer.java
- external/storm-redis/src/main/java/org/apache/storm/redis/state/RedisKeyValueState.java
- external/storm-redis/src/main/java/org/apache/storm/redis/state/RedisKeyValueStateIterator.java
- external/storm-redis/src/main/java/org/apache/storm/redis/state/RedisKeyValueStateProvider.java
- external/storm-redis/src/test/java/org/apache/storm/redis/state/RedisKeyValueStateIteratorTest.java
- external/storm-redis/src/test/java/org/apache/storm/redis/state/RedisKeyValueStateTest.java
- storm-core/src/jvm/org/apache/storm/state/BaseBinaryStateIterator.java
- storm-core/src/jvm/org/apache/storm/state/BaseStateIterator.java
- storm-core/src/jvm/org/apache/storm/state/DefaultStateEncoder.java
- storm-core/src/jvm/org/apache/storm/state/StateEncoder.java
- storm-core/test/jvm/org/apache/storm/state/BaseBinaryStateIteratorTest.java
* introduce new command interface and relevant containers
* new command interface will contain both binary and string commands once we address STORM-2304
* change RedisKeyValue to use byte[] for State key and value management instead of String
* get rid of Base64 encode/decode on RedisEncoder, and also SafeEncoder.encode() in Jedis internal
* implement some utils for handling Map with byte[]: since byte[] is bad for key type of Map
* users can select either Redis single server or Redis Cluster by passing JedisPoolConfig or JedisClusterConfig
PR for master: #2172
> STORM-2369 [storm-redis] Use binary type for State management (1.x)

- storm-client/src/jvm/org/apache/storm/utils/NimbusClient.java
To void the long time waiting, add the timeout parameter to the method of getting the nimbus client.
> STORM-2601: add the timeout parameter to the method of getting the nimbus client
