apache/storm

external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/state/HBaseMapState.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/state/HBaseState.java
correct problem reading configuration data as reported in STORM-627 - Storm-hbase configuration error
=> STORM-627 - Storm-hbase configuration error

SECURITY.md
=> [STORM-624] Fix typos in SECUTIRY.md

docs/documentation/Multilang-protocol.md
Minor typo I caught while reading the docs.
=> Correct capitalization typo

docs/documentation/Trident-API-Overview.md
MyFilter should extends BaseFilter not BaseFunction.
=> Fix java code error in doc

SECURITY.md
=> fixed daemon typo

external/README.md
JIRA: https://issues.apache.org/jira/browse/STORM-656
=>  STORM-656: Document "external" modules and "Committer Sponsors"

external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisState.java
See https://issues.apache.org/jira/browse/STORM-690 for more details.
=> STORM-690 Return Jedis into JedisPool with marking 'broken' if connection is broken

docs/documentation/Clojure-DSL.md, docs/documentation/Command-line-client.md, docs/documentation/Common-patterns.md, docs/documentation/Concepts.md, docs/documentation/Configuration.md, docs/documentation/Distributed-RPC.md, docs/documentation/Guaranteeing-message-processing.md, docs/documentation/Hooks.md, docs/documentation/Local-mode.md, docs/documentation/Running-topologies-on-a-production-cluster.md, docs/documentation/Serialization-(prior-to-0.6.0).md, docs/documentation/Serialization.md, docs/documentation/Structure-of-the-codebase.md, docs/documentation/Transactional-topologies.md, docs/documentation/Tutorial.md, docs/documentation/Understanding-the-parallelism-of-a-Storm-topology.md
Replace links to old api documents with new ones.
=> [STORM-669] Replace links with ones to latest api document

storm-core/src/ui/public/css/style.css
=> [STORM-714] Make CSS more consistent with self, prev release

external/storm-redis/README.md, external/storm-redis/src/test/java/org/apache/storm/redis/topology/PersistentWordCount.java
I've missed it from STORM-691, sorry!
=> STORM-724 [storm-redis] Document RedisStoreBolt and RedisLookupBolt which is missed

docs/documentation/Trident-API-Overview.md
Fixed a typo in the section explaining benefits of CombinerAggregator
=> Correcting a typo in Trident-API-Overview.md

storm-core/src/clj/backtype/storm/cluster.clj
JIRA: https://issues.apache.org/jira/browse/STORM-747
=> Issue assignment-version/info-with-version-callback when any assignment changes

external/storm-redis/pom.xml, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisContainer.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisMapState.java
Release news: https://groups.google.com/d/msg/jedis_redis/rz5o8i0uvvQ/y-zCxPDFQ3QJ
https://issues.apache.org/jira/browse/STORM-735 for more details.
=> [STORM-735] [storm-redis] Upgrade Jedis to 2.7.0

README.markdown
Travis CI has a fancy little badge that shows the build status of the project. We should add it to the README.markdown file now that #486 is in.
=> [STORM-801] Add Travis CI badge to README

storm-core/src/jvm/backtype/storm/task/IBolt.java
Internet grammar police and apostrophes!
=> Fix minor grammar bug in javadoc

docs/documentation/Setting-up-a-Storm-cluster.md
Update the Setting-Up-a-Storm-cluster.md document to provide instructions for the storm-483 extlib modification.
=> [STORM-795] Update the user document for the extlib issue

external/storm-redis/README.md, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterStateUpdater.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisStateUpdater.java, external/storm-redis/src/test/java/org/apache/storm/redis/trident/WordCountTridentRedis.java, external/storm-redis/src/test/java/org/apache/storm/redis/trident/WordCountTridentRedisCluster.java
It's not released to official, and I've just changed constructor signature so I'm not sure it can be treated to small patch.
If you feel that it requires JIRA issue, please let me know to file it. Thanks!
=> [STORM-752] [storm-redis] Clarify Redis*StateUpdater's expire is optional

storm-core/src/jvm/backtype/storm/messaging/netty/Client.java
STORM-835 Netty Client hold batch object until io operation complete
=> STORM-835 Netty Client hold batch object until io operation complete

storm-core/src/clj/backtype/storm/ui/core.clj
* flatten arguments so that it can be treated to each arguments
Please refer https://issues.apache.org/jira/browse/STORM-853 for more details.
Please review and comment. Thanks in advance!
=> STORM-853 Fix upload API to handle multi-args properly

bin/storm.py, storm-core/src/clj/backtype/storm/command/get_errors.clj
This has been tested with the latest src code.
=> STORM-847 Adding new cli for getting latest errors from running storm topology

external/flux/flux-core/src/main/java/org/apache/storm/flux/FluxBuilder.java, external/flux/flux-core/src/test/java/org/apache/storm/flux/TCKTest.java, external/flux/flux-core/src/test/resources/configs/diamond-topology.yaml
JIRA: https://issues.apache.org/jira/browse/STORM-873
=> STORM-873: Flux does not handle diamond topologies

docs/documentation/Tutorial.md
Fixed small grammar error in documentation.
=> Corrected grammar in documentation

external/storm-redis/src/main/java/org/apache/storm/redis/bolt/AbstractRedisBolt.java, external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisLookupBolt.java, external/storm-redis/src/main/java/org/apache/storm/redis/bolt/RedisStoreBolt.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/config/JedisClusterConfig.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/config/JedisPoolConfig.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisClusterContainer.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisCommandsContainerBuilder.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisCommandsInstanceContainer.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisContainer.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/mapper/RedisDataTypeDescription.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/mapper/RedisLookupMapper.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/mapper/RedisMapper.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/mapper/RedisStoreMapper.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/mapper/TupleMapper.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/AbstractRedisMapState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/AbstractRedisStateQuerier.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/AbstractRedisStateUpdater.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/KeyFactory.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/Options.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterMapState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterStateQuerier.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterStateUpdater.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisMapState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisStateQuerier.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisStateUpdater.java
* didn't leave javadoc if method is overriding Trident API directly : it should be treated from Trident API
* some code cleanup
=> STORM-843 Add Javadoc to storm-redis

external/flux/flux-core/src/main/java/org/apache/storm/flux/FluxBuilder.java
Add public access modifier to buildTopology().
=> Update FluxBuilder.java - buildTopology() public access modifier

storm-core/src/jvm/backtype/storm/utils/StormBoundedExponentialBackoffRetry.java
This is to reduce the noisiness of supervisor logs.
=> [STORM-937] Changing the log level from info to debug

storm-dist/binary/src/main/assembly/binary.xml
Ubuntu 14.04
Apache Maven 3.3.3
=> STORM-924:Set the file mode of the files included when packaging release packages

external/storm-kafka/src/jvm/storm/kafka/KafkaUtils.java, external/storm-kafka/src/jvm/storm/kafka/PartitionManager.java
STORM-643 fixing for 0.9.x-branch
=> [STORM-643] KafkaUtils repeatedly fetches messages whose offset is out of range

storm-core/src/jvm/backtype/storm/drpc/DRPCSpout.java, storm-core/src/jvm/storm/trident/TridentTopology.java
=> [STORM-968] Adding support to generate the id based on names in Trident

external/storm-jdbc/README.md, external/storm-jdbc/src/main/java/org/apache/storm/jdbc/trident/state/JdbcState.java, external/storm-jdbc/src/test/java/org/apache/storm/jdbc/topology/UserPersistanceTridentTopology.java
credit for finding the issue goes to @gbraccialli
=> Corrected ConnectionPrvoider to ConnectionProvider

conf/defaults.yaml, storm-core/src/jvm/backtype/storm/Config.java
Users can provide optional parameters to the plugin in the form of a Map.
=> [STORM-958] adds config for group.mapping.service init params

external/storm-elasticsearch/README.md, external/storm-elasticsearch/pom.xml, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/ElasticsearchGetRequest.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/EsLookupResultOutput.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/AbstractEsBolt.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/ElasticSearchClient.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsLookupBolt.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/EsLookupResultOutput.java, external/storm-elasticsearch/src/main/java/org/apache/storm/elasticsearch/bolt/TransportAddresses.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/AbstractEsBoltIntegrationTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/AbstractEsBoltTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsIndexBoltTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsLookupBoltIntegrationTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsLookupBoltTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/EsPercolateBoltTest.java, external/storm-elasticsearch/src/test/java/org/apache/storm/elasticsearch/bolt/TransportAddressesTest.java
https://issues.apache.org/jira/browse/STORM-978
=> STORM-978: Implemented EsLookupBolt

external/storm-jdbc/README.md
Fixed README by adding note about com.google.common.collect class usage, also fixed hikariConfigMap reference in example.
=> STORM-1055

storm-core/src/jvm/backtype/storm/topology/TopologyBuilder.java, storm-core/test/clj/backtype/storm/nimbus_test.clj, storm-core/test/jvm/backtype/storm/topology/TopologyBuilderTest.java
- added IllegalArgumentException to .setBolt(...), .setSpout(...), and .setStateSpout(...) in TopologyBuilder
=> [STORM-1044] Setting dop to zero does not raise an error

.travis.yml, external/sql/storm-sql-core/pom.xml, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/TridentCompiler.java, external/sql/storm-sql-core/src/native/CMakeLists.txt, external/sql/storm-sql-core/src/native/bindings/CMakeLists.txt, external/sql/storm-sql-core/src/native/bindings/jni/CMakeLists.txt, external/sql/storm-sql-core/src/native/bindings/jni/jni.cc, external/sql/storm-sql-core/src/native/cmake/FindLLVM.cmake, external/sql/storm-sql-core/src/native/include/stormsql/stormsql.h, external/sql/storm-sql-core/src/native/lib/CMakeLists.txt, external/sql/storm-sql-core/src/native/lib/tool/CMakeLists.txt, external/sql/storm-sql-core/src/native/lib/tool/facade.cc, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestTridentCompiler.java
This PR establishes the basic structure of the code generator to provide the essential build blocks for the actual implementation of the code generator.
=> STORM-1062. Establish the basic structure of the code generator.

downloads.html
It's another version of #725, only difference is base branch. It is asf-site now.
Please refer STORM-1033 or #725 to more details.
=> STORM-1033 replace closer.cgi to closer.lua

.gitignore
Modified .ignore file to skip some files generated by eclipse when importing the project.
=> Modified .ignore file

storm-core/src/jvm/backtype/storm/utils/DisruptorQueue.java, storm-core/src/jvm/backtype/storm/utils/RateTracker.java, storm-core/test/jvm/backtype/storm/utils/RateTrackerTest.java
, more accurate, and very fast. Removed sub-sampling of rate calculation in disruptor, because sub-sampling was more expensive than just doing the calculation.
=> STORM-1078: Updated RateTracker to be thread safe

external/sql/storm-sql-core/src/native/CMakeLists.txt, external/sql/storm-sql-core/src/native/third_party/CMakeLists.txt, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/CMakeLists.txt, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/LICENSE, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/gmock-gtest-all.cc, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/gmock/gmock.h, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/gmock_main.cc, external/sql/storm-sql-core/src/native/third_party/gmock-1.7.0/gtest/gtest.h, external/sql/storm-sql-core/src/native/third_party/json11/CMakeLists.txt, external/sql/storm-sql-core/src/native/third_party/json11/json11/json11.cpp, external/sql/storm-sql-core/src/native/third_party/json11/json11/json11.hpp
This PR includes json11 and gmock into the storm-sql project. These two third-party libraries are going to be used in the later jiras.
=> STORM-1081. Import json11 and gmock into the storm-sql project.

storm-core/src/clj/backtype/storm/daemon/logviewer.clj, storm-core/src/clj/backtype/storm/ui/core.clj, storm-core/src/clj/backtype/storm/ui/helpers.clj, storm-core/src/jvm/backtype/storm/Config.java
Backporting STORM-912 (#604) fix to 0.10.x branch.
=> STORM-912: Support SSL on Logviewer

bin/storm.py, conf/defaults.yaml, storm-core/src/clj/backtype/storm/daemon/drpc.clj, storm-core/src/clj/backtype/storm/ui/core.clj, storm-core/src/jvm/backtype/storm/security/auth/ReqContext.java, storm-core/src/jvm/backtype/storm/security/auth/kerberos/ServerCallbackHandler.java, storm-core/test/clj/backtype/storm/security/auth/DefaultHttpCredentialsPlugin_test.clj
Conflicts:
storm-core/src/clj/backtype/storm/ui/core.clj
=> STORM-1096: Fix some issues with impersonation on the UI

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprSerializer.java, external/sql/storm-sql-core/src/native/lib/compiler/expr_compiler.cc, external/sql/storm-sql-core/src/native/lib/compiler/expr_compiler.h, external/sql/storm-sql-core/src/native/lib/compiler/expr_visitor.h, external/sql/storm-sql-core/src/native/lib/compiler/typesystem.cc, external/sql/storm-sql-core/src/native/lib/compiler/typesystem.h, external/sql/storm-sql-core/src/native/test/compiler/CMakeLists.txt, external/sql/storm-sql-core/src/native/test/compiler/expr_compiler_test.cc, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCalcitePlanSerializer.java
This PR augments the compilers to compile the comparison, arithmetic and field references in SQL expressions.
=> STORM-1085. Compile comparison, arithmetic, and field reference expressions.

storm-core/src/clj/backtype/storm/ui/core.clj
Also corrects arity of one function, removing an unused parameter.
=> [STORM-1117] Adds visualization-init route previously missing

docs/documentation/FAQ.md
=> Minor grammar fix to FAQ

storm-core/src/clj/backtype/storm/cluster.clj, storm-core/src/clj/backtype/storm/daemon/nimbus.clj
Separate reader and writer for nimbus to avoid longer waits for reads to finish.
=> [STORM-1125] Adding separate ZK client for read in Nimbus ZK State

storm-core/src/jvm/backtype/storm/utils/Utils.java
Delete the abandoned comment "(defn xxx )" function, 
fix a bunch of messed indention, 
unify inconsistent space format, 
expand "import java.io.*" and "import java.util.*" in the file header.
=> [STORM-1122] Fix the format issue in Utils.java

storm-core/src/jvm/storm/trident/spout/ITridentSpout.java
Improve documentation including incorrect serialization framework issue described in STORM-566.
=> Improve documentation including incorrect Kryo ser. framework docs

storm-core/src/jvm/backtype/storm/StormSubmitter.java, storm-core/src/jvm/backtype/storm/validation/ConfigValidation.java
adding config validation during the topology submission process so that incorrect configs can be detected early
=> [STORM-1143] - Validate topology Configs during topology submission

dev-tools/travis/ratprint.py
@revans2 Apologies, but I just realized that my squash for this JIRA dropped one new file.  This PR adds it back.
=> STORM-1161: Adding ratprint.py

external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestSequenceFileBolt.java
These are just a start, I am not terribly knowledgeable of SequenceFiles
=> STORM-1154: SequenceFileBolt needs unit tests

storm-core/src/clj/backtype/storm/daemon/executor.clj
Currently when overflow buffer is not empty or pending is equal or greater than max spout pending, Spout doesn't handle activate / deactivate.
I've met this scenario with Trident topology, max spout pending is 10, $batch's complete latency is about to 20 sec.
Please refer https://issues.apache.org/jira/browse/STORM-794 for more description.
After applying this patch to 0.9.3, issue is resolved, though it still handles already emitted batches. 
>> deactivate
```
2015-05-04 16:35:52.127 INFO  [Thread-12-spout0][RecollectSpout] batchId <46253> start
2015-05-04 16:35:53.538 INFO  [Thread-16-$mastercoord-bg0][executor] Deactivating spout $mastercoord-bg0:(1)
2015-05-04 16:35:54.130 INFO  [Thread-12-spout0][RecollectSpout] batchId <46244> end
2015-05-04 16:35:54.130 INFO …
```
=> STORM-794 Modify Spout async loop to treat activate/deactivate ASAP

storm-core/src/clj/backtype/storm/daemon/logviewer.clj
Fixing dumps endpoints, if URL request has no file/directory it return 500 instead of page-not-found.
=> [STORM-1204] Fixing attempt to access to directory before authorizing user

examples/storm-starter/src/jvm/storm/starter/trident/TridentKafkaWordCount.java, external/storm-kafka/README.md, external/storm-kafka/src/jvm/storm/kafka/bolt/KafkaBolt.java, external/storm-kafka/src/jvm/storm/kafka/trident/TridentKafkaState.java, external/storm-kafka/src/jvm/storm/kafka/trident/TridentKafkaStateFactory.java, external/storm-kafka/src/test/storm/kafka/TestUtils.java, external/storm-kafka/src/test/storm/kafka/TridentKafkaTest.java, external/storm-kafka/src/test/storm/kafka/TridentKafkaTopology.java, external/storm-kafka/src/test/storm/kafka/bolt/KafkaBoltTest.java
This PR allows users to specify multiple Kafka configurations so that the topology can write to multiple Kafka clusters.
=> STORM-1352. Trident should support writing to multiple Kafka clusters.

external/flux/flux-core/src/main/java/org/apache/storm/flux/FluxBuilder.java, external/flux/flux-examples/README.md, external/flux/flux-examples/src/main/java/org/apache/storm/flux/examples/TestPrintBolt.java, external/flux/flux-examples/src/main/java/org/apache/storm/flux/examples/TestWindowBolt.java, external/flux/flux-examples/src/main/resources/simple_windowing.yaml
1. Added flux support for handling IWindowed bolt
2. Fix `canInvokeWithArgs` to handle multi argument overloaded methods
3. Sample flux topology with windowing
=> STORM-1207: Added flux support for IWindowedBolt

bin/storm.py
Opening a new PR for this due to issues in my fork.
=> Fix typo in get_jars_full

CHANGELOG.md, conf/defaults.yaml, storm-core/src/jvm/backtype/storm/Config.java, storm-core/src/jvm/backtype/storm/task/ShellBolt.java, storm-core/src/jvm/backtype/storm/utils/ShellBoltMessageQueue.java, storm-core/test/clj/backtype/storm/multilang_test.clj, storm-core/test/jvm/backtype/storm/utils/ShellBoltMessageQueueTest.java
This PR fixes unit test which is included via #897 
I've run the test from Travis CI 3 times and ShellBoltMessageQueueTest always succeed.
@d2r @revans2 Please check it again. Thanks!
=> STORM-756 Handle taskids response as soon as possible (with fixing unit test)

storm-core/test/jvm/backtype/storm/windowing/WindowManagerTest.java
* Problem: Trigger could be called two times while sleeping
* which first one has the events which are actually we want
* and second one resets it, which makes test failed
* Solution: Trigger manually
* and remove sleep if not necessary
@arunmahadevan Please verify this shouldn't break your intention on WindowManagerTest.
=> STORM-1374 fix random failure on WindowManagerTest

external/storm-cassandra/README.md, external/storm-cassandra/pom.xml, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/client/impl/DefaultClient.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/CQLResultSetValuesMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/impl/BoundStatementMapperBuilder.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraQuery.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraState.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraStateFactory.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraStateUpdater.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/TridentResultSetValuesMapper.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/DynamicStatementBuilderTest.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/WeatherSpout.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/bolt/BatchCassandraWriterBoltTest.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/bolt/CassandraWriterBoltTest.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/trident/TridentTopologyTest.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/trident/WeatherBatchSpout.java, external/storm-cassandra/src/test/resources/schema.cql
Trident state and query support for Cassandra.
=> STORM-1211 Added trident Update/Query support for Cassandra connector.

pom.xml, storm-multilang/javascript/pom.xml, storm-multilang/python/pom.xml, storm-multilang/ruby/pom.xml
https://issues.apache.org/jira/browse/STORM-1395
=> STORM-1395: move JUnit dependency to top-level pom

storm-core/src/jvm/backtype/storm/windowing/EventImpl.java, storm-core/src/jvm/backtype/storm/windowing/TimeTriggerPolicy.java, storm-core/src/jvm/backtype/storm/windowing/WatermarkTimeTriggerPolicy.java
https://issues.apache.org/jira/browse/STORM-1411
=> [STORM-1411] some fixes for storm-windowing

storm-core/src/clj/backtype/storm/daemon/logviewer.clj
The authorize check incorrectly use the worker log manner for daemon log.
Here remove that permission checks for daemon logs.
If necessary, we may later file a separate JIRA to enable different authorize check for daemon logs.
=> [STORM-1407] fix authorize issue for daemon log link in UI

storm-core/src/jvm/backtype/storm/scheduler/resource/User.java
https://issues.apache.org/jira/browse/STORM-1412
=> [STORM-1412] null check should be done in the first place

storm-core/test/jvm/backtype/storm/blobstore/BlobStoreTest.java, storm-core/test/jvm/backtype/storm/localizer/LocalizerTest.java
https://issues.apache.org/jira/browse/STORM-1413
=> [STORM-1413] remove unused variables for some tests

docs/documentation/State-checkpointing.md
Documentation for the state store support added to storm core as a part
of the windowing in STORM-1175.
=> [STORM-1416] Documentation for state store

examples/storm-starter/README.markdown, examples/storm-starter/pom.xml
=> STORM-706 . Clarify examples README.

external/storm-jdbc/pom.xml, external/storm-jdbc/src/main/java/org/apache/storm/jdbc/common/ConnectionProvider.java, external/storm-jdbc/src/main/java/org/apache/storm/jdbc/common/HikariCPConnectionProvider.java
https://issues.apache.org/jira/browse/STORM-1462
=> [STORM-1462] Upgrade HikariCP to 2.4.3

external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/HBaseBolt.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/HBaseLookupBolt.java, external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java, external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java, external/storm-hive/src/test/java/org/apache/storm/hive/bolt/TestHiveBolt.java
https://issues.apache.org/jira/browse/STORM-1425
=> [STORM-1425] Tick tuples must be acked like normal tuples

storm-core/src/jvm/backtype/storm/multilang/JsonSerializer.java
https://issues.apache.org/jira/browse/STORM-1414
=> [STORM-1414] Some improvements for multilang JsonSerializer

storm-core/src/jvm/storm/trident/state/map/MapCombinerAggStateUpdater.java, storm-core/src/jvm/storm/trident/state/map/MapReducerAggStateUpdater.java
https://issues.apache.org/jira/browse/STORM-1415
=> [STORM-1415] Some improvements for trident map StateUpdater

storm-core/src/jvm/org/apache/storm/trident/partition/IndexHashGrouping.java, storm-core/src/jvm/org/apache/storm/utils/Utils.java
https://issues.apache.org/jira/browse/STORM-1481
=> [STORM-1481] avoid Math.abs(Integer) get a negative value

storm-core/src/jvm/org/apache/storm/trident/Stream.java, storm-core/src/jvm/org/apache/storm/trident/operation/Assembly.java, storm-core/src/jvm/org/apache/storm/trident/operation/BaseOperation.java, storm-core/src/jvm/org/apache/storm/trident/operation/Filter.java, storm-core/src/jvm/org/apache/storm/trident/operation/Function.java, storm-core/src/jvm/org/apache/storm/trident/operation/Operation.java, storm-core/src/jvm/org/apache/storm/trident/operation/TridentCollector.java, storm-core/src/jvm/org/apache/storm/trident/operation/builtin/Debug.java, storm-core/src/jvm/org/apache/storm/trident/operation/builtin/FilterNull.java, storm-core/src/jvm/org/apache/storm/trident/operation/builtin/FirstN.java, storm-core/src/jvm/org/apache/storm/trident/operation/builtin/Negate.java
JIRA: https://issues.apache.org/jira/browse/STORM-1214
This is just a work in progress for STORM-1214, if this is merged, please don't resolve the JIRA.
I plan on further docs. But I didn't want this to get lost in the 1.x work.
=> STORM-1214: add javadoc for Trident Streams and Operations

storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
=> [STORM-1496] Nimbus periodically throws blobstore-related exception

bin/storm-config.cmd, bin/storm.cmd
Filter -c options from args and add them as part of storm.options
=> STORM-1476 Filter -c options from args and add them as part of storm.options

external/storm-hbase/src/main/java/org/apache/storm/hbase/security/HBaseSecurityUtil.java
When using a topology that has multiple executors in same process or multiple HBase bolts the tickets do not get renewed. After the ticket expiration the bolts are no longer able to write/read from HBase. That is caused by a login from keytab for every thread, this fixe ensures that there will only be one login per process.
=> [STORM-1521] When using Kerberos login from keytab with multiple bolts/executors ticket is not renewed

storm-core/src/clj/org/apache/storm/daemon/executor.clj, storm-core/src/clj/org/apache/storm/util.clj, storm-core/src/jvm/org/apache/storm/utils/Utils.java
=> Storm 1539 - Improve Storm ACK-ing performance

documentation/Setting-up-a-Storm-cluster.md, documentation/Setting-up-development-environment.md, documentation/flux.md, documentation/ui-rest-api.md
Please note that I'm not fluent so you may want to correct syntax, nuance, and so on.
=> STORM-1493 Update Documentation for {{nimbus.seeds}}

storm-core/src/clj/org/apache/storm/ui/core.clj, storm-core/src/ui/public/component.html, storm-core/src/ui/public/templates/topology-page-template.html, storm-core/src/ui/public/topology.html
=> [STORM-1488] fix broken component error times

documentation/cgroups_in_storm.md
Related to PR:
https://github.com/apache/storm/pull/1053
=> Documentation for cgroup support in Storm

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/CompilerUtil.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/StormParser.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestExprSemantic.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/standalone/TestPlanCompiler.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/trident/TestPlanCompiler.java, external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
Added support to handle array, map and nested field lookups and user defined functions
in Storm SQL.
=> [STORM-1570] Storm SQL support for nested fields and array

storm-core/src/clj/org/apache/storm/cluster.clj, storm-core/src/clj/org/apache/storm/daemon/nimbus.clj, storm-core/src/clj/org/apache/storm/daemon/worker.clj, storm-core/src/jvm/org/apache/storm/utils/WorkerBackpressureCallback.java, storm-core/src/jvm/org/apache/storm/utils/WorkerBackpressureThread.java, storm-core/test/jvm/org/apache/storm/utils/WorkerBackpressureThreadTest.java
Better handle backpressure exception etc. Clear backpressure topo dir during kill. Add unit test.
=> [Storm-1574] [1.x-branch]Better handle backpressure exception etc.

storm-core/src/jvm/org/apache/storm/security/auth/AuthUtils.java, storm-core/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java, storm-core/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGTKrb5LoginModule.java, storm-core/test/clj/org/apache/storm/security/auth/auto_login_module_test.clj
This needs to be ported to 1.x-branch as well.
=> [STORM-1596] Do not use single Kerberos TGT instance between multiple threads.

storm-core/src/jvm/org/apache/storm/drpc/DRPCSpout.java
`DRPCSpout` should be able to reconnect to DRPC server.
=> [STORM-1543] Always try to reconnect disconnected DRPCInvocationsClient

storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
=> STORM-1588: Do not add event logger details if number of event logger is zero

storm-core/test/clj/backtype/storm/supervisor_test.clj
* supervisor UTs seem not handle file path delimeter properly
* due to absolute-storm-local-dir, we should care Windows specific
* if worker dir path is relative and storm.home is empty, path will be invalid
I think it would affect 1.x and even master, but other tests disturb me verifying test result of supervisor-test.
For example, blobstore UTs are failed on Windows, and it even makes other UTs crashed (so that running test is stopped at the moment).
If I can see the test result for other branches, I'll craft pull request for each branches.
=> STORM-1603 Storm UT fails on supervisor test in Windows

storm-core/src/jvm/org/apache/storm/Config.java, storm-core/src/jvm/org/apache/storm/security/auth/SimpleTransportPlugin.java, storm-core/src/jvm/org/apache/storm/security/auth/ThriftConnectionType.java, storm-core/src/jvm/org/apache/storm/testing/SingleUserSimpleTransport.java
This pull request awaits merging in #1173 merged into 1.x-branch as well.
=> [STORM-1469] Decommissioning SimpleTransportPlugin and configuration

pom.xml
See https://issues.apache.org/jira/browse/STORM-1620
=> STORM-1620: Update curator to fix CURATOR-209

conf/defaults.yaml
=> Fix incorrect comment in default.yaml

external/storm-mongodb/README.md, external/storm-mongodb/pom.xml, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/AbstractMongoBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/MongoDBClient.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/QueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/SimpleQueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/MongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoUpdateMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoState.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateFactory.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateUpdater.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/InsertWordCount.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/UpdateWordCount.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/WordCounter.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/WordSpout.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/trident/WordCountTrident.java, pom.xml, storm-dist/binary/src/main/assembly/binary.xml
Initial commit for code review.
=> [STORM-1483] add storm-mongodb connector

documentation/Command-line-client.md
Trivial update for the rebalance command - now similar to the output of 'storm help rebalance'
=> Update doc for rebalance command

external/storm-mongodb/README.md, external/storm-mongodb/pom.xml, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/AbstractMongoBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/MongoDBClient.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/QueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/SimpleQueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/MongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoUpdateMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoState.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateFactory.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateUpdater.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/InsertWordCount.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/UpdateWordCount.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/WordCounter.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/topology/WordSpout.java, external/storm-mongodb/src/test/java/org/apache/storm/mongodb/trident/WordCountTrident.java, pom.xml, storm-dist/binary/src/main/assembly/binary.xml
=> STORM-1483: add storm-mongodb connector

README.markdown
=> [STORM-1624] add maven central status in README

log4j2/cluster.xml, log4j2/worker.xml
=> Fix logging for LoggingMetricsConsumer on branch 0.10.x STORM-584

examples/storm-starter/src/jvm/org/apache/storm/starter/tools/SlotBasedCounter.java
=> Revised wipeZeros() in SlotBasedCounter to avoid creating new hash set.

docs/Kestrel-and-Storm.md, docs/index.md, docs/storm-cassandra.md, docs/storm-elasticsearch.md, docs/storm-mongodb.md, docs/storm-mqtt.md
This PR can be merged to both master and 1.x branch.
=> STORM-1659:Add documents for external projects

docs/Kestrel-and-Storm.md, docs/index.md, docs/storm-cassandra.md, docs/storm-elasticsearch.md, docs/storm-mongodb.md, docs/storm-mqtt.md
=> STORM-1659 (1.x): Add documents for external projects

external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/MongoDBClient.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoState.java
https://issues.apache.org/jira/browse/STORM-1573
=> [STORM-1573] Add batch support for MongoInsertBolt

external/storm-solr/src/main/java/org/apache/storm/solr/bolt/SolrUpdateBolt.java
https://issues.apache.org/jira/browse/STORM-1669
=> STORM-1669: Fix SolrUpdateBolt flush bug

external/storm-solr/src/main/java/org/apache/storm/solr/bolt/SolrUpdateBolt.java
=> STORM-1669 (1.x): Fix SolrUpdateBolt flush bug

log4j2/worker.xml
=> STORM-1673 (1.x) log4j2/worker.xml refers old package of LoggerMetricsConsumer

log4j2/worker.xml
=> STORM-1673 log4j2/worker.xml refers old package of LoggerMetricsConsumer

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/TestCompilerUtils.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/compiler/backends/standalone/TestPlanCompiler.java
The proposed patch adds UDF support in ExprComplier. This can then be exposed via DDL. (https://issues.apache.org/jira/browse/STORM-1585)
Note: This includes changes from https://github.com/apache/storm/pull/1141 and needs to be rebased after that gets merged.
=> [STORM-1586] Add UDF support in ExprComplier

external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/windowing/HBaseWindowsStore.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/windowing/HBaseWindowsStoreFactory.java, storm-core/src/jvm/org/apache/storm/trident/windowing/InMemoryWindowsStoreFactory.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowKryoSerializer.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowTridentProcessor.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStateUpdater.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStore.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStoreFactory.java
This PR is raised as other https://github.com/apache/storm/pull/1273 is merged/closed but it is reverted saying that there was a build error. But [Travis CI build](https://travis-ci.org/apache/storm/builds/119160406) and my local builds are passed.
Could not reopen https://github.com/apache/storm/pull/1273 as it is merged/closed.
=> STORM-1649 Optimize Kryo instaces creation in trident windowing

external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/windowing/HBaseWindowsStore.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/windowing/HBaseWindowsStoreFactory.java, storm-core/src/jvm/org/apache/storm/trident/windowing/InMemoryWindowsStoreFactory.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowKryoSerializer.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowTridentProcessor.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStateUpdater.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStore.java, storm-core/src/jvm/org/apache/storm/trident/windowing/WindowsStoreFactory.java
@ptgoetz @harshach https://github.com/apache/storm/pull/1295 was raised on master. There were conflicts with 1.x-branch because of different HBase version issues in 1.x-branch and master, which are resolved.
=> Storm 1649 Optimize Kryo instaces creation in trident windowing for 1.x

external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaConfig.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaUtils.java
Added Kafka Spout Config FetchByte to Storm-Kafka  https://issues.apache.org/jira/browse/STORM-1680
=> STORM-1680, Added Kafka Spout Config FetchByte to Storm-Kafka

storm-core/src/jvm/org/apache/storm/topology/BaseStatefulBoltExecutor.java, storm-core/src/jvm/org/apache/storm/topology/CheckpointTupleForwarder.java, storm-core/src/jvm/org/apache/storm/topology/IStatefulBolt.java, storm-core/src/jvm/org/apache/storm/topology/StatefulBoltExecutor.java, storm-core/src/jvm/org/apache/storm/topology/TopologyBuilder.java
Refactored IstatefulBolt to be independent of IRichBolt so that setBolt overloads in TopologyBuilder can work correctly.
=> [STORM-1714] StatefulBolts ends up as normal bolts while using TopologyBuilder.setBolt without parallelism

pom.xml
* upgrade commons-io from 2.4 to 2.5 to resolve IO-378
Fix for master: #1411
=> STORM-1773 (1.x) Utils.javaDeserialize() doesn't work with primitive types

external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/HBaseBolt.java, external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java, storm-core/src/jvm/org/apache/storm/utils/BatchHelper.java
=> STORM-1678 (1.x): abstract batch processing to common api `BatchHelper`

storm-multilang/javascript/src/main/resources/resources/storm.js
Convenience methods for checking if tuple is tick or heartbeat tuple to match python version, also fix some comment typos.
=> add convenience methods for checking tuple type in node.js library

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/StormSqlImpl.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/ExprCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/BuiltinAggregateFunctions.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/PlanCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/AbstractChannelHandler.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/ChannelContext.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/ChannelHandler.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/Channels.java, external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
Added group by support for storm-sql in standalone mode and handle user defined aggregation operations as well.
=> [STORM-1709] Added group by support in storm sql standalone mode

docs/Command-line-client.md
Fix broken link to setup dev env link and complete options for `storm rebalance` command for Storm 0.9.6
=> minor: update command line client documentation

external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
Adding topic name and partition id to the log output makes it easier to debug when an issue arises.
=> STORM-1745: Add partition to log output in PartitionManager

examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentKafkaWordCount.java
@harshach @ptgoetz can you take a look ?
=> [STORM-1868] Modify TridentKafkaWordCount to run in distributed mode

external/storm-hive/src/test/java/org/apache/storm/hive/trident/TridentHiveTopology.java, storm-core/src/jvm/org/apache/storm/StormSubmitter.java, storm-core/src/jvm/org/apache/storm/hooks/SubmitterHookException.java
Cherry picked form master #1446 and made relevant changes for this branch.
=> STORM-1864 : StormSubmitter should throw respective exceptions and log respective errors forregistered submitter hook invocation

docs/Metrics.md
Please keep in mind while reviewing that this is written by not native and good writing skill for English.
So you may want to correct many places which are wrong or weird use of vocabulary, grammar, nuance, and so on.
=> STORM-1724 Fill up lacking contents to Metrics documentation

docs/Metrics.md
Please keep in mind while reviewing that this is written by not native and good writing skill for English.
So you may want to correct many places which are wrong or weird use of vocabulary, grammar, nuance, and so on.
It's same as master version (#1354) since there's no difference for now.
=> STORM-1724 (1.x) Fill up lacking contents to Metrics documentation

external/storm-kafka/src/jvm/org/apache/storm/kafka/DynamicBrokersReader.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/DynamicPartitionConnections.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaUtils.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkCoordinator.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkState.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TridentKafkaEmitter.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/ZkBrokerReader.java
[STORM-1874](https://issues.apache.org/jira/browse/STORM-1874)
Update Log access permissions from public to private .
=> [STORM-1874]Update logger private permissions

docs/Command-line-client.md
This can be cherry-picked to 1.x-branch.
=> STORM-1865: update command line client document

external/storm-hdfs/README.md
=> STORM-1909 Updating HDFS spout documentation

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
[STORM-1896](https://issues.apache.org/jira/browse/STORM-1896)
remove duplicated code in HdfsSpout open()
=> [STORM-1896] HdfsSpout remove duplicated code

storm-core/src/clj/org/apache/storm/daemon/nimbus.clj
PR for master: #1513 
* Nimbus fails to start in secure mode since authrization is not passed
* Extract the logic of getClusterInfo to new function 'get-cluster-info'
* and let both of callers call this function instead
=> STORM-1925 Remove Nimbus thrift call from Nimbus itself (1.x)

SECURITY.md
This patch must be cherry picked in 0.10.x-branch, 1.x-branch, and master
=> STORM-1834: Documentation How to Generate Certificates For Local Testing SSL Setup

docs/distcache-blobstore.md
[STORM-1895](https://issues.apache.org/jira/browse/STORM-1895)
Storm command line argument --repl-fctr have update to replication-factor and update the document .
Replace repl-fctr with replication-factor
=> [STORM-1895] Blob Store replication-factor argument

storm-core/src/jvm/org/apache/storm/daemon/supervisor/SupervisorUtils.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/SyncProcessEvent.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/SyncSupervisorEvent.java
* sync-supervisor just downloads new topology code and writes new local assignment
* shutting down workers and removing topology code is moved to sync-processes
* sync-processes does all of jobs based on local assignment and allocated workers
PR for 1.x-branch: #1528
Please note that supervisor is ported to Java, so PR for master and PR for 1.x-branch are having different diff. But concept is same.
=> STORM-1934 Fix race condition between sync-supervisor and sync-processes

storm-core/src/ui/public/templates/index-page-template.html
*before fix preview:*
*after fix preview:*
=> STORM-1922: Supervisor summary default order by host

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/PostOrderRelNodeVisitor.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/PlanCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/AbstractChannelHandler.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/ChannelContext.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/ChannelHandler.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/Channels.java, external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
Added support for simple equi-joins with single condition in storm-sql
standalone mode.
Note: this includes changes from https://github.com/apache/storm/pull/1336
=> [STORM-1833] Simple equi-join in storm-sql standalone mode

storm-core/src/jvm/org/apache/storm/topology/BaseConfigurationDeclarer.java, storm-core/src/jvm/org/apache/storm/trident/TridentTopology.java, storm-core/src/jvm/org/apache/storm/trident/graph/Group.java, storm-core/src/jvm/org/apache/storm/trident/operation/DefaultResourceDeclarer.java, storm-core/src/jvm/org/apache/storm/trident/planner/Node.java, storm-core/src/jvm/org/apache/storm/trident/planner/ProcessorNode.java, storm-core/src/jvm/org/apache/storm/trident/topology/TridentTopologyBuilder.java, storm-core/test/clj/integration/org/apache/storm/trident/integration_test.clj
New behavior: 
- Added a way to specify default values for operations in Trident
- New behavior requires all components in group have same types of resources set (or defaults)
- Added a way to specify resources for master-coord Spouts.
=> STORM-1913: Additions and Improvements for Trident RAS API

storm-core/src/jvm/org/apache/storm/spout/ShellSpout.java
When nextTuple is not calling at any chances (max spout pending, backpressure introduced at 1.0.0, and so on) multi-lang spout don't receive any message from ShellSpout, thus no messages from multi-lang spout side. (because multilang spout and ShellSpout communicates like ping-pong, unlike multilang bolt and ShellBolt)
In result, no heartbeat is being marked, and finally raises subprocess heartbeat timeout.
This PR changes ShellSpout to only check heartbeat while ShellSpout is waiting for subprocess to sync.
And this PR also changes ShellSpout.die logic similar to ShellBolt, since I found ShellSpout's die message was logged but worker itself was not died after logging. Only that task was died.
=> STORM-1928 ShellSpout should check heartbeat while ShellSpout is waiting for subprocess to sync

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java
- KafkaSpoutRetryExponentialBackoff#nextTime(...) method is off by order of magnitude
=> Kafka Spout New Consumer API - KafkaSpoutRetryExponentialBackoff Bug

storm-core/src/jvm/org/apache/storm/scheduler/Cluster.java, storm-core/src/jvm/org/apache/storm/scheduler/resource/RAS_Node.java, storm-core/src/jvm/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java, storm-core/test/jvm/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java, storm-core/test/jvm/org/apache/storm/scheduler/resource/TestUtilsForResourceAwareScheduler.java, storm-core/test/jvm/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
Backport of #1398 to 1.x branch.  I'm not sure this actually needs a PR, but since it's been a while since #1398 was merged, I'll put one anyways since the code went into 2.x a while ago
=> Backport to 1.x [STORM-1766] - A better algorithm server rack selection for RAS

storm-core/src/jvm/org/apache/storm/StormSubmitter.java, storm-core/src/jvm/org/apache/storm/blobstore/NimbusBlobStore.java, storm-core/src/jvm/org/apache/storm/security/auth/ThriftClient.java, storm-core/src/jvm/org/apache/storm/utils/NimbusClient.java
https://github.com/apache/storm/pull/1630 ported to master branch.
=> [STORM-2042] Nimbus client connections not closed properly causing connection leaks

external/storm-submit-tools/pom.xml, log4j2/worker.xml, storm-core/src/clj/org/apache/storm/util.clj
@d2r did the original work for this.
=> Storm 2063 thread name in worker log improvements

storm-core/src/ui/public/component.html, storm-core/src/ui/public/deep_search_result.html, storm-core/src/ui/public/topology.html
Reverting some of the changes I made in: https://github.com/apache/storm/pull/1536
What is on master shouldn't break requests, but it is sloppy, so this should clean up. I didn't create a new JIRA but can if appropriate. Will PR for 1.x and 1.0.x
=> STORM-1890: looks like too many calls were moved to getStatic

external/storm-kafka-monitor/src/main/java/org/apache/storm/kafka/monitor/KafkaOffsetLagUtil.java
https://issues.apache.org/jira/browse/STORM-2074
=> STORM-2074: fix storm-kafka-monitor NPE bug

storm-core/src/jvm/org/apache/storm/transactional/TransactionalSpoutCoordinator.java
A better way to get default value.
=> A better way to get default value

storm-core/src/ui/public/js/script.js
This can get cherry-picked to 1.x
=> STORM-2078: enable paging in worker datatable

docs/STORM-UI-REST-API.md, storm-core/src/clj/org/apache/storm/ui/core.clj, storm-core/src/ui/public/index.html, storm-core/src/ui/public/templates/index-page-template.html, storm-core/src/ui/public/templates/supervisor-page-template.html
Most of the work performed by @jerrypeng.
I added a few changes for consistency and issues with the tooltips in the index page
=> Storm 2105 cluster supervisor total and avail resources

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java, external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestUtils.java
1. Cast the result, accumulator and value types correctly
2. Support aggregate functions with more than one argument
=> [STORM-2118] A few fixes for storm-sql standalone mode

storm-core/src/jvm/org/apache/storm/scheduler/multitenant/IsolatedPool.java
@jerrypeng made the change originally. I changed the wording slightly. @jerrypeng can you check it out and see if it makes sense?
Also should be easily cherry-pickeable for 1.x
=> STORM-2066: make error message in IsolatedPool.java more descriptive

external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/PlanCompiler.java, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/compiler/backends/standalone/RelNodeCompiler.java
Fix group-by to not rely on monotonic group-by keys
=> [STORM-2144] Fix Storm-sql group-by behavior in standalone mode

storm-core/src/jvm/org/apache/storm/daemon/supervisor/AdvancedFSOps.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/Container.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/SupervisorUtils.java, storm-core/src/native/worker-launcher/impl/main.c, storm-core/src/native/worker-launcher/impl/worker-launcher.c, storm-core/src/native/worker-launcher/impl/worker-launcher.h
Re-opening this, as I reverted the last one to fix a typo (#1723)
=> STORM-2131: Add blob command to worker-launcher, make stormdist directory not writeable by topo owner 

examples/storm-starter/src/jvm/org/apache/storm/starter/spout/RandomSentenceSpout.java, examples/storm-starter/src/jvm/org/apache/storm/starter/trident/DebugMemoryMapState.java, examples/storm-starter/src/jvm/org/apache/storm/starter/trident/TridentKafkaWordCount.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaUtils.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TransactionalTridentKafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TridentKafkaEmitter.java, storm-core/src/jvm/org/apache/storm/trident/operation/builtin/Debug.java, storm-core/src/jvm/org/apache/storm/trident/spout/IOpaquePartitionedTridentSpout.java, storm-core/src/jvm/org/apache/storm/trident/spout/IPartitionedTridentSpout.java, storm-core/src/jvm/org/apache/storm/trident/spout/OpaquePartitionedTridentSpoutExecutor.java, storm-core/src/jvm/org/apache/storm/trident/spout/PartitionedTridentSpoutExecutor.java, storm-core/src/jvm/org/apache/storm/trident/state/CombinerValueUpdater.java, storm-core/src/jvm/org/apache/storm/trident/topology/MasterBatchCoordinator.java, storm-core/src/jvm/org/apache/storm/trident/topology/state/RotatingTransactionalState.java, storm-core/src/jvm/org/apache/storm/trident/topology/state/TransactionalState.java
- Improve logging in trident core, MasterBatchCoordinator,  and examples
- Added DebugMemoryMapState
=> STORM-2097: Improve logging in trident core and examples

docs/storm-sql-internal.md, docs/storm-sql-reference.md, docs/storm-sql.md
NOTE: This should be merged after STORM-2125 (#1714) is merged to master
* add a new page "storm-sql-reference" based on Calcite SQL reference
=> STORM-2135 document covered features of SQL reference in Calcite

docs/storm-sql-example.md, docs/storm-sql-internal.md, docs/storm-sql-reference.md, docs/storm-sql.md
This is on top of STORM-2135 (#1725).
* This should be merged after STORM-2135 - #1725 (hence after STORM-2125 - #1714 , too)
* This should also be merged after STORM-1444 - #1681
=> STORM-2136 Write some examples to show the usage of Storm SQL

pom.xml
https://issues.apache.org/jira/browse/STORM-2012
=> STORM-2012: Upgrade Kafka to 0.8.2.2

external/storm-eventhubs/pom.xml, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/bolt/EventHubBolt.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/BinaryEventDataScheme.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventDataScheme.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventHubSpout.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventHubSpoutConfig.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/FieldConstants.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/IEventDataScheme.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/StringEventDataScheme.java, pom.xml
STORM-2127: Storm-eventhubs should use latest amqp and eventhubs-client versions
=> STORM-2127: Storm-eventhubs should use latest amqp and eventhubs-client versions

storm-core/src/clj/org/apache/storm/testing.clj, storm-core/src/jvm/org/apache/storm/ProcessSimulator.java, storm-core/src/jvm/org/apache/storm/StormTimer.java, storm-core/src/jvm/org/apache/storm/command/KillWorkers.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/ReadClusterState.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/UniFunc.java, storm-core/src/jvm/org/apache/storm/daemon/supervisor/timer/SupervisorHealthCheck.java, storm-core/src/jvm/org/apache/storm/utils/DisruptorQueue.java
Will put up a pull request for 1.x shortly.
=> STORM-2175: fix double close of workers

docs/storm-kafka.md
[docs/storm-kafka.md](https://github.com/apache/storm/blob/d88558237f37de87d81fad0be7d51042328c615e/docs/storm-kafka.md) is out of date. This updates it to be the same as [storm/external/storm-kafka/README.md](https://github.com/apache/storm/tree/d88558237f37de87d81fad0be7d51042328c615e/external/storm-kafka)
=> Update storm kafka docs.

external/sql/pom.xml, external/sql/storm-sql-core/src/jvm/org/apache/storm/sql/parser/SqlCreateTable.java, external/sql/storm-sql-core/src/test/org/apache/storm/sql/TestStormSql.java, external/sql/storm-sql-external/storm-sql-kafka/pom.xml, external/sql/storm-sql-external/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/KafkaDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-mongodb/pom.xml, external/sql/storm-sql-external/storm-sql-mongodb/src/jvm/org/apache/storm/sql/mongodb/MongoDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-mongodb/src/resources/META-INF/services/org.apache.storm.sql.runtime.DataSourcesProvider, external/sql/storm-sql-external/storm-sql-mongodb/src/test/org/apache/storm/sql/mongodb/TestMongoDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-redis/src/jvm/org/apache/storm/sql/redis/RedisDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-redis/src/test/org/apache/storm/sql/redis/TestRedisDataSourcesProvider.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/DataSourcesProvider.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/DataSourcesRegistry.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/utils/FieldInfoUtils.java, storm-dist/binary/src/main/assembly/binary.xml
major changes as following:
- new KafkaDataSourcesProvider & unit tests
- change DataSourcesProvider method `constructTrident()`'s arg `properties` data type from `String` to `Properties`
- abstract common logic to Utils
- some minor improvements
=> [STORM-2103][SQL] Introduce new sql external module: storm-sql-mongodb

storm-core/src/jvm/org/apache/storm/security/auth/ThriftClient.java
=> STORM-2197: NimbusClient connections leak due to leakage in ThriftClient.

external/sql/storm-sql-external/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/KafkaDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-mongodb/src/jvm/org/apache/storm/sql/mongodb/MongoDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-mongodb/src/test/org/apache/storm/sql/mongodb/TestMongoDataSourcesProvider.java, external/sql/storm-sql-external/storm-sql-redis/src/jvm/org/apache/storm/sql/redis/RedisDataSourcesProvider.java, external/sql/storm-sql-runtime/pom.xml, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/avro/AvroScheme.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/avro/AvroSerializer.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/avro/CachedSchemas.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/serde/json/JsonScheme.java, external/sql/storm-sql-runtime/src/jvm/org/apache/storm/sql/runtime/utils/SerdeUtils.java, external/sql/storm-sql-runtime/src/test/org/apache/storm/sql/TestAvroSerializer.java
This is STORM-2172 for 1.x-branch.
=> [STORM-2172][SQL][1.x branch] Support Avro as input / output format

storm-core/src/jvm/org/apache/storm/scheduler/resource/RAS_Node.java
Fixed a typo in RAS_Node::consumeCPU()
=> [STORM-2196] A typo in RAS_Node::consumeCPU

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java
This is STORM-2198 for 1.x-branch.
=> STORM-2198: [1.x-branch] perform RotationAction when stopping HdfsBolt

storm-core/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java
This is porting of #1784 to master
=> STORM-2205 Racecondition in getting nimbus summaries while ZK connectionions are reconnected

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/trident/HdfsState.java
- Close OutputStream before file gets deleted
=> STORM-2208: HDFS State Throws FileNotFoundException in Azure Data Lake Store file system (adl://)

docs/index.md, docs/storm-cassandra.md, docs/storm-druid.md, docs/storm-kafka-client.md, docs/storm-kinesis.md, docs/storm-mongodb.md, docs/storm-opentsdb.md, docs/storm-redis.md
This PR is STORM-2209 for 1.x-branch.  PR for master branch has been merged.
=> STORM-2209: 1.x-branch Update documents adding new integration for some external systems

docs/Trident-RAS-API.md
Adding documentation for defaults, clarifying other parts.
=> Updating Trident RAS Documentation.

docs/Windowing.md, storm-core/src/jvm/org/apache/storm/Config.java, storm-core/src/jvm/org/apache/storm/executor/Executor.java, storm-core/src/jvm/org/apache/storm/topology/IWindowedBolt.java, storm-core/src/jvm/org/apache/storm/topology/TupleFieldTimestampExtractor.java, storm-core/src/jvm/org/apache/storm/topology/WindowedBoltExecutor.java, storm-core/src/jvm/org/apache/storm/topology/base/BaseStatefulWindowedBolt.java, storm-core/src/jvm/org/apache/storm/topology/base/BaseWindowedBolt.java, storm-core/src/jvm/org/apache/storm/windowing/TimestampExtractor.java, storm-core/test/jvm/org/apache/storm/topology/WindowedBoltExecutorTest.java
Added a timestamp extractor so that the tuple timestamp can be derived from the tuple than directly
mapping it to a field within the tuple.
=> [STORM-2238] Add Timestamp extractor for windowed bolt

integration-test/pom.xml
* fix integration-test's pom.xml to have root pom as parent, and remove version and storm version
=> STORM-2251 Integration test refers specific version of Storm which should be project version

external/storm-kafka-client/pom.xml, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/SerializableDeserializer.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/KafkaConsumerFactory.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/KafkaConsumerFactoryDefault.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/TopicKeyValueTupleBuilder.java
1.x version of https://github.com/apache/storm/pull/1696
=> STORM-2104 1.x

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/blobstore/HdfsClientBlobStore.java, storm-core/src/jvm/org/apache/storm/StormSubmitter.java, storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreUtils.java, storm-core/src/jvm/org/apache/storm/utils/NimbusClient.java
This is cherrypicked from #1846
=> STORM-2266 Close NimbusClient instances appropriately

external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
* use user's maven local repository if possible
* if it's not available, just use 'local-repo' (it will be created if not exists)
=> STORM-2267 Use user's local maven repo. directory to local repo.

external/storm-pmml/src/main/java/org/apache/storm/pmml/model/jpmml/JpmmlModelOutputs.java
=> PMMLPredictorBolt - Handle duplicate output and predicted fields

external/storm-hdfs/README.md, external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java
Minor updates to code and documentation
=> Storm 2274 - Adding support for named output stream in HdfsSpout

external/storm-druid/README.md, external/storm-druid/pom.xml, external/storm-druid/src/main/java/org/apache/storm/druid/bolt/DruidBeamBolt.java
Support given for storm-druid connector shaded jar and added some debug logs to DruidBolt
=> STORM-2277: Support given for storm-druid connector shaded jar 

storm-core/src/jvm/org/apache/storm/state/DefaultStateSerializer.java
Raising a separate patch for the state issue fixed in https://github.com/apache/storm/pull/1693
=> [STORM-2283] Fix multi threading issues in DefaultStateSerializer

integration-test/config/Vagrantfile, integration-test/config/install-storm.sh, integration-test/pom.xml, integration-test/run-it.sh, integration-test/src/test/java/org/apache/storm/st/wrapper/TopoWrap.java
@HeartSaVioR Can you please review ?
=> STORM-2268: Fix integration test for Travis CI build

storm-core/src/clj/org/apache/storm/daemon/executor.clj, storm-core/src/clj/org/apache/storm/util.clj, storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java, storm-core/src/jvm/org/apache/storm/utils/Utils.java
Please refer [STORM-2293](https://issues.apache.org/jira/browse/STORM-2293) for more details.
=> STORM-2293 hostname should only refer node's 'storm.local.hostname' (1.x)

storm-core/src/clj/org/apache/storm/daemon/executor.clj, storm-core/src/clj/org/apache/storm/util.clj, storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java, storm-core/src/jvm/org/apache/storm/utils/Utils.java
Please refer [STORM-2293](https://issues.apache.org/jira/browse/STORM-2293) for more details.
=> STORM-2293 hostname should only refer node's 'storm.local.hostname' (1.0.x)

storm-core/src/jvm/org/apache/storm/daemon/supervisor/Supervisor.java, storm-core/src/jvm/org/apache/storm/executor/Executor.java, storm-core/src/jvm/org/apache/storm/executor/error/ReportError.java, storm-core/src/jvm/org/apache/storm/utils/Utils.java
Please refer [STORM-2293](https://issues.apache.org/jira/browse/STORM-2293) for more details.
=> STORM-2293 hostname should only refer node's 'storm.local.hostname'

storm-core/src/jvm/org/apache/storm/daemon/GrouperFactory.java, storm-core/src/jvm/org/apache/storm/daemon/nimbus/Nimbus.java, storm-core/src/jvm/org/apache/storm/utils/TupleUtils.java
@HeartSaVioR @arunmahadevan Please review.
=> STORM-2305: STORM-2279 calculates task index different from grouper code

dev-tools/rc/download-rc-directory.sh, dev-tools/rc/verify-release-file.sh
* download-rc-directory.sh downloads all files in directory from RC URL to current directory
* verify-release-file.sh verifies signature, MD5, SHA of the archive file
Requires `gpg` and `wget`.
Might be better to add guide to verify RC in DEVELOPER.md or so. Welcome any ideas!
=> Add some scripts for help verifying the RC

storm-core/src/jvm/org/apache/storm/daemon/supervisor/Container.java, storm-core/test/jvm/org/apache/storm/daemon/supervisor/ContainerTest.java
This is same as https://github.com/apache/storm/pull/1898 ... just  specific to master branch.
=> STORM-2324 : Fix deployment failure if resources directory is missing in topology jar

dev-tools/rc/download-rc-directory.sh, dev-tools/rc/verify-release-file.sh
Added missing licenses for
`dev-tools/rc/download-rc-directory.sh`
`dev-tools/rc/verify-release-file.sh`
=> STORM-2346: Files with unapproved licenses: download-rc-directory.sh verify-release-file.sh

examples/storm-kafka-client-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaClientWordCountNamedTopics.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/LocalSubmitter.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaConsumerTopology.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaWordCount.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutBatchMetadata.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutEmitter.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutManager.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaque.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutOpaqueCoordinator.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTopicPartition.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/trident/KafkaTridentSpoutTopicPartitionRegistry.java
To review this PR please review only the commit that has STORM-2281. It is currently sitting on top of the multiple commits addressing STORM-2225, waiting for them to be squashed in and eventually merged.
@harshach can you please review. Thanks.
=> STORM-2281: Running Multiple Kafka Spouts (Trident) Throws Illegal State Exception

examples/storm-kafka-client-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaClientWordCountNamedTopics.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/DrpcResultsPrinter.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaConsumerTopology.java, examples/storm-kafka-examples/src/main/java/org/apache/storm/kafka/trident/TridentKafkaWordCount.java
- Client necessary to check for DRPC results while running in distribute mode
=> STORM-2320: DRPC client printer class reusable for local and remote DRPC

docs/index.md
Rearrange a bit and add documentations about some missing Storm SQL.
=> Add Storm SQL docs to index page for 1.x branch

docs/index.md
Rearrange a bit and add documentations about Streams API and some missing Storm SQL.
=> Add Streams API and Storm SQL docs to index page

pom.xml
Compiled and packaged with
```
mvn clean install -DskipTests=true
cd storm-dist/binary && mvn package
```
Works fine in both local and deployed mode.
=> STORM-2326 Upgrade log4j and slf4j for branch 1.0.x

pom.xml
See #1946 for 1.0.x equivalent
=> STORM-2326 Upgrade log4j and slf4j for branch 1.x

storm-core/src/jvm/org/apache/storm/cluster/PaceMakerStateStorage.java, storm-core/src/jvm/org/apache/storm/pacemaker/Pacemaker.java
=> STORM-2372: Pacemaker client doesn't clean up heartbeats properly. (2.x)

storm-core/src/clj/org/apache/storm/pacemaker/pacemaker.clj, storm-core/src/clj/org/apache/storm/pacemaker/pacemaker_state_factory.clj
=> STORM-2372: Pacemaker client doesn't clean up heartbeats properly. (1.0.x)

external/storm-kafka/src/jvm/org/apache/storm/kafka/DynamicBrokersReader.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/IntSerializer.java
just remove some unused import and all tests passed
=> remove unused import in module kafkaclient

storm-core/src/clj/org/apache/storm/pacemaker/pacemaker_state_factory.clj
Code cherry-picked onto this branch in PR #1953 broke this.
1.0.x-branch does not have Pacemaker-HA.
=> STORM-2385: pacemaker_state_factory.clj does not compile on branch-1.0.x

pom.xml
See #1946 for 1.0.x equivalent
` mvn clean install -DskipTests=true` ran without problems
=> STORM-2326 Upgrade log4j and slf4j for branch 2.x

external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java
Try to route acks/fails to recreated partition managers if manager is not found by exact (broker, partition, topic) combination
=> STORM-2361 Kafka spout - after leader change, it stops committing offsets to ZK

examples/storm-pmml-examples/src/main/java/org/apache/storm/pmml/JpmmlRunnerTestTopology.java, external/storm-pmml/src/main/java/org/apache/storm/pmml/model/jpmml/JpmmlModelOutputs.java, external/storm-pmml/src/main/java/org/apache/storm/pmml/runner/jpmml/JpmmlFactory.java
- Created factory to create ModelRunner and ModelOutputs from Blobstore
- Updated example topology to support loading PMML model from file and from Blobstore
=> STORM-2240: STORM PMML Bolt - Add Support to Load Models from Blob Store

storm-core/src/jvm/org/apache/storm/blobstore/LocalFsBlobStore.java
Syncing up blobs throws KeyNotFoundException when deleting blobs which are already deleted from ZK.
Currently deleting blob requires pulling the latest change first to check ACL. That makes sense, but in above case we already deleted the blob from ZK so it just fails. We need to have "force delete" when request for deletion comes from syncing up blobs.
* add new method: clearRemovedBlob
* skip checking ACL while deleting when blob is already removed from ZK
This patch is easy to be cherry-picked to master and 1.0.x branches as well.
=> STORM-2414 Skip checking meta's ACL when subject has write privileges for any blobs (1.x)

external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java
Invoking `retireIdleWriters` when the hive bolt receives a tick tuple will periodically close the idle connections.
=> STORM-2425: Storm Hive Bolt not closing open transactions

storm-core/src/ui/public/component.html, storm-core/src/ui/public/js/script.js, storm-core/src/ui/public/templates/component-page-template.html, storm-core/src/ui/public/templates/topology-page-template.html, storm-core/src/ui/public/topology.html
Applying relevant commits from 1.x and some minor fix.
=> [STORM-2427] Fix event logger enable disable UI buttons

storm-core/src/clj/org/apache/storm/daemon/executor.clj
Issue: https://issues.apache.org/jira/browse/STORM-2440
=> [STORM-2440] Prevent KafkaSpout from hanging under certain Kafka failure scenarios

external/storm-kafka-client/README.md
[https://issues.apache.org/jira/browse/STORM-2442](url)
The Usage Example in storm-kafka-client's README.md is Incorrect in some place.For example, This variables ,“kafkaSpoutConfig,kafkaSpoutStreams,kafkaConsumerProps,tuplesBuilder,retryService”, should be defined before it is used.And I think "props" should be named kafkaConsumerProps as there is a Map named kafkaConsumerProps .
=> [STORM-2442]modify the Usage Examples in storm-kafka-client's README.md

storm-core/src/jvm/org/apache/storm/Config.java, storm-core/test/jvm/org/apache/storm/TestConfigValidate.java
https://issues.apache.org/jira/browse/STORM-2429
=> STORM-2429: Properly validate supervisor.scheduler.meta

external/storm-cassandra/README.md, external/storm-cassandra/pom.xml, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/executor/AsyncExecutor.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/executor/AsyncResultSetHandler.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/query/AyncCQLResultSetValuesMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraBackingMap.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/CassandraMapStateFactory.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/MapStateFactoryBuilder.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/NonTransactionalTupleStateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/OpaqueTupleStateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/SerializedStateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/SimpleStateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/SimpleTuple.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/StateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/TransactionalTupleStateMapper.java, external/storm-cassandra/src/main/java/org/apache/storm/cassandra/trident/state/TridentAyncCQLResultSetValuesMapper.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/testtools/EmbeddedCassandraResource.java, external/storm-cassandra/src/test/java/org/apache/storm/cassandra/trident/MapStateTest.java, external/storm-cassandra/src/test/resources/cassandra.yaml
STORM-1369: Add MapState implementation to storm-cassandra.
https://issues.apache.org/jira/browse/STORM-1369
=> STORM-1369: Add MapState implementation to storm-cassandra.

docs/storm-mongodb.md
[https://issues.apache.org/jira/browse/STORM-2464](url)
storm-mongodb.md is out of date.For example,there is a new method in MongoMapper,but there isn't description in storm-mongodb.md. So ,storm-mongodb.md should be updated to be as same as storm-mongodb's README.md.
=> [STORM-2464] update storm-mongodb.md

storm-multilang/javascript/src/main/resources/resources/storm.js
Logging now supports logging levels (trace, debug, info, …warn and error).
Logging methods now accept multiple arguments and argument types are not restricted.
Some style fixes to make it more consistent.
=> STORM-2435: Logging levels and consistency with console.log etc

CHANGELOG.md, storm-client/src/jvm/org/apache/storm/metric/SystemBolt.java
* Add new metric
* Java8-ify two existing metrics
=> [STORM-2471] Add metric for thread count.

external/README.md
This is a really minor change to fix the file markdown format.
=> STORM-2474: fix external README format

docs/storm-hbase.md, docs/storm-hdfs.md, external/storm-hbase/README.md, external/storm-hdfs/README.md
[https://issues.apache.org/jira/browse/STORM-2480](url)
As "principal" could be right in kerberos, "principle" should be modified to "principal".
=> [STORM-2480] principle should be modified to principal

pom.xml, storm-submit-tools/pom.xml, storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/AetherUtils.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/RepositorySystemFactory.java, storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/AetherUtilsTest.java, storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/DependencyResolverTest.java
* this resolves NPE issue on Aether and helps showing proper error message
* this also fixes the bug which dependencies root directories does not exist
* after the patch it will create the directory if not found
=> STORM-2481 Upgrade Aether version to resolve Aether bug BUG-451566

external/storm-submit-tools/pom.xml, external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/AetherUtils.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/RepositorySystemFactory.java, external/storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/AetherUtilsTest.java, external/storm-submit-tools/src/test/java/org/apache/storm/submit/dependency/DependencyResolverTest.java, pom.xml
* this resolves NPE issue on Aether and helps showing proper error message
* this also fixes the bug which ouurs when dependencies root directories does not exist
* after the patch it will create the directory if not found
=> STORM-2481 Upgrade Aether version to resolve Aether bug BUG-451566 (1.x)

integration-test/README.md
DemoTest.java link in integration-test README.md fixed
=> Fixed DemoTest.java link

bin/storm.py, docs/Classpath-handling.md, docs/Command-line-client.md, docs/Running-topologies-on-a-production-cluster.md, docs/Setting-up-a-Storm-cluster.md, docs/index.md, storm-core/src/jvm/org/apache/storm/daemon/supervisor/BasicContainer.java
Backport of PR #2094 to 1.x-branch.
=> [STORM-2191] shorten classpaths by using wildcards

storm-core/src/clj/org/apache/storm/daemon/logviewer.clj
This fix is not required in master
=> [STORM-2498] Fix Download Full File link in 1.x branch

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java
Kafka maintains the spout progress (offsets for partitions) which can hold a value which no longer exists (or offset+1 doesn't exist) in the topic due to following reasons
Topology stopped processing (or died) & topic got compacted (cleanup.policy=compact) leaving offset voids in the topic.
Topology stopped processing (or died) & Topic got cleaned up (cleanup.policy=delete) and the offset.
When the topology starts processing again (or restarted), the spout logic suggests that the next offset has to be (committedOffset+1) for the spout to make progress, which will never be the case as (committedOffset+1) has been removed from the topic and will never be acked.
**OffsetManager.java**
```
if (currOffset == nextCommitOffset + 1) {
found = true;
nextCommitMsg = currAckedMsg;
nextCommitOffset = …
```
=> [STORM-2505] Spout to support topic compaction

external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractAutoCreds.java
@HeartSaVioR , please take a look.
=> STORM-2519: Modify AbstractAutoCreds to look for configKeys in both nimbus and topology configs.

external/storm-eventhubs/README.md, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/BinaryEventDataScheme.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/EventDataScheme.java, external/storm-eventhubs/src/main/java/org/apache/storm/eventhubs/spout/FieldConstants.java
This PR adds a serialization scheme for eventhub systemproperties. There is also a bug fix in an existing serialization scheme which violates the schema setting.
=> STORM-2499: Add Serialization plugin for EventHub System Properties

storm-core/src/jvm/org/apache/storm/blobstore/BlobStoreAclHandler.java
* if ACLs have both empty name and user, discard empty name ACLs
* add default ACL for user when neither empty name nor user ACL exists
* populate empty name ACLs to users in Subject: set name to user for each
PR for master : #2120
=> (1.x) STORM-2518 Handles empty name for "USER type" ACL when normalizing ACLs

storm-client/src/jvm/org/apache/storm/blobstore/BlobStoreAclHandler.java
* if ACLs have both empty name and user, discard empty name ACLs
* add default ACL for user when neither empty name nor user ACL exists
* populate empty name ACLs to users in Subject: set name to user for each
PR for 1.x : #2121
=> STORM-2518 Handles empty name for "USER type" ACL when normalizing ACLs

sql/README.md
I have a question, in the `Current Limitations` section, you mention `Windowing is yet to be implemented`,  what does it mean?
=> nothing but fix one word

storm-core/src/clj/org/apache/storm/daemon/common.clj, storm-core/src/clj/org/apache/storm/daemon/nimbus.clj, storm-core/src/clj/org/apache/storm/testing.clj, storm-core/src/jvm/org/apache/storm/StormSubmitter.java, storm-core/src/jvm/org/apache/storm/generated/StormTopology.java, storm-core/src/jvm/org/apache/storm/topology/TopologyBuilder.java, storm-core/src/jvm/org/apache/storm/utils/Utils.java, storm-core/src/py/storm/ttypes.py, storm-core/src/storm.thrift
=> STORM-2448:  Add in Storm and JDK versions when submitting a topology

external/storm-jdbc/src/main/java/org/apache/storm/jdbc/bolt/AbstractJdbcBolt.java
* also fixed some checkstyle violations
=> STORM-2527 Initialize java.sql.DriverManager earlier to avoid deadlock

pom.xml
@HeartSaVioR can you please review.
=> STORM-2528: Bump log4j version to 2.8.2

storm-core/test/clj/integration/org/apache/storm/integration_test.clj
https://issues.apache.org/jira/browse/STORM-2535
=> STORM-2535: Replace test-reset-timeout with a more reliable test

external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/format/TestSimpleFileNameFormat.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java, storm-client/src/jvm/org/apache/storm/Config.java, storm-client/src/jvm/org/apache/storm/daemon/Task.java, storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java, storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java, storm-client/src/jvm/org/apache/storm/task/TopologyContext.java, storm-client/src/jvm/org/apache/storm/utils/ConfigUtils.java, storm-client/src/jvm/org/apache/storm/utils/Utils.java, storm-server/src/main/java/org/apache/storm/Testing.java, storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/SupervisorUtils.java, storm-server/src/main/java/org/apache/storm/localizer/Localizer.java, storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java, storm-server/src/test/java/org/apache/storm/localizer/LocalizerTest.java
=> STORM-2543: Let Topology query if blobs have changed

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutMessageId.java
Equivalent to STORM-1848 and https://github.com/apache/storm/pull/1428
=> STORM-2552: KafkaSpoutMessageId should be serializable

external/storm-redis/pom.xml, external/storm-redis/src/main/java/org/apache/storm/redis/common/config/JedisClusterConfig.java, external/storm-redis/src/main/java/org/apache/storm/redis/common/container/JedisCommandsContainerBuilder.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterMapState.java, external/storm-redis/src/main/java/org/apache/storm/redis/trident/state/RedisClusterState.java
Upgrade Jedis version to 2.9.0, and modify some api for password support in JedisCluster
=> STORM-2553:  Add support for password in JedisCluster

storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
https://github.com/apache/storm/blob/master/storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java#L225
The "userCons.setAccessible(true)" invokes constructor of a package private class bypassing the Java access control checks and raising red flags in our internal security scans.
The "loginUserFromSubject(Subject subject)" has been added to UGI (https://issues.apache.org/jira/browse/HADOOP-10164) and available since Hadoop version 2.3 released over three years ago (http://hadoop.apache.org/releases.html).
I think the workaround is no longer required since the case will not happen when using hadoop-common versions >= 2.3
@revans2 , could you take a look ?
=> [STORM-2563] Remove the workaround to handle missing UGI.loginUserFromSubject

storm-client/src/jvm/org/apache/storm/security/auth/ThriftClient.java
Add socket timeout for Thrift Client.
=> STORM-2551: Thrift client socket timeout

external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractAutoCreds.java, external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/AutoHBase.java, external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/HBaseSecurityUtil.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/HBaseClient.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/Utils.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/state/HBaseMapState.java
Please refer [STORM-2555](http://issues.apache.org/jira/browse/STORM-2555) for more details.
There had been code block for handling impersonation, but actually it didn't work.
Please review and comment, thanks in advance.
PR for master branch: #2160
=> (1.x) STORM-2555 handle impersonation properly for HBase delegation token

external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractHadoopAutoCreds.java, external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/AutoHBaseNimbus.java, external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/HBaseSecurityUtil.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/HBaseClient.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/Utils.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/trident/state/HBaseMapState.java
Please refer [STORM-2555](http://issues.apache.org/jira/browse/STORM-2555) for more details.
There had been code block for handling impersonation, but actually it didn't work.
Please review and comment, thanks in advance.
PR for 1.x branch: #2171
=> STORM-2555 handle impersonation properly for HBase delegation token

bin/storm.py, external/storm-submit-tools/pom.xml, external/storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/AetherUtils.java, external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
* add options to storm.py and dependency resolver: --proxyUrl, --proxyUsername, --proxyPassword
* address some checkstyle issue for storm-submit-tool
=> (1.x) STORM-2598 Add proxy server option for dependency resolver

bin/storm.py, storm-submit-tools/pom.xml, storm-submit-tools/src/main/java/org/apache/storm/submit/command/DependencyResolverMain.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/AetherUtils.java, storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/DependencyResolver.java
* add options to storm.py and dependency resolver: --proxyUrl, --proxyUsername, --proxyPassword
* address some checkstyle issue for storm-submit-tool
=> STORM-2598 Add proxy server option for dependency resolver

storm-server/src/main/java/org/apache/storm/daemon/supervisor/BasicContainer.java
https://issues.apache.org/jira/browse/STORM-2599
=> STORM-2599: Fix BasicContainer wildcard classpath on Windows

docs/State-checkpointing.md, external/storm-hbase/pom.xml, external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/mapper/HBaseProjectionCriteria.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/ColumnList.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/HBaseClient.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/state/HBaseKeyValueState.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/state/HBaseKeyValueStateIterator.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/state/HBaseKeyValueStateProvider.java, external/storm-hbase/src/test/java/org/apache/storm/hbase/state/HBaseClientTestUtil.java, external/storm-hbase/src/test/java/org/apache/storm/hbase/state/HBaseKeyValueStateIteratorTest.java, external/storm-hbase/src/test/java/org/apache/storm/hbase/state/HBaseKeyValueStateProviderTest.java, external/storm-hbase/src/test/java/org/apache/storm/hbase/state/HBaseKeyValueStateTest.java, storm-client/test/jvm/org/apache/storm/state/DefaultStateSerializerTest.java
* Implement HBase state backend
* picked Redis state backend implementation
* also implemented state iterator
* Added 'how to set up' to State-checkpointing doc
* address @arunmahadevan's review comment
* also fixed some checkstyle issues
This is a forward porting of #1970 against master branch, hence same except some fixes for check style. #1970 already got +1.
=> STORM-2383 [storm-hbase] Support HBase as state backend

examples/storm-starter/src/jvm/org/apache/storm/starter/ThroughputVsLatency.java, storm-client/src/jvm/org/apache/storm/daemon/metrics/SpoutThrottlingMetrics.java, storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java, storm-client/src/jvm/org/apache/storm/utils/NimbusClient.java
I still need to add these to the docs, but I wanted to capture my progress before the long weekend.
=> STORM-2610: Fixed the metrics

external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java, external/storm-kafka/src/test/org/apache/storm/kafka/KafkaTestBroker.java, external/storm-kafka/src/test/org/apache/storm/kafka/PartitionManagerTest.java
@HeartSaVioR  this PR includes fixes for https://issues.apache.org/jira/browse/STORM-2608 targeting the master branch per https://github.com/apache/storm/pull/2190
=> STORM-2608 Remove any pending offsets that are no longer valid (master)

external/storm-mongodb/README.md, external/storm-mongodb/pom.xml, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/AbstractMongoBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoInsertBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoLookupBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/bolt/MongoUpdateBolt.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/MongoDbClient.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/MongoUtils.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/QueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/SimpleQueryFilterCreator.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/MongoLookupMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/MongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/MongoUpdateMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoLookupMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/common/mapper/SimpleMongoUpdateMapper.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoMapState.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoState.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateFactory.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateQuery.java, external/storm-mongodb/src/main/java/org/apache/storm/mongodb/trident/state/MongoStateUpdater.java, sql/storm-sql-external/storm-sql-mongodb/src/test/org/apache/storm/sql/mongodb/TestMongoDataSourcesProvider.java
=> STORM-2589: Apply new code style to storm-mongodb

docs/Setting-up-a-Storm-cluster.md
I plan to do a separate pull request to the 1.x branch(s) too.
=> STORM-2620: Updated docs for JDK needed

sql/storm-sql-external/storm-sql-hdfs/pom.xml, sql/storm-sql-external/storm-sql-hdfs/src/jvm/org/apache/storm/sql/hdfs/HdfsDataSourcesProvider.java
=> STORM-2630: Apply new code style to storm-sql-hdfs

sql/storm-sql-external/storm-sql-mongodb/pom.xml, sql/storm-sql-external/storm-sql-mongodb/src/jvm/org/apache/storm/sql/mongodb/MongoDataSourcesProvider.java
=> STORM-2631: Apply new code style to storm-sql-mongodb

sql/storm-sql-external/storm-sql-kafka/pom.xml, sql/storm-sql-external/storm-sql-kafka/src/jvm/org/apache/storm/sql/kafka/KafkaDataSourcesProvider.java
=> STORM-2632: Apply new code style to storm-sql-kafka

sql/storm-sql-external/storm-sql-redis/pom.xml, sql/storm-sql-external/storm-sql-redis/src/jvm/org/apache/storm/sql/redis/RedisDataSourcesProvider.java
=> STORM-2633: Apply new code style to storm-sql-redis

storm-client/src/jvm/org/apache/storm/utils/DisruptorQueue.java
also fix the sojourn_time metric by using the new one.
=> STORM-2621: add tuple_population metric

storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java
1. add shutdown checking before connecting
2. add try-catch block for robustness.
=> [STORM-2653] Pacemaker code improvement

docs/SECURITY.md
[https://issues.apache.org/jira/browse/STORM-2657](https://issues.apache.org/jira/browse/STORM-2657)
There are several PRs about storm acl merged into master,so I update SECURITY.md.
=> [STORM-2657] Update SECURITY.MD

storm-client/src/jvm/org/apache/storm/Config.java, storm-client/src/jvm/org/apache/storm/cluster/StormClusterStateImpl.java, storm-client/src/jvm/org/apache/storm/generated/Nimbus.java, storm-client/src/jvm/org/apache/storm/generated/StormBase.java, storm-client/src/jvm/org/apache/storm/generated/TopologyPageInfo.java, storm-client/src/jvm/org/apache/storm/generated/TopologySummary.java, storm-client/src/py/storm/Nimbus.py, storm-client/src/py/storm/ttypes.py, storm-client/src/storm.thrift, storm-core/src/clj/org/apache/storm/ui/core.clj, storm-core/src/ui/public/templates/index-page-template.html, storm-core/src/ui/public/templates/owner-page-template.html, storm-core/src/ui/public/templates/topology-page-template.html, storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Display topology version on UI.
see: https://issues.apache.org/jira/browse/STORM-1347
=> [STORM-1347] display topology version on UI

docs/Metrics.md, storm-client/src/jvm/org/apache/storm/daemon/metrics/ErrorReportingMetrics.java, storm-client/src/jvm/org/apache/storm/executor/Executor.java, storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java, storm-client/src/jvm/org/apache/storm/executor/bolt/BoltOutputCollectorImpl.java, storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java, storm-client/src/jvm/org/apache/storm/executor/spout/SpoutOutputCollectorImpl.java
See: https://issues.apache.org/jira/browse/STORM-2672
Add a metric for calls to reportError.
=> [STORM-2672] Expose a metric for calls to reportError()

storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
Quick fix on a few typos in Worker.java
=> Fix typos in Worker.java

storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
See: https://issues.apache.org/jira/browse/STORM-2703
Keep supervisor from crashing when exception happens because of blob permission exception (or KeyNotFound exception). The code change here will bring state machine back to `MachineState.EMPTY` when that happens and start over.
So, if the blob ACL permission is fixed (or the key is uploaded) during the runtime, the topology will start to work; if the topology is killed, the Slot is able to continue to deal with other assignment.
=> [STORM-2703] Handle ExecutionException in handleWaitingForBlobLocalization state

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/EmptyKafkaTupleListener.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaTupleListener.java
=> STORM-2694: STORM-Add KafkaTupleListener to storm-kafka-client

storm-core/src/jvm/org/apache/storm/command/ListTopologies.java
I think we should output topology id from the storm list command for debugging purpose.
JIRA: https://issues.apache.org/jira/browse/STORM-2717
=> [STORM-2717] Output topology Id from storm list command

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestWritersMap.java
[JIRA-STORM-2732](https://issues.apache.org/jira/browse/STORM-2732)
`WritersMap` serves as an LRU cache for `maxWriters` number of `Writer`s. But it doesn't close the removed writer, which could lead to potential data loss.
The exception handling is really hard. The bolt behaviors depend on later on situations. I don't know how to address the exception handling currently so I chose to just log the error which is also what we have done elsewhere in this class.
--------
I wanted to discuss about what would happen. Please correct me if I am wrong.
If `eldest.getValue().close()` failed, assume next tuple invokes SyncPolicy but the sync failed, then the bolt will call `collector.fail()` on all the tuples in `tupleBatch`. In this case, all those tuples will be transferred again, which gives the …
=> [STORM-2732] Close the eldest writer before removing it from WritersMap

external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/HBaseSecurityUtil.java
update HBaseSecurityUtil singleton to fix double_checked locking
See url link for details: http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html
=> STORM-2750：fix double_checked locking

storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
A trivial improvement: Add logging to monitor how long scheduling is taking
https://issues.apache.org/jira/browse/STORM-2743
A test:
=> [STORM-2743] Add logging and metrics to monitor how long scheduling is taking

storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
=> Quick fix: typo in LogviewerServer

conf/defaults.yaml, storm-client/src/jvm/org/apache/storm/Config.java, storm-core/test/clj/org/apache/storm/nimbus_test.clj, storm-server/pom.xml, storm-server/src/main/java/org/apache/storm/DaemonConfig.java, storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/BlacklistScheduler.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/Sets.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/reporters/IReporter.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/reporters/LogReporter.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/strategies/DefaultBlacklistStrategy.java, storm-server/src/main/java/org/apache/storm/scheduler/blacklist/strategies/IBlacklistStrategy.java, storm-server/src/test/java/org/apache/storm/scheduler/blacklist/FaultGenerateUtils.java, storm-server/src/test/java/org/apache/storm/scheduler/blacklist/TestBlacklistScheduler.java, storm-server/src/test/java/org/apache/storm/scheduler/blacklist/TestUtilsForBlacklistScheduler.java
This is rebased version of #1674 with addressing latest review comments from me.
Sure the credit for providing great stuff should go to @nilday. :)
Since now I can't give +1 to my patch, it would be really appreciated if someone could review and do some manual tests.
Thanks in advance.
This closes #1674
=> STORM-2083 Blacklist scheduler

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStore.java
If the changes look good I am happy to put up pull requests for other branches too.
=> STORM-2764:  Only login the user if not already done

storm-core/src/ui/public/logviewer.html, storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
JIRA: https://issues.apache.org/jira/browse/STORM-2718
Display some messages on logviewer front page so that the first-time users can be less confused.
=> [STORM-2718] Show some messages on Logviewer index page

pom.xml
See https://issues.apache.org/jira/browse/STORM-2767
=> STORM-2767: Disable Surefire stack trace trimming

docs/storm-kafka-client.md, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaUnitSetupHelper.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java
See https://github.com/apache/storm/pull/2249
The first commit is a cherry pick of https://github.com/apache/storm/commit/48f6969027e7b02a5b9220577189d3911aa2226d, the second commit should contain the actual changes for this branch.
I'll squash them before merging.
=> STORM-2648/STORM-2357 1.x

storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java
=> Quick fix: typo in WorkerState class

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoff.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutRetryService.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryExponentialBackoffTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
This is https://github.com/apache/storm/pull/2356 plus one commit to fix conflicts.
=> STORM-2666 (1.1.x)

external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java
Targeting master for #2370 
FYI @srdo 
(cherry picked from commit 8db4e90)
=> STORM-2775 (master) Update kafkaPartition metric names

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
Same as https://github.com/apache/storm/pull/2369 but for 1.1.x. The changes since the 1.x branch are in the last commit. Will squash once reviewed.
=> STORM-2607 1.1.x

flux/flux-examples/pom.xml, pom.xml, storm-client/pom.xml, storm-core/pom.xml, storm-core/src/clj/org/apache/storm/ui/core.clj, storm-core/src/clj/org/apache/storm/ui/helpers.clj, storm-core/src/jvm/org/apache/storm/ui/UIHelpers.java, storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java, storm-webapp/src/main/java/org/apache/storm/daemon/drpc/DRPCServer.java
We need to upgrade to jetty latest version. The current jetty version is really old
=> [STORM-1927] upgrade to jetty 9

pom.xml
I noticed that the indent of this dependency doesn't match the rest of the pom.
=> Fix pom dependency indent

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/OffsetManager.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutCommitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRebalanceTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/builders/SingleTopicKafkaSpoutConfiguration.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/internal/OffsetManagerTest.java
1.x version of https://github.com/apache/storm/pull/2156.
The changes are in the last commit. Will squash once reviewed.
=> STORM-2549 (1.x)

storm-core/test/clj/integration/org/apache/storm/integration_test.clj
Pull https://github.com/apache/storm/pull/2141 to 1.x
=> STORM-2535: Replace test-reset-timeout (1.x)

storm-client/src/jvm/org/apache/storm/security/auth/kerberos/KerberosSaslTransportPlugin.java
https://issues.apache.org/jira/browse/STORM-2806
With this patch, users can add `disableLoginCache=true` to the jaas.conf file to disable the login cache.  For example,
```
StormClient {
com.sun.security.auth.module.Krb5LoginModule required
doNotPrompt=true
useTicketCache=true
disableLoginCache=true
serviceName="gstorm";
};
```
=> [STORM-2806] Give users an option to disable the login cache

external/storm-hdfs/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImpl.java, external/storm-hdfs/src/main/java/org/apache/storm/hdfs/bolt/AbstractHdfsBolt.java, external/storm-hdfs/src/main/java/org/apache/storm/hdfs/spout/HdfsSpout.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestFixedAvroSerializer.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/avro/TestGenericAvroSerializer.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/blobstore/BlobStoreTest.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/blobstore/HdfsBlobStoreImplTest.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/AvroGenericRecordBoltTest.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestHdfsBolt.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/bolt/TestSequenceFileBolt.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestDirLock.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestFileLock.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSemantics.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestHdfsSpout.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/spout/TestProgressTracker.java, external/storm-hdfs/src/test/java/org/apache/storm/hdfs/testing/MiniDFSClusterRule.java
1.x version of https://github.com/apache/storm/pull/2413. Will squash after review.
Please use ?w=1 in the diff url, or this will be a bad time to review.
=> STORM-2810: Fix resource leaks in storm-hdfs tests (1.x)

storm-core/src/clj/org/apache/storm/daemon/logviewer.clj, storm-core/src/clj/org/apache/storm/ui/helpers.clj
Similar to https://github.com/apache/storm/pull/2420 . This is for  1.x-branch.
=> [STORM-2814] Logviewer HTTP server should return 403 if the user is unauthorized

storm-core/src/clj/org/apache/storm/daemon/logviewer.clj, storm-core/src/clj/org/apache/storm/ui/core.clj, storm-core/src/clj/org/apache/storm/ui/helpers.clj
Portback of https://github.com/apache/storm/pull/2421
=> [STORM-2815] UI HTTP server should return 403 if the user is unauthorized (1.x)

storm-client/pom.xml, storm-client/src/jvm/org/apache/storm/Constants.java, storm-server/pom.xml, storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/timer/SupervisorHeartbeat.java, storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java, storm-server/src/main/java/org/apache/storm/scheduler/ExecutorDetails.java, storm-server/src/main/java/org/apache/storm/scheduler/ISchedulingState.java, storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignment.java, storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignmentImpl.java, storm-server/src/main/java/org/apache/storm/scheduler/SupervisorDetails.java, storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/NormalizedResourceOffer.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/NormalizedResourceRequest.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/NormalizedResources.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceUtils.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/DefaultResourceAwareStrategy.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/GenericResourceAwareStrategy.java, storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/TestResourceAwareScheduler.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/TestUtilsForResourceAwareScheduler.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java
The goal here was at a minimum have a clear way to know if the resources were normalized or not, and secondarily to have something a bit better performance wise from a HashMap.
=> STORM-2813: Use a class for normalized resources not a map.

storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
https://issues.apache.org/jira/browse/STORM-2834
The condition of `scheduler instanceof ResourceAwareScheduler` or `scheduler instanceof MultitenantScheduler` will never be true because the scheduler is wrapped as BlacklistScheduler
=> [STORM-2834] getOwnerResourceSummaries not working properly because scheduler is wrapped as BlacklistScheduler

docs/index.md
This is very minor change. Fixed links for YARN&Kubernetes Integration.
=> STORM-2842: Fixed links for YARN&Kubernetes Integration

docs/storm-kafka.md
=> Quick fix: correcting markdown format

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/ManualPartitionSubscription.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscriptionTest.java
https://github.com/apache/storm/pull/2451
Will squash before merge. Only changes are replacing Mockito 2 with Mockito 1 in the test.
=> STORM-2850 1.x

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/MaxUncommittedOffsetTest.java
See https://github.com/apache/storm/pull/2453
Will squash once reviewed.
=> STORM-2851 1.x

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/ManualPartitionSubscription.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutEmitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutLogCompactionSupportTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutReactivationTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutRetryLimitTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaSpoutTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaUnitSetupHelper.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SpoutWithMockedConsumerSetupHelper.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/subscription/ManualPartitionSubscriptionTest.java
1.x for https://github.com/apache/storm/pull/2454
=> STORM-2847 1.x

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutAbstractTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutSingleTopicTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutTopologyDeployActivateDeactivateTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/SingleTopicKafkaUnitSetupHelper.java
https://github.com/apache/storm/pull/2481 for 1.x
=> STORM-2869 1.x

storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
We do not make a transaction when supervisor clean up local files for a overdue storm, if an exception occurred during deleting storm-code/ser/jar, an overdue local assignment will be left on disk.
Then when supervisor restart from the exception above, the slots will be initial and container will be recovered from LocalAssignments, the blob store will fetch the files from Nimbus/Master, but will get a KeyNotFoundException, and supervisor collapses again.
So lets make the current assignment null when we first initial a Slot and recover container from local assignment but there are no local needed files, just let the supervisor clean up the local assignment and Nimbus/master will reassign it finally.
This is the JIRA issue [STORM-2879](https://issues.apache.org/jira/browse/STORM-2879).
=> [STORM-2879] Supervisor collapse continuously when there is a expired assignment for overdue storm

external/storm-autocreds/src/main/java/org/apache/storm/common/AbstractHadoopAutoCreds.java, external/storm-hive/README.md
=> STORM-2903: Fix possible NullPointerException in AbstractHadoopAutoCreds and doc cleanups

storm-core/src/jvm/org/apache/storm/Config.java, storm-core/src/jvm/org/apache/storm/spout/ShellSpout.java, storm-core/src/jvm/org/apache/storm/task/ShellBolt.java, storm-core/src/jvm/org/apache/storm/utils/DefaultShellLogHandler.java, storm-core/src/jvm/org/apache/storm/utils/ShellLogHandler.java, storm-core/src/jvm/org/apache/storm/utils/ShellUtils.java, storm-core/test/jvm/org/apache/storm/utils/DefaultShellLogHandlerTest.java, storm-core/test/jvm/org/apache/storm/utils/ShellUtilsTest.java
Connected to https://issues.apache.org/jira/browse/STORM-2862; 1.1.x version of apache/storm#2475.
=> STORM-2862: More flexible logging in multilang

storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
@HeartSaVioR 
Really sorry that i copied the code from previous PR and miss one line, i will try to use rebase for the later on PRS' commits.
Please help me to merge this in and i'm doing the 1.x-branch patch, really thx.
The original PR is here: [#2522](https://github.com/apache/storm/pull/2522).
=> [STORM-2901] Fix BlobSynchronizer zk-client non set problem

conf/defaults.yaml, storm-core/src/jvm/org/apache/storm/Config.java, storm-core/src/ui/public/component.html, storm-core/src/ui/public/index.html, storm-core/src/ui/public/topology.html
Backporting this Storm UI change which has already been merged in master.
JIRA ticket: https://issues.apache.org/jira/browse/STORM-2877
Merged PR in master branch: #2505
=> STORM-2877: Backport for 1.x-branch

docs/storm-kafka-client.md, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/internal/CommitMetadataManager.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutConfigTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java, storm-core/src/jvm/org/apache/storm/annotation/InterfaceStability.java
The backport changes are in separate commits. Let me know when I should squash and merge.
=> Storm 2913 2914 1.x

external/storm-hive/src/test/java/org/apache/storm/hive/bolt/TestHiveBolt.java
* while mocking partially, oddly it calls real method intermittently which breaks test
Please refer https://issues.apache.org/jira/browse/STORM-2841 to see the detail of failure.
I guess this is clean cherry-picking for 1.x version lines. I'll submit another one if not.
=> STORM-2841 Use extended class instead of partial mock for TestHiveBolt

external/storm-kafka/README.md, external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/OpaqueTridentKafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TransactionalTridentKafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/trident/TridentKafkaState.java
https://issues.apache.org/jira/browse/STORM-2952
Please let this sit for a few days before merging, to give people time to object. We had a discussion thread about doing this, but it's good not to sneak a change like this by quietly.
=> STORM-2952: Deprecate storm-kafka

external/storm-kafka-migration/README.md, external/storm-kafka-migration/pom.xml, external/storm-kafka-migration/src/main/conf/example-spout-migration-config.yaml, external/storm-kafka-migration/src/main/conf/example-trident-spout-migration-config.yaml, external/storm-kafka-migration/src/main/java/org/apache/storm/kafka/migration/KafkaSpoutMigration.java, external/storm-kafka-migration/src/main/java/org/apache/storm/kafka/migration/KafkaTridentSpoutMigration.java, external/storm-kafka-migration/src/main/java/org/apache/storm/kafka/migration/MapUtil.java, pom.xml
Master version of https://github.com/apache/storm/compare/master...srdo:STORM-2896-master?expand=1
=> STORM-2896 master

pom.xml
1.x version of https://github.com/apache/storm/pull/2567
=> STORM-2967: Upgrade jackson to latest version

pom.xml
https://issues.apache.org/jira/browse/STORM-2981
=> STORM-2981: Upgrade Curator to 4.0.1

examples/storm-starter/README.markdown
https://issues.apache.org/jira/browse/STORM-2980
https://issues.apache.org/jira/browse/STORM-2447 made some changes to local mode, we should reflect these in the storm-starter documentation.
=> STORM-2980: Update storm-starter docs concerning local mode

external/storm-eventhubs/pom.xml, external/storm-kafka-migration/pom.xml, external/storm-kafka-monitor/pom.xml, external/storm-kafka/pom.xml, external/storm-kinesis/pom.xml, pom.xml, storm-core/pom.xml, storm-server/pom.xml
https://issues.apache.org/jira/browse/STORM-2978
=> STORM-2978: Fix Zookeeper transitive dependency version to 3.4.6

storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/LogviewerServer.java
https://issues.apache.org/jira/browse/STORM-2986
This will fix NPE in LogCleaner
=> [STORM-2986] create worker artifacts directory if not exists

storm-client/src/jvm/org/apache/storm/cluster/PaceMakerStateStorage.java, storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java, storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClientPool.java
Explained in https://issues.apache.org/jira/browse/STORM-2987
=> [STORM-2987] PaceMakerStateStorage should deal with InterruptedException correctly

bin/flight.bash
port of #2607 to master branch
=> STORM-3011 Use default bin path in flight.bash if JAVA_HOME is undefined

storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java
by returning results from resending HBMessage
Detailed explanation at  https://issues.apache.org/jira/browse/STORM-3012
=> [STORM-3012] Fix the issue that nimbus will crash if pacemaker is restarted

docs/SECURITY.md
[https://issues.apache.org/jira/browse/STORM-2997](https://issues.apache.org/jira/browse/STORM-2997)
Add logviewer ssl module in SECURITY.md like UI and DRPC
=> [STORM-2997] Add logviewer ssl module in SECURITY.md

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutMessageId.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutNullTupleTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/config/builder/SingleTopicKafkaSpoutConfiguration.java
Hello,
Let's kick off this pull request.
Unit tests for null tuples were missing. I'm in the process of adding them.
I'll update this PR asap. Meanwhile, these seem to be the necessary changes
=> STORM-2994 KafkaSpout doesn't  commit null tuples offsets

docs/metrics_v2.md
=> spelling fixes

external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java, external/storm-hive/src/main/java/org/apache/storm/hive/bolt/mapper/DelimitedRecordHiveMapper.java, external/storm-hive/src/main/java/org/apache/storm/hive/common/HiveWriter.java, external/storm-hive/src/test/java/org/apache/storm/hive/bolt/TestHiveBolt.java, external/storm-hive/src/test/java/org/apache/storm/hive/common/TestHiveWriter.java
* mock/extend any needed classes to avoid interacting with Hive itself
=> STORM-3022 Decouple storm-hive UTs with Hive

external/storm-hive/pom.xml, external/storm-hive/src/main/java/org/apache/storm/hive/bolt/HiveBolt.java, external/storm-hive/src/main/java/org/apache/storm/hive/bolt/mapper/DelimitedRecordHiveMapper.java, external/storm-hive/src/main/java/org/apache/storm/hive/common/HiveWriter.java, external/storm-hive/src/test/java/org/apache/storm/hive/bolt/TestHiveBolt.java, external/storm-hive/src/test/java/org/apache/storm/hive/common/TestHiveWriter.java, pom.xml
* mock/extend any needed classes to avoid interacting with Hive itself
This patch is for 1.x-branch. Patch for master branch is here: #2626
=> STORM-3022 Decouple storm-hive UTs with Hive (1.x)

storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
https://issues.apache.org/jira/browse/STORM-3044
=> [STORM-3044] AutoTGT should check if a TGT is address-less and reject if it's not

external/storm-autocreds/src/main/java/org/apache/storm/hbase/security/HBaseSecurityUtil.java, external/storm-hbase/src/main/java/org/apache/storm/hbase/common/Utils.java
https://issues.apache.org/jira/browse/STORM-3029
=> [STORM-3029] don't use keytab based login for hbase if AutoTGT is used.

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpout.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/NullRecordTranslator.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutNullTupleTest.java
https://issues.apache.org/jira/browse/STORM-3059
1.x version of https://github.com/apache/storm/pull/2662
=> Storm 3059 1.x

bin/storm.py, pom.xml, storm-core/pom.xml
This is for disruptor and java.jmx
=> STORM-3061: Remove unused core dependencies

docs/Hooks.md
https://issues.apache.org/jira/browse/STORM-3089
=> STORM-3089: Describe worker hooks in documentation

storm-client/src/jvm/org/apache/storm/StormSubmitter.java
https://issues.apache.org/jira/browse/STORM-3111
=> STORM-3111: Remove dead code in StormSubmitter related to local mode

pom.xml
https://issues.apache.org/jira/browse/STORM-3113
=> STORM-3113: Upgrade Mockito to fix Java 10 incompatibility

external/storm-hdfs-blobstore/pom.xml, pom.xml
https://issues.apache.org/jira/browse/STORM-3114
=> STORM-3114: Ban jdk.tools

storm-core/src/jvm/org/apache/storm/command/AdminCommands.java, storm-core/src/jvm/org/apache/storm/command/CLI.java, storm-core/src/jvm/org/apache/storm/shade/org/apache/zookeeper/ZkCli.java
Something that we have needed for a while to help with fixing issues and debugging.
=>  STORM-3115: Add zookeeper CLI to admin command 

storm-core/src/jvm/org/apache/storm/daemon/supervisor/timer/UpdateBlobs.java
There's race condition between "async localizer" and "update blob" timer thread.
When worker is shutting down, reference count for blob will be 0 and supervisor will remove actual blob file. There's also "update blob" timer thread which tries to keep blobs updated for downloaded topologies. While updating topology it should read some of blob files already downloaded assuming these files should be downloaded before, and the assumption is broken because of async localizer.
@arunmahadevan suggested an approach to fix this: "updateBlobsForTopology" can just catch the FIleNotFoundException and skip updating the blobs in case it can't find the stormconf, and the approach looks simplest fix so I'll provide a patch based on suggestion.
Btw, it doesn't apply to master branch, since in master …
=> (1.x) STORM-3122 Avoid supervisor being crashed due to race condition between "async localizer" and "update blob" timer thread

storm-server/src/main/java/org/apache/storm/daemon/drpc/BlockingOutstandingRequest.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java, storm-server/src/main/java/org/apache/storm/daemon/supervisor/Supervisor.java, storm-server/src/main/java/org/apache/storm/localizer/AsyncLocalizer.java, storm-server/src/main/java/org/apache/storm/localizer/IOFunction.java, storm-server/src/main/java/org/apache/storm/localizer/LocalizedResource.java, storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java, storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedTopologyBlob.java, storm-server/src/main/java/org/apache/storm/utils/EnumUtil.java, storm-server/src/test/java/org/apache/storm/daemon/supervisor/SlotTest.java, storm-server/src/test/java/org/apache/storm/localizer/AsyncLocalizerTest.java
This is a supplement issue page to STORM-3099 (PR #2710), separating out refactoring work from newly implemented metrics.
A few misc bugs discovered during refactoring have been incorporated in this PR as well, including STORM-3126/3127.
=> [STORM-3125/3126/3127]: Refactoring components for Supervisor and DRPC

external/storm-kafka/src/jvm/org/apache/storm/kafka/KafkaSpout.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/PartitionManager.java, external/storm-kafka/src/jvm/org/apache/storm/kafka/ZkCoordinator.java, external/storm-kafka/src/test/org/apache/storm/kafka/TestUtils.java, external/storm-kafka/src/test/org/apache/storm/kafka/ZkCoordinatorTest.java
This pull request contains the same changes from https://github.com/apache/storm/pull/2726 that was merged in 1.x branch. As there are some conflicts during cherry-picking of these changes into 1.0.x/1.1.x branch this pull request is created for 1.0.x branch.
=> STORM-3090 - Fix bug when different topics use the same offset for a partition

storm-core/test/jvm/org/apache/storm/messaging/netty/NettyTest.java
Adding test as per discussion on https://github.com/apache/storm/pull/2643#issuecomment-385003933
=> STORM-3056: Add a test for quickly rebinding to a port

bin/storm.py, docs/Command-line-client.md, storm-core/src/jvm/org/apache/storm/command/AdminCommands.java, storm-core/src/jvm/org/apache/storm/command/CLI.java, storm-core/src/jvm/org/apache/storm/command/UploadCredentials.java, storm-core/test/jvm/org/apache/storm/command/TestCLI.java
This also fixes a bug in upload-credentials when it was translated to java by adding in optionalArg to CLI
=> STORM-3134: Improve upload-creds user experience

storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogCleaner.java
See https://issues.apache.org/jira/browse/STORM-3169 for details
=> STORM-3169: Correctly convert configured minutes to milliseconds

external/storm-kafka-client/src/main/java/org/apache/storm/kafka/bolt/KafkaBolt.java, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/bolt/PreparableCallback.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/bolt/KafkaBoltTest.java
[STORM-3175](https://issues.apache.org/jira/browse/STORM-3175)
=> STORM-3175 - Allow usage of custom Callback.

storm-server/src/main/java/org/apache/storm/metric/StormMetricsRegistry.java, storm-server/src/main/java/org/apache/storm/pacemaker/Pacemaker.java
This contains and address the issues in #2763. This should help standardize the process to register metrics and MetricSet in the future.
=> STORM-3157: General improvement to StormMetricsRegistry

storm-client/src/jvm/org/apache/storm/security/auth/ReqContext.java, storm-webapp/src/main/java/org/apache/storm/daemon/ui/filters/AuthorizedUserFilter.java
The changes to ReqContext are not needed.  I started to make a change there, and cleaned it up before realizing that it was not going to fix the problem, but I decided to leave the code cleanup in place.
I also fixed a few other issues with AuthorizedUserFilter including leaking a nimbus client, and not returning after aborting the request, which was resulting in an NPE in some cases.
=> STORM-3218: Return the correct error from AuthorizedUserFilter

storm-webapp/src/main/java/org/apache/storm/daemon/ui/filters/AuthorizedUserFilter.java
Full disclosure I am really just pushing back some changes that @govind-menon did, but was missed when the majority of UI changes going to java were put in open source.
=> STORM-3225: Use MediaType for check

storm-client/src/jvm/org/apache/storm/tuple/TupleImpl.java
See [Jira](https://issues.apache.org/jira/browse/STORM-3205) description for measurements and details
=> STORM-3205 Optimization in TuplImpl

storm-client/src/jvm/org/apache/storm/utils/IVersionInfo.java, storm-client/src/jvm/org/apache/storm/utils/SimpleVersion.java, storm-client/src/jvm/org/apache/storm/utils/Utils.java, storm-client/src/jvm/org/apache/storm/utils/VersionInfo.java, storm-client/test/jvm/org/apache/storm/utils/UtilsTest.java, storm-client/test/resources/storm-core-version-info.properties, storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java, storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/index.html, storm-webapp/src/main/java/org/apache/storm/daemon/ui/WEB-INF/templates/index-page-template.html
Also display the full version info from STORM-621
=>  STORM-3232: Display on the UI all versions of storm that are supported

docs/storm-hive.md, external/storm-hive/README.md
=> Replace docs reference to Flume with HiveBolt

storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/DirectoryCleaner.java, storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogCleaner.java, storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/WorkerLogs.java, storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/utils/LogCleanerTest.java, storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/utils/WorkerLogsTest.java
The empty directories are also deleted after they age out.
=> STORM-3245: Don't blow up if empty log dirs exist

storm-server/src/main/java/org/apache/storm/blobstore/BlobStoreUtils.java, storm-server/src/main/java/org/apache/storm/blobstore/LocalFsBlobStore.java
1.Bug fix for blob sync frequency with time unit error.
2.Bug fix for blob sync delete file, add catch NoSuchFileException.
3.Bug fix for blob sync update blob flie, add catch FileNotFoundException
=> [STORM-3252] Bug fix for blobstore sync

bin/storm.py
minor fix.
https://issues.apache.org/jira/browse/STORM-3264
=> [STORM-3264] fix "local variable referenced before assignment" in storm.py

pom.xml
See https://issues.apache.org/jira/browse/STORM-2891
=> STORM-2891: Upgrade checkstyle plugin to 3.0.0

pom.xml
https://issues.apache.org/jira/browse/STORM-3296
=> STORM-3296: Upgrade curator-test to avoid CURATOR-409

external/storm-kafka-monitor/src/main/java/org/apache/storm/kafka/monitor/NewKafkaSpoutOffsetQuery.java
Just complete information in three methods(toString , equals, hashCode).
=> STORM-3318: Complete information in Class NewKafkaSpoutOffsetQuery

dev-tools/travis/travis-script.sh
https://issues.apache.org/jira/browse/STORM-3325
=> STORM-3325: Move storm-webapp to Server module on travis, instead of Externals

storm-client/src/jvm/org/apache/storm/cluster/ClusterUtils.java, storm-client/src/jvm/org/apache/storm/utils/ConfigUtils.java, storm-client/src/jvm/org/apache/storm/utils/Utils.java, storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/webapp/LogviewerResource.java, storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java, storm-webapp/src/main/java/org/apache/storm/daemon/ui/resources/StormApiResource.java, storm-webapp/src/main/java/org/apache/storm/daemon/utils/UrlBuilder.java, storm-webapp/src/test/java/org/apache/storm/daemon/logviewer/handler/LogviewerLogSearchHandlerTest.java
https://issues.apache.org/jira/browse/STORM-3327
=> STORM-3327: Use UTF-8 for URL encoding in storm-webapp

external/storm-blobstore-migration/pom.xml, external/storm-hdfs/pom.xml, external/storm-mqtt/pom.xml, pom.xml
Confirmed modified URLs also exist.
=> [MINOR] Update repository URLs from http to https

storm-client/src/jvm/org/apache/storm/daemon/worker/WorkerState.java, storm-client/src/jvm/org/apache/storm/executor/Executor.java, storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java, storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
https://issues.apache.org/jira/browse/STORM-3320
=> STORM-3320: Ensure executors start when worker connections are ready

storm-client/test/jvm/org/apache/storm/utils/JCQueueTest.java
https://jira.apache.org/jira/browse/STORM-3343
=> STORM-3343: Fix flaky JCQueue test

external/storm-submit-tools/src/main/java/org/apache/storm/submit/dependency/Booter.java
PR for master: #2971 
This can be ported back to 1.1.x-branch as well.
=> [MINOR] Update maven repository URL to https (1.x)

examples/storm-hdfs-examples/pom.xml, examples/storm-hive-examples/pom.xml, examples/storm-mqtt-examples/pom.xml, examples/storm-pmml-examples/pom.xml, examples/storm-solr-examples/pom.xml, external/storm-autocreds/pom.xml, external/storm-blobstore-migration/pom.xml, external/storm-elasticsearch/pom.xml, external/storm-hdfs-blobstore/pom.xml, external/storm-hdfs/pom.xml, external/storm-hive/pom.xml, external/storm-jdbc/pom.xml, external/storm-mqtt/pom.xml, external/storm-opentsdb/pom.xml, external/storm-pmml/pom.xml, external/storm-redis/pom.xml, external/storm-solr/pom.xml, pom.xml, shaded-deps/pom.xml, sql/storm-sql-core/pom.xml, sql/storm-sql-external/storm-sql-hdfs/pom.xml, sql/storm-sql-external/storm-sql-kafka/pom.xml, sql/storm-sql-runtime/pom.xml
https://issues.apache.org/jira/browse/STORM-3312
=> STORM-3312: Upgrade Guava to latest version where possible

pom.xml
https://issues.apache.org/jira/browse/STORM-3353
=> STORM-3353: Upgrade to Curator 4.2.0

external/storm-autocreds/pom.xml, external/storm-hive/pom.xml
https://issues.apache.org/jira/browse/STORM-3356
=> STORM-3356: Exclude slf4j-binding from Hive dependencies

pom.xml
https://issues.apache.org/jira/browse/STORM-3357
=> STORM-3357: Bump Clojure version to 1.10

pom.xml
https://issues.apache.org/jira/browse/STORM-3373
=> STORM-3373: Use Log4j BOM, align SLF4j dependencies, upgrade SLF4j

storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
Placeholder components num_tasks and num_executors now show expected value
=> STORM-3395 Fix Placeholder Topology page components show task counts

docs/_includes/footer.html
Have I just won the prize for the most trivial contribution ever?
=> copyright year set to 2019

docs/storm-jdbc.md, examples/storm-jdbc-examples/pom.xml, examples/storm-jdbc-examples/src/main/java/org/apache/storm/jdbc/spout/UserSpout.java, examples/storm-jdbc-examples/src/main/java/org/apache/storm/jdbc/topology/AbstractUserTopology.java, examples/storm-jdbc-examples/src/main/java/org/apache/storm/jdbc/topology/UserPersistenceTopology.java, examples/storm-jdbc-examples/src/main/java/org/apache/storm/jdbc/topology/UserPersistenceTridentTopology.java, external/storm-jdbc/README.md
Note: "persistance" no longer exists in the repository.
=> [STORM-3416] Checkstyle jdbc examples

pom.xml, storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/RocksDbMetricsWriter.java, storm-server/src/main/java/org/apache/storm/metricstore/rocksdb/RocksDbStore.java
https://issues.apache.org/jira/browse/STORM-3408
The current version of rocks doesn't work on some installs of windows 10. Update to the most recent 5.x version
=> STORM-3408 - update rocks version

conf/defaults.yaml, storm-client/src/jvm/org/apache/storm/Config.java, storm-server/src/main/java/org/apache/storm/DaemonConfig.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
Updated pull request due to problems with https://github.com/apache/storm/pull/3022
=> STORM-3407 Storm 2.x ConstraintSolverStrategy backward compatibility

README.markdown
In this PR, I replace a broken link to the page listing companies that use Storm.
=> MINOR: Fix powered by readme link

storm-client/src/jvm/org/apache/storm/testing/TupleCaptureBolt.java
Fixes [STORM-3422](https://issues.apache.org/jira/browse/STORM-3422).
Note, **this is a preview PR meant as a base for more discussion**.
There are two commits, two different approaches to the same problem, please take a look. The latter, I believe, is simpler and easier to understand.
The synchronization is expected to be completely uncontended, we simply need a way to safely publish the changes made by one thread or the other. Either way, the usage of the class feels dirty, but there isn't much we can do now, is there?
=> STORM-3422: TupleCaptureBolt is not thread-safe

external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutMessagingGuaranteeTest.java, pom.xml
Also bumping Mockito version because why not, it's been a while.
=> STORM-3478: Upgrade to JUnit 5.5.1 and Mockito 3.0.0

storm-server/pom.xml, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
exposes scheduling StackOverflowError with large number of executors/constraints
=> STORM-3475 Add ConstraintSolverStrategy Unit Test

storm-server/src/main/java/org/apache/storm/daemon/nimbus/TopologyResources.java, storm-server/src/main/java/org/apache/storm/scheduler/Cluster.java, storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignment.java, storm-server/src/main/java/org/apache/storm/scheduler/SchedulerAssignmentImpl.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/RAS_Node.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestDefaultResourceAwareStrategy.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
=> STORM-3488 Scheduling can cause RAS_Node resources to become negative

storm-server/src/main/java/org/apache/storm/scheduler/TopologyDetails.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/ResourceAwareScheduler.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceOffer.java, storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResources.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestGenericResourceAwareStrategy.java
Don't scheduling topology if topology resource requirements exceeds total available on cluster.
=> STORM-3509 Improved RAS scheduling

storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/ConstraintSolverStrategy.java, storm-server/src/test/java/org/apache/storm/scheduler/resource/strategies/scheduling/TestConstraintSolverStrategy.java
Avoid StackOverflowException and speed up scheduling.
=> [STORM-3519] Change ConstraintSolverStrategy::backtrackSearch to iteration

storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java
https://issues.apache.org/jira/browse/STORM-3527
In some rare cases, `workers-users/<workerid>` can be empty:
https://github.com/apache/storm/blob/master/storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java#L561-L565
>  protected void saveWorkerUser(String user) throws IOException {
type.assertFull();
LOG.info("SET worker-user {} {}", workerId, user);
ops.dump(new File(ConfigUtils.workerUserFile(conf, workerId)), user);
}
Above code could be interrupted because supervisor got killed/terminated. So the file could be created but left as empty. 
Supervisor will then never be able to clean up directories for this worker because it can't get the worker user information correctly
=> [STORM-3527] getWorkerUser() should never return empty username

RELEASING.md
Add some details to make things more clear
=> MINOR: update RELEASING doc to include more details

storm-server/src/main/java/org/apache/storm/metricstore/NoOpMetricStore.java
…se in the config to disable monitoring.
=> STORM-3512 Empty implementation for the MetricStore. 

storm-client/src/jvm/org/apache/storm/trident/topology/state/TransactionalState.java
I have close [PR #3192 ] and repull this request only fix the log issue.
=> [MINOR] complete log info in TransactionalState.java file

storm-client/src/jvm/org/apache/storm/security/auth/ClientAuthUtils.java, storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
=> [STORM-3578] ClientAuthUtils.insertWorkerTokens removed tokens incorrectly

storm-server/src/main/java/org/apache/storm/stats/StatsUtil.java
Details explained in the JIRA https://issues.apache.org/jira/browse/STORM-3598
Now visualization works with the example topology (in the jira)
=> [STORM-3598] Fix UI visualization NullPointException

storm-core/test/jvm/org/apache/storm/integration/TopologyIntegrationTest.java
[STORM-3306] TopologyIntegrationTest.java use TopologyBuilder to build topologies not Thrift
=> [STORM-3306] TopologyIntegrationTest.java use TopologyBuilder to build topologies not Thrift

storm-core/src/jvm/org/apache/storm/utils/Utils.java
https://github.com/apache/storm/pull/3229
=> [STORM-2483] misnamed parameters

DEPENDENCY-LICENSES, LICENSE-binary, pom.xml
=> [STORM-3608] upgrade snakeyaml from 1.11 to 1.26 (latest)

storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java, storm-client/src/jvm/org/apache/storm/executor/spout/SpoutExecutor.java
described in https://issues.apache.org/jira/browse/STORM-3609
=>  [STORM-3609] fix ClassCastException when credentials are updated for ICredentialsListener spout/bolt instances

storm-client/src/jvm/org/apache/storm/validation/ConfigValidation.java
This is a expected scenario, warn level is more appropriate than error.
=> [MINOR] change config validation to warn

.github/pull_request_template.md, pom.xml
A very short template just to remind developers to explain what the PR is and what the tests were done. Especially the latter one, to gives more confidence for reviewers about the code change.
Tested this template on my own test repo. Example: https://github.com/Ethanlm/storm/pull/2
=> [MINOR] Add pull request template

storm-client/src/jvm/org/apache/storm/security/auth/sasl/SimpleSaslServerCallbackHandler.java
Reduce the supervisor log size.
=> STORM-3632 reduce SimpleSaslServerCallbackHandler logging

storm-server/src/main/java/org/apache/storm/daemon/supervisor/ReadClusterState.java
Provide information about why workers are being killed.
=> STORM-3633 add message we're about to kill detached workers

storm-client/src/jvm/org/apache/storm/metrics2/StormMetricRegistry.java
Some metrics reporters using the metrics tick already report metric dimensions such as hostname and topology.  For such cases, adding these to the V2 metric name prevents useful metric aggregation.  This PR allows disabling reporting of the extended metric name for the metrics tick.
Launched topology with -c topology.enable.v2.metrics.tick=true -c topology.metrics.use.shortname=true/false and validated short/long name for metrics was reported.
=> STORM-3627 allow using short metric names for V2 metrics tick

storm-client/src/jvm/org/apache/storm/security/auth/kerberos/AutoTGT.java
Update the AutoTGT metric to the newer metrics API.
built storm-client
=> STORM-3642 update AutoTGT metric to new API

storm-client/src/jvm/org/apache/storm/pacemaker/PacemakerClient.java
Improve error message on pacemaker connection exceptions.
Built storm-client.
=> STORM-3644 update pacemaker connection error log

storm-server/src/main/java/org/apache/storm/daemon/supervisor/Container.java, storm-server/src/test/java/org/apache/storm/daemon/supervisor/ContainerTest.java
What is the purpose of the change
When checking if all processes are dead, each process is checked by issuing a "ps" or "tasklist" command. This command uses LDAP integration in Linux to determine user. When LDAP is slow, this
process overall response time is slow.
(Explain why we should have this change)
This change checks all processes in a single command, and thus avoid expensive subprocess invocations. For POSIX systems, and additional speedup is achieved using cached mapping of USER to UID mapping and using uid to determine liveness. The latter avoid LDAP hits altogether and avoid LDAP timeouts.
How was the change tested
A new test ContainerTest.testIsAnyProcessAlive() was written to test both the positive and negative cases. Additional test testGetUserId() checks correctness of …
=> [STORM-3638] Add fast process liveness check

storm-server/src/main/java/org/apache/storm/scheduler/resource/normalization/NormalizedResourceRequest.java
Reduce debugging output related to scheduling
built storm-server
=> STORM-3676 reduce debug logging output

storm-server/src/main/java/org/apache/storm/utils/ServerUtils.java, storm-server/src/test/java/org/apache/storm/utils/ServerUtilsTest.java
*(Pushback to Community) Owner on /proc/pid is sometimes returned as UID instead of username in production. Handle this special case.*
*New test was written to mock this condition and test the correct behavior of ServerUtils.isAnyPosixProcessPidDirAlive()*
=> [STORM-3692] Handle UID return from Files.getOwner()

storm-client/src/jvm/org/apache/storm/executor/Executor.java
Add the missed timer metrics rates to the V2 metrics tick.
Ran topology with timer and V2 metrics tick and LoggMetricsConsumer and validated Timer rates were logged.
=> STORM-3695 add timer rates to V2 metrics tick

docs/LocalityAwareness.md
Rework https://github.com/apache/storm/pull/3268
Add doc for locality awareness
N/A
=> [STORM-3635] Add Locality Awareness documentation

storm-client/src/jvm/org/apache/storm/executor/bolt/BoltExecutor.java, storm-client/src/jvm/org/apache/storm/metric/internal/MultiCountStat.java, storm-client/src/jvm/org/apache/storm/metrics2/RollingAverageGauge.java, storm-client/src/jvm/org/apache/storm/metrics2/TaskMetrics.java, storm-client/src/jvm/org/apache/storm/stats/BoltExecutorStats.java
Allow users to track a capacity metric other than on UI
Ran topology with load and validated reported capacity was in line with UI.
=> STORM-3697 add capacity metric

external/storm-hdfs-blobstore/src/main/java/org/apache/storm/hdfs/blobstore/HdfsBlobStore.java
Adding some cache might help lower the frequency of hdfs calls by the HdfsBlobStore while reporting replicationCount and meta for permission checks.
Manually tested the changes.
=> STORM-3715: Add Caching to HDFS BlobStore

storm-server/src/main/java/org/apache/storm/daemon/supervisor/Slot.java
I don't see what action we should take for this log line.  Changing to info.
=> MINOR change log level to info on force kill

integration-test/pom.xml, storm-checkstyle/pom.xml, storm-client/pom.xml, storm-core/pom.xml, storm-server/pom.xml, storm-shaded-deps/pom.xml, storm-webapp/pom.xml
*Few pom.xml files (out of 105 files) do not reference the parent pom.xml but specify the directory in the relative path*
*Build project*
=> [STORM-3721] Change parent reference to include pom.xml 

README.markdown, pom.xml
*Add new committers*
*Documentation only change - No test except rebuild project*
=> [STORM-3722] Add new committers

storm-client/src/jvm/org/apache/storm/drpc/DRPCSpout.java
Fix DRPC Spout SPOF to handle DRPC connections in a real async fashion
Launching BasicDRPC topo in dev cluster with 2 DRPC servers.
1. Both DRPC servers are down, worker will keep retrying to create DRPC client
2. Only 1 DRPC server is up, keep retrying to create client for the down server and work well with the other up server
3. Both server are up. After worker is up, kill the servers. Worker will not fail but keep reconnecting until one of the server is back up.
=> [STORM-3725] make DRPCSpout support real async connections

examples/storm-loadgen/src/main/java/org/apache/storm/loadgen/OutputStream.java
*Remove unused import*
*mvn clean intall under both JDK 8 and JDK 16 EA*
=> [STORM-3731] Remove unused imports for nashorn and package class

storm-server/src/main/java/org/apache/storm/scheduler/resource/strategies/scheduling/BaseResourceAwareStrategy.java
*When resource is tight and the number of ackers is high, it may not always be possible to assign the ackers evenly with executors. When an executor is assigned, then try to assign as many (and upto) the calculated number of ackers.*
*Run unit tests*
=> [STORM-3755] While scheduling multiple ackers with executor use best effort basis

storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
*Zookeeper reconnect events can cause an exception when timer is executing Worker#checkCredentialsChanged. This causes the worker to be restarted. Ignore a few consecutive exceptions to avoid this transient error.*
*No new tests added.*
=> [STORM-3758] Ignore upto 10 consecutive exceptions within Worker#checkCredentialsChanged

storm-client/src/jvm/org/apache/storm/Constants.java, storm-client/src/jvm/org/apache/storm/daemon/worker/Worker.java
*Sharing Worker Metric Registry can help in integrating with Guice AOP Based Metrics Integeration*
=> STORM-3737: Shared Worker Registry

storm-client/src/jvm/org/apache/storm/executor/Executor.java
=> [STORM-3785] Follow up: fix the checkstyle issue

README.markdown
Proposing removing the unused (?) IRC room from here, just one other (unresponsive) person when I joined.
=> README - remove IRC section

external/storm-autocreds/pom.xml
Build issue - detailed in https://issues.apache.org/jira/browse/STORM-3828
CI build
=> [STORM-3828] try to fix build issue related to javax.el

DEPENDENCY-LICENSES, dev-tools/validate-license-files.py, pom.xml
upgrade jar due to cve
CI build
=> [STORM-3837] upgrade activemq-client due to cve

examples/storm-starter/src/jvm/org/apache/storm/starter/AnchoredWordCount.java, examples/storm-starter/src/jvm/org/apache/storm/starter/ExclamationTopology.java, examples/storm-starter/src/jvm/org/apache/storm/starter/LambdaTopology.java, external/storm-hdfs-oci/src/main/java/org/apache/storm/container/oci/HdfsOciResourcesLocalizer.java, pom.xml
*Change version on maven-pmd-plugin to 3.16.0 and fix errors encountered with "mvn pmd:check"*
*Build and run tests*
=> [STORM-3853] Change version on maven-pmd-plugin to 3.16.0

pom.xml
To be able to better debug clojure-maven-plugin errors.
built storm code.
=> STORM-3861 update clojure-maven-plugin

DEPENDENCY-LICENSES, LICENSE-binary, pom.xml
Updated rocksdb to version 6.27.3 which supports s390x.
=> [STORM-3866] Updated rocksdb version 

aws-bin/README, aws-bin/aws_kafka.py, aws-bin/init.sh
*Command processor to interact with AWS Kafka cluster*
*Ran each command*
=> [STORM-3887] Add AWS Kafka command processor

docs/Metrics.md, docs/Multilang-protocol.md, docs/Stream-API.md, docs/Windowing.md, docs/storm-hive.md, docs/storm-jms-example.md, docs/storm-jms-spring.md, flux/flux-core/src/test/resources/configs/bad_hbase.yaml
=> [hotfix] fix typo

external/storm-kafka-monitor/README.md
*Documentation does not what parameters to pass*
*Look at the formatted document in IntelliJ*
=> [STORM-3890] Insert java class name and parameters.

flux/flux-core/src/test/java/org/apache/storm/flux/multilang/MultilangEnvironmentTest.java, flux/pom.xml
*Make sure only one version of commons-cli is used and switch to python3*
*Check mvn dependency tree and run test in flux directory*
=> [STORM-3891] Use commons-cli defined in parent pom, change python to python3

external/storm-pulsar/pom.xml, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/MessageToValuesMapper.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarBolt.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarBoltConfiguration.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarSpout.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarSpoutConfiguration.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarSpoutConsumer.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarStormConfiguration.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/PulsarTuple.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/SharedPulsarClient.java, external/storm-pulsar/src/main/java/org/apache/pulsar/storm/TupleToMessageMapper.java, external/storm-pulsar/src/main/javadoc/overview.html, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/MockOutputCollector.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/MockSpoutOutputCollector.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/PulsarBoltIntegrationTest.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/PulsarSpoutIntegrationTest.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/PulsarSpoutTest.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/TestUtil.java, external/storm-pulsar/src/test/java/org/apache/pulsar/storm/example/StormExample.java
Apache Pulsar is a popular streaming and messaging platform. 
It provides storm integration as part of the [pulsar-adapters](https://github.com/apache/pulsar-adapters) subproject but the storm adapter never keeps up with the latest storm changes/builds. 
The adapter does not require much knowledge about the pulsar internals but knowledge of Storm internals is something that is more beneficial. 
This PR is an attempt to transition pulsar-storm adapter to the storm community .
Unit/integration test.
=> Storm-Pulsar bolt and spout

.github/workflows/maven.yaml, dev-tools/travis/travis-script.sh, integration-test/run-it.sh
- This re-adds the integration test in GitHub Actions similar to the one previously executed in Travis CI.
- Via GitHub actions on fork.
=> STORM-3898 - Add Integration Test Github Action

SECURITY.md, conf/defaults.yaml, storm-client/src/jvm/org/apache/storm/Config.java
Update the document for setting up secure cluster
Tested on a secure cluster
=> STORM-3920 Update security document

bin/storm, bin/storm.ps1, bin/storm.py
*bin/storm dev-zookeeper command fails to find python*
*Run command "bin/storm dev-zookeeper*
=> [STORM-3926] Require python3 for bin/storm

storm-client/src/jvm/org/apache/storm/utils/VersionInfo.java, storm-server/src/main/java/org/apache/storm/localizer/LocalizedResource.java, storm-server/src/main/java/org/apache/storm/localizer/LocallyCachedBlob.java, storm-webapp/src/main/java/org/apache/storm/daemon/logviewer/utils/LogCleaner.java
see https://issues.apache.org/jira/browse/STORM-3800
=> [STORM-3800]  fix resource leak due to Files.walk Files.list

RELEASING.md
*Update for version 2.6.0*
*No code change. Very document change by viewing trasnsformed document in IntelliJ*
=> [STORM-3953] Update releasing document.

examples/storm-kafka-client-examples/pom.xml, examples/storm-perf/pom.xml, examples/storm-solr-examples/pom.xml, external/storm-kafka-client/pom.xml, external/storm-solr/pom.xml, pom.xml, storm-client/pom.xml, storm-core/pom.xml, storm-server/pom.xml, storm-shaded-deps/pom.xml
*Importing Storm into eclipse and a maven project shows some errors and warnings*
*Import into eclipse as well as following github actions*
=> [STORM-3963] Add m2e plugin to storm-shaded-deps and few minor pom.xml fixes

DEVELOPER.md
- Removes obsolete information from developer docs
- Updates versions for nvm and rvm
Note: Don't think this requires an extra Jira but can create one if you think, it needs one.
=> [STORM-3980] Updates developer docs and removing obsolete content

storm-server/src/main/java/org/apache/storm/nimbus/TimeOutWorkerHeartbeatsRecoveryStrategy.java
https://issues.apache.org/jira/browse/STORM-3984
Since the [TimeOutWorkerHeartbeatsRecoveryStrategy.startTimeSecs is set on Nimbus start-up](https://github.com/apache/storm/blob/4374fdc93982db3e511ed5e8af642eef97c89aae/storm-server/src/main/java/org/apache/storm/nimbus/TimeOutWorkerHeartbeatsRecoveryStrategy.java#L48) and never updated,[TimeOutWorkerHeartbeatsRecoveryStrategy#exceedsMaxTimeOut](https://github.com/apache/storm/blob/4374fdc93982db3e511ed5e8af642eef97c89aae/storm-server/src/main/java/org/apache/storm/nimbus/TimeOutWorkerHeartbeatsRecoveryStrategy.java#L68-L70) always returns true after 600s (the value of supervisor.w\
orker.heartbeats.max.timeout.secs) are passed after Nimbus is started.
Invalid timeout in new leader Nimbus causes unnecessary reassign right after failover. …
=> STORM-3984: Nimbus failover causes unnecessary reassign if 600s are passed after starting Nimbus.

DEPENDENCY-LICENSES, sql/storm-sql-external/storm-sql-hdfs/pom.xml
*mvn test warns of illegal reflection in jdk11+*
*Unit test and github actions*
=> [STORM-3966] Allow reflection in JDK11 test for storm-sql-hdfs; update guava version

storm-server/src/main/java/org/apache/storm/daemon/nimbus/Nimbus.java
=> [STORM-3992]Print stack trace upon Exception when getting heartbeat timeout

DEPENDENCY-LICENSES, pom.xml
=> STORM-3993 - ActiveMQ 5.18.3

storm-server/src/main/java/org/apache/storm/scheduler/blacklist/BlacklistScheduler.java
https://issues.apache.org/jira/projects/STORM/issues/STORM-3986
=> [STORM-3986] Get rid of BlacklistScheduler timer [INFO] logs

.github/workflows/maven.yaml, pom.xml
See what happens with CI if we add Java 21 to the matrix
=> STORM-3999 - Add Java 21 to Build Matrix

DEPENDENCY-LICENSES, LICENSE-binary, examples/storm-kafka-client-examples/pom.xml, external/storm-kafka-client/pom.xml, external/storm-kafka-client/src/main/java/org/apache/storm/kafka/spout/KafkaSpoutConfig.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/KafkaUnit.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/bolt/KafkaBoltTest.java, external/storm-kafka-client/src/test/java/org/apache/storm/kafka/spout/KafkaSpoutNullTupleTest.java, pom.xml
- Upgrade old dependencies
- CI
=> STORM-4004 - Upgrade Kafka Clients to 3.6.0

DEPENDENCY-LICENSES, LICENSE-binary, pom.xml
* reduce asm mess in dependency tree
* CI
=> STORM-4010 - Reduce ASM Mess in dependency tree

docs/Setting-up-a-Storm-cluster.md
Update the documentation to reflect the minimum version of Java required. 
Updated documentation
Checked the Java version against which storm is being built in github actions. 
Not Applicable
=> [STORM-4015][DOCS] Update the minimum Java version required to Java 11

storm-client/src/jvm/org/apache/storm/messaging/netty/Login.java
This change is needed to avoid having to specify `java.security.auth.login.config` as both a Storm configuration property (for initial login) and a Java system property (for background periodic re-login).
See [STORM-4023](https://issues.apache.org/jira/browse/STORM-4023) for complete technical details.
Unit tests.
=> [STORM-4023] Background periodic Kerberos re-login should use same JAAS configuration as initial login

storm-webapp/src/main/java/org/apache/storm/daemon/ui/UIHelpers.java
- Fix  https://issues.apache.org/jira/browse/STORM-4025
- CI
=> STORM-4025 - ClassCastException when changing log level in Storm UI

DEPENDENCY-LICENSES, LICENSE-binary, pom.xml
- https://github.com/EsotericSoftware/kryo/releases
- CI
=> STORM-4027 - Kryo 5.6.0

DEPENDENCY-LICENSES, external/storm-hdfs-blobstore/pom.xml, external/storm-hdfs-oci/pom.xml, external/storm-hdfs/pom.xml, sql/storm-sql-external/storm-sql-hdfs/pom.xml
Superseeds https://github.com/apache/storm/pull/3636
=> [STORM-4053] Add Hadoop client API dependency back to storm-hdfs

RELEASING.md
=> Fixing error on release notes

storm-client/src/jvm/org/apache/storm/trident/topology/MasterBatchCoordinator.java
see https://issues.apache.org/jira/projects/STORM/issues/STORM-4069 (or mailing list)
- CI
=> STORM-4069 - java.lang.ClassCastException for Trident-based Topology

.github/workflows/maven.yaml, .github/workflows/nightlies.yaml, .github/workflows/snapshots.yaml, pom.xml
Move to Java 17.
Update Build Tools
=> STORM-4133 - Raise Minimum JRE Level to 17
